### ISSUE TITLE
When choosing "Use current position" twice in succession, location is lost

### ISSUE THREAD

**Issue by TheLastProject** [grote/Transportr#103]
Let's hope this is not yet another NS-only bug.

How to reproduce:
1. Open drawer
2. Go to Nearby stations
3. Press "Use Current Position"
4. See search field filled with coordinates
5. Press "Use Current Position" again

Expected result:
No change

Actual result:
"Searching for current position..." appears and Transportr asks Android for GPS location. However, it seems to get stuck at this phase and doesn't enable GPS either (the marker icon which shows up when using OsmAnd, for example, does not appear in the right top of the Android status bar). Any other attempt to "Use current position" causes Transportr to search again. The app needs to be closed for the function to work again.

**Comment by TheLastProject** [comment]
Forgot to mention, this is on Android 5.1.1, running CyanogenMod 12.1.

**Comment by grote** [comment]
I think it is expected that the found location gets lost when you search again for a new position. You might have moved in the meantime.
However, there were two issues related to activating the GPS function. Thanks for spotting these, you are a good tester! :)
