### ISSUE TITLE
No network names or pictures

### ISSUE THREAD

**Issue by frazzmark** [grote/Transportr#105]
At first start, you cannot see the network names or the pictures. Touching the arrows shows the same picture all over. The text doesn't show, maybe it's in the wrong color...
Using slimlp 5.1.1 on galaxy s3

**Comment by grote** [comment]
I'm not sure I understand what you mean. Could you maybe provide a screenshot?

**Comment by frazzmark** [comment]
![tmp_18762-screenshot_2015-10-24-15-12-23465061190](https://cloud.githubusercontent.com/assets/7524830/10710621/eac413a2-7a61-11e5-9943-ff958c4c75b1.png)

**Comment by grote** [comment]
Oh that doesn't look good. Could you please try the latest beta version available [here](http://grobox.de/fdroid/) and see if you still have this bug?

**Comment by frazzmark** [comment]
No, this bug isn't present in beta.

**Comment by grote** [comment]
Great, then we can close this issue, because the beta will soon become the new stable version.

Btw. the [Italian translation](https://www.transifex.com/grobox/transportr/language/it/) is only at 93% with a few strings left to translate in case you are interested ;)
