### ISSUE TITLE
Make vibrating optional, disable by default

### ISSUE THREAD

**Issue by TheLastProject** [grote/Transportr#107]
I noticed that https://github.com/grote/Transportr/commit/b6c5d2c0e0d9f8882836ea2184533b01e7c98b24 introduced vibrating on long-clicking an option.

If there is one thing I'd like to call an antifeature, it is this.

I'd recommend at very least disabling this by default for the following reasons:
- Basically not a single other Android app does this, which makes Transportr inconsistent with expected behaviour.
- It is annoying. I feel like a lab rat being punished for doing an action whenever my device vibrates when I do it. And yes, I know this is an opinion, but a very strong one of mine, and I will not upgrade beyond 1.0.0-beta2 in its current state (in normal circumstances, I simply uninstall apps who do things like this).

Instead of vibrating, I'd like to recommend to just show a toast. You want to direct the user's attention to a small, otherwise easy to miss change. Toasts are literally made for this specific purpose. On systems that support it, you could even use a snackbar with an UNDO button: https://www.google.com/design/spec/components/snackbars-toasts.html#snackbars-toasts-usage.

**Comment by grote** [comment]
I'd assign this one to @ByteHamster if I could ;)
