### ISSUE TITLE
VGN Network missing (Nuremberg, Fürth & Erlangen)

### ISSUE THREAD

**Issue by stweller** [grote/Transportr#110]
Although listed in the website, the network mentioned above does not appear in Transportr (1.0.0-beta2 via F-Droid). This is the one thing keeping me from deleting Öffi from my phone...

**Comment by grote** [comment]
The VGN Network requires an API endpoint which is secret. They made a special one for Oeffi. Maybe you could contact VGN and ask they could make the same one for Transportr or if Transportr could use the same one that Oeffi is using. At the moment Transportr is causing way less traffic than Oeffi, so they hopefully shouldn't be a problem.

**Comment by stweller** [comment]
Thanks for the quick reply!

I'll see whether I can do something about the API. In the meantime, I think it would be fair to remove the entry on the website...

**Comment by stweller** [comment]
I don't know exactly what happened as I did not do anything, but in the latest version of Transportr (from F-Droid repo) suddenly VGN network pops up. Way to go! I'll close this now.
