### ISSUE TITLE
Add to favourites button in trip list

### ISSUE THREAD

**Issue by TheLastProject** [grote/Transportr#111]
The new favourites option and display on the home screen is awesome! However, having to add it from "Recent trips" seems like something that would harm discoverability to me.

I'd like to suggest adding a star in the trip list (right after pressing search) to add this trip to favourites.

I am not sure if the same should be done when looking at one specific trip in the lists, I feel that would be a bad idea, as people may think it will save the time of the trip in their favourites then.

Off-topic, but I must say, Transportr is starting to look amazingly professional. The animation when I select a trip in the list, whoa!

**Comment by grote** [comment]
Yes good idea! This could be an action button in the toolbar and I agree that the same button in the trip detail screen would give the wrong idea.

Thanks for the compliment! The trip selection animation was done by @ByteHamster!
