### ISSUE TITLE
Removing recent trips crashes Transportr

### ISSUE THREAD

**Issue by motatuc** [grote/Transportr#113]
Hello

I wanted to remove recent trips but after trying a few times Transportr crashes. This is reproducable.
Happens with 1.0.0beta3.

The recent trips is also buggy. For example:
1) open recent trips
2) mark the oldest recent trip
3) remove it
-> suddenly three other recent trips are marked. clicking one of these marked trips twice (because one click does not work) unmarks the two others.

anyways, here's the crashlog:

>E/AndroidRuntime(22608): FATAL EXCEPTION: main
E/AndroidRuntime(22608): Process: de.grobox.liberario, PID: 22608
E/AndroidRuntime(22608): java.lang.IndexOutOfBoundsException: Invalid index 40, size is 28
E/AndroidRuntime(22608): 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
E/AndroidRuntime(22608): 	at java.util.ArrayList.get(ArrayList.java:308)
E/AndroidRuntime(22608): 	at android.widget.ArrayAdapter.getItem(ArrayAdapter.java:337)
E/AndroidRuntime(22608): 	at de.grobox.liberario.fragments.RecentTripsFragment.isFavouriteSelected(RecentTripsFragment.java:264)
E/AndroidRuntime(22608): 	at de.grobox.liberario.fragments.RecentTripsFragment.access$200(RecentTripsFragment.java:51)
E/AndroidRuntime(22608): 	at de.grobox.liberario.fragments.RecentTripsFragment$1$2.onClick(RecentTripsFragment.java:298)
E/AndroidRuntime(22608): 	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
E/AndroidRuntime(22608): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(22608): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(22608): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
E/AndroidRuntime(22608): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22608): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(22608): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(22608): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
W/ActivityManager(  555):   Force finishing activity 1 de.grobox.liberario/.activities.MainActivity

**Comment by ByteHamster** [comment]
Looks like this was my fault... Going to have a look at it soon. 

Notice: Happens when there are more items than the screen height.

**Comment by grote** [comment]
@ByteHamster Any news here?

**Comment by ByteHamster** [comment]
I am extremely busy with university, sorry. If you could fix it, that would be nice. I think you need to subtract getFirstVisiblePosition somewhere... The app crashes when you try to check the favourite status of an item that is outside the screen in isFavouriteSelected

**Comment by ByteHamster** [comment]
I am extremely busy with university, sorry. If you could fix it, that would be nice. I think you need to subtract getFirstVisiblePosition somewhere... The app crashes when you try to check the favourite status of an item that is outside the screen in isFavouriteSelected

**Comment by grote** [comment]
This should have been resolved in version 1.0.0-rc1. Could you please verify?
