### ISSUE TITLE
If there are several possible stations for the beginning and the end finding a connection is not possible

### ISSUE THREAD

**Issue by dktzde** [grote/Transportr#114]
Hi, I noticed the following bug in the newest beta (3) - i could not reproduce it in beta 2.
Network: Deutsche Bahn
When I'm searching for a connection with ambiguous station at the beginning and at the end (e.g. AC -> PB) I end up in an endless loop: first I'm asked what is the meant start station - then what is the meant destination - then what is the meant start station -- and so on.

Thanx for your great work!

**Comment by grote** [comment]
Thanks a lot for spotting this! It probably got introduced with the new trip refresh feature in 8eaea21. Will look into it soon.

**Comment by grote** [comment]
This should have been resolved in version 1.0.0-rc1. Could you please verify?

**Comment by dktzde** [comment]
Works on my device. So it's ok.
