### ISSUE TITLE
VRR doesn't work any more

### ISSUE THREAD

**Issue by haary** [grote/Transportr#116]
Since yesterday it is no longer possible to look for connections with VRR (Verkehrsverbund Rhein-Ruhr). Autocompletition doesn't work, i. e. gives no results.  Error Message is: BlockedExcetion: null

DB  (Deutsche Bahn) is still working with Transportr. The prorietary VRR app works as well for VRR connections.

**Comment by haary** [comment]
It seems that the app "Öffi" had similar problems with VRR recently, they fixed it in version 8.97

**Comment by grote** [comment]
Yes unfortunately, @schildbach did not push his PTE changes yet: https://github.com/schildbach/public-transport-enabler/commits/master

**Comment by grote** [comment]
This should have been resolved in version 1.0.0-rc1. Could you please verify?

**Comment by haary** [comment]
Verified, VRR works again. Thank you.
