### ISSUE TITLE
Add Lyon, France

### ISSUE THREAD

**Issue by corzntin** [grote/Transportr#119]
Hi,

Adding Lyon would be really great. Data is available here : http://data.grandlyon.com/transport/ :)
More specifically : http://data.grandlyon.com/equipements/rfseau-de-transport-en-commun-du-grand-lyon-tcl-sytral/

Thank you

**Comment by grote** [comment]
As I don't speak French, I have trouble to see in what format the data is available there. Is it GTFS? Do you already know the information I put together here? http://transportr.grobox.de/#add_region
If so, did you check if the Lyon data is already available via Navitia?

**Comment by TeXitoi** [comment]
It seems there is licencing problems. @rpdcorbion can you confirm that?

**Comment by grote** [comment]
Navitia cites this page as the reason for the license problem: http://data.grandlyon.com/transport/horaires-thforiques-du-rfseau-tcl/

I'll close this issue as there's nothing that can be done within Transportr to solve it.
