### ISSUE TITLE
Add visual indicator of the current time in connection/trip view

### ISSUE THREAD

**Issue by Natureshadow** [grote/Transportr#12]
When searching connections at hh:mm, Liberario lists some results within a time frame between some time _before_ hh:mm, and the latest connection at hh:mm. This would be ok when searching for arrival time, but it makes no sense when searching by _deprture_ time. In that casae, Liberario should list connections _after_ the departure time.

**Comment by grote** [comment]
I could implement the visual indicator of current time, but would be grateful, for design proposals. What @Paspartout proposed of giving the current trip a red glow, does not really look nice.

**Comment by grote** [comment]
Transportr 2 now adds `X min ago` and `in X min` to the trip overview. Maybe that resolves this issue as well?

![image](https://github.com/grote/Transportr/blob/master/fastlane/metadata/android/en-US/images/phoneScreenshots/3_Trips_1510348436922.png?raw=true)

**Comment by Natureshadow** [comment]
Looks good!
