### ISSUE TITLE
Need help to build project with android studio?

### ISSUE THREAD

**Issue by MangeshKadam** [grote/Transportr#121]
Can someone help me to build this project with android studio on windows platform?

**Comment by grote** [comment]
Sorry, but I don't use windows. Did you follow the instructions? Any specific point where you are having issues?

If you just want to test the latest beta release, you can also get it here: http://transportr.grobox.de/#contribute

**Comment by MangeshKadam** [comment]
Hi,
I tried building on linux and its working. Thanks.

**Comment by grote** [comment]
Great! :)

Do you want to contribute to Transportr or just build your own version?

**Comment by MangeshKadam** [comment]
Hi Grote,
I am great fan of your work and I want to contribute to this project too. Help me finding out how I can start my contribution to this project.

**Comment by grote** [comment]
@MangeshKadam Thanks a lot! :)
As a start, I would recommend reading what I have written here: http://transportr.grobox.de/#contribute especially the section "Working with the Source Code". There's also the reference to the beginner tasks some of which already have notes for the implementation.
