### ISSUE TITLE
Adding support for Malaga, Spain public transport

### ISSUE THREAD

**Issue by timofonic** [grote/Transportr#122]
Hello.

I dislike the mess of apps for loading places and managing public transport and need to use proprietary software for it. I even tried to use Moovit and OsmAnd and got lost, it's a mess and have many issues.

I have severe orientation and time management issues due to my ADHD, so I need training therapy but assistance technology helps me a lot.

I found data somewhere, I'll modify this message and put the URL with it. There was an attempt by someone to understand it.

What about integration with FOSS map apps? Would it be possible? It could be amazing for people like me or even blind FOSS users.

Kind regards.

**Comment by grote** [comment]
Hi @timofonic!

did you already check if the Malaga data is available somehow and if so in what format? Did you read the information, I provided here? http://transportr.grobox.de/#add_region

Kind Regards,
Torsten

**Comment by timofonic** [comment]
Hi Torsten!


Sorry for the late reply!

I didn't. But I ended to read it now.

Most or all cities are available in Google.

I found the following URLs:

- Málaga

http://datosabiertos.malaga.eu/dataset/lineas-y-horarios-bus-paradas

http://datosabiertos.malaga.eu/api/3
It uses the CKAN API.

Places to charge the bus card:
http://datosabiertos.malaga.eu/dataset/puntos-de-venta-emt

(Málaga is implementing NFC as virtual bus card, right now only for Orange
mobile provider)


- Madrid
http://datos.madrid.es/portal/site/egob/menuitem.c05c1f754a33a9fbe4b2e4b284f1a5a0/?vgnextoid=adaf314eb5503410VgnVCM2000000c205a0aRCRD&vgnextchannel=374512b9ace9f310VgnVCM100000171f5a0aRCRD
(yes, Spain's public institution sites sucks)

http://opendata.emtmadrid.es

I may locate other places, I'm sure there's Open Data about other locations
in Spain.

Kind regards.

**Comment by grote** [comment]
I didn't find complete GTFS data on the website. Here you see a list of files that are needed: https://developers.google.com/transit/gtfs/reference#feed-files

If you can find all those files, please submit their location to Navitia directly and keep us updated on the progress in this issue. As soon as the data is live in Navitia, I can add it to Transportr.

**Comment by grote** [comment]
There are now more datasets for Spain included, but Malaga still seems to be missing:

https://navitia.opendatasoft.com/explore/dataset/es/table/?sort=type_file

As soon as Navitia adds those, they will automatically work in Transportr. Therefore, I will close this ticket, as there's nothing left to do here within Transportr.
