### ISSUE TITLE
Add New Search "From Here" and "To Here" to Location Popup Menu

### ISSUE THREAD

**Issue by dktzde** [grote/Transportr#124]
Sometimes I go from A to B. It is possible, that I lose my train in stop C. Then it would be fine, when I could use C as the new start position for a new connection search. (I would like to mark it in the trip overview - there is e.g. the possibility "show on map" - and maybe it could be added "use as start location")

**Comment by grote** [comment]
When you click "Show On Map" and then click the station on the map, the popup window already includes "From Here" and "To Here". So this would be very simple to implement. Therefore, it is tagged as a beginner job.
