### ISSUE TITLE
IllegalStateException after update

### ISSUE THREAD

**Issue by JairLeBentz** [grote/Transportr#131]
Hi!
I was able to use Liberario without problems, but after the actualization to Transportr I get this message:
IllegalStateException after update: cannot normalize mot='13'symbol='s2'.............
You can see that problem in this picture:
http://imgur.com/W4fq8Pa
I use the net KVV
I really would like to use this app again
Thanks for your work!

**Comment by ByteHamster** [comment]
I already fixed this. Going to upload the fix next weekend ;)

@grote: Is it enough to create a pull request on public-transport-enabler with my changes? I have never worked with git submodules before.

**Comment by grote** [comment]
@ByteHamster awesome you have a fix already! Please submit a pull request to PTE asap, because otherwise @schildbach does your work again and then one of you would have done duplicated work.

Once the fix is merged in PTE, I will bump the commit ID of the submodule, so Transportr is build with the latest version.

**Comment by schildbach** [comment]
I have a fix for this already.

**Comment by grote** [comment]
@schildbach would you mind pushing it?

**Comment by schildbach** [comment]
I just refined it and will test it today. If all runs well I'll push it this night.

**Comment by JairLeBentz** [comment]
Hey guys, great work. Now I am waiting for the next update.
Thanks!

**Comment by schildbach** [comment]
Just pushed.

**Comment by grote** [comment]
Thanks @schildbach for your fixes, for notifying us and a big thanks for your continued work on PTE!
