### ISSUE TITLE
Problem with With Wiener Linien

### ISSUE THREAD

**Issue by pwnage-pineapple** [grote/Transportr#135]
When attempting to search for a route using Wiener Linien, the search fails and this popup appears: http://tinypic.com/r/23vyquq/9

**Comment by grote** [comment]
I can confirm this problem. Wiener Linien changed their API. This needs to be fixed within [/schildbach/public-transport-enabler](/schildbach/public-transport-enabler).

**Comment by grote** [comment]
This problem is apparently caused by the Wiener Linien company itself and can not be solved by us. Somebody needs to contact them and let them know about this problem with their server.

**Comment by grote** [comment]
Problem was fixed by Wiener Linien company now.
