### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by JasperWeiss** [grote/Transportr#138]
IllegalArgumentException: cannot handle location(gps coördinates)
This shows up when using the current position

**Comment by grote** [comment]
Hi Jasper, thanks for your report!

Unfortunately, it contains very little information, too little to be useful. Could it be that you are seeing the issue already reported in #102?

**Comment by JasperWeiss** [comment]
Yes that is precisely the problem I am experiencing. I hadn't noticed there was already an issue opened for this. 
This may be marked as a duplicate

**Comment by grote** [comment]
If you know how to program, you could help with fixing the upstream issue here: https://github.com/schildbach/public-transport-enabler/issues/49
