### ISSUE TITLE
Delay state on refresh does not properly get saved

### ISSUE THREAD

**Issue by TheLastProject** [grote/Transportr#139]
How to reproduce:
1. Search for a route
2. Choose a train
3. Hit refresh
4. Hit "Into calender" or back

If the delay has changed after hitting the refresh button, you will notice this information does not get saved. Imagine the following situation:

Your train leaves at 8:00 and arrives at 8:45, you see it displayed this way in the connection list. You then tap the train and tap refresh. New delay information is available and shown on the screen. Your train now leaving at 8:05 and arriving at 8:50 instead. You tap "Into Calendar", but the calendar appointment generated is from 8:00 to 8:45 instead of from 8:05 to 8:50. You return to Transportr, which still shows the delay, and hit the back button, returning you to the overview. However, in the overview, the delay is again not displayed. You tap the train again, the delay gone until you do another manual refresh.

It took me a bit to realize what was happening and thus I have no screenshots to better display. I will try to get some next time I run into this issue.

**Comment by grote** [comment]
There's two issues here:
1. trip list/overview does not get updated after trip was refreshed
2. delay information is not included when trip is shared/entered in calendar

While the second issue is quite easy to resolve, the first is quite tricky and I am not sure whether this is worth the effort.

Let's have this issue be about the delays in the calendar.

**Comment by TheLastProject** [comment]
Actually, issue 2 you list is not correct.

If your train normally leaves at 7:45 and is delayed by 2 minutes, and you share to calendar, the time of departure in the calendar will be 7:47. However, if the delay changes since you open the trip (by hitting refresh), the old delay will be shared to the calendar.

**Comment by grote** [comment]
> However, if the delay changes since you open the trip (by hitting
> refresh), the old delay will be shared to the calendar.

Yes this is exactly the bug I have fixed in this issue.
