### ISSUE TITLE
Add İstanbul, Turkey

### ISSUE THREAD

**Issue by muhammetardayildiz** [grote/Transportr#140]

**Comment by grote** [comment]
Hey @muhammetardayildiz,

just creating an issue will not help. Did you read http://transportr.grobox.de/#contribute on adding new cities? There's some information on what needs to be done. Please update this issue with your progress or close it.

**Comment by grote** [comment]
I haven't heard anything in over a month, so I'm going to close this issue. We can reopen this as soon as İstanbul is supported by Navitia and has support in the public-transport-enabler. See #137 for an example of how the latter was done.

**Comment by glemco** [comment]
It seems that the local bus company (IETT) does have static [GTFS files](https://data.ibb.gov.tr/en/dataset/public-transport-gtfs-data), they probably need some adjustment but they seem to be updated yearly and look good enough. 
However, it seems that Navitia [won't support Turkey](https://groups.google.com/g/navitia/c/p1ED4Qtzyy4/m/6g-ZvK7LFgAJ).
Now, do you think it's still possible to add a basic support for Istanbul using this GTFS alone? I could give a try implementing something but I cannot host a Navitia instance just for this.
