### ISSUE TITLE
Query realtime like Bahn.de

### ISSUE THREAD

**Issue by beerisgood** [grote/Transportr#142]
It is a chance to add +- minutes like www.bahn.de have in their app?
So we can see delay from public transport.

**Comment by TheLastProject** [comment]
This is supported for NS. Not in real-time, you need to manually tap the refresh icon, but it does work just fine. Maybe it's just not supported for your transportation network? In which case it'd be an upstream issue with public-transport-enabler. While I don't know how to debug this, it'd be good to know which transport network you are using. I'd assume Deutsche Bahn, but it's better to be sure, makes things easier for the developer.

**Comment by beerisgood** [comment]
I use Deutsche Bahn and SH (Schleswig-Holstein, Kiel, Lübeck, Hamburg).

**Comment by grote** [comment]
Hi @beerisgood. Transportr does support delays already. It is working for sure with DeutscheBahn even without refreshing the trip. I am not sure about the SH provider. This needs indeed be discussed upstream at the public transport enabler library.

**Comment by beerisgood** [comment]
Oh okay, nice!

Thanks for your answer.
