### ISSUE TITLE
version 1.0.2 problems with dark theme

### ISSUE THREAD

**Issue by beerisgood** [grote/Transportr#143]
If switching to the dark theme, the background get grey, instead of dark.
With the white text color its then realy hard to read.

(tested only with F-Droid version)

Edit: Here my screen
![transportr](https://cloud.githubusercontent.com/assets/9625159/12242712/f39c8352-b89a-11e5-83aa-137c8636f448.jpg)

**Comment by benediktg** [comment]
I also have the F-Droid version 1.0.2 and it looks like this with dark design enabled:
![tmp_16296-screenshot_20160111-180559350024460](https://cloud.githubusercontent.com/assets/14795615/12242567/34418a2a-b89a-11e5-88f9-dfec0a93bb2b.png)

**Comment by grote** [comment]
Thank you for reporting this! I can reproduce the issue and will try to fix this soon.

**Comment by benediktg** [comment]
That was quick. Thanks!

**Comment by beerisgood** [comment]
Yes, thanks for the fast update!
