### ISSUE TITLE
Add Rio de Janeiro

### ISSUE THREAD

**Issue by pizzamaker** [grote/Transportr#148]
Apparently the city maintains its own API, as can be seen by this other project that uses it: https://github.com/RioBus/android

**Comment by grote** [comment]
Please observe what is written on the homepage about adding new Transport networks: https://transportr.grobox.de/#contribute

So in this case, you either find the GTFS data for Rio first or implement a custom Provider for the public transport enabler java library. The data seems to come from this page: http://www.fetranspor.com.br/

**Comment by grote** [comment]
I haven't heard anything in 15 days, so I'm going to close this issue. We can reopen this as soon as Rio is supported by Navitia and has support in the public-transport-enabler. See #137 for an example of how the latter was done.
