### ISSUE TITLE
add support for North-East of France

### ISSUE THREAD

**Issue by stragu** [grote/Transportr#149]
I created a pull request into PTE for this provider: https://github.com/schildbach/public-transport-enabler/pull/64

Let me know if it looks ok. After that gets into PTE, what are the next steps to add that to Transportr?

**Comment by grote** [comment]
Thanks for pushing this forward!

Have a look here for what is needed on the Transportr side: https://github.com/grote/Transportr/commit/25a51433bc5aecb1b6e2f5baf96eed763139962a

Do you maybe also have a graphic that could be used for this provider?

**Comment by stragu** [comment]
Where would the graphic go? There is a bunch of companies included in that region.

**Comment by grote** [comment]
Unfortunately, it can only be one graphic. Maybe there's something representing the region or the biggest company there. See [Design and Graphics -> Transport Network Logos](https://transportr.grobox.de/#contribute) on the homepage for details on how to do it.

**Comment by grote** [comment]
Should be resolved with e494538542c1a8d02294152d125a1c5b23b05c44
