### ISSUE TITLE
Network VRS has encoding issues

### ISSUE THREAD

**Issue by Natureshadow** [grote/Transportr#150]
For example, the stop "René-Schickele-Str." is missing the é and not searchable.

**Comment by grote** [comment]
This is an issue best filed against [schildbach/public-transport-enabler](/schildbach/public-transport-enabler/) since it needs to be solved there. Would you mind filing it upstream?

**Comment by grote** [comment]
I haven't heard back anything in more than a month, so I'm closing this one. If the issue still persists, please open a ticket with upstream.
