### ISSUE TITLE
Departures contain lines from different stations

### ISSUE THREAD

**Issue by dotlambda** [grote/Transportr#152]
When I search for departures from "Kirchheim/Rohrbach" (which is in Heidelberg, Germany), Transportr gives me the following results:
<img src="https://cloud.githubusercontent.com/assets/6806011/12546572/0228d9e2-c34b-11e5-810b-61fbc650cc24.png" width="200">
But line 26 actually doesn't stop at that station, only at a nearby station.
To make sure this isn't an upstream bug, I searched for departures from the same station in Öffi:
<img src="https://cloud.githubusercontent.com/assets/6806011/12546573/022b0b2c-c34b-11e5-9c61-ad44a93e0e99.png" width="200">
By the way, I'm using the VRN network.

**Comment by grote** [comment]
Is it possible that "Kirchheim/Rohrbach" is somehow considered an equivalent station to the one where line 26 actually departs? Transportr considers "equivalent" stations for departures as well and Oeffi might not be doing this.

**Comment by dotlambda** [comment]
Well they should not be considered equivalent. The stations Kirchheim/Rohrbach and Odenwaldstr. are about 500 m apart.

How does Transportr decide whether two stations are equivalent?

By the way, this is not only the case for that particular station:
<img src="https://cloud.githubusercontent.com/assets/6806011/12696111/acddb7b2-c761-11e5-9dba-1109839b1f8e.png" width="200px">
Here, lines 721, 34 and 35 do not stop at that station as you can see on [this](https://www.rnv-online.de/fileadmin/user_upload/downloads/Plaene/Liniennetzplaene/Liniennetzplan_HD.pdf) plan.

**Comment by grote** [comment]
If I look with logcat into the debug output, I get this:
```
Departure from Location{STATION, 6001203, 49379165/8675317, place=Kirchheim (HD), name=Kirchheim/Rohrbach}: []
Departure from Location{STATION, 6001208, 49378195/8672501, place=Kirchheim (HD), name=Hagellachstraße}: [Departure{planned=Sat 12:34, predicted=Sat 12:35, Line{vrn, BUS, 33}, destination=Location{STATION, 6001127, name=Emmertsgrund, Endstelle}}]
Departure from Location{STATION, 6001265, 49377867/8677378, place=Rohrbach (HD), name=Erlenweg}: []
Departure from Location{STATION, 6001216, 49379202/8669464, place=Kirchheim (HD), name=Odenwaldstraße}: [Departure{planned=Sat 12:30, predicted=Sat 12:31, Line{vrn, TRAM, 26}, destination=Location{STATION, 6001207, name=Kirchheim, Friedhof}}, Departure{planned=Sat 12:35, predicted=Sat 12:35, Line{vrn, TRAM, 26}, destination=Location{STATION, 6001146, name=Heidelberg, Bismarckplatz}}]
Departure from Location{STATION, 6001215, 49377267/8668968, place=Kirchheim (HD), name=Obere Seegasse}: []
Departure from Location{STATION, 6003373, 49378707/8682261, place=Rohrbach (HD), name=Viktoriastraße}: []
Departure from Location{STATION, 6001200, 49382680/8672071, place=Kirchheim (HD), name=Albert-Fritz-Straße}: []
Departure from Location{STATION, 6006141, 49379948/8682212, place=Rohrbach (HD), name=Fabrikstraße}: []
Departure from Location{STATION, 6003368, 49382995/8678666, place=Rohrbach (HD), name=NVZ}: [Departure{planned=Sat 12:34, Line{vrn, BUS, 28}, destination=Location{STATION, 6001276, name=Rohrbach, Markt}}]
Departure from Location{STATION, 6001262, 49376747/8682370, place=Rohrbach (HD), name=Baden-Badener Straße}: []
```
So there's all sorts of other stations in Kirchheim *and* Rohrbach considered as equivalent stations. This information is coming from the public-transport-enabler library and probably the VRN server. @schildbach knows better whether this is a bug or not!?

I could of course not include equivalent stations in the result to fix this, but then you will not get all departures at Berlin Hbf for example which is divided into many equivalent stations.

**Comment by dotlambda** [comment]
Well this should be where the `equivs` option is parsed: https://github.com/schildbach/public-transport-enabler/blob/master/enabler/src/de/schildbach/pte/AbstractEfaProvider.java#L1512

If I am correct, `useProxFootSearch` means that departures from all stations within walking distance are queried. If that is the case, I think the option should be disabled for VRN and other EFA providers for which this produces nonsense.

**Comment by grote** [comment]
Thanks for digging into this! It looks like this was added intentionally in schildbach/public-transport-enabler@36e52ae4ee, but I don't really understand why. It seems like @schildbach intends the equiv option only to be used for querying departures in a larger area. Let's wait a bit for him to confirm that and then act accordingly.

**Comment by schildbach** [comment]
If these stations are in walking distance, the outcome is expected. Are they?

Unfortunately "equivs" is not well defined.
