### ISSUE TITLE
Add logo BSVAG and NASA

### ISSUE THREAD

**Issue by 0x11de784a** [grote/Transportr#153]
Here are the logos for the BSVAG (Braunschweiger Verkehrs AG) and NASA (Nahverkehrsservice Sachsen-Anhalt GmbH). I hope they are correct. 
Please insert them in one of your pulls.

![network_nasa_logo](https://cloud.githubusercontent.com/assets/5939268/12553203/4cbafc44-c376-11e5-9560-70fadd989762.png)
![network_bsvag_logo](https://cloud.githubusercontent.com/assets/5939268/12553188/3fa4c9fe-c376-11e5-9fdc-89d55710c728.png)

**Comment by TheLastProject** [comment]
I'm afraid you hit "Submit new issue" slightly too quickly and the images were still uploading. You may want to edit your issue with the images included.

**Comment by 0x11de784a** [comment]
There seems to be a uploading problem right now. I'll add the logos later.

**Comment by 0x11de784a** [comment]
Done!
