### ISSUE TITLE
add support for North-West of France

### ISSUE THREAD

**Issue by axac** [grote/Transportr#154]
Hello,
I want to add support for north-west of france in Transportr, specialy Brest city, but i don't know how !.
I see this : https://navitia.opendatasoft.com/explore/dataset/fr-nw/information/?sort=type_file
and : GTFS files : https://geo.pays-de-brest.fr/actualites/Pages/public/Offre_Theorique_Bibus.aspx

Thanks

**Comment by grote** [comment]
Hi @axac! Great that you want to help adding `fr-nw`. Do you know a little Java? If so, you can look into issue #137 to see how `fr-sw` was added. Basically, you need to do a small PR for public-transport-enabler and then another even smaller one for Transportr.

**Comment by grote** [comment]
Here's a recent example of how it was done for Ontario, Canada:
* PTE: https://github.com/schildbach/public-transport-enabler/commit/e78e6bdf73fa9a690b919f04cccc689d40adc7df
* Transportr: #157

**Comment by axac** [comment]
ok, thank you.
I'm learning Java. Just a little.

**Comment by patkan** [comment]
Sorry, I overlooked this issue when I created mine :-)
Once #236 is done and merged this can be closed.
