### ISSUE TITLE
Space between Statusbar and Actionbar

### ISSUE THREAD

**Issue by scoute-dich** [grote/Transportr#156]
![screenshot_20160203-110321](https://cloud.githubusercontent.com/assets/3949944/12779138/ba3cf870-ca66-11e5-9d28-3ae6e95b3721.png)

As shown in the screenshot there is space between status- and actionbar.
I'm using a Galaxy Note 1 (Samsung n7000) with a cm13 rom. I'm using a screen DPI of 240 but tested it also with the default value of 340.

Thanks for your great work. Found the app in F-Droid.

**Comment by grote** [comment]
That's very strange. I've never seen this. Is this just in the settings or everywhere? Is one of 240 or 340 the default DPI your device came with? Do you see similar problems with other apps?

**Comment by scoute-dich** [comment]
At the first page, where I can choose the region, everything is ok. But on all other pages inclusive settings this bug appears. 340 DPI is the default one. There is only one other app where I discovered this kind of bug, but I don't know the name...

I also tested this app with the default dpi and without activated xposed framework. I also don't have any gapps installed...

**Comment by scoute-dich** [comment]
Hi,

I tested the app now a little bit more:
The bug only appears on activities which I reach from the navigationdrawer (mainview, settings, latest queries, stations and so on). On the site of found connections, the detail view of a connection or the map view everything works fine.

**Comment by maxirnilian** [comment]
By changing the DPI value I am able to reproduce this effect, also with details/maps view showing up just fine. But however... by applying the same DPI value a second time, the issue is gone.

**Comment by scoute-dich** [comment]
I recently changed my Rom from cm13 to RessurectionRemix. There wasn't such a problem. Also, when I use an xposed module named "Tinted Translucent Status Bar" with default settings the problem disappears also.

So I don't have problems with this bug anymore. I can use the xposed workaround. So if you want and I'm the only one with this bug, you can close the issue.

By the way red an article, where the app was tested:
https://mobilsicher.de/2016/02/09/transportr-bahn-und-oepnv-suche-bundesweit/

Thanks again for the great app.
