### ISSUE TITLE
Departure time

### ISSUE THREAD

**Issue by amilopowers** [grote/Transportr#162]
When I try to change the departure time after a connection lookup for example to search another connection I can't choose the hour but only the minute. It just shows the minute dialogue instead of the hour first. I have to close the app entirely and then I can open and use it again.

Neuxs 5 on Android 6.0.1.
![screenshot](https://cloud.githubusercontent.com/assets/9914682/13346150/84fe7688-dc64-11e5-9daf-1eb21ef81f29.png)

**Comment by amilopowers** [comment]
Btw: I am using version 1.0.4 of Transportr from f-droid.

**Comment by grote** [comment]
Did you try clicking on the big first 17 at the top?

**Comment by amilopowers** [comment]
Ok got it. Case closed.
