### ISSUE TITLE
Please add support for Winnipeg, Canada

### ISSUE THREAD

**Issue by Skeptyc** [grote/Transportr#168]
Winnipeg Transit has an open transit data api available at http://api.winnipegtransit.com/home/api/v2

Would it be possible to get support enabled for this city?  Thank you.

**Comment by grote** [comment]
All information regarding this should be available here: https://transportr.grobox.de/#add_region 
Let me know if there's something missing.

**Comment by grote** [comment]
Haven't heard back on this issue in months. Closing.
