### ISSUE TITLE
Issue: Menu shows Logo of this and the last Network I used

### ISSUE THREAD

**Issue by dktzde** [grote/Transportr#172]
Hi, when I change the network, the menu shows the logo of the chosen network in big, and on the right upside the logo of the network I used before in small. See also screenshots.
I use: 1.1.0-pre1, on Android 6.0.1 (CM 13) on a gt-i9300 (Samsung).

Used network: DB, (after I used VRR)
![db](https://cloud.githubusercontent.com/assets/12322609/14257867/0e1b98fc-faa0-11e5-82a2-81d5551a5b58.png)
Changed network to VRR
![vrr](https://cloud.githubusercontent.com/assets/12322609/14257868/0e1d4ab2-faa0-11e5-8cd8-98eb13b53f8e.png)

**Comment by TheLastProject** [comment]
That's a feature to be able to switch between networks more quickly.

**Comment by grote** [comment]
Yes exactly! ;)

![not a bug](https://simonerescio.it/wp-content/uploads/2014/10/keep-calm-its-not-a-bug-its-a-feature.png)
