### ISSUE TITLE
New network icons

### ISSUE THREAD

**Issue by nautilusx** [grote/Transportr#173]
Hello,

here are some new or improved network icons.
![network_avv_logo](https://cloud.githubusercontent.com/assets/8766955/14259303/9c344b6a-faa6-11e5-9135-a02fca5f62fb.png)
![network_invg_logo](https://cloud.githubusercontent.com/assets/8766955/14259309/a1669106-faa6-11e5-93ee-3ba0aca1708f.png)
![network_mvg_logo](https://cloud.githubusercontent.com/assets/8766955/14259313/a48941e4-faa6-11e5-9038-6c6d3b47922a.png)
![network_sh_logo](https://cloud.githubusercontent.com/assets/8766955/14259317/a6bf7640-faa6-11e5-9c3d-c6f05806e232.png)
![network_vms_logo](https://cloud.githubusercontent.com/assets/8766955/14259318/a8a3319a-faa6-11e5-80f0-7007334f626f.png)
![network_vmv_logo](https://cloud.githubusercontent.com/assets/8766955/14259336/aa865c4e-faa6-11e5-9fa4-2ce777cc8d8b.png)
![network_vvo_logo](https://cloud.githubusercontent.com/assets/8766955/14259337/ac36a45e-faa6-11e5-9ca9-e88423f9358d.png)

There will be more in the next days ;o)

**Comment by grote** [comment]
Nice, thanks a lot! :)

I'll wait for you to add the others here before adding them to the code.

What would actually be most awesome is to use vector graphics wherever possible. Android does not use standard SVG images, but there are tools to convert SVG into Android vector format:
https://inloop.github.io/svg2android/

We have the AVV logo here as SVG: https://github.com/grote/Transportr/blob/master/art/networks/avv.svg

**Comment by nautilusx** [comment]
Hi Torsten,

the avv.svg has no white background. It looks not so nice if you use the dark theme.

I can make svg if you want but on your transportr homepage is the description for png.

**Comment by grote** [comment]
Yes, I mention the white background on the homepage as well. You can easily add a white-background there with Inkscape.

The vector support on Android is new. When it works here, I will add this to the homepage. The challenge is to get a vector graphic in the format Android needs.

**Comment by nautilusx** [comment]
Hi Torsten,

I made new svgs with inkscape and convert the svg with https://inloop.github.io/svg2android/

[svg_and_xml_logos.zip](https://github.com/grote/Transportr/files/203903/svg_and_xml_logos.zip)

But I get only new xml files to download with this converter.

Can you please check what you need and I will do the new network logos.

By the way thanks to github ;o( (Unfortunately, we don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.)

**Comment by grote** [comment]
Thanks for trying producing vector drawables. Unfortunately, they do not work.

It is normal that you get an XML. It is a slightly different format from SVG and therefore has a different file ending as well.

I tried it myself with the AVV logo and I can not even get this to work in the svg2android. I can import it with AndroidStudio and create a vector drawable there, but it does not look right :(
Maybe you understand now, why I didn't put vector drawables on the homepage. It is quite tricky to get those right and simple raster graphics is much easier.

You are welcome to try again. With Android Studio, you can check the result and make sure it is correct. If not, we just take the raster graphics.

**Comment by grote** [comment]
Actually, I got something working with the AVV logo. It just misses the white background. I guess this needs to be its own path. Also it does not look *exactly* as the official logo, but this is already the case in your SVG file.

Taking my original SVG, I get this which is working and looking like the official logo (still without white background):
```xml
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="164.17184dp"
        android:height="164.15652dp"
        android:viewportWidth="164.17184"
        android:viewportHeight="164.15652">

    <path
        android:fillColor="#0070ae"
        android:pathData="M27.3211,54.8533 L-0.7414,106.103 L15.7586,106.103 L33.7586,73.1973
L45.3211,106.103 L61.8211,106.103 L43.7898,54.8533 L27.3211,54.8533 Z" />
    <path
        android:fillColor="#50bede"
        android:pathData="M52.8836,54.8533 L70.8836,106.103 L70.9146,106.103 L87.3834,106.103
L115.446,54.8533 L98.9455,54.8533 L80.9455,87.7593 L69.3518,54.8533
L52.883,54.8533 Z" />
    <path
        android:fillColor="#c2ce00"
        android:pathData="M145.228,54.8533 L127.197,87.7593 L119.103,64.6973 L109.072,83.0413
L117.166,106.103 L133.666,106.103 L161.729,54.8533 L145.229,54.8533 Z" />
    <path
        android:fillColor="#005386"
        android:pathData="M43.8041,54.8573 L27.3153,54.8573 L27.3153,54.8583 L33.764,73.2003
L43.804,54.8583 L43.804,54.8573 Z" />
    <path
        android:fillColor="#009ad5"
        android:pathData="M70.8962,106.118 L87.3837,106.118 L80.9362,87.7743 L70.8962,106.118 Z" />
    <path
        android:fillColor="#90b912"
        android:pathData="M117.168,106.118 L133.657,106.118 L127.208,87.7743 L117.168,106.118 Z" />
</vector>
```

**Comment by grote** [comment]
OK and this is how it looks perfect and finished with white background:

```xml
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="48dp"
        android:height="48dp"
        android:viewportHeight="164"
        android:viewportWidth="164">

    <path
        android:fillColor="#ffffff"
        android:pathData="M0,0 L164,0 L164,164 L0,164 L0,0 Z"/>
    <path
        android:fillColor="#0070ae"
        android:pathData="M31.6494,56.9398 L5.8712,104.018 L21.028,104.018 L37.5628,73.7906
L48.1841,104.018 L63.341,104.018 L46.7774,56.9398 L31.6493,56.9398 Z"/>
    <path
        android:fillColor="#50bede"
        android:pathData="M55.1311,56.9398 L71.6658,104.018 L71.6943,104.018 L86.8225,104.018
L112.6,56.9398 L97.4435,56.9398 L80.9087,87.1672 L70.2587,56.9398
L55.1305,56.9398 Z"/>
    <path
        android:fillColor="#c2ce00"
        android:pathData="M139.958,56.9398 L123.395,87.1672 L115.96,65.9825 L106.745,82.8333
L114.18,104.018 L129.337,104.018 L155.116,56.9398 L139.959,56.9398 Z"/>
    <path
        android:fillColor="#005386"
        android:pathData="M46.7907,56.9435 L31.6441,56.9435 L31.6441,56.9444 L37.5679,73.7934
L46.7906,56.9444 L46.7906,56.9435 Z"/>
    <path
        android:fillColor="#009ad5"
        android:pathData="M71.6774,104.032 L86.8228,104.032 L80.9002,87.181 L71.6774,104.032 Z"/>
    <path
        android:fillColor="#90b912"
        android:pathData="M114.182,104.032 L129.329,104.032 L123.405,87.181 L114.182,104.032 Z"/>
</vector>
```

**Comment by grote** [comment]
Da das so super funktionier hat, hab ich das mal offiziell in den Code eingebaut, damit du direkt siehst, wie das geht: b88b2de95e

Meinst du, du koenntest auch andere logos in dieses format wandeln?

**Comment by grote** [comment]
Oops, switching back to English here. The DB logo doesn't work, because of the way it uses paths. I created an issue for this here: inloop/svg2android#43

**Comment by grote** [comment]
There's another converter that has a special option to deal with this problem: https://github.com/a-student/SvgToVectorDrawableConverter#not-supported-svg-features
It also supports batch processing which might be nice to convert many images in one go.

**Comment by nautilusx** [comment]
Hi Torsten,

all network logos for Germany and Austria are done.

Next week I try all the other 35 networks. ;o)

@vinzv Can you help me please with the MVV, DING, VRS and SVV (Austria). There are still pictures in the svgs.

**Comment by grote** [comment]
Thanks @nautilusx and @vinzv!

I have now added all logos and fixed the problematic ones. This completes Germany and Austria! Feel free to complete all the logos! :)
If you want to do more, maybe write here which ones, so that you don't do something the other one is already doing.

I'll update the SVG for Ontario and Quebec and create the vector drawables for those.

**Comment by grote** [comment]
Since all network logos (at least for Germany and Austria) have been implemented, I will close this issue. Feel free to open a new one for other regions.
