### ISSUE TITLE
Trips with GPS coordinates can not be made a Favourite Trip

### ISSUE THREAD

**Issue by grote** [grote/Transportr#174]

**Comment by bkqtnte10** [comment]
This bug still happens for me. The screenshot still shows I pressed the star-icon
![Screenshot_20190718-132931_Transportr](https://user-images.githubusercontent.com/42800803/61588178-33dc5580-ab97-11e9-96c1-6a5f8614792c.png)

It happens on SBB and ÖBB network but only if the app is slow enough not to convert the coordinates to an address.

**Comment by grote** [comment]
That there's a crash is a dedicated bug. Can you please open a new ticket?
