### ISSUE TITLE
NotFoundException - Stockholm / 1.1.0-pre1

### ISSUE THREAD

**Issue by regagain** [grote/Transportr#175]
Hi!

I get the following error since 1.1.0-pre1: 

![screenshot_2016-04-06-06-50-14-1](https://cloud.githubusercontent.com/assets/1060371/14306168/8b9e6ab4-fbc4-11e5-837b-15193b7422f6.png)

It only happens in Stockholm.

**Comment by grote** [comment]
Looks like they changed their API URL. Maybe you can find out the new URL somehow. If not, you can report this against the public-transport-enabler.

**Comment by regagain** [comment]
Thanks @grote, I've just found out that this API has been discontinued (as explained [here](http://www.trafiken.nu/stockholm/arkiv/2016/reseplaneraren-avvecklad/) – in Swedish).

I have now reported this to public-transport-enabler, as you advised. See https://github.com/schildbach/public-transport-enabler/issues/83

**Comment by grote** [comment]
So since the API was closed, I will close this issue as well. I already removed Stockholm from Transportr. Let's use the upstream issue to continue the discussion as needed. Maybe you can confirm there whether the SeProvider already provides all information needed.
