### ISSUE TITLE
Support Different Trip Detail Header Graphics

### ISSUE THREAD

**Issue by vinzv** [grote/Transportr#177]
On https://transportr.grobox.de/#sourcecode localized trip detail header graphics are mentioned. I can't find something on that in the sourcecode. Can you give some details (resolution, filetype) and a place where to put them? And: is it possible to give multiple photos to let them be shown randomly?

**Comment by grote** [comment]
The trip header graphic is located here: https://github.com/grote/Transportr/blob/master/res/drawable/trip_header_bus.jpg
Currently, there's no mechanism to change it (randomly or by network). I don't know for sure if that is going to stay and which resolutions would be good. Ideally, these graphics are available in different resolutions and not part of the app itself, but loaded via WiFi on-demand.

**Comment by grote** [comment]
This ticket does not apply anymore for the upcoming Transportr v2 as there are no more trip header graphics.
