### ISSUE TITLE
Cache recent connections

### ISSUE THREAD

**Issue by Matthias84** [grote/Transportr#178]
Hi, some users might not be online 24/7 but connect via wifi only. Thus it would  be very useful, if the app could store the full details of the recently requested connections. Usually I keep the app opened, but a cache would keep the information local and safe :floppy_disk:

**Comment by TheLastProject** [comment]
You could export the connections you care about to the Android calendar. If you use an app like Offline Calendar that keeps them offline and safe. Won't this do?

**Comment by grote** [comment]
This might be the same feature request as #171. @Matthias84 can you confirm it is that what you want? Can you do Java programming and help with this feature?
