### ISSUE TITLE
Pressung back button navigates back but does not update navigation drawer

### ISSUE THREAD

**Issue by mar-v-in** [grote/Transportr#186]
This is on 1.1.0 release.

Steps to reproduce:
1. Start the app
2. Open navigation drawer
3. Select "About" (or any other item)
4. Press back key (you will be back to start screen)
5. Open navigation drawer, it will highlight what you selected in 3, although it's no longer opened

Either exit on back key (not to unusual behavior) or update the navigation drawer.

**Comment by grote** [comment]
Hey @mar-v-in, good catch! :)

I had two pre-releases in [my F-Droid repo](https://grobox.de/fdroid/) and nobody caught this bug. Maybe you would like to use the repo and test the pre-releases as well? ;)
