### ISSUE TITLE
Set icon to define what kind of transport passes in a stop

### ISSUE THREAD

**Issue by Airon90** [grote/Transportr#191]
As you can see in my screenshot it is not clear what kind of transport passes in that stops near Central Railway station in Milan: some are bus stops, some underground stations and some tram stops. Is it possible to restyle map icons by adding some info?

![tmp_6796-screenshot_2016-05-23-08-39-13-763955643](https://cloud.githubusercontent.com/assets/139841/15462381/c103ce4c-20c2-11e6-9301-5d76f5821502.png)

If you don't like to set marker by transport you, you could add an icon in popup.

![tmp_6796-screenshot_2016-05-23-08-40-06-160216643](https://cloud.githubusercontent.com/assets/139841/15462474/53825d2e-20c3-11e6-8c06-b419cf8344e6.png)

I think that this leads to add an icon in dropdown menus when you select the station

![tmp_6796-screenshot_2016-05-23-08-36-55-1561426241](https://cloud.githubusercontent.com/assets/139841/15462492/755c04c2-20c3-11e6-8fb7-a88c940469da.png)

**Comment by grote** [comment]
There's some stations in Transportr where 5 different kinds of transports are available. These hardly fit into one icon in the map. That is why Transportr already shows them in the popup **if** they are available in the data. For Italy, they have not been, but just yesterday I opened schildbach/public-transport-enabler#89 that will give this functionality once accepted.

As for your second suggestion, I don't see how product icons have space in the auto-complete list. As you can see the last station in the list is already too long to be displayed.

**Comment by grote** [comment]
This has been fixed in 79b59d8

**Comment by Airon90** [comment]
Thank you :)
