### ISSUE TITLE
Fix icon alignment

### ISSUE THREAD

**Issue by Airon90** [grote/Transportr#192]
The pic is too clear.

![tmp_6796-screenshot_2016-05-23-08-53-332139578741](https://cloud.githubusercontent.com/assets/139841/15462646/6b6e05d6-20c4-11e6-9efa-9a0947299d98.png)

**Comment by grote** [comment]
The problem is that the INVG logo has a different size than the other logos. You could make it into a square and leave a transparent border left and right. There's an SVG file in the repository and #173 explains how to convert them for use in Android.

**Comment by grote** [comment]
@nautilusx Do you maybe want to look into this?

**Comment by nautilusx** [comment]
Hi Torsten,

here is my version with the white background.

[invg.zip](https://github.com/grote/Transportr/files/287321/invg.zip)

There is the same problem with ding.

**Comment by grote** [comment]
Thanks a lot!

I don't see a problem with DING btw.
