### ISSUE TITLE
Menu crashing

### ISSUE THREAD

**Issue by eri451** [grote/Transportr#196]
I updated recently from f-droid. Now the app crashes when i try to access the menu via the hamburger button

**Comment by grote** [comment]
Could this be a duplicate of #190 or #194? Do you have Xposed installed? Do you know how to get a stack trace for more information?

**Comment by grote** [comment]
Could you try 1.1.2-beta1 and see if this issue maybe got resolved?

**Comment by grote** [comment]
No feedback for a month, so I'll close this.
