### ISSUE TITLE
Caltrain Baby Bullet not working 

### ISSUE THREAD

**Issue by betsythefc** [grote/Transportr#198]
![screenshot_2016-06-05-15-19-02](https://cloud.githubusercontent.com/assets/15450365/15808635/33b625f2-2b31-11e6-84e7-fb6c0abaf36e.png)

When the app tries to use the Caltrain, it returns an exception. Attached is a screenshot.

Installed from F-Droid
Note 4
Sprint
Android 6.1

**Comment by betsythefc** [comment]
IllegalStateException: cannot normalize mot='0' symbol='BAB' name='Baby Bullet' long='Train BABY BULLET' trainType='null' trainNum='BABY BULLET' trainName='null'

**Comment by grote** [comment]
Hey, thanks for reporting this issue. It is actually a problem of another library. Would you mind reporting this again here: https://github.com/schildbach/public-transport-enabler/issues

**Comment by betsythefc** [comment]
No problem, I'm posting it now.

**Comment by betsythefc** [comment]
I just posted it, thanks a ton!

https://github.com/schildbach/public-transport-enabler/issues/98

**Comment by grote** [comment]
I'm closing this issue. Once resolved upstream, it will automatically be resolved in Transportr.
