### ISSUE TITLE
List of bus/train stations

### ISSUE THREAD

**Issue by FrankEular** [grote/Transportr#199]
Since sometimes due to imprecision of location, computed routes are sometimes imprecise, for example, I'd better get off the bus a station later. I think it's better if we can obtain a list of all stations of a bus (especially in the route transportr planned).

**Comment by grote** [comment]
Could you please describe the problem in a little more detail and maybe give an example?

**Comment by FrankEular** [comment]
I choose "SNCF, Paris". I'm near a station and when I use transportr to query for a route. However, it leads me to walk to the next station, and I also walked a lot after getting off the bus because in fact I can get off 2 stations after the station transportr indicated me to get off (I cannot remember exactly where I was, but along the path I found another station of the same bus line). I think it's better that there's a feature to list all stations of a bus.

**Comment by grote** [comment]
Is "SNCF, Paris" what you entered as destination? So the problem is that you destination location was too imprecise? If so, why didn't you enter a more precise destination?

**Comment by FrankEular** [comment]
No, no, I checked the term. I meant that I chose the "SNCF, Paris" as a Transportation Network. I click "Use Current Position" as input, and the market I wanted to go to as "To". It's autocompleted in the menu it pops out. I checked the path in the map, and that the place is correct. However, when I was walking along the path which transportr gave me, I found another station. Anyway, I think if possible, it's better to view a list of the bus stations of the bus line (in the current version, I can get a list of bus stations which I pass through), but I don't know how hard it is.

**Comment by grote** [comment]
The routing for Paris is done by Navitia. It is possible that their routing algorithm isn't working properly. I already observed issues there as well. But this you would need to report to Navitia, since it has nothing to do with Transportr.

I don't understand how a list of bus stations of a bus would help you in this case, but anyway this is not supported by the public-transport-enabler, so that won't work.

**Comment by FrankEular** [comment]
Thanks for the info. It helps me because I cooperate this app with osmand, which supports to show the routes of bus lines, but the stations aren't very easy to figure out.
