### ISSUE TITLE
Import geo location from external map apps or geo info

### ISSUE THREAD

**Issue by FrankEular** [grote/Transportr#200]
It's reported before: https://github.com/grote/Transportr/issues/58

Since now, it seems to me that we can use the current location from GPS device, why can't we import from external maps or geo: location?

**Comment by grote** [comment]
As I explained in #58:
> Import is a lot more tricky since the selected network might not cover the geo coordinate. So before that can be implemented, we need automatic selection of network based on coordinates.

So what should happen if you import a geo location and your current network does not even cover this location?

**Comment by FrankEular** [comment]
Simply reporting "no solution found" or something similar. I don't know how is it treated if I am at some place which isn't covered and use click "Current Location"?

**Comment by grote** [comment]
So in this case, that's easy to implement. The app would need to register to handle `geo:` intents in the Manifest like described here: https://developer.android.com/guide/components/intents-common.html#Maps

Then the `MainActivity` would need to pass this intent on to some fragment that should handle the location like the `DirectionsFragment`. There's already methods for that which can be reused.
