### ISSUE TITLE
Show number of changeover for all trips

### ISSUE THREAD

**Issue by dktzde** [grote/Transportr#201]
When I search for a long distance trip I also choose the the connection depending on the number of changeovers. At the moment, some of the connections show the number (4) some not (3 or 2) changeovers. It would be helpful for me, when I could see number changeover for all connections - maybe with a switch in the settings.

An alternative could be, to show the number of changeovers for all connections of one search, when there is one, witch has 4 (or more) changeovers.

btw: I find the place over the travel time to show the changeovers perfectly fine

**Comment by grote** [comment]
The number of changeovers is only shown for long trips, because for short ones, you can easily glance at the number of line icons to get this information.
