### ISSUE TITLE
nvv/rmv not working

### ISSUE THREAD

**Issue by lebkayn** [grote/Transportr#202]
on my device, nvv/rmv isn't working at the moment. all i get is a toast: "SSLPeerUnverified Exception: Hostname auskunft.nvv.de not verified ..."
i checked db, which is working fine

**Comment by grote** [comment]
This is caused by https://github.com/schildbach/public-transport-enabler/commit/4a47cafd00052b523ea24cc27434e74ee153dc92 and is waiting for a fix from upstream.

In the meantime, you can either use DB or downgrade to the latest working version.
