### ISSUE TITLE
Unknown error message

### ISSUE THREAD

**Issue by grizzee** [grote/Transportr#205]
Unknown error message after searching for an connection.  
![screenshot_2016-06-30-22-42-17](https://cloud.githubusercontent.com/assets/20231913/16503975/e0e1db52-3f15-11e6-9b2b-68d201436681.png)

**Comment by grote** [comment]
This seems to happen for all VVS requests. But is not a Transportr problem, but one of the PTE. You can report the issue there: https://github.com/schildbach/public-transport-enabler/issues

**Comment by grote** [comment]
Maybe VRN or DING work instead for you?

**Comment by grote** [comment]
Haven't heard back and when this is resolved by upstream, it will be automatically resolved by Transportr.

**Comment by grizzee** [comment]
I've tested it a few minutes ago and got the same error. Should it be solved now?

**Comment by grote** [comment]
I don't know. This is with the public-transport-enabler and needs to be solved there as explained above.

**Comment by grizzee** [comment]
Ok, thank you.
