### ISSUE TITLE
VGN lines not shown

### ISSUE THREAD

**Issue by theScrabi** [grote/Transportr#211]
When using the VGN service the platform from where a train starts or arrives is not displayed.

**Comment by grote** [comment]
If this information is not shown for VGN, but for other provides, the [public transport enabler](https://github.com/schildbach/public-transport-enabler/) does not provide this data. Please open an issue with PTE for this as this can not be fixed within Transportr.

**Comment by theScrabi** [comment]
All right I'll do that.
