### ISSUE TITLE
Add "OK" and "Cancel" to translation

### ISSUE THREAD

**Issue by verdulo** [grote/Transportr#214]
Please allow translating phrases "OK" and "Cancel" (don't use default system values), because not all languages (for example Esperanto) are natively supported by Android.

**Comment by grote** [comment]
@kas70 Do you maybe want to look into this? Should be rather easy to do and you have your build environment already set up ;)

**Comment by kas70** [comment]
Yes, i can do this. Watch out for a pull request 😉

**Comment by kas70** [comment]
I've started working on this, but i'm not quite finished yet.
https://github.com/grote/Transportr/pull/229

**Comment by grote** [comment]
Awesome, thanks!
