### ISSUE TITLE
Displaying some parts of the program in default language instead of selected language

### ISSUE THREAD

**Issue by verdulo** [grote/Transportr#215]
Previously reported here: #212 The list of transport network providers is displayed in language of device instead of language selected in options. When you change language (to any not-default) and then click "Network" in options, the phrase "Pick a transportation network" is also displayed in wrong language. The problem has not been observed for another phrases in the app.

**Comment by grote** [comment]
Can this still be reproduced?

**Comment by verdulo** [comment]
In 1.1.6 yes.

**Comment by verdulo** [comment]
Now the whole application is in Esperanto and it's not possible to change it.

**Comment by grote** [comment]
Can you clarify? Why is it not possible to change it?

**Comment by verdulo** [comment]
Sorry, I've used another app to force language. Now everything works, thanks.
