### ISSUE TITLE
Make swipe gesture for later/newer connections shorter

### ISSUE THREAD

**Issue by paskalito** [grote/Transportr#217]
Hi

i like very much the ability to just swipe further down when i want to see connecitons that are later than the currently loaded ones. ( and also opposit direction) but, i really feel that this gestures requires me a far to far/big swipe.
i feel like it should have the same lenght you need for pulling the information layer of android down. or the reload one in k9.

its a very very small thing i konw and supposedly easy to change, but it really bugs me every single time ^^

**Comment by grote** [comment]
What device do you have and what is its screen resolution?

**Comment by paskalito** [comment]
hi, i have an s3
1280×720 px
https://de.wikipedia.org/wiki/Samsung_Galaxy_S_III

**Comment by PanderMusubi** [comment]
Possible to show how many earlier to request (in time or max numbers) before releasing the swipe. So swiping a little will show only one earlier for example

**Comment by grote** [comment]
The overhead with making network request is so large compared to fetching a few more trips that I think it isn't worth doing anything like that. Also, I am not aware of any pull to refresh library that offers this functionality.

**Comment by paskalito** [comment]
for me i also wouldnt want that. in  general i want always more info than any interface shows me normally and i hate having to reload and reload again. if i could wish i would like to have ALL the information available at one fetch only scrolled to the point in time where i am now.
(i believe this is completely out of the scope/goal of transportr but there was once an app for my sony erricson w995 that had offline connections of my whole country available. i liked that)

**Comment by grote** [comment]
> i believe this is completely out of the scope/goal of transportr but there was once an app for my sony erricson w995 that had offline connections of my whole country available.

Actually, no. It would be possible. This is tracked as #126 and would just be lots of work somebody would have to do.

**Comment by paskalito** [comment]
I made a little video visualising what i'm talking about

https://vimeo.com/181474900
passwort is: asdf

**Comment by grote** [comment]
Thanks for the video. So the problem is that with Transportr you need to swipe down the half of the screen, for the loading to trigger while for K9 you only need a quarter of the screen?

The problem probably comes from [OrangeGangsters/SwipyRefreshLayout](https://github.com/OrangeGangsters/SwipyRefreshLayout) which is used for the down and up swipe, because the official SwipeRefreshLayout does not support swiping up.

**Comment by paskalito** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Yes exacrly also in owncloud, and the android system drag down thing. And i more think its 1/8 there. In any case a loot less.

Is this just me or everyone?

- - is it possible to easily adjust that?

Am 5. September 2016 15:30:53 MESZ, schrieb Torsten Grote <notifications@github.com>:
>Thanks for the video. So the problem is that with Transportr you need
>to swipe down the half of the screen, for the loading to trigger while
>for K9 you only need a quarter of the screen?
>
>The problem probably comes from
>[OrangeGangsters/SwipyRefreshLayout](https://github.com/OrangeGangsters/SwipyRefreshLayout)
>which is used for the down and up swipe, because the official
>SwipeRefreshLayout does not support swiping up.
>
>--
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/grote/Transportr/issues/217#issuecomment-244747538

- --
Diese Nachricht wurde von meinem Cyanogen-Mod-Mobiltelefon mit K-9 Mail über das Tor-Netzwerk gesendet.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJFBAEBCgAvBQJXzXUYKBxQYXNjYWwgSm9sbGVyIDxwYXNjYWwuam9sbGVyQHBv
c3Rlby5kZT4ACgkQ6uqiCHoc5UfRPxAAmiQekF3p7XLrk/U77ZD4GWHJukt8T4pe
rjDK25LRV5+4NRDdZ6iHAyHj4/48QTvTGbzd5z3A4U8NFQNx3+mYHAjlYD1PLrpp
+SSdkKBLBktaeUsalg48+22cluGmae8FNywp7WpeJ/LG8/w9HUD4V3yqtqpzIP5A
JrsXsO3gAY9C/fhsBioXjZNLws327y8VE2Ex3oQhQOWFRQdYRYauJs1pY0M8iNtG
OdYbBIrCPsRGlyDYOALCmWoGgXLMNOhIJqQufuAmt9WmLwYhZU/p2Fspv5afongi
AvYzQl5i60h2wiP5GH+/9A3H3mGu0Jmsxy41ZTBaJTlMsLI6mAn0/6/HIp6ryTyI
X2kREKIfE7QVP+znsTNSaXIZjEeRt1k0U0F7639gSB7yeA2CVAT8YKoNy7xkyjjd
EYpLey1V4oQYGprRMy5HwywiU65O0XNIYlFpkjnpOdURJE+/hUO3o6a0ioGcEUee
GksiyJikFrAUgjMI3r0NMCMGRgImDeYbL8E143jY7qTKdZMe5PlUwbnjpEUWayjA
yBktpFCMFH3Tr7x1OFRUlqbKXROW//A7LbUKpafAkmLNqncgD+BltMv2oxpzGWK6
xfBqu9Olr0Ag4dCooIliCL1t//mEbF59g7tkJUaIRuMbS5s3BTn7lc2/woLp23HO
OQrPpMyLy2Y=
=pk1E
-----END PGP SIGNATURE-----

**Comment by grote** [comment]
If you have F-Droid, you can get beta releases from https://grobox.de/fdroid/ and check if the bug is indeed fixed in an upcoming 1.1.5 beta release.

**Comment by paskalito** [comment]
thanks a lot :) !

i also added the repo so i think i will get an update once the 1.15 beta is available :)

**Comment by grote** [comment]
Yes, you will be notified about an update. However, if you installed Transportr from the main F-droid repo before, you can only install it after uninstalling the main repo version first (due to a signature being used) and loosing all data in the process.

**Comment by paskalito** [comment]
Hmm.. thanks, i uninstalled and reinstalled but still can only see 1.1.4
do i need to install 1.1.4-rc1 ?

**Comment by grote** [comment]
Did you install the repo properly? I have 1.1.5-beta1 available.

**Comment by paskalito** [comment]
Hey i dono how or why but today I got update notice and i could update to beta.
And swiping works now well to my gousto thanks a lot !
(I think refreshing repo lists did not work before (cause i suddenly got loads of updates ))
