### ISSUE TITLE
Strange Station Naming - NVBW Network - Tübingen Hauptbahnhof

### ISSUE THREAD

**Issue by github-user-1** [grote/Transportr#219]
Hello,
I just encountered something strange and a bit confusing - if I run a search (see below for screenshot) and on the result screen mark that search as a favorite search, the station name gets changed on the favorites list (changed from "Tübingen, Hauptbahnhof" to "Obf"):

![screenshot](https://cloud.githubusercontent.com/assets/6796538/16809796/203f863c-4911-11e6-8606-d1d71e65a7a7.png)

The search itself works, just the "Obf" name is confusing. The network selected is "NVBW". Is this reproducable for others?

**Comment by grote** [comment]
I just tried with NVBW, the exact same locations and the latest version and can not reproduce this. Will close this issue. If you have more information for how to reproduce this, please post it here.

**Comment by github-user-1** [comment]
Just gave it another try right now - what I got now when trying to search for connections is the following. Maybe somthing's wrong with my phone...  :-(

![screenshot_2016-09-04-17-33-48](https://cloud.githubusercontent.com/assets/6796538/18231990/6e5dfbd0-72c6-11e6-9747-9e93a137d0d6.png)

**Comment by grote** [comment]
What version of Transportr do you use? If you don't have important favorites and data, you could also clear all app data of Transportr and try fresh.

**Comment by github-user-1** [comment]
I'm using version 1.1.3 (via F-Droid). I cleared all cache and app data and tried again:

![screenshot_2016-09-04-18-33-52](https://cloud.githubusercontent.com/assets/6796538/18232364/8b09ed86-72ce-11e6-95ca-1d2550fa69a2.png)

**Comment by grote** [comment]
Try 1.1.4. This might have been resolved with schildbach/public-transport-enabler@b2a1f94e55b6ab453a721648d2d732760f5006f2

**Comment by github-user-1** [comment]
Just downloaded 1.1.4 via F-Droid and in fact it seems to be working fine now (after a few quick checks). Great and many thanks!
