### ISSUE TITLE
Cannot get nearest station

### ISSUE THREAD

**Issue by betsythefc** [grote/Transportr#222]
https://i.imgur.com/H8mGfAR.jpeg

Cannot get nearest station on transportr
San Francisco CalTrain

**Comment by grote** [comment]
Thanks for reporting this. I guess the same like in #198 applies are as well. Before opening a ticket with the PTE, you could try if it finds nearby stations from another station instead of a GPS location to narrow down the problem.

**Comment by betsythefc** [comment]
How do I make it select a station? Do I type the name of the station or is there a dropdown list?

**Comment by grote** [comment]
Unfortunately, San Francisco had to be removed because they turned off the API server used by Transportr.
