### ISSUE TITLE
Deutsche Bahn - No Map available

### ISSUE THREAD

**Issue by motatuc** [grote/Transportr#227]
Hello

Thanks for Transportr!

One bug I recently run into: Using Deutsche Bahn as Network I do not get maps when pressing the map icon. Can you confirm this? 

Have a look at the screen shot:

![screenshot_20160815-103359](https://cloud.githubusercontent.com/assets/15171154/17659678/7decbcdc-62d4-11e6-93c8-f8656ffa0c55.png)

**Comment by grote** [comment]
Does this only happen with the DB provider or with other's as well? Is your internet connection working when opening the map? Are you using Android 6? If so, did you allow the permission to access the SD card? osmdroid needs that to cache map tiles.

**Comment by motatuc** [comment]
Maybe a problem with their server? Because it stopped working from one day to the other. And now it's working again.

Can be close because the problem disappeared.

**Comment by grote** [comment]
The map tiles are always loaded from OpenStreetMap and should be totally independent from the used network provider.
