### ISSUE TITLE
direction screen does not update time when clicking "Search"

### ISSUE THREAD

**Issue by eighthave** [grote/Transportr#233]
When the user goes to the Directions screen, it sets the time field based on the current time.  But then that doesn't get updated, so if the user was interrupted in the process and comes back to it, the search will be for that old time.

I propose changing the button to the words "Now"  and "Today" by default, then if the user touches either of those, or the Dep/Arr or +15 buttons, it will change to the time.  Then Now and Today will be replaced by the current time/date when the user clicks Search.

**Comment by grote** [comment]
Normally, the time should be reset when it is in the past and the activity is reloaded, but there might be a bug.

Thanks for your UI proposal! Sounds indeed like a good idea!

**Comment by grote** [comment]
Btw. hidden feature, if you long press the time or date button, it gets also set to current time.
