### ISSUE TITLE
Line name in departures is single line only

### ISSUE THREAD

**Issue by patkan** [grote/Transportr#237]
I am currently trying out the new France North West provider. Basically it seems to work fine. I will use it some more, but I think this will soon be beta-worthy.

However, I have found a weird interface-glitch. When I am searching for departures there are some dots on the upper border of the tiles. (Please see the screenshots below.) I first thought it were something like diacritics, but the second screenshot insinuates that it might be cut off text.
![screenshot_2016-09-29-12-40-34](https://cloud.githubusercontent.com/assets/4189642/18950900/90fab5e0-8642-11e6-8758-2869ca3c8e78.png)
![screenshot_2016-09-29-12-42-23](https://cloud.githubusercontent.com/assets/4189642/18950922/a4bc67b8-8642-11e6-8bcf-4e82e78d70d2.png)

Now to my question: How do I debug something like this? I would like to now where this does come from. I could not observe this behavior with other providers (I tested BVG and VBB).

**Comment by patkan** [comment]
Ok, I haven't seen that before but I think the Text is very long, as the lower text parts seem not be complete. So this is probably the whole text that wraps up. How could I fix something like that. (I mean, I can't really change the data that comes from the provider.)

**Comment by grote** [comment]
Thanks for reporting! Looks like a UI glitch indeed. This needs to be fixed in the layout XML, but can be tricky if you don't have experience with it.

**Comment by patkan** [comment]
I try to learn Android a bit, so I had a look. (But probably I won't be able to fix this properly.)
I found out where this would have to be fixed: `res/layout/departure.xml`. (Correct?)

How about simply ellipsizing in the middle?
Like this:
![screenshot_2016-09-29-20-35-11](https://cloud.githubusercontent.com/assets/4189642/18967339/129746a8-8685-11e6-999d-09fb32158a52.png)

At least in this example it would suffice to always guess the meaning. At least I don't know how to make a dynamically resizing layout :-)

**Comment by grote** [comment]
I'd prefer dynamically re-sizing the height, but I'd recommend not to learn Android layout with this example ;)

If you want to learn Android layout, forget the old stuff and learn the new `ConstraintLayout`. I'm planning to migrate the tricky views to that one eventually.

**Comment by patkan** [comment]
OK, thank you for the hint. I will leave this for now and get a PR for the strings-stuff together. Maybe I have then the time to learn something.
