### ISSUE TITLE
 "IllegalStateException: unknown error: Fehlerhaftes Ziel"

### ISSUE THREAD

**Issue by wasamasa** [grote/Transportr#244]
I've tried out your app from the Android store, picked Germany/VRS, then entered two locations at the search in hope of getting suggestions for the respectively named train stations.  Instead I got a toast with an error message as in the title.  To ensure that core functionality is still working, I picked the map selection option to choose the targets manually and got the search working this way.

**Comment by patkan** [comment]
Could you please add the names that you tried? I just tried to reproduce it and entered "Hansaring 1" to " Chlodwigplatz 1" and it worked without any problems.

**Comment by wasamasa** [comment]
Thanks for the suggestion!  It looks as if this happens if you enter a location and fail picking any of the suggested stops from the dropdown menu, be it because you don't get any dropdown menu in the first place (which was the case for me) or because you deliberately ignore it and proceed with the search (which I did now to narrow down the problem).  This way one can trigger an "IllegalStateException: unknown error: Fehlerhafter Start" as well.

I'll still keep this open because it's a rather unexpected error, maybe one could highlight the offending user interface element to direct the user of the app into correcting their error?

**Comment by grote** [comment]
The expected behavior is that the `VrsProvider` handles the `AMBIGIOUS` location and offers a list of locations to choose from instead of throwing an error. We would need to ask @schildbach from upstream public-transport-enabler if that is indeed expected and if so, why the  `VrsProvider` deviates from that expectation.

**Comment by grote** [comment]
This behavior should be improved in the upcoming Transportr v2.
