### ISSUE TITLE
Austrian providers require API authorization

### ISSUE THREAD

**Issue by tbart** [grote/Transportr#249]
Austria's VOR/ÖBB routing stopped working a few months ago with the given exception.
It seems upstream have changed their API.

**Comment by tbart** [comment]
logcat:

```
10-28 11:40:08.643 21052 25098 D AsyncQueryTripsTask: From: Location{ANY, IS_AMBIGUOUS, place=wien hauptbahnhof, name=wien hauptbahnhof}
10-28 11:40:08.644 21052 25098 D AsyncQueryTripsTask: To: Location{ANY, IS_AMBIGUOUS, place=wien rennweg, name=wien rennweg}
10-28 11:40:08.644 21052 25098 D AsyncQueryTripsTask: Date: Fri Oct 28 11:40:08 GMT+02:00 2016
10-28 11:40:08.644 21052 25098 D AsyncQueryTripsTask: Optimize for: LEAST_DURATION
10-28 11:40:08.644 21052 25098 D AsyncQueryTripsTask: Walk Speed: NORMAL
10-28 11:40:10.442 21052 25098 W System.err: java.lang.RuntimeException: uncategorized problem while processing https://efa.vor.at/vor/XSLT_TRIP_REQUEST2
10-28 11:40:10.442 21052 25098 W System.err: 	at de.schildbach.pte.AbstractEfaProvider$8.onSuccessful(AbstractEfaProvider.java:2065)
10-28 11:40:10.442 21052 25098 W System.err: 	at de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:208)
10-28 11:40:10.442 21052 25098 W System.err: 	at de.schildbach.pte.AbstractEfaProvider.queryTrips(AbstractEfaProvider.java:2071)
10-28 11:40:10.442 21052 25098 W System.err: 	at de.grobox.liberario.tasks.AsyncQueryTripsTask.doInBackground(AsyncQueryTripsTask.java:112)
10-28 11:40:10.442 21052 25098 W System.err: 	at de.grobox.liberario.tasks.AsyncQueryTripsTask.doInBackground(AsyncQueryTripsTask.java:42)
10-28 11:40:10.442 21052 25098 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
10-28 11:40:10.442 21052 25098 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-28 11:40:10.442 21052 25098 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
10-28 11:40:10.442 21052 25098 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-28 11:40:10.442 21052 25098 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-28 11:40:10.442 21052 25098 W System.err: 	at java.lang.Thread.run(Thread.java:818)
10-28 11:40:10.442 21052 25098 W System.err: Caused by: java.lang.IllegalStateException: expecting attribute: version
10-28 11:40:10.442 21052 25098 W System.err: 	at de.schildbach.pte.util.XmlPullUtil.attr(XmlPullUtil.java:120)
10-28 11:40:10.442 21052 25098 W System.err: 	at de.schildbach.pte.AbstractEfaProvider.enterItdRequest(AbstractEfaProvider.java:3127)
10-28 11:40:10.443 21052 25098 W System.err: 	at de.schildbach.pte.AbstractEfaProvider.queryTrips(AbstractEfaProvider.java:2168)
10-28 11:40:10.443 21052 25098 W System.err: 	at de.schildbach.pte.AbstractEfaProvider.access$1200(AbstractEfaProvider.java:92)
10-28 11:40:10.443 21052 25098 W System.err: 	at de.schildbach.pte.AbstractEfaProvider$8.onSuccessful(AbstractEfaProvider.java:2061)
10-28 11:40:10.443 21052 25098 W System.err: 	... 10 more
```

**Comment by grote** [comment]
Thanks for reporting. This should be fixed by https://github.com/schildbach/public-transport-enabler/commit/a59d696a42daf3366de302721fbfdbbfb5304518 will need to update the library and make a new release.

**Comment by grote** [comment]
Unfortunately, the `VOR` provider as well as the `SVV` provider now require an authorization secret to use their API. I will need to disable them until somebody gets such a secret for Transportr. Would you like asking these companies to provide a authorization token for their JSON API?

**Comment by tbart** [comment]
Could you please provide a little more reference (e.g. the URL of the APIs used, some kind of info page of the respective providers' API services) so they know what I am talking about?
I'll see what I can do, then!

**Comment by grote** [comment]
Unfortunately, I don't know any info pages or contacts at those providers. All I can give you is the API URLs from the public transport enabler source:
* VOR: https://anachb.vor.at/bin/
* VMOBIL: http://fahrplan.vmobil.at/bin/
* OOEVV: http://verkehrsauskunft.ooevv.at/bin/
* SVV: https://fahrplan.salzburg-verkehr.at/bin/

**Comment by grote** [comment]
VVT is now affected as well :(

**Comment by sirnone** [comment]
little Information from Austria:
There is a new Projekt from most Austrian transport providers named [VAO](http://www.verkehrsauskunft.at)
the Idea is to have one Plattform for the country and save some Money on new Developments.

the problem on this system is, that every call to the API's is counted and has to be payed (also from the members) to get the money for new features.

so i can't see an chance to get an new API URL in next time for Austria...

**Comment by tbart** [comment]
Great. They ruined it.
Will we have to pay for using their fahrplan.oebb.at and friends as well?!
Though a horrible solution, parsing e.g. https://anachb.vor.at output could be a solution for everything in eastern Austria. I'm good with bash, regexps and a little perl, but I won't be of any help with java..

**Comment by tbart** [comment]
VAO backend has at least re-enabled my usual Viennese VOR queries and works nicely here!
Station names have changed, so using old favorites does not work (noting this just for reference).
I think this issue can be closed?

**Comment by grote** [comment]
Yes, thanks for the feedback!
