### ISSUE TITLE
VGN provider does not list addresses

### ISSUE THREAD

**Issue by patkan** [grote/Transportr#258]
When I was testing for #257 I found that the VGN provider changed behavior between 1.1.5 and the current master at 571996f750aa1b60e3b33f6c90155765bf968b2e. When I entered something like the street name "Hauptstraße" in 1.1.5 I would get a list of stops, POIs and addresses in the dropdown of the DirectionFragment.
When I do the same in current master then only stops are proposed. The handling of ambigous directions by just entering them still works and also finds POIs, but the propositions in the dropdown consist only of stops.

I seem to not get this behavior with other providers. Can someone reproduce this? Maybe this is an upstream issue? (In this case I would report it upstream, but I haven't found the change yet)

**Comment by grote** [comment]
Maybe it has do do with this? https://github.com/schildbach/public-transport-enabler/commit/b18ec864a9696d2fbe135e01fb3bc3addfc754dc

**Comment by patkan** [comment]
Thank you for the find. This could be the case since I also saw some Unicode issues that I shrugged of as unrelated.
I will investigate this and create an issue against pte if needed.

**Comment by grote** [comment]
Was closed upstream and will be fixed here soon.
