### ISSUE TITLE
Support Mexico City

### ISSUE THREAD

**Issue by valessiobrito** [grote/Transportr#259]
This issue is to join efforts to register and activate the application for Mexico City.

**Comment by grote** [comment]
Great! Let me know if you guys need any help or guidance.

**Comment by grote** [comment]
Mexico City [is already in Navitia](https://navitia.opendatasoft.com/explore/dataset/mx/table/?sort=type_file), so it should be relatively easy to add it to Transportr [as explained on the homepage](https://transportr.grobox.de/#add_region).

**Comment by grote** [comment]
This ticket is quite old and nobody took it up. I am not living in this country and can't do it. Let's close it until someone has added support for this country in public transport enabler.

As a reminder, the process for adding support for a new region is described on the homepage: https://transportr.app/contribute/#translating-into-your-language
