### ISSUE TITLE
San Francisco is broken

### ISSUE THREAD

**Issue by boconnell** [grote/Transportr#261]
Steps to repro:
Choose San Francisco Bay Area as network in Settings
Try to navigate between 2 points within SF proper (for example from 37.7789/-122.43 to 47.7775/-122.41)
Observe error toast:
![error toast](https://cloud.githubusercontent.com/assets/2806089/20444888/bdf5e1d4-ad87-11e6-95ff-b3ff541d0433.png)

**Comment by grote** [comment]
Thanks for reporting! Unfortunately, you reported against the wrong project. See here: https://github.com/grote/Transportr/blob/master/CONTRIBUTING.md#creating-issues

**Comment by schildbach** [comment]
Yes, it looks like as if they switched away from EFA.

**Comment by boconnell** [comment]
What is EFA? Sorry, unfamiliar with the acronym

**Comment by schildbach** [comment]
EFA = Elektronische Fahrplanauskunft. In this case this means a product by the Munich company "Mentz DV".

**Comment by grote** [comment]
So to explain further, if SF moved to a different company's product, it can only be supported further if that product can also be accessed by PTE. If it can't, somebody would need to add support to whatever API they use now.
