### ISSUE TITLE
Set Home only seems to accept stops, not addresses

### ISSUE THREAD

**Issue by joaobarcia** [grote/Transportr#262]
Hi all. Have been using the app for some time now. Great job! Better than most official apps in every city I've tried.

The only minor issue for me is that when I try to Set Home, the dropdown options only present transport stops, not addresses. The closest stop is 5min walk from my place and would not generate optimal results as my house is in the middle of several stops.

Am I missing something, or is it not possible to select addresses as Home?

My use case is Android 7.1 and Transport system BVG.

**Comment by grote** [comment]
Thanks for the report! The same thing is already tracked as #32. Therefore, I will close this one.

**Comment by joaobarcia** [comment]
Ah, great. Thanks for the quick feedback. My search-fu had not returned any results.
