### ISSUE TITLE
Navitia: Wrong Destination of Departures

### ISSUE THREAD

**Issue by tenminutemail** [grote/Transportr#274]
Hi,

I realized that there is one more problem with some data offered by Navitia.

If I look up departures for Spain in Navitia, I get this result:
![departure](https://cloud.githubusercontent.com/assets/23173049/21009437/d6ad9540-bd46-11e6-88f9-cb72c27da9f8.png)

In Transportr, the data misbehaves and I get this result, where one train lines is only going into one direction and the other train line only goes into the other direction:

![dep2](https://cloud.githubusercontent.com/assets/23173049/21009496/39a260fe-bd47-11e6-82d5-d05731ce97db.png)

Anyone can help? Is this related to PTE?

It's not a big problem, anyway it would be nice to fix it ;)

**Comment by patkan** [comment]
I think this is a bug in PTE or Navitia.
Could you please check if you can find the "same" stop multiple times?

In FranceNorthWest I can find e.g. `IUT, Rennes` twice or `République, Rennes` even more.
I can find all the single stops and they are not grouped as an area. (I think this is how it is called.)
So when I search for the one "IUT", I only find departures in the one direction that leave at exactly this stop. When I choose the other one I find the others.
I haven't looked at the code, but I think this might be the problem here.

**Comment by grote** [comment]
Also, could you post a link to that Navitia query? What I am seeing here in JSON returned from Navitia seems to match what Transportr shows.

**Comment by tenminutemail** [comment]
@patkan thanks for your reply. I'm afraid this isn't the case here: there is only one stop, so that works fine.

@grote thanks for the reply, as well. Here is the [link to the query.](https://api.navitia.io/v1/coverage/es/stop_areas/stop_area%3AE39%3ASA%3ACTP-E3915/departures?from_datetime=20161213T130000&)

What transportr shows istn't exactly the same as what Navitia does. Navitia shows me that there is a train called S1 (see my first screenshot): at 13.04 it goes to `Terrassa Nacions Unides`, the other S1 train at 13.07 goes to `Pl. Catalunya`. In Transportr just every S1 train goes to `Pl. Catalunya`. 

That's somehow a strange behaviour, because looking up a direct connection works like a charm.

**Comment by grote** [comment]
I debugged this a bit more and it looks to me like this is a Navitia bug:

Have a look at the `display_informations`, there it says correctly `Terrassa Nacions Unides (Terrassa)`. Transportr however needs a proper `stop_area`, so it takes the information from `route.direction` and there it suddenly says `Pl. Catalunya (Barcelona)`.

![screen shot 2017-01-07 at 16 34 27](https://cloud.githubusercontent.com/assets/244947/21744116/37ec197c-d4f7-11e6-9c8d-fc58948b1361.png)

**Comment by grote** [comment]
I asked Navitia about this here: https://groups.google.com/forum/#!topic/navitia/7TZQcxnaU2Q

**Comment by ialokim** [comment]
See also https://github.com/CanalTP/navitia/issues/1931 to follow up on this issue.
