### ISSUE TITLE
Dubai & ATC (Italy) not working

### ISSUE THREAD

**Issue by tenminutemail** [grote/Transportr#276]
Hi,

While looking for some new logos, I realized that two providers don't work:

- Dubai. Can someone check if it stopped working or if it's only me?

- ATC (Italy) also stopped working. On their [homepage](http://atc.bo.it/), there is some information that this network was integrated into a new one called TPER, they also have some open data available: http://www.tper.it/tper-open-data

**Comment by grote** [comment]
Thanks something to report against PTE primarily.
