### ISSUE TITLE
Allow external apps to query Transportr via Service

### ISSUE THREAD

**Issue by mar-v-in** [grote/Transportr#28]
Move connection/station retrieval to an exported service (with permission required), so that applications may contact Liberario for connections and nearby stations.

This could be used eg. to display nearby stations in a map application or to show a notification if one should go to the next bus station to be on time for the next calendar event (sounds like an epic feature, but should not be part of Liberario directly - i don't think you want a big ball of mud)

Moreover I think moving network stuff to a service (ideally aidl based) could make the application code cleaner and more straight-forward.

**Comment by grote** [comment]
This ticket is quite old and nobody has worked on it until now. I personally don't have time to work on it in the foreseeable future. Since there are many other open tickets, let's close this one until someone is interested in the implementation.
