### ISSUE TITLE
Tabbing on current network should go to network picker view

### ISSUE THREAD

**Issue by sedrubal** [grote/Transportr#282]
IMHO it was more intuitive to go to the "pick a transportation network" view after tabbing on the icon of the current network in the side bar instead of closing the side bar.

**Comment by grote** [comment]
I think the default logic is that tapping on one of the logos selects the corresponding transport network. But I wouldn't mind if somebody would change this, so that the network picker would open  when the currently selected transport network is clicked.

**Comment by bugzillus** [comment]
Thanks!
