### ISSUE TITLE
Adding Algeria to Transportr

### ISSUE THREAD

**Issue by BoFFire** [grote/Transportr#283]
Hi, grote :)
I'm a contributor in #OSMAlgeria and I was watching your conference about Transportr app :) and let me say that you are doing a great job.
The community is betatesting some FLOSS apps over OSM, such as OSMAnd, MapsMe, Vespucci ... and we would like to ask you if you can add Algeria (zoom on Algiers the capital) so that we can betatest our contributions.
Link 1 : https://www.öpnvkarte.de/#3.0627;36.7415;11
Link 2 : http://openptmap.org/?zoom=12&lat=36.74777&lon=3.06067&layers=B0000TFFT
Link 3 some betatesting by me : https://www.öpnvkarte.de/#4.6311;36.5994;15
Nah ! They are not using GTFS ! **(*they*)** ;) you know.
Their static data look like : http://www.urbanrail.net/af/alg/algiers.htm
So we want to have something visual to create a simulation. The only data we have are static and concerns train transportation that you can find on this website : http://www.sntf.dz/
(Hope that foreign IP addresses are not banned to consult that site too ;) )
In english it looks like "Woow ! MySQL stuff ! Hoho :D ) : http://www.sntf.dz/en
If you need additional information, please ping us on the section Algeria in the official [OpenStreetMap forum](https://forum.openstreetmap.org/viewforum.php?id=53) :)
Have a nice day and ... happy new year ;)
Salutations amicales.

**Comment by grote** [comment]
@BoFFire Thanks for watching my presentation!

Unfortunately, I can't add new regions all by myself. I have barely enough time to maintain Transportr and my other software initiatives. That is why I give presentations and publish all my knowledge and tools for other people to do the work for their region. Check out this section on the homepage if you haven't already: https://transportr.grobox.de/#add_region

I'd be glad to help somebody to take this on for Algeria, but I can't do it all by myself.

**Comment by okbus** [comment]
Hi @ghost,
Any chance for you to add Algeria into the project ?
