### ISSUE TITLE
Language of name of places

### ISSUE THREAD

**Issue by Airon90** [grote/Transportr#286]
Are name of cities and regions written in English or in the local language?
Some places are written in English (Upper Austria, Saxony) while other are written in local language (Corse, Roma, Milano, Venezia).
Let's decide a standard and adapt all names.

**Comment by grote** [comment]
in `values/strings.xml` the names should be in English.

**Comment by Airon90** [comment]
Ok, I'm assigning this bug ;)

**Comment by grote** [comment]
Fixed by  684a7d1

**Comment by Airon90** [comment]
I didn't check all names as yesterday I didn't have much spare time. That's why I added (1/2). Today I'll check all the remaining places ;)
