### ISSUE TITLE
Added transport data to Navitia, isn't showing up in Transportr

### ISSUE THREAD

**Issue by ericblank** [grote/Transportr#292]
How long does it take to appear?

**Comment by patkan** [comment]
@ericblank It depends on which data you are referring to. If it is part of a region that Transportr already supports in the form of a provider it should be available as soon as it is in Navitia. You can check that with the Navitia Playground. This is not part of this project, so you should best check with Navitia if you've got problems in that direction.

If you are referring to "new" regions the answer is simply never, unless someone adds it. You can do that yourself by following the procedure described on this project's website.

**Comment by grote** [comment]
@ericblank after @patkan's answer, is there anything left that needs to be tracked within Transportr? If not, please close the ticket.

**Comment by ericblank** [comment]
I'll check the website about adding the new region. I added the data to Navitia for Torrance Transit (Torrance CA) and Los Angeles Metro, via their Google Group, and they said it was added. I also see the LA section on the playground.

In Transportr, I only see two transit services under United States, neither are the ones I added. Is the FDroid version the most recent?

**Comment by grote** [comment]
Yes, it is the most recent version.

Please see the homepage for how to add a `CaliforniaProvider` for the navitia [`us-ca`](https://navitia.opendatasoft.com/explore/dataset/us-ca/) region.
