### ISSUE TITLE
Adding Lyon to Transportr

### ISSUE THREAD

**Issue by Montagnard65** [grote/Transportr#293]
Hi,
Like many others issues, I would like to add Lyon to Transportr. I have already ask Navitia to add the data, and the job is done now : http://canaltp.github.io/navitia-playground/play.html?request=https%3A%2F%2Fapi.navitia.io%2Fv1%2Fcoverage%2Ffr-se%2Fcontributors%2FDGL%2Flines%3Fcount%3D200%26
I read the web that described the next step and I read the same others issues too, but I'm not a dev (and of course I don't have a dev environment...), so I don't understand at all what I have to do for adding my city...
If any one can help, it could be great !

Thanks !

**Comment by grote** [comment]
I wish it was always that easy, but in this case it should be. Lyon should be in the French South East region which is already in Transportr. Could you please verify and close this issue if this is indeed the case?

**Comment by Montagnard65** [comment]
Hi @grote ,
Thanks for your quick reply.
In Transportr, it's indicated Rhone-Alpes district (where Lyon is) is in the south east part of France, and in Navitia, it's indicate "fr-se" which means I can imagine South East. Is it the verification you want ?

**Comment by grote** [comment]
Yes, if you want you could update the description of the fr-sw provider so it mentions Lyon (and maybe other cities that have been added in the meantime).

**Comment by Montagnard65** [comment]
Yes, of course, where can I do that ?

**Comment by patkan** [comment]
Hi @Montagnard65 the easiest way is to do it on GitHub. You go to this file https://github.com/grote/Transportr/blob/master/res/values/strings.xml#L249-L250
This file describes all of the text that is used in the app in english language. You will have to click on the edit button in the top right corner of the code that you are seeing. Then you can change the lines 249 and 250. Please also update the names of the supported operators.

When "saving" you enter a commit message that should describe what you have changed. The other languages have then to be edited in Transifex by the translation teams. If you want to you could e.g. join the French team. (Transifex is a translation platform and you don't need to know any coding for it)

Feel free to ask if you have any questions.

**Comment by Montagnard65** [comment]
Hi @patkan,
Sorry for my late reply... Thanks for your advices, I did the job with a fork of the mentionned file, I modified the lines 257 and 258. Is it ok for you ?

**Comment by patkan** [comment]
Hi @Montagnard65 looks good.
One last thing that you have to do: You have to create a Pull Request which asks for the changes to be included.
For this you can click on Pull Request besides the box where you can select the branch.
This link should probably get you there if you don't find it: https://github.com/grote/Transportr/compare/master...Montagnard65:patch-1?expand=1
It has to be from your patch-1 branch against grote/master.

**Comment by Montagnard65** [comment]
OK, thank you. I think it's good now.
Anything else to do ?

**Comment by patkan** [comment]
Not really ;-)
