### ISSUE TITLE
[DE] Some trains do not show up

### ISSUE THREAD

**Issue by bugzillus** [grote/Transportr#299]
Einige Züge werden nicht angezeigt, obwohl sie existieren und pünktlich fahren. Beispiel: Hannover Hbf <> Berlin Hbf, hier werden fast alle IC ausgeblendet und nur die ICE angezeigt.

Vermutliche Ursache: Die Bahn-Reiseauskunft (rabdc.bahn.de) hat standardmäßig "Schnelle Verbindungen bevorzugen" aktiviert und zeigt dann gleiches Verhalten. Erst wenn dies abgewählt wird, werden alle Züge bzw. hier auch die IC angezeigt.

Transportr fehlt dieser Schalter. Solange er nicht aufgenommen wird (vielleicht unnötig), bitte die Abfrage-Parameter unbedingt so setzen, dass "Schnelle Verbindungen bevorzugen" nicht aktiviert ist. Danke.

(Es gibt inzwischen einen weiteren Parameter: "Zusätzlich nach alternativen Verbindungen auf Basis der aktuellen Verkehrslage suchen" und ist standardmäßig aktiviert. Was die Abwahl bewirkt, erschließt sich nicht.)

**Comment by grote** [comment]
Helfen andere Einstellungen fuer "Optimiert fuer" ?

**Comment by bugzillus** [comment]
Nein. Das scheint eine andere Unterscheidungs-Ebene zu sein bzw. lässt sich die Priorität "geringste Dauer" nur durch Umstiege/Fußweg ersetzen, was beides im Fall von Hannover Hbf <> Berlin Hbf irrelevant ist (keine Umstiege, gleicher Fußweg) und daher zu keiner anderen Anzeige führt. (Wäre hier ein Feld "Keine Priorisierung" sinnvoll/möglich?) Die Frage ist vermutlich, welcher Parameter bei der HAFAS-Abfrage gesetzt werden muss, um "alle" Züge zu bekommen (auch die langsameren).

**Comment by grote** [comment]
Der PTE bietet nur diese drei Optionen: https://github.com/schildbach/public-transport-enabler/blob/master/enabler/src/de/schildbach/pte/NetworkProvider.java#L55

Falls es irgendwann mal mehr Optionen gibt, können diese für Transportr berücksichtigt werden. Bis dahin gibt es hier nichts weiter zu tun.

Um der Sache mit den nicht angezeigten Zuegen auf den Grund zu gehen, am besten DB app, webseite und Oeffi Ergebnisse vergleichen und die Differenzen beim PTE als Ticket anlegen. Transportr zeigt nur an, was es vom PTE bekommt.
