### ISSUE TITLE
[DE] Mean of transport / train selection enhancements needed

### ISSUE THREAD

**Issue by bugzillus** [grote/Transportr#300]
Zur "Verkehrsmittelauswahl" folgende Bitte um Ergänzung:

1. Es gibt in Transportr bislang keine Unterscheidung des Fernverkehrs in ICE (DB: "Produktklasse A") und IC/EC (DB: "Produktklasse B"). Da beide unterschiedlich tarifiert bzw. die Fahrkarten entsprechend ausgestellt sind, wäre zumindest für Deutschland diese Unterscheidung sehr wichtig.

2. Für Aktionstickets (z. B. Wochenendticket, Ländertickets) gab es bisher bei der DB die sehr hilfreiche Checkbox "nur Nahverkehr". Diese ist wohl bei der DB nun in die Auswahl-Reihe integriert, was inkonsistent ist (D/IRE ist auch Nahverkehr, U-Bahn und Tram/Bus nur bedingt, in Berlin bspw. bei manchen Aktionstickets schon, im Vor-/Nachlauf zum Fernverkehr nicht). Der Aus-/Einschluss von Fähre, Seilbahn und AST scheint jedoch bei der Nutzung von Transportr kaum erforderlich, da über einen Via-Punkt im Zweifel eine unerwünschte Fähre/Seilbahn auch umgangen werden kann und AST meist nur fahren, wenn sonst nichts anderes geht.

3. Daher mein Vorschlag für Neugestaltung der Auswahl-Checkboxen:
- ICE ("high speed train")
- IC/EC ("long distance train")
- NV oder R ("local train", D/IRE, RB/RE, Regionalzüge privater Unternehmen)
- S
- U
- Tram/Bus
- Fahrradmitnahme
- Barrierefrei

4. Hilfreich wäre, wenn die Logos auch von den Farben her den offiziellen Piktogrammen entsprechen oder nachempfunden wären (im Bedarfsfall kann ich mich einbringen) und ohne Umweg über zusätzlichen Dialog direkt ausgewählt werden können. Hier ist Öffi schön gemacht: ausgewählt = farbig, abgewählt = hellgrau.

**Comment by grote** [comment]
Bitte nur ein Ticket pro Anliegen.

Zu 1: Die von Transportr verwendete API gibt diese Unterscheidung leider nicht her. Dort gibt es nur [diese Produkte](https://github.com/schildbach/public-transport-enabler/blob/master/enabler/src/de/schildbach/pte/dto/Product.java#L27). Es muesste dort ein Ticket angelegt werden.

Transportr funktioniert in weiten Teilen der Welt (nicht nur in Deutschland und im Netz der DB), deswegen ist die Farbgestaltung ganz bewusst neutral gehalten.
