### ISSUE TITLE
Enhancement: More train info possible?

### ISSUE THREAD

**Issue by bugzillus** [grote/Transportr#302]
Sometimes, it would be helpful to know the stations/departure times of a train before or after a selected route as well (e. g. to consider a faster way from A to B).

The extended train view (rabdc.bahn.de/bin/traininfo.exe) contains helpful additional information (train features for families, wheel chair places, bike transport, ...).

Would it be possible to somehow toggle an extended "full train info" or have an extra window with the information?

**Comment by grote** [comment]
Unfortunately, the API used by Transportr doesn't allow for that. You would need to file a ticket for that with the public transport enabler.
