### ISSUE TITLE
Vector maps?

### ISSUE THREAD

**Issue by jnytucep** [grote/Transportr#306]
Does transportr support the use of on device vector maps via mapforge adapter for osmdroid?

**Comment by grote** [comment]
v2 will support vector maps, but not via the adapter you talk about. Do you have more information/documentation about this?

**Comment by jnytucep** [comment]
I believe this is the repo: https://github.com/MKergall/osmbonuspack/tree/master/MapsForgeForOsmdroid

**Comment by grote** [comment]
Thanks, but doesn't look like something I would want to use with this binary jar as a dependency.
