### ISSUE TITLE
Bicycle routing

### ISSUE THREAD

**Issue by ghost** [grote/Transportr#307]
Many cities have bike racks on all buses. Is there a way to select cycling instead of walking?

The faster speed of cycling over walking means more options for transfers and potentially faster routes.

**Comment by grote** [comment]
Bicycle routing is out of scope of the project (for now), but contributions are welcome. PTE has a `BIKE` option, but I think it is only for when you want to take a bike on the train. Some providers also support a cycling to  station option, but I don't know if that is exposed via PTE properly.

**Comment by jnytucep** [comment]
Ok, would you like me to close this issue for now?

**Comment by Echolon** [comment]
Is this a duplicate refering to https://github.com/grote/Transportr/issues/84 ?

**Comment by grote** [comment]
I think #84 is phrased a little more specific, but generally they seem to refer to the same issue.

**Comment by comradekingu** [comment]
[GraphHopper](https://www.graphhopper.com/) and [Mapzen](https://mapzen.com/products/turn-by-turn/) are the alternatives for bicycle routing on openstreetmap.org, though i think OsmAnd+ uses a custom thing, one could launch that, if installed.

**Comment by grote** [comment]
This ticket is quite old and nobody has worked on it until now. I personally don't have time to work on it in the foreseeable future. Since there are many other open tickets, let's close this one until someone is interested in the implementation.
