### ISSUE TITLE
Add seting for showing trip (list) over the lockscreen

### ISSUE THREAD

**Issue by OffifialMITX** [grote/Transportr#308]
If you open the view of a road and lock the screen its still shown when you unlock the screen.

**Comment by TheLastProject** [comment]
This is a feature, not a bug

**Comment by OffifialMITX** [comment]
Well then it would be nice if you could give an option to deactivate it because its only causing problems on my phone.

P.S. This is what a friend of mine says every time I tell him that I have a problem with a program ;-)
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by grote** [comment]
If this is causing problems, maybe we should rather try solving the problems. What kind of problems is it causing? Are there steps to reproduce them on other devices?

**Comment by mark-orion** [comment]
I am not experiencing any real problem with this, but I would appreciate a setting that allows to disable this feature for security reasons and to give people peace of mind. I am aware of other people who use transportr and who are concerned about this.

**Comment by OffifialMITX** [comment]
My problem is that for some reason, when I try to unlock my screen after closing that window and waiting like 10 seconds the whole androids UI crashes and is being restarted.

Anyway, it's probably not Transportr's fault since it's not the only app I have problems like this.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.
