### ISSUE TITLE
Favorites list covered by suggestions 

### ISSUE THREAD

**Issue by ByteHamster** [grote/Transportr#309]
Using version 1.1.7

The "from" text field is focused by default, which shows the popup list of recent places. This list covers the favorites, so I need to click the back button before choosing a favorite. Is this intended behavior?

**Comment by grote** [comment]
It used to be the intended behavior, but is not necessarily anymore (now where we have favorite trips on the first screen). Was it different with 1.1.6?

I think the reason is that the input field automatically grabs focus and thus shows the drop-down.

**Comment by ByteHamster** [comment]
Using version 1.1.6, the input field is not focused by default. Thus, the popup is not directly opened.

**Comment by grote** [comment]
Thanks for checking. So it is an unintended regression. Feel free to submit a PR for the v1 branch. I am pretty busy and focus all available time on the master branch.

**Comment by grote** [comment]
Looks like this solved itself in the latest 1.1.8 release. Can anyone confirm?

**Comment by ByteHamster** [comment]
Going to test as soon as it's available on F-Droid. I don't know why this takes so long.

**Comment by grote** [comment]
Some problem with the build server: https://f-droid.org/wiki/page/de.grobox.liberario/lastbuild_48

**Comment by ByteHamster** [comment]
Fixed for me too.
