### ISSUE TITLE
Idea: Suggest whether we should be in front or rear of the subway

### ISSUE THREAD

**Issue by Phyks** [grote/Transportr#310]
Hi,

Citymapper app has a nice feature which is that it tells the user whether they should take the subway in the front car, rear car or middle car, to be as close as possible to their exit or connection afterwards, so as to optimize a bit more the route.

I am not sure how including such feature is feasible, but it would be really great to see this appearing in Transportr as well! I am not sure such dataset of the location of exits compared to the trains positions is available anywhere, but it could be quite easily built by asking users to fill-in the data in Transportr, if they are willing to.

Thanks for this great app!

**Comment by grote** [comment]
Thanks for this idea. Would be a nice feature to have indeed. However, I have no idea where to get this information from. It is certainly not available at the moment. Does Citymapper provide this feature for all the regions they support?

You are welcome to research where they get the information from. Then, you would need to find out how to get this information for all regions that Transportr supports and then integrate this into PTE before it can be added to Transportr. Therefore, I am closing this ticket for now.

**Comment by Phyks** [comment]
Hi,

I think Citymapper built its own dataset, mainly by asking their users to report this information. I am not aware of any available datasets, to date. But I know Citymapper offers this service for almost all the covered regions (at least I always saw this service being available when traveling).

I was mostly suggesting that perhaps Transportr could display the information if available, and offer a way to fill-in this information when looking for a route, if the information is not available yet. This way, it could build up an alternative (open) dataset containing the closest exits.
