### ISSUE TITLE
Searching for nearby stations by GPS does not show the results

### ISSUE THREAD

**Issue by RunasSudo** [grote/Transportr#314]
Version: 1.1.7

When going to ‘Nearby Stations’ from the side menu and selecting ‘Use Current Position’, GPS is activated, and the location box is updated with the current GPS position. Network requests are then made, but the results are not shown on the screen.

This appears to be due to the following line in `NearbyStationsFragment`, since `deactivateGPS` is called from `LocationGpsView` when the GPS lookup completes:

```java
LocationGpsView.LocationGpsListener listener = new LocationGpsView.LocationGpsListener() {
	...
	@Override
	public void deactivateGPS() { ui.stations_area.setVisibility(GONE); }
```

Removing this statement fixes the issue and results are shown as expected.

**Comment by grote** [comment]
This should be fixed with the latest 1.1.8 release. Please let me know if it isn't!
