### ISSUE TITLE
Upstream pull requests are languishing

### ISSUE THREAD

**Issue by jlingod** [grote/Transportr#315]
Many [PR](https://github.com/schildbach/public-transport-enabler/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20add%20provider%20) containing new regions from [Public Transport Enabler](https://github.com/schildbach/public-transport-enabler) have been waiting to be merged for quite a while. Is there any way to assist upstream to get these merged in a more timely manner?

Alternatively, is a fork and/or more active maintainer needed to allow more people to use your app? It's holding up many potential users.

**Comment by grote** [comment]
> Many PR containing new regions from Public Transport Enabler have been waiting to be merged for quite a while.

That seems to be a correct observation.

> Is there any way to assist upstream to get these merged in a more timely manner?

This question should be directed at upstream. I suggest you get in touch with @schildbach, the upstream maintainer, if you haven't done so already.

> Alternatively, is a fork and/or more active maintainer needed to allow more people to use your app? It's holding up many potential users.

My recommendation would be to exhaust all other means of resolving your problem before seriously considering a fork.

**Comment by rugk** [comment]
Currently 6 open ones. Is this situation better than in February? (Some old ones are still not merged.)

**Comment by grote** [comment]
In the linked upstream issue, the hesitation is explained and it is mostly about Navitia-based providers which indeed tend to have lower quality than the other ones.

**Comment by rugk** [comment]
Hmm… okay.

**Comment by grote** [comment]
Providers can be [added to the staging project](https://gitlab.com/opentransitmap/public-transport-enabler) now after a proper PR has been made to PTE upstream.
