### ISSUE TITLE
Trip details

### ISSUE THREAD

**Issue by jamescr** [grote/Transportr#321]
I have been testing the app downloading the master branch and compiling it. I've doing this mainly to test a provider that isn't yet available in the public-transport-enabler.  

I had used a prior version of Transportr but unfortunately I don't remember the version,i think it was a January version,  lets say it was version XX.   Now I have installed the 1.1.7 version. 

In 1.1.7 version I don't now how to open the trip detail. In version XX I just tap over a suggested trip and the stops and change of lines details where displayed, but don't know how to see tat info in version 1.1.7. 

My phone is a LG G3 with Android 4.4.2.

**Comment by grote** [comment]
The master branch is for ongoing Transportr v2 development. Please check out and try the v1 branch instead and see if it solves your issue.

**Comment by jamescr** [comment]
The v1 branch solved my issue. Thanks!
