### ISSUE TITLE
Designation of bus stops in Switzerland (SBB)

### ISSUE THREAD

**Issue by Zeralda** [grote/Transportr#324]
In schedules using busses rather than trains, Transportr shows the name of the stop but hides the name of the town. This means that if you have to take several busses to go from one town/village to another, you will see a schedule from "Train station" to "Post" with a change at "Post" (the three stops actually being in different towns). Can anyone change this to show both the town name and the stop? Thank you!

**Comment by tenminutemail** [comment]
Hi @Zeralda 

I've tried the SBB provider and I understand what you are refering to. I guess this issue is also related to how the stops are designated by the local public transport operators.

Anyway, when typing in the bus stop you are looking for, the name usually pops up with the town's name afterwards. If you use the map feature you can also get a fast overview of where you need to change, even if the bus stops have the same name.

**Comment by grote** [comment]
Hi @Zeralda,

I think that @tenminutemail is generally right. Adding the place name to *all* stops would make all names much much longer and hurt readability on small screens. There is a mechanism in PTE though for stops with common names such "Bahnhof" to automatically add the place there. Maybe "Post" should be added to that list of names. This would be an issue to file for PTE though.

**Comment by Zeralda** [comment]
Hi Grote,

I answered your post in a new thread at the time because I didn't realize I could answer a closed issue. 

I don't know what PTE is but given that for languages are used in Switzerland (and many more in other countries covered by the app), I'm not sure it is realistic to add all the "common" names to a list.

A suggestion - I don't know if it is technically feasible: why not show the place/town name whenever a route goes through more than one place/town? In other words, if I get a schedule to go from the train station to the post office in the same town, I don't need the details but if I go from one town to another, I really think I do.

I was bothered again by this missing information last week-end...

**Comment by grote** [comment]
Thanks for you feedback @Zeralda and sorry that the app is misleading you.

Would it help you if the app would automatically show you a small map of your trip when selecting one from the list of options or maybe already when searching?

**Comment by Zeralda** [comment]
Thanks a lot for following up on this!

To me, that doesn't seem ideal - a map would use up a lot of space on a smartphone screen. And actually, I don't always know exactly where I am going ;-) (meaning I couldn't always pinpoint the place on a map - and villages with post offices can be quite close to each other - still). But it might be useful for other people!

For me, just mentioning the town or municipality, even in a tiny font, at the end of the stop's name, would definitely be best.

Have a nice day!
