### ISSUE TITLE
About libs does not fit the dark theme

### ISSUE THREAD

**Issue by mueller-ma** [grote/Transportr#327]
Switch to dark theme and go to about and than libaries. The boxes still have a white background and black font

**Comment by grote** [comment]
Could you please post a screenshot to illustrate the problem? I think that might be an issue of the upstream AboutLibraries library.

**Comment by mueller-ma** [comment]
![screenshot_20170318-044001](https://cloud.githubusercontent.com/assets/22525368/24068685/af3db15a-0b95-11e7-96ab-9d60a647a0b4.png)

**Comment by grote** [comment]
Thanks! So it is not a bad bug, but rather a stylistic inconsistency. If somebody wants to do the research for how to fix this with the AboutLibraries, please be my guest.

**Comment by mueller-ma** [comment]
Fix: https://github.com/openhab/openhab.android/pull/575/commits/0097e34d638686e78081f1d0f9e80610c47285de

**Comment by grote** [comment]
@mueller-ma Thanks! A pull request for this would be great!
