### ISSUE TITLE
Belgium NMBS not working anymore

### ISSUE THREAD

**Issue by Andychu1997** [grote/Transportr#328]
The app won't list any stations when typing in the from text field or the to text field. Even typing the stations in manually won't give any result.

**Comment by grote** [comment]
Somebody else reported that a "UnexpectedRedirectException" is shown.

**Comment by Sarkasper** [comment]
![tmp_7542-screenshot_20170331-0124401279314037](https://cloud.githubusercontent.com/assets/806597/24530233/f818168e-15b0-11e7-9954-09031c7a201d.png)

**Comment by grote** [comment]
Should be fixed in the next release where the API URL will be migrated back to http without s.

**Comment by grote** [comment]
This should be fixed with the latest 1.1.8 release. Please let me know if it isn't!

**Comment by gargamelak47** [comment]
Hi, the same issue is back in version 2.02
