### ISSUE TITLE
Add favorites as home screen launcher (or as widget or shortcut)

### ISSUE THREAD

**Issue by moejoeblue** [grote/Transportr#329]
Feature request: It would be great to have the possibility to save relations specified as favorites as launchers on the android home screen. (This feature has been removed from the DB Navigator app. It would be great to see it in TransportR!)
This could be done as a shortcut, similar to the "Get me Home"-shortcut that is already implemented (which is great).
The idea of a shortcut would be to save as much screen taps as possible: Ideally only one tap on the shortcut "Aa to Bb" should open TransportR and directly give the search results for Aa to Bb for the current time.

**Comment by grote** [comment]
This has been implemented in #375 and is available in the latest beta. Thanks @Noxsense
