### ISSUE TITLE
Designation of bus stops in Switzerland (SBB) - reaction

### ISSUE THREAD

**Issue by Zeralda** [grote/Transportr#330]
Hi,

I didn't have time to react to the answers I got on this post.

It's true that in the search, the full name of the stop appears. What bothers me is that in "Recents", it doesn't - so I can't reproduce a search without typing everything again. The other problem I had - which is really my fault - was that once, I chose the wrong post office - mountain villages often have similar names - and didn't realize it afterwards because the name of the village didn't show in the schedule.

A suggestion - I don't know if it is technically feasible: why not show the place name whenever a route goes through more than one place? In other words, if I get a schedule to go from the train station to the post office in the same town, I don't need the details but if I go from one town to another, I think I really do.

Thanks,
Zeralda

**Comment by patkan** [comment]
Hi @Zeralda, just so you know: you can answer to closed issues. This makes it more clear to what you are referring.
Otherwise it is also sensible to link to an issue that you are referring to like this: #324
