### ISSUE TITLE
Paris - RATP SNCF - Blocked Exception

### ISSUE THREAD

**Issue by hugoroy** [grote/Transportr#333]

**Comment by hugoroy** [comment]
Navitia error:

![tmp_17816-screenshot_2017-03-28-17-13-13929355568](https://cloud.githubusercontent.com/assets/1629771/24412991/5f82cb94-13da-11e7-9742-4a5c4e9b942e.png)

Sorry for thé style. I'm on mobile

**Comment by grote** [comment]
It could be that your saved location has changed its internal ID in the API (shit, but happens). Can you try searching for that location again and using that one?

**Comment by hugoroy** [comment]
That's it! Thanks
-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by grote** [comment]
So we have #207 already to deal with this annoying issue.
