### ISSUE TITLE
UnexpectedRedirectException using DSB Transportation Network

### ISSUE THREAD

**Issue by caspervk** [grote/Transportr#335]
**Problem**
The Danish transportation network DSB is currently completely broken; No suggestions are provided while inputting addresses and searching fails with an UnexpectedRedirectException.

**Analysis**
The error message includes the URL `http://mobil.rejseplanen.dk`, however, when visiting this on a computer you are redirected to Rejseplanen's new beta website `www.rejseplanen.dk/webapp/`. I believe this is what causes the error.

**Comment by grote** [comment]
Sorry, but I can't reproduce this with 1.1.8. Which version are you using?

**Comment by caspervk** [comment]
Wow what a fast reply!

I'm using 1.1.7 as present in F-Droid. I apologize if this issue has already been fixed, will try with apk from GitHub.

**Comment by grote** [comment]
If you don't have important data to loose, you mind want to consider switching to the beta F-Droid repo: https://transportr.grobox.de/#testing_beta

**Comment by caspervk** [comment]
The latest version from the beta repo (1.1.8) seems to have resolved this issue.

Thanks for your fast replies and awesome work on this irreplaceable piece of software.
