### ISSUE TITLE
indicate current choice of transport categories

### ISSUE THREAD

**Issue by sebalis** [grote/Transportr#338]
In the form for entering details of an extended query (with a via and transport categories from “high-speed” to “on demand”), there is no indication which of the various categories are currently chosen. It would be natural and helpful to show some kind of differentiation on the various icons, e.g. via colour.

**Comment by grote** [comment]
Can you please be more specific and maybe explain your proposal with the help of graphics?

The list of chosen transports should be visible in the form. When a transport product is not going to be used, it should not be shown.

**Comment by sebalis** [comment]
You’re right and I’m confused because I have a memory that the box that contains all these symbols was red, but now as I wanted to take a screenshot I find it’s white. That’s just an aside though. :-) I think I only took out the very first transport (high-speed trains) earlier and didn’t realise that the row of symbols had been reduced by one. In my defence I’ll say that some of the symbols look quite similar. :-)

**Comment by grote** [comment]
You should have seen how they looked before ;)

Now, most icons use the official material icons as used by other apps. But feel free to open a PR that improves the icons.

**Comment by sebalis** [comment]
I wonder if it would be a good idea to not remove any unchecked transport but show them greyed out (as I expected when I wrote this ticket). It would certainly make the mistake I made very unlikely. :-)

**Comment by grote** [comment]
Sure you could do that. Then the only problem is that you might still need to scroll the list of transport products horizontally, depending on your screen size. Removing icons from the list makes this more likely.

Feel free to submit a PR that greys out items instead.

**Comment by sebalis** [comment]
Well I have worked as a Java developer for years but only worked with web CMS backends, not Android. I’m tempted but have to give it a low priority :-)
