### ISSUE TITLE
map display for walks: improve symbols shown

### ISSUE THREAD

**Issue by sebalis** [grote/Transportr#339]
When showing a map for walking sections of a connection, the map displayed shows (H) symbols for the two points at the start and end of the walk. Two issues with that: 1. the (H) symbol appears to be a German thing (I haven’t checked but we know that “H” is an initial for “Haltestelle” [stop]), 2. there is no differentiation between the nature of the two positions (one of them might be the starting position defined for the search, i.e. no stop at all). I would suggest some kind of pictorial symbold instead of a letter and a different symbol for intermediate stops and start/destination.

**Comment by grote** [comment]
The map for the walking section is most likely going away in Transportr 2. If this ticket is only about this specific map, it can probably be closed.

**Comment by sebalis** [comment]
It is just about this specific map, but I would be very sad to see it go.

**Comment by grote** [comment]
You will eventually be able to zoom into this part of your trip.

**Comment by sebalis** [comment]
I like the way it’s been done in v2. (If only my test hadn’t created an entry in my history …)
