### ISSUE TITLE
map display for walks: include foot routing

### ISSUE THREAD

**Issue by sebalis** [grote/Transportr#340]
If a map is shown for a walk, ask a provider such as Graphhopper to generate a routing for the walk and include it in the map.

**Comment by grote** [comment]
Some providers do provide a properly routed walk, so this would only need to be done for those that don't do provide this. However, it might not be trivial to detect if the walk is already routed or not.

**Comment by grote** [comment]
This ticket is quite old and nobody has worked on it until now. I personally don't have time to work on it in the foreseeable future. Since there are many other open tickets, let's close this one until someone is interested in the implementation.
