### ISSUE TITLE
map display: introduce a map showing the whole trip

### ISSUE THREAD

**Issue by sebalis** [grote/Transportr#341]
Offer to show a map with symbols for each stop. See issue #339 for suggestions on the kind of symbols shown, and #340 for an alternative to straight lines for connecting the symbols if a section of the trip is a walk. For non-walk sections, I would suggest a sequence of straight lines connecting each intermediate stop but symbols only for the start and end of the section.

**Comment by grote** [comment]
Do you mean a map like shown here? https://twitter.com/TransportrApp/status/698905802548060161

**Comment by sebalis** [comment]
How silly of me. I thought it would be interesting if I’d provide some potentially valuable first-time impressions, having known you and Transportr for a long time but only now being able to use it on my first smartphone. But this is a stupid newbie mistake as a map can indeed be generated exactly as I described in this ticket. I just defined the symbol. I think walking sections should be routed too but that is issue #340. This one can be closed (which I will try now).
