### ISSUE TITLE
Offer Other Map Styles

### ISSUE THREAD

**Issue by sebalis** [grote/Transportr#342]
It would make sense to offer the transport tiling used on openstreetmap.org and/or the tiles of öpnvkarte.de as alternatives. And perhaps hillshading. I would not only introduce these as a setting for the whole app but also provide a switch each time a map is shown, it makes sense to study different views for an individual map in particular if it shows a walking section of a trip.

**Comment by grote** [comment]
In Transportr v2, a different vector theme might be used. However, I tend to think that the app should only use one single style and do not provide a switch.

**Comment by sebalis** [comment]
I strongly disagree. As a frequent user of openstreetmap.org I can say from experience that being able to switch between styles adds a lot of value (to me). And it’s not like the switch would need to take away significant screen space. Please reconsider :-)

**Comment by grote** [comment]
If somebody wants to work on this and finds a way to add a style switch without cluttering the UI or making the code more difficult to maintain, I'd be happy to merge this.

**Comment by grote** [comment]
This ticket is quite old and nobody has worked on it until now. I personally don't have time to work on it in the foreseeable future. Since there are many other open tickets, let's close this one until someone is interested in the implementation.

There's also #467 which I'll leave open since I think it is more urgent and related.

**Comment by sebalis** [comment]
While I understand the wish to tidy up the list of open issues, I fear that simply closing them will effectively hide what might be a useful feature request from the view of any developer that might want to take it on (whether it’s you, @grote, or a willing volunteer). Closing probably has a connotation that the issue has been resolved even if strictly speaking the meaning of “closed” is of course more than that. Is there no other way? Perhaps use some kind of label instead of or at least in addition to closing the issue?

**Comment by grote** [comment]
I'd love developers to show up here, look at the tickets and implement them. Unfortunately, in the 5 years of Transportr that never happened like this. The homepage instructs people to also look at the closed issues.

If you think a labeling scheme makes sense, feel free to propose one. There could be a `Fixed` label for stuff that got implemented for example. If the scheme makes sense, I can give you permission to implement it here.

**Comment by sebalis** [comment]
What would immediately be needed would be an `Unresolved` label for issues that are closed although the problem still exists. And a specific reminder for would-be developers to search for those. At the moment the only hint about looking at closed issues that I could find is in the section for would-be issue reporters. If you want more precision you could of course also add `Fixed` and anything else for closed issues in between these states (at the moment I do not have a picture of that else exists). And yes, I would volunteer to help with labelling.

**Comment by grote** [comment]
Could we use the existing [wontfix](https://github.com/grote/Transportr/labels/wontfix%20%F0%9F%9A%B7) label for it or should we rename it to Unresolved?

> And a specific reminder for would-be developers to search for those.

The website repo is available for pull requests at https://github.com/grote/Transportr-website

**Comment by sebalis** [comment]
Not knowing your usage practices, I don’t know. Generally I would regard `wontfix` as a statement of intent (probably with good reasons) that would only apply to some unresolved issues. At the moment it does not apply to the closed issues I care about. `Unresolved` to me would be a statement of fact that would include issues closed for mere inactivity and other reasons.

**Comment by sebalis** [comment]
For a more thorough approach you might decide not close any issues for inactivity and assign milestones to everything that you (or any potential active developers) want to take on, with one unspecific milestone-label like “want to do” for anything else you might want to look at “as and when” :-)

**Comment by grote** [comment]
Since I am the only person sitting on the receiving end of the issue tracker, I prefer to have only open issues that have a chance to ever receive any work.

I created an [unresolved](https://github.com/grote/Transportr/labels/unresolved%20%F0%9F%A4%9B) label and gave you rights to label closed issues with it.

**Comment by sebalis** [comment]
I’m working my way down to issue number 300, the rest will have to wait …

**Comment by grote** [comment]
Btw. as you can see in #467 creating other styles is something everybody could do without any programming knowledge. Let's see if somebody does that for #467.
