### ISSUE TITLE
include places chosen on the map in history

### ISSUE THREAD

**Issue by sebalis** [grote/Transportr#344]
Would it make sense to also store a place chosen via the map in the history, not just stops? To differentiate from stops, I would suggest using an icon different to the star ✭ currently used for stops, in particular if issues #320, #246, #230 might get implemented (which would turn map entries into text rather than coordinates, making them hard to distinguish from stops).

**Comment by grote** [comment]
In Transportr2, locations chosen from the map will receive a name. For the history, this ticket is (technically) almost identical to #32.

**Comment by sebalis** [comment]
Actually #32 doesn’t mention the history at all, but it sounds like a prerequisite for including non-ID places in the history.

**Comment by grote** [comment]
Yes, when #32 is done, this one will be implemented automagically.

**Comment by grote** [comment]
In the upcoming Transportr v2, places from the map are not saved. However, I am thinking about changing this so they are only saved when used for a directions search.
