### ISSUE TITLE
Save trips as Repeating Trips and notify on changes

### ISSUE THREAD

**Issue by georgjaehnig** [grote/Transportr#345]
# Use case

I'd like to cover the following use case:

- A user regularly commutes from A to B, for instance every weekday from her home to her workplace.
- She wants to get notified if her regular trip is not possible or will be delayed, for instance because of construction works.

# Implementation and UI

I suggest the following implementation:

- First: implementation of #171 
- Then, at the same UI point where a single trip can be save, another option for this feature shall be there, for instance:
  - "Save trip"
  - "Save as repeating trip and notify on changes"

A click on the latter would open a new screen, with the following options:

- _Weekdays_ with 7 checkboxes from Monday to Sunday, with 5 checkboxes from Monday to Friday preselected
- _Notify on changes_ with 3 checkboxes 
  - 24 hours before
  - 12 hours before
  - 1 hour before

In the main menu, under _Recent Trips_ add a new item _Repeating Trips_. Click on it will list all saved repeated trips, with the ability to edit the weekdays and the time point when to check.

# Functionality

What Transportr would do:

- Fetch the connection with the saved _From_, _To_ and _Departure time_ at the set time point, e.g. 12 hours before.
- If the fetched result has a diff to the saved connection, create a Push notification which links to a screen with the newly fetched connection. Otherwise, do nothing.

**Comment by grote** [comment]
One comment: This feature should only be available for providers that offer realtime data (or update their data very regularly). Ideally, there would be new `REALTIME` option added to [`Capability`](https://github.com/schildbach/public-transport-enabler/blob/931dafb628c23733c162bd23972c97ef1a72e642/enabler/src/de/schildbach/pte/NetworkProvider.java#L44).

**Comment by grote** [comment]
The upstream issue about adding a `REALTIME` capability is schildbach/public-transport-enabler#95

Transportr now has a [`TripsRepository`](https://github.com/grote/Transportr/blob/master/app/src/main/java/de/grobox/transportr/trips/search/TripsRepository.kt) which would be the perfect place to implement this feature. Although it is not really future proof, the easiest way would probably be to just serialize trips and write them to disk for #171 and then build the refreshing on top.

**Comment by bbastin** [comment]
I think this feature should not be limited to real time providers as changes can also be planned due to road work or events causing a departure from the usual schedule.

Also I would like to see the option for a fixed arrival time because for me the arrival often should be fixed instead of the departure time.

**Comment by grote** [comment]
> I think this feature should not be limited to real time providers as changes can also be planned due to road work or events causing a departure from the usual schedule.

The assumption is that if the provider is not a `REALTIME` provider, then it doesn't know about changes and always just returns a fixed schedule.

> Also I would like to see the option for a fixed arrival time because for me the arrival often should be fixed instead of the departure time.

This sounds like a feature that already exists. How does it relate to this ticket though?

**Comment by grote** [comment]
This ticket is quite old and nobody has worked on it until now. I personally don't have time to work on it in the foreseeable future. Since there are many other open tickets, let's close this one until someone is interested in the implementation.
