### ISSUE TITLE
Add route info for Norway?

### ISSUE THREAD

**Issue by unhammer** [grote/Transportr#346]
There's an API for getting route info for Norwegian public transport, some docs at
https://api-test.rutebanken.org/doc/

The API is from Entur AS, a company owned by the Norwegian Ministry of Transport and Communications. Documentation unfortunately seems quite thin at the moment.

**Comment by grote** [comment]
Have a look at those two upsteam tickets:
* schildbach/public-transport-enabler#150
* schildbach/public-transport-enabler#159

I think they address what you are looking for.
