### ISSUE TITLE
Build failes in Android Studio

### ISSUE THREAD

**Issue by mueller-ma** [grote/Transportr#348]
````
Error:Could not find com.android.support.constraint:constraint-layout:1.0.0-beta4.
Required by:
    project :
Search in build.gradle files
````

**Comment by grote** [comment]
Google might have removed those files. Try bumping these dependencies to the latest version.

**Comment by grote** [comment]
Or make sure you have the appropriate version of the library installed via the SDK Manager.

**Comment by mueller-ma** [comment]
Version 1.0.2 seems to work. How can I update the checksums?

**Comment by mueller-ma** [comment]
Can't built it competly on my laptop with only 4GB Ram
