### ISSUE TITLE
Suggestion: Additional button to add +1 day for trips on the next day

### ISSUE THREAD

**Issue by Echolon** [grote/Transportr#349]
Hi,

I've made some simple visual edits to show you what I'd like to suggest for Transportr:

<img src="https://cloud.githubusercontent.com/assets/29168011/26803673/56ffe80c-4a45-11e7-84ab-9855e4606659.png" height="462" width="270">

**As you see there is a new additional button nearby the "TODAY" button. Thus, you could quickly add +1 day (or more) without opening the calendar.** Furthermore it might be more intutive if both buttons would be connected, but differ in their color. I've made another picture.

<img src="https://cloud.githubusercontent.com/assets/29168011/26803773/b9ad9ae4-4a45-11e7-9b23-d361e70e0ecb.png" height="462" width="270">

Finally, if some one would implement this, I recommend to do this as well for the other pair of buttons (the "+15 minutes" on the left) - guess that's also more intuitive and consistent.

If not good as standard configuration - this would be great for an additional option in 'Settings', too.

Cheers

**Comment by grote** [comment]
Thanks for the mockup!

Unfortunately, you are a but late. This screen is already redesigned in Transportr v2 (master branch).

Also, you need to consider very small screens that have not enough horizontal space to show an additional button.

**Comment by Echolon** [comment]
Okay, anyway good luck and thanks for the great app.
Cheers
