### ISSUE TITLE
Recent trips flow a bit too cumbersome

### ISSUE THREAD

**Issue by jancborchardt** [grote/Transportr#350]
I use Transportr sometimes only since I mostly ride by bike. One thing I never noticed was the "Recent trips" entry in the sidebar. Turns out that is very useful, similar to the list of favorites displayed in the main view.

For a nicer UX it would be good to list the recent trips directly below the favorites. This works regardless if you have lots, few or no favorites too. If you have many favorites, you can still use the dedicated sidebar entry. If you don't have that many you can simply scroll.

**Comment by grote** [comment]
Thanks for the feedback! This is actually how it is already implemented for Transportr v2 ;)

**Comment by jancborchardt** [comment]
Yeeha, good news. :) If there's any beta on Fdroid or elsewhere I'm happy to betatest.

**Comment by grote** [comment]
Thanks! I am currently short on time to finish up v2 to beta level. When it is ready, it will show up here in this repo: https://grobox.de/fdroid/
