### ISSUE TITLE
Add "Set to Now" Button to TimePicker

### ISSUE THREAD

**Issue by jancborchardt** [grote/Transportr#351]
Until recently I was clueless about the ability to long-press the time to reset it to current. It's not really something you expect or is hinted at - while for example the "+15" button is very present.

A nice way to make this easier would be, if possible, to add the button "Set to current time" in the timepicker at the bottom.

**Comment by grote** [comment]
Thanks for the suggestion!

Unfortunately, there's no space for that in the timepicker on very small screens and I usually don't like to maintain two versions of one screen.

What do you think about an onboarding dialog that comes the first time the user changes the time/date to something else from now? It would highlight the button to be long-pressed and inform the user about that possibility?

**Comment by jancborchardt** [comment]
I'd then suggest to get rid of the Cancel button and put a "Set to now" button there - or both if there's enough space.

A crucial function like that should not rely on a tutorial which is often clicked away. :)
(Canceling the time input on the other hand can be done by both clicking outside the popup and using the back button.)
