### ISSUE TITLE
Add support to new data for Italy

### ISSUE THREAD

**Issue by airon90** [grote/Transportr#353]
Navitia added support to some Italian transit data, such as Trenord and Trenitalia train data.
Please add support in Transportr to those data

**Comment by grote** [comment]
If Navitia added it to the existing `it` region, there's nothing Transportr needs to do. The data should already be available.

The only thing that somebody might do is add these areas to the description of Italy.

**Comment by airon90** [comment]
Data are not available: if you insert i.e. Canegrate → Parabiago you only get the possibility to go by foot instead of getting data of [S5 trains](https://en.wikipedia.org/wiki/Line_S5_(Milan_suburban_railway_service)) from "Orario Ferroviario Regionale Lombardia" dataset.

I don't know what you mean by «add these areas to the description of Italy». Please, could you explain it better?

**Comment by grote** [comment]
Transportr's Italy region is using the data from https://navitia.opendatasoft.com/explore/dataset/it/table/?sort=type_file

There's nothing we can do if the data does not show up. This needs to be checked with Navitia. First step would be [to query their server directly](http://doc.navitia.io/#navitia-for-human) and see if you get results there.

**Comment by grote** [comment]
> I don't know what you mean by «add these areas to the description of Italy». Please, could you explain it better?

When you select the Italy provider in Transportr, it has a description listing the regions it should work it. This *could* be updated to include the new areas/companies (if they actually work).
