### ISSUE TITLE
NVBW Network - XmlPullPerserException

### ISSUE THREAD

**Issue by github-user-1** [grote/Transportr#356]
On th NVBW network I contantly get the following error message:

![transportr error](https://user-images.githubusercontent.com/6796538/29964685-26ecc2d8-8f0b-11e7-8342-cd6627cf2f42.png)

What does this mean - a fist suggestion would be to try to make the error messages more clear to the end-user (me) and then to try to find out what is actually going wrong here.

**Comment by grote** [comment]
Maybe the saved station doesn't exist anymore in the API. Otherwise, this looks like a PTE bug, not necessarily Transportr related. 

> make the error messages more clear to the end-user

I am just showing what the API reports back in order to save time when debugging this.

**Comment by github-user-1** [comment]
I did test it with and without using saved stations. Any lookup fails with the same error message like shown above. Also irrespective of what stations are selected. So (at least for me; should be confirmed by others) this network is not working.

**Comment by grote** [comment]
This needs to be fixed in PTE upstream if it is still an issue. Once fixed there, Transportr will pick it up with the next update.
