### ISSUE TITLE
VBB network no connection/restults

### ISSUE THREAD

**Issue by robfech** [grote/Transportr#362]
Searching for a connection via VBB network gives no results since yesterday. For example S+U Alexanderplatz Bhf to S+U Berlin Hauptbahnhof.
The BVG network is still working.

**Comment by soerenk** [comment]
Can't reproduce here with Transportr 1.1.8. Do You use WiFi or mobile broadband? Can you give us more information about your device and how we can reproduce that behavior? Did you closed the app completly or reboot your phone? Do you have any logs?

**Comment by robfech** [comment]
I have Android 6.0.1 and transportr 1.1.8.
I can't reproduce the problem anymore after reinstalling the APP. So it's working now as expected. Sorry for opening an issue to solve it so easily.
