### ISSUE TITLE
Live times for VGS (Saarland, Germany) stopped working

### ISSUE THREAD

**Issue by RalfJung** [grote/Transportr#363]
Live delay updates and canceled buses stopped working for the VGS transport system in Saarland, Germany. This used to work fine at the beginning of the year, so probably something changed on their side? No idea how to even debug this.

This is using Transportr 1.1.8 installed via F-Droid.

**Comment by grote** [comment]
Like [written in the contribution guidelines](https://github.com/grote/Transportr/blob/master/CONTRIBUTING.md), this is an upstream PTE issue and can not be fixed in Transportr directly.

**Comment by RalfJung** [comment]
@grote Yeah sorry I should have read that first. :/

Does this mean I should open the same bug upstream? Of course, I am not a user of that upstream library directly, so I may not be able to follow up if upstream requests further details.

**Comment by grote** [comment]
Unfortunately, upstream is not very active anyway. You can check if their Oeffi app has the live times, then it is just a question of upgrading the library. If they also don't have it there's a deeper issue. Are the live times still in VGS's own app, on their website? Maybe they stopped exposing the data through the API.

**Comment by RalfJung** [comment]
> Are the live times still in VGS's own app, on their website?

Yes, both of these still work.

> You can check if their Oeffi app has the live times, then it is just a question of upgrading the library.

Nope, Oeffi disabled VGS years ago (the app says that they requested to be disabled).

**Comment by grote** [comment]
If Oeffi disabled VGS, then PTE upstream has little to no interest to improve the `VgsProvider`. Also, it still uses the `AbstractHafasLegacyProvider`. **Maybe** trying to switch to the new one will help.
