### ISSUE TITLE
Add Israel

### ISSUE THREAD

**Issue by Sarkasper** [grote/Transportr#365]
Is it possible to support it?
I found these links:
http://transitfeeds.com/p/ministry-of-transport-and-road-safety/820
https://navitia.opendatasoft.com/explore/dataset/il/

**Comment by grote** [comment]
It could be supported since Navitia offers an API for this data. Examples on how to do this are linked from the homepage: https://transportr.grobox.de/#add_region

However, please note that the data Navitia is using is out of date, so it couldn't be actually in the present unless updated.

**Comment by Sarkasper** [comment]
Ok, I contacted Navitia if they can update the data.

I checked the page and the examples but didn't get any the wiser. I have no programming skills at all. Is there something else I can do to ease the inclusion?

**Comment by grote** [comment]
Without any idea about programming, this will be difficult. Maybe you can find someone with the skills and motivation to do it.

**Comment by WtfJoke** [comment]
As far as I tell they updated the data.

```
July 8 2018 11:20 PM (metadata)
July 8 2018 11:20 PM (data)
```

**Comment by grote** [comment]
This ticket is quite old and nobody took it up. I am not living in this country and can't do it. Let's close it until someone has added support for this country in public transport enabler.

As a reminder, the process for adding support for a new region is described on the homepage: https://transportr.app/contribute/#translating-into-your-language
