### ISSUE TITLE
"No sufficient internet connection available" even though internet is available and location autocomplete works

### ISSUE THREAD

**Issue by infinity0** [grote/Transportr#367]
I use Orbot + Orwall and block most things from connecting to the internet. Transportr used to work fine with this, but recently it has not, it keeps saying "No sufficient internet connection available" when I search.

The strange thing is that location auto-complete works so clearly it can indeed actually connect to the internet. I suspect this check is to blame:

https://github.com/grote/Transportr/blob/master/src/de/grobox/liberario/tasks/AsyncQueryTripsTask.java#L111

Could you delete this check or make it optional please? Yes I tried allowing Google Connectivity Services through the Orwall firewall already but this doesn't fix the problem (and it shouldn't be necessary; Google doesn't need to know when I'm using Transportr).

**Comment by grote** [comment]
hmm... have you changed something recently? I wonder why that used to work and now doesn't...

**Comment by infinity0** [comment]
I don't think I changed anything recently, regards to Transportr and Orbot/Orwall anyway. `adb logcat` doesn't show anything useful except the Task class name:

~~~~
10-09 16:30:07.443  1447  1447 D getLocationId: Found location: Location{STATION, XXX}
10-09 16:30:07.444  1447  1447 D getLocationId: Found location: Location{STATION, YYY}
10-09 16:30:07.452  4217  6702 D msm8974_platform: platform_send_audio_calibration: [..]
10-09 16:30:07.453  4217  6702 I ACDB-LOADER: ACDB AFE returned = -19
10-09 16:30:07.453  4217  6702 D audio_hw_primary: enable_audio_route: [..]
10-09 16:30:07.483  1447  1506 D AsyncQueryTripsTask: From: Location{STATION, XXX}
10-09 16:30:07.484  1447  1506 D AsyncQueryTripsTask: To: Location{STATION, YYY}
10-09 16:30:07.484  1447  1506 D AsyncQueryTripsTask: Date: Mon Oct 09 16:30:53 GMT+02:00 2017
10-09 16:30:07.485  1447  1506 D AsyncQueryTripsTask: Optimize for: LEAST_DURATION
10-09 16:30:07.486  1447  1506 D AsyncQueryTripsTask: Walk Speed: NORMAL
10-09 16:30:07.556  5361  6963 W InputMethodManagerService: Window already focused, [..]
10-09 16:30:07.634  1447  1464 V RenderScript: 0x7f759bb000 Launching thread(s), CPUs 6
10-09 16:30:07.942  4217  6702 D audio_hw_primary: disable_audio_route: [..]
10-09 16:30:07.945  4217  6702 D audio_hw_primary: disable_snd_device: [..]
10-09 16:30:07.959  4217  6702 D audio_hw_primary: disable_snd_device: [..]
10-09 16:30:07.959  4217  6702 D audio_hw_primary: disable_audio_route: [..]
~~~~

**Comment by grote** [comment]
Should be resolved in upcoming Transportr v2
