### ISSUE TITLE
Please add german nah.sh

### ISSUE THREAD

**Issue by beerisgood** [grote/Transportr#368]
For north germany http://www.nah.sh is better then "Deutsche Bahn"

**Comment by grote** [comment]
Like written in https://github.com/grote/Transportr/blob/master/CONTRIBUTING.md, somebody needs to add this to PTE first.

**Comment by rugk** [comment]
upstream issue created: https://github.com/schildbach/public-transport-enabler/issues/177

**Comment by rugk** [comment]
> It's implemented already (ShProvider.java).

**Comment by grote** [comment]
Turns out [this provider requires authorization](https://github.com/grote/Transportr/blob/master/app/src/main/java/de/grobox/transportr/networks/NetworkProviderFactory.java#L235) for Transportr to use its API. If you get an API secret, I can simply activate it.

**Comment by rugk** [comment]
Okay, as said in the other issue I've already contacted them, so I'll see what they reply.

**Comment by beerisgood** [comment]
Any updates?

**Comment by rugk** [comment]
Oh, that's old. I got no reply…

Maybe someone else can try it again? @grote?

**Comment by rugk** [comment]
Or rather from nah people… If they are not willingless to even respond we cannot do much.

**Comment by grote** [comment]
Since it is free software now, we could maybe use those credentials: https://gitlab.com/oeffi/oeffi/blob/350f686e667c4557c2450d0ac5e828eaddc385a9/oeffi/src/de/schildbach/oeffi/network/NetworkProviderFactory.java#L117

Pull requests welcome!

**Comment by rugk** [comment]
Ough, `r00t`… :thinking:…

**Comment by JoKeyser** [comment]
I've just requested directly for an API key, via Email to kundendialog-AT-nah.sh, fingers crossed.

If I understand correctly, it would be much better if the keys were independent between apps, i.e. sharing the same credentials with Öffi would not have any upsides, right?

**Comment by ialokim** [comment]
@JoKeyser could you post your correspondence with nah.sh here? I think it would be nice to have a proper API key for this network provider for Transportr. I could take over, but I guess it might be better to find someone living in that area to continue the correspondence and sign the agreement. @beerisgood @JoKeyser @rugk Are you living in that area and would be willing to contact them again?

**Comment by beerisgood** [comment]
@ialokim yes i living in that area but doesn't use Transportr anymore. That's also why i leave this here now.

**Comment by JoKeyser** [comment]
@ialokim, I'm no longer living in the area, so I'm glad if you would pick this up.
However, I'm not willing to publish the correspondence here without permission from the author, and it's also quite long, and in German. Alternatively, I could offer you to forward you the conversation, so you can refer to that in your own correspondence. (I'm not sure if you can see my email address in the profile?)

**Comment by ialokim** [comment]
Okay, please do so :) I can't see your email address, but mine is ialokim[at]mailbox.org.

**Comment by JoKeyser** [comment]
@ialokim, I forwarded it to you, thanks for picking this up!

**Comment by ialokim** [comment]
@JoKeyser Just as a side-note for your information: [PTE currently still not supports the HaFas public REST API](https://github.com/schildbach/public-transport-enabler/issues/54), which was proposed to you in the mail correspondence. I've rather stuck to the entrypoint and credentials used by Öffi.
