### ISSUE TITLE
Busses are displayed wrongly in the search result

### ISSUE THREAD

**Issue by tgc-dk** [grote/Transportr#369]
The attached image shows the issue. When doing a search in Denmark, busses gets extra/duplicate text in their tag, which looks a bit weird.
This could be an upstream bug, but thought I would report it here first.

![screenshot_2017-10-20-07-58-11](https://user-images.githubusercontent.com/1773050/31807207-21ab0f72-b56d-11e7-81b3-d1474ae1514c.png)

**Comment by grote** [comment]
That's indeed an upstream bug of the `DsbProvider` of PTE.

**Comment by tgc-dk** [comment]
Just had a quick look at the DsbProvider, I think I should be able to provide a simple patch...

**Comment by grote** [comment]
Upstream PR at schildbach/public-transport-enabler#171

**Comment by grote** [comment]
I am closing this ticket as an upstream PR now exists. No need to track this twice.
