### ISSUE TITLE
[Website] Is this expected? (image of train shown when zooming in map)

### ISSUE THREAD

**Issue by rugk** [grote/Transportr#370]
Webm video:
[transportr.zip](https://github.com/grote/Transportr/files/1405118/transportr.zip)

Firefox 56

**Comment by grote** [comment]
No, not supposed to happen, never saw this.

**Comment by grote** [comment]
Pull requests welcome here: https://github.com/grote/Transportr-website

**Comment by grote** [comment]
Looks like this was fixed by upgrading leaflet.

**Comment by rugk** [comment]
Is this change live yet? Because it still happens here.

**Comment by grote** [comment]
Try full refresh, Shift+F5 or whatever or browser uses

**Comment by rugk** [comment]
Ah okay, it happens not so often anymore. Zoooming is not enough, you also have to click on the markers (and move around, zoom again) and at one point, it will happen… Then the image even stays there until you use your scroll wheel or similar.
