### ISSUE TITLE
[Website] Sidebar empty after click

### ISSUE THREAD

**Issue by rugk** [grote/Transportr#372]
When you click on the sidebar it is just empty. If that is by design, then it is at least bad UX.

BTW: generally it is confusing (i.e. bad UX) when you have two menus with the same links…

Webm: 
[sidebar.zip](https://github.com/grote/Transportr/files/1405125/sidebar.zip)

Firefox 56

**Comment by grote** [comment]
The sidebar should probably be disabled for desktop screen sizes. Pull requests welcome here: https://github.com/grote/Transportr-website

**Comment by rugk** [comment]
No time to make a PR for this, but I'll move the issue…
