### ISSUE TITLE
Routing is unreliable

### ISSUE THREAD

**Issue by airon90** [grote/Transportr#376]
I tried Transportr after times as now Milan, Italy is supported by Navitia.

I tested it and I found some weird information:

1. I tried Canegrate-Rho Fieramilano. The only way to reach the metro station is to get S5 train to Rho-Fiera and by foot go to the metro station. transportr tell me to get off the train to Rho and reach Rho f.s. (which are the same!) and get another train. There is also a bug about the final destination of the train. Here is the proof
![screenshot_2017-11-02-09-58-25](https://user-images.githubusercontent.com/139841/32317801-59ffd162-bfb5-11e7-9dd5-da7da99004c0.png)

2. Canegrate-Rho Fieramilano again. The weirdest routing I ever found: Transportr tells me to reach my final destination, to take the metro for one stop and then go back!
![screenshot_2017-11-02-09-58-56](https://user-images.githubusercontent.com/139841/32317904-c44b2558-bfb5-11e7-8900-49b46939ed96.png)

3. Canegrate-via Cesare Saldini (50, there is no address number support), Milano
You should get S5 up to Milano Dateo, then by foot go to get on autobus number 61 and you get off in front of the place. Another routing is offered but it is longer than my usual path
![screenshot_2017-11-02-10-00-32](https://user-images.githubusercontent.com/139841/32318077-59f09106-bfb6-11e7-8d2d-2d139079c688.png)

**Comment by airon90** [comment]
Moreover, if you insert an intermediate stop, it's not always considered.
I tried Canegrate - Milano Dateo - Via Cesare Saldini, Milano. Between the results there is no train+61 option and some of them didn't even consider Dateo. Here is an example
![screenshot_2017-11-02-10-21-00](https://user-images.githubusercontent.com/139841/32318620-1a4c42c8-bfb8-11e7-8f30-a0341ba2cc16.png)
This is not just about routing reliability but it is a bug

**Comment by grote** [comment]
Thanks for the issue report. However, all this seems to be related to Navitia. Transportr merely displays what their API returns. You can either get them to improve their results or setup your own Navitia server and improve the results yourself.

**Comment by grote** [comment]
Btw. Navitia doesn't respect VIA search locations. So this would need to be deactivated. The upstream issues for this are: schildbach/public-transport-enabler#95 and CanalTP/navitia#1589

**Comment by airon90** [comment]
If somebody wants to follow this bug report see https://groups.google.com/forum/#!topic/navitia/3LGQNkQ1OCs
