### ISSUE TITLE
ni SNCF timetables in Isère routes (France Sud-Est)

### ISSUE THREAD

**Issue by remontees** [grote/Transportr#379]
Hello,

When I try to have a route between two rail stations (f.e. between Lancey ans Brignoud un Isère, France), thé app returns None response.

**Comment by remontees** [comment]
This ils a nullpointerexception: nulle

When I show thé timetables et a train station, that's all good but it's when I search a route between for exemple the two rail stations cited in the previous message.

**Comment by remontees** [comment]
And I use Transportr 1.1.8

**Comment by grote** [comment]
Thanks for reporting. This is known already in #360 and needs to be fixed upstream in  schildbach/public-transport-enabler#169

Unfortunately, these fixes get merged very slowly upstream :( Maybe you or @thony8 can revive the discussion.
