### ISSUE TITLE
Version 2.00-beta1 Time Input always with am/pm

### ISSUE THREAD

**Issue by jlammrs** [grote/Transportr#380]
Version 2.0-beta1: When i want to change depart or arrival time i have tot select a.m or p.m. Since all other times shown are 24 hour based (at least on my tablet) this is rather confusing.

**Comment by grote** [comment]
Looks like we need to manually check which format the user should see and if it is the 24h format, we need to use [setIs24HourView(true)](https://developer.android.com/reference/android/widget/TimePicker.html#setIs24HourView%28java.lang.Boolean%29)
