### ISSUE TITLE
Feedback Transportr 2.0.0-beta1

### ISSUE THREAD

**Issue by tenminutemail** [grote/Transportr#383]
Hi,

thank you for developing Transportr, it is a great and very useful app. I've tried Transportr 2.0.0-beta1 on Android 6 and would like to give some feedback.

- Using the Spain provider (which based on Navitia data), I experience a strange bug. Every time I look up a street there is now a "0" added to the street name; this wasn't the case in earlier versions of Transportr.

![bug](https://user-images.githubusercontent.com/23173049/33079806-d1f96072-ced6-11e7-88e6-d941177a00a1.jpg)

- Selecting time and date of travel is a bit cumbersome. It's only one tap to access the time menu, but I am still missing the "+15" button which I found really helpful. There is a "now" button in the time menu, but I don't think this is necessary, because simply holding the time icon in the upper corner sets the time to now. 

- Changing the date of travel is a bit trickier: you have to select the time menu and then click again so that the calender view will open up. That seems a bit too complicated to me (I am aware of the option to select "today" and "tomorrow", but it is not always useful) and was easier with the old Transportr app.

- Setting the time to "arrival" or "departure" also has gotten more complicated, with the integration in the context menu. It should be possible to change that when selecting the time and date of travel.

- When starting the app it shows me the map, a search box, home and work option, favourites, and the latest connections I looked up. Then when clicking on an option (let's say the work option), the app takes me to another screen where these options (home and work option, favourites, and the latest connections) are shown again (until the current position is loaded or a starting point is selected). Is this behaviour intended? I find it rather redundant to show the same information twice.

The redesign with the new map is nice, but to me the app feels less simple and elegant than it was. 

I hope this feedback is helpful.

**Comment by grote** [comment]
Hi @tenminutemail,

thanks a lot for your feedback that's very appreciated!

> Every time I look up a street there is now a "0" added to the street name;

Thanks for reporting! This is a bug in PTE, but one I am responsible for. Will fix.

> I am still missing the "+15" button which I found really helpful.

The form was stripped down to its essentials intentionally to make it less confusing for users and take up less space. I understand that for power users, certain functionality is now more difficult to access. However, the reasoning is that such functionality is rarely used by people anyway.

> There is a "now" button in the time menu, but I don't think this is necessary, because simply holding the time icon in the upper corner sets the time to now.

Simply holding the time icon is hard to discover for non-power users though. This was #351.

> Changing the date of travel is a bit trickier

Yes, like said above, this is intentional. It should just be one click more though.

> Setting the time to "arrival" or "departure" also has gotten more complicated, with the integration in the context menu. It should be possible to change that when selecting the time and date of travel.

Unfortunately the screen for setting date and time doesn't have any more space available for that. Please keep in mind that there's also phones with very small screens.

> When starting the app it shows me the map, a search box, home and work option, favourites, and the latest connections I looked up. Then when clicking on an option (let's say the work option), the app takes me to another screen where these options (home and work option, favourites, and the latest connections) are shown again (until the current position is loaded or a starting point is selected). Is this behaviour intended? I find it rather redundant to show the same information twice.

Thanks for the feedback. Here the idea is that under normal circumstances, you wouldn't see this information duplicated. It only comes, because the app does not know your starting point.

Do you think it would be better to show a loading animation while the app tries to find your current location?

**Comment by grote** [comment]
> Thanks for reporting! This is a bug in PTE, but one I am responsible for. Will fix.

Done in schildbach/public-transport-enabler#176

**Comment by tenminutemail** [comment]
Hi @grote,

thank you for your answer. 

I get your point about the time and the date selection and I really think the apps works very well so far. The options are actually fine (usually you just look up connections for today, so accessing the time menu is very easy and smooth. Setting the date is also fine, taking into account that it is not the most important option); the only thing I would change is the option of setting the time to departure/arrival. A small switch somewhere for departure or arrival would be awesome or otherwise reducing the "clicks" you need to do so. Now it takes three (selecting the context menu, then selecting "time is" and then selecting departure/arrival), maybe it could be reduced to two (selecting context menu, then selecting time is departure/arrival directly). Anyway this last idea could also be confusing.

Even though I like the minimalist menu options of Transportr I wonder if you considered placing date and time selection in a horizontal bar just beneath the station input fields?

> Do you think it would be better to show a loading animation while the app tries to find your current location?

Yes, to me this sounds like a good solution.

There is two more things I realized:

- When selecting a station from the map and then selecting departures, the departures shown can not be selected. Is this on purpose? 

- When sharing a connection, the output message is nice but there is no date included. At least if the connection shared with someone is not today, including a date would be useful.

Cheers and thank you for keeping up this really good work!

**Comment by rugk** [comment]
>  A small switch somewhere for departure or arrival would be awesome or otherwise reducing the "clicks" you need to do so.

👍 Yeah, just use the same switch one usually sees in the settings. This way, the user also knows what is currently selected.

(Disclaimer: Did not test the new beta. Is there a pre-compiled APK somewhere?)

**Comment by grote** [comment]
> usually you just look up connections for today, so accessing the time menu is very easy and smooth

Exactly that is what I am thinking. Thanks for confirming!

> A small switch somewhere for departure or arrival would be awesome or otherwise reducing the "clicks" you need to do so.

Let me know if you have a good proposal on how to integrate this into the current UI. I don't track app usage, but I also suppose that most people don't use the departure/arrival query feature.

>  I wonder if you considered placing date and time selection in a horizontal bar just beneath the station input fields?

Maybe a another line in the form will be necessary eventually, but so far I try to avoid it, to keep the form simple and less confusing for less technical users.

> When selecting a station from the map and then selecting departures, the departures shown can not be selected. Is this on purpose?

Yes, I guess you want to be able to click a departure to see where the vehicle is going from there and when it arrives where, right?
Unfortunately, the API does not support that, so you can't click the departures.

> When sharing a connection, the output message is nice but there is no date included. At least if the connection shared with someone is not today, including a date would be useful.

Good point. Could you create a ticket for that please?

**Comment by grote** [comment]
> Good point. Could you create a ticket for that please?

No need. Implemented in 8a83383

**Comment by tenminutemail** [comment]
@grote Thank you for the answer and the fix :)

> Let me know if you have a good proposal on how to integrate this into the current UI. I don't track app usage, but I also suppose that most people don't use the departure/arrival query feature.

If you were to integrate another line beneath the station input fields, I'd just put it there. If not, I would place it in the time menu: there is one line for the date and there could be another one for changing departure/arrival (selecting time and arrival usually goes hand in hand). I am not sure, though, if there is enough space for that. Anyway, this is just a minor UI decision.

**Comment by TheLastProject** [comment]
@grote Could you explain what you mean with the "departure/arrival query feature"? The button you can tap in the current stable to switch between searching for leaving or arriving trains at the set time? I use this button almost as often as setting the time, as I need both options quite often.

If you mean the "Departures" option in the sidebar, I never use this.

**Comment by grote** [comment]
> If not, I would place it in the time menu: there is one line for the date and there could be another one for changing departure/arrival (selecting time and arrival usually goes hand in hand).

Like I said: This unfortunately doesn't fly for extremely small screens. I want to keep the UI generic, so it works on small and large screens alike.

> Could you explain what you mean with the "departure/arrival query feature"? The button you can tap in the current stable to switch between searching for leaving or arriving trains at the set time? I use this button almost as often as setting the time, as I need both options quite often.

Yes, I mean this. The feature is still there in Transportr 2, but needs more clicks. I suggest you try the beta and give feedback before it gets released as stable soon.

**Comment by TheLastProject** [comment]
I just installed Transportr 2 beta 1, it looks nice.

On the departure/arrival time, I must agree with @tenminutemail. It was rather hard to find this option, while the time/date screen is rather simple. Would it really cost too much screen space to add two small radio boxes (arrival/departure) or (to save a bit of space), a dropdown on top that says "Arrive at:" or "Depart at:"?

**Comment by grote** [comment]
This is from one of my test devices and there's phones with smaller screens:

![device-2017-11-29-185817](https://user-images.githubusercontent.com/244947/33398824-739493e6-d537-11e7-9a30-0bfe2c71892b.png)

Everything above "Today" is controlled by Android can not be made smaller.

**Comment by rugk** [comment]
Ehm what does the screenshot have to do with arrival/departure times? I see no such thing there, just a usual date/time selector.

**Comment by TheLastProject** [comment]
@rugk The purpose is to show that there isn't really any screen space left for this option on small screens.

@grote I still believe this dialog window is the best place for it, and I see two possible workarounds for small screens:
1. Make the dialog scrollable and on small screens make clear scrolling is possible (perhaps a toast: "Scroll for more options"?)
2. If it fits, place "Arr/Dep:" in front of the clock on the top bar above it, where currently a favourite icon, and move the favourite icon to the drop-down menu. This can be an independent toggle, with only larger screens showing the option to make the time arrival/departure on the time selection screen for easy selection at the same time:
![photo_2017-11-30_07-29-03](https://user-images.githubusercontent.com/1885159/33417181-af732170-d5a0-11e7-82dd-c34df0190016.jpg)

**Comment by sphh** [comment]
I also switch between `departure`/`arrival` quite a lot (to be honest, I use `arrival` more often than `departure`). I miss a quick and easy way to switch between those two desperately. I like @TheLastProject suggestion of having a toggle in front of or after the clock icon. This would also give an indication of the selection made. This would even fit on my tiny 240x432px display:
![screenshot_20181127-165133](https://user-images.githubusercontent.com/4856462/49094209-02a8c100-f266-11e8-9fd6-1fbbb1719a6d.png)


The time selector for the `Alarm` app looks like this (on Android 8.1):
![screenshot_20181127-165025](https://user-images.githubusercontent.com/4856462/49094267-2835ca80-f266-11e8-9872-1a00f6fdf119.png)

Here the keyboard input icon and `CANCEL` and `OK` are in one row. @grote, would that be possible when extending the time input screen? (Well, then these buttons are obviously in the wrong place...) Can this place re-used for the `departure`/`arrival` switch?
![screenshot_20181127-165045](https://user-images.githubusercontent.com/4856462/49094276-2e2bab80-f266-11e8-9762-013c444a8424.png)

Some comments/ideas:
- I had no problem to find the date selector. IMHO it's in an obvious place.
- I always cancel the time input form with the button left of the home button. Can the `Cancel` button become the `departure`/`arrival` switch?
- Moving the `departure`/`arrival` switch to the time selection screen makes much sense, because if you want arrival times, you always (well, nearly always) have to set the time as well.

**Comment by grote** [comment]
Thanks for your suggestions. This ticket is closed already. I think it is best to open a dedicated one about improving the directions form.

> I like @TheLastProject suggestion of having a toggle in front of or after the clock icon.

I personally think that the top row is already quite messy. It either needs some better design or we introduce an (optional) button row under the form.

> Here the keyboard input icon and CANCEL and OK are in one row. @grote, would that be possible when extending the time input screen?

I don't think so. The keyboard icon is part of the system time selector widget. But maybe there's a way. You can check the docs.

> Can this place re-used for the departure/arrival switch?

I don't think there's space in this dialog for any more UI elements.

> I always cancel the time input form with the button left of the home button.

Unfortunately, not everybody knows you can close dialogs like this.

> Moving the departure/arrival switch to the time selection screen makes much sense, because if you want arrival times, you always (well, nearly always) have to set the time as well.

I'd prefer moving it to the form directly, maybe into an (optional) row at the bottom.

**Comment by sphh** [comment]
Thank you for your reply. As suggested by @grote, I opened the new issue #548 .
