### ISSUE TITLE
F-Droid testing repo broken

### ISSUE THREAD

**Issue by rugk** [grote/Transportr#384]
Currently the F-Droid testing repo seems to be broken. F-Droid always shows me an error: "index.jar <somenumbers> is older than current <somenumbers" when I try to update it.

(But after disabling the source, it is still shown – so I am not entirely sure this error is caused by this archive.)

In any case when searching for "Transportr" I can only find the one installed via the official F-Droid archive.

----

Besides of that, F-Droid seems to have [released a new Repomaker](https://f-droid.org/de/repomaker/). Maybe you switch to/use it…

**Edit:** BTW, the icon on [that page](https://grobox.de/fdroid/) is also outdated.

**Comment by grote** [comment]
What F-Droid version are you using? It works fine here.

**Comment by grote** [comment]
That is the same one I am using. Just tested it again.

Can you outline the steps you took to add the repo?

**Comment by rugk** [comment]
I scanned the QR code and opened with F-Droid… then it was there. Pretty starightforward. 👍

**Comment by grote** [comment]
can you please click on the repo in the repo list and post a screenshot of that?

**Comment by grote** [comment]
Also, if [another repo is causing the error](https://gitlab.com/fdroid/fdroidclient/issues/1262) try disabling all other repos except mine to be sure this is actually in issue with my repo.

**Comment by rugk** [comment]
Nice you've discovered my issue there. So I already tried it, but I could not actually figure out whether it is this repo…

Let me try some things…

**Comment by grote** [comment]
When you disable/enadble a repo, all enabled ones are updated. This could be better. So you first need to disable all and then only enable mine. If another update job was still running, you need to disable and enable only mine again.

**Comment by comradekingu** [comment]
@rugk It does that if you have the wrong thing added. Make sure it says "https://grobox.de/fdroid/" Fingerprint should be: 28e14fb3b280bce8ff1e0f8e82726ff46923662cecff2a0689108ce19e8b347c

**Comment by rugk** [comment]
That seems to be okay…

![screenshot](https://user-images.githubusercontent.com/11966684/33289058-8233052e-d3be-11e7-8b2a-2086ff389f40.png)

…but I seem to have caused general issues: https://gitlab.com/fdroid/fdroidclient/issues/1263

----

So I just deleted all app data of F-Droid. But when entering "transportr" in the search, I still just find v1.1.8 I have currently installed from F-Droid.

**Comment by grote** [comment]
> So I just deleted all app data of F-Droid. But when entering "transportr" in the search, I still just find v1.1.8 I have currently installed from F-Droid.

You probably have an incompatible version installed from another repository (probably F-Droid's). This uses a different signature and thus can't be upgraded. You need to uninstall this version. If you want to test in the future, I suggest to stay on the version signed by me. When F-Droid's multi-sig support is ready, I plan on adding my signature to F-Droid as well.

**Comment by rugk** [comment]
Indeed I have, but as the two apps have different IDs I think they can be installed in parallel. At least if they were just an APK…

So maybe you could adjust so you can install both the "stable" and the "testing" version? I really don't want to uninstall the stable version, just wanna test the beta. 
As your F-Droid repo is also labeled "grobox testing" I only use this for testing apps. You could even rename the beta version as "Transportr Dev" or so. See https://github.com/westnordost/StreetComplete/issues/591 for a similar project doing that.

**Comment by grote** [comment]
Sorry, I am only publishing one version that can be upgraded to stable releases as well. Anything else is too much work.

The beta is stable enough for daily use. It is out for some time and no serious issues have been reported.
