### ISSUE TITLE
Change Favourite Connections to Favourite Destinations

### ISSUE THREAD

**Issue by bbastin** [grote/Transportr#385]
I really like the favourite feature as I have some destinations that I have to get to almost daily. The problem is that I don't always have the same starting point. This leads to me only using this feature when starting from home, because for me to use it from anywhere else would force me to tap it, wait for the query to finish, go back, change the starting point and query again.

What I would love to see is an option to interchange the favourite connections panel below the input mask for a favourite destinations panel. This would behave differently in that it would change the destination and start the query, but leave the starting point intact.

# Solution
Add an option to interchange the favourite connections panel for a favourite destination panel which leaves the starting point intact on interaction.

In the next couple of days I could also try to create a mockup or add more details, if wished.

**Comment by grote** [comment]
> I have some destinations that I have to get to almost daily. The problem is that I don't always have the same starting point.

For this use case, there's the Home and Work location. These take your current location as starting point. Sounds like this is what you want.

> would force me to tap it, wait for the query to finish, go back, change the starting point and query again.

You don't need to wait for it to finish, you can just change the from location and it will start another query right away.

**Comment by bbastin** [comment]
Sorry for the long silence.

That does not really cover my use case, as I have more than two destinations. Also, the Home and Work locations do not support addresses whereas the favourite connections do.
I have at least five locations that I regularly drive to, but sometimes need to get from A to B to C to A whereas other times I need to get from A to C and back directly and things like that. Therefore, the connections panel isn't really helpful to me, what would instead help me more is a destination panel so that I can put down my home address, my university addresses, my work place and so on. Having these five locations interconnected with favourite connections would be really impractical and clutter Transportr's start screen very much.

![transportr_favourite_destinations_mockup](https://user-images.githubusercontent.com/30876209/37349090-ed0603e6-26d5-11e8-9753-a31710999944.png)

This is a very rough mockup of what I mean. Tapping on one of the destinations sets it as the destination without changing the starting point. In the overflow menu of each destination there could be the possibility to instead set it as the starting point as well as remove the destination as favourite. Another advantage might be that these destination elements can be smaller than the current connection ones.

I know you can already edit the query, but this is rather tedious in my case. I often times end up switching the former destination into the next starting point (as I have arrived there) and then need to enter the next destination manually as the favourite connections all have my home address as the starting point. Doing this while walking (which I often have to do due to my tight schedule) is at least more inconvenient than pressing a button to have the destinations entered into the destination field.

I don't know wether my use case is a very special one but I could imagine many people having this kind of problem. If you think this feature is something you'd like to see in Transportr or at least would be an option that is tolerable for you, but you don't have the time for that or don't consider it that important, I could also try to implement it myself, but this might then take a while since I am busy with university right now.

Sorry for the wall of text, I don't really know how to explain this issue shorter.

**Comment by grote** [comment]
This ticket is quite old and nobody has worked on it until now. I personally don't have time to work on it in the foreseeable future. Since there are many other open tickets, let's close this one until someone is interested in the implementation.

There's now the Home and Work location. That's at least two, so it might help at least a bit.

**Comment by bbastin** [comment]
Due to the changed UI in the new version, this is less important. Work and Home locations do help, yes. Thank you.
