### ISSUE TITLE
2.0.0-beta1 search weirdness with 9292

### ISSUE THREAD

**Issue by TheLastProject** [grote/Transportr#386]
The search in 2.0.0-beta1 seems a bit broken, at least with 9292:

As an example: "bushalte heuvel" does not return a single bus stop with this name, yet "heuvel bushalte" returns all of them. I can't seem to reproduce this with other bus stops.

I also noticed all results are now Dutch. While I previously searched for "bus stop" I now have to search for "bushalte", regardless of device language. This was unexpected to me.

**Comment by grote** [comment]
That is strange, because nothing here should have changed since 1.x. Do you maybe have another phone or an emulator and can compare the behavior with both version to narrow the problem down?

**Comment by TheLastProject** [comment]
I have an Android tablet at home, I'll try the current stable on that to compare as soon as I get a chance.

**Comment by TheLastProject** [comment]
I see no noticeable change between the stable and the beta, aside that the current stable seems to insist to search in English (bus stop) and the beta seems to insist to search in Dutch (bushalte) despite both devices being set to English. I suppose this is not so much a regression then and I don't remember how I found the location in stable before.

**Comment by grote** [comment]
thanks, so this can be closed?

**Comment by TheLastProject** [comment]
Well, it would still be good if "bushalte heuvel" would return all bus stops in that name just like "heuvel bushalte" does, but looking online, the 9292 website returns the exact same wrong results, so this is an issue on their side then.

You may still want to leave this open (or I can create a new issue seeing how this was just a sidenote of the original issue) for the fact that I now have to search in Dutch in the beta despite my device language being set to English and the 9292 API supporting English search (https://github.com/schildbach/public-transport-enabler/blob/fa418ddbe36a5ee56d39d66a6bc140977d83e09d/enabler/src/de/schildbach/pte/NegentweeProvider.java#L88). I can also understand that it seems natural to search in Dutch with a Dutch provider, but I would be lost trying to type "bus stop" in France or Germany for example.

**Comment by grote** [comment]
Thanks for the explanation @full-duplex!

If I saw it correctly, the locale switch is not applied on the `master` branch. The `v1` branch is going to die soon, so maybe you would like to add it to `master` as well?

**Comment by full-duplex** [comment]
Correct, I created a PR with the fix.
