### ISSUE TITLE
Recommendation for testing recently added networks 

### ISSUE THREAD

**Issue by jamescr** [grote/Transportr#391]
I'll like to encourage some users of Costa Rica train service to Test Transportr 2. Accomplish this is easier if they can download the app from your F-Droid repo but the version 2.0.0-beta1 (latest on your F-Droid repo) doesn't include the very recently added Costa Rica provider.

Do you plan to update the app on your F-Droid repo soon, or do you you recommended me to build the apk and share it will some local alpha testers?

**Comment by grote** [comment]
I was planning on doing a release later after I got some more work done, but I can try to do one today and then do another one after the work is done.

**Comment by grote** [comment]
A new beta has been released: https://transportr.grobox.de/#beta

**Comment by jamescr** [comment]
Thanks a lot!
