### ISSUE TITLE
Wiener Linien broken

### ISSUE THREAD

**Issue by 011000110110000101110100** [grote/Transportr#393]
I'm using transportr in Vienna and today I can't find any directions.
Error message: "no directions found"
I already reinstalled the app, no improvement.

It will propably fix itself (might be server issues), just wanted to let you know.

**Comment by grote** [comment]
Thanks for reporting!

I am getting an `InternalErrorException` at the moment. As stated in the contribution guide, this needs to be reported to PTE upstream, since this is technically not a Transportr problem.

**Comment by 011000110110000101110100** [comment]
It's working again :)

**Comment by grote** [comment]
If there's a problem in the future, please complain directly with them, because their API has issues all the time and they need to fix it.
