### ISSUE TITLE
[2.0.0-beta2] Discoverability for sharing is bad

### ISSUE THREAD

**Issue by TheLastProject** [grote/Transportr#394]
I found it really hard to discover the share and send to calendar options in the new Transportr. Only found out by accident that I can do it when, in a trip, I drag the trip up. Could these options maybe always be in an overflow menu on the right top, with the overflow menu and back button coloured red to make it more discoverable?

**Comment by grote** [comment]
I guess you were mostly going on shorter rides. If you want to see the end of a longer ride, you will need to scroll up and will eventually discover these features.

Adding them to the action bar above the map could be a solution, but I don't like making them red.

Personally, I am fine with people discovering these non-essential features later on. However, an alternative could be some onboarding help that shown users that they can swipe the connection bottomsheet up and down when they first see it.

**Comment by TheLastProject** [comment]
Yeah, indeed, short rides to work mostly, I tend to share to my calendar to keep track of these things and  if trains run on time. It was actually about 2 weeks until I had my first longer ride.

The action bar would be great. The red note was mostly because the map tends to be rather white-ish, making the white hard to see, but I guess there are probably better ways to solve that, like one pixel of black around the icons or some shadow at the top. Seeing how great most of the UI of the new version is I probably didn't even need to make a suggestion for this :)

Onboarding would work too, but that could be annoying for people who don't use the app so often, as it would be easy to forget small things like this.

**Comment by grote** [comment]
Does the onboarding I added recently solve this? Can it be closed?
