### ISSUE TITLE
(re)move osmdroid-folder

### ISSUE THREAD

**Issue by DJCrashdummy** [grote/Transportr#397]
Transportr 1.1.8 creates a folder `osmdroid` as soon as you view a map in Transportr for the cached osm-tiles.
causal users have no idea from where it comes and what it contains... and probably afraid of deleting it.

please move this folder into the `../Android/data/"app-id"/` "system", so the cache gets automatically deleted if the app is uninstalled.

**Comment by grote** [comment]
The cache is supposed to be used/shared by several apps I think. So you would need to open this ticket with osmdroid and not Transportr.

Another reason why this isn't relevant here anymore: Transportr 2 (currently in beta) does not use osmdroid anymore.

**Comment by DJCrashdummy** [comment]
@grote thanks for the info about Transportr 2 and sorry for bothering with this.

i thought it was a Transportr-related issue, because it the last app i use, which creates a osmdroid-folder.
