### ISSUE TITLE
Impossible to save transport vehicle selection in landscape

### ISSUE THREAD

**Issue by Lesik** [grote/Transportr#398]
In landscape mode, selecting transport vehicles has no OK/cancel buttons. Clicking outside of the Dialog doesn't save the selection.

![screenshot_20171214-152522](https://user-images.githubusercontent.com/2021487/33997117-a7f1b7f6-e0e3-11e7-9e9b-9f7a8dfa0d23.png)

**Comment by grote** [comment]
Thanks for reporting!

Do you use this screen frequently in landscape mode?

**Comment by Lesik** [comment]
Not too frequently, but I decided to report it anyway (for tablet users maybe?). I am not requesting a particularly urgent fix, if that is what you are asking.
