### ISSUE TITLE
Feature request: expand / collapse all route details

### ISSUE THREAD

**Issue by samtuke** [grote/Transportr#4]
Please provide the ability to expand and collapse all route details with a single click. This would be a useful usability improvement, and very helpful for quickly returning to your route overview (with only parent nodes displayed) when switching trains etc. on foot.

**Comment by grote** [comment]
Isn't that already possible by using "Show Separate"? Or do you need to see all intermediate stops along a leg as well?

**Comment by grote** [comment]
This ticket does not apply anymore for the upcoming Transportr v2 as route details can not be expanded there anymore.
