### ISSUE TITLE
Odd routing

### ISSUE THREAD

**Issue by n76** [grote/Transportr#400]
Using a self-built v2 that includes some transit systems in California I notice that bus to train transfers are not used in cases where they might save considerable travel time. I can list a couple of starting and end points to illustrate.

However my first question is: Is the routing done within the Transportr app or by Navitia and then the results displayed in the app? If the routing is done on Navitia's servers then I ought to post the issue there.

**Comment by grote** [comment]
The routing for the CaliforniaProvider is exclusively done by Navitia. You would need to talk to them about it.

I suspect the issue might be related to `transfers.txt` handling which is not optimal in Navitia, especially when several GTFS feeds are involved.
