### ISSUE TITLE
Add support for realtime API in Paris

### ISSUE THREAD

**Issue by Phyks** [grote/Transportr#402]
Hi,

RATP (public transport provider in Paris) is offering a [realtime API](https://dataratp2.opendatasoft.com/explore/dataset/horaires-temps-reel/). It's apparently [not yet available in Navitia](https://groups.google.com/forum/#!msg/navitia/jp58u_4szIo/uY5L_WQFFQAJ) (as of one year ago), I'm not sure if this is something that could easily be plugged into Transportr? Would be really awesome to get realtime travel times!

Thanks

**Comment by grote** [comment]
First it needs to be available in Navitia, then it needs to be added to PTE and then it can be added to Transportr. If you want to work on this, I can give you some pointers on how to achieve this.

**Comment by Phyks** [comment]
Ok… If it has to be in Navitia, then it is probably not possible at the moment. Navitia has the offline data for Paris, but no realtime data.

From https://groups.google.com/forum/#!searchin/navitia/ratp%7Csort:date/navitia/MeCz7W__ZGE/3HnGcWs1CwAJ

> 2) Tu n'obtiens pas de data_freshness=realtime simplement parce qu'il n'y a pas de fournisseur de données temps réel branché dans fr-idf

(there is only `base_schedule` available, no realtime data provider is available for Paris region in Navitia)


and from https://groups.google.com/forum/#!searchin/navitia/ratp%7Csort:date/navitia/jp58u_4szIo/iqUHI-AbFgAJ

> Pour l'instant, il n'est pas prévu à court et moyen terme de l'intégrer à la roadmap.
which translates roughly to
> For now, there is no plan to integrate the realtime feature (for Paris) in a short to mid term.

I was thinking that Transportr could maybe call the API by itself, without relying on Navitia?

**Comment by grote** [comment]
What is possible is to use the SNCF API via Navitia. This already has real-time information. I don't know how much of that for Paris though.

**Comment by Phyks** [comment]
There are two public transport systems in Paris: SNCF and RATP. SNCF already has real-time information in Navitia but only covers "regional" transit (as in the large metropolitan area, regional trains). RATP on the contrary recently opened up their real-time API, but this is not yet available in Navitia apparently. RATP has the data for the main city area (subway, buses etc). :/

**Comment by grote** [comment]
If there's already SNCF real-time information in Navitia, this can be used to add support for it to PTE (in `AbstractNavitiaProvider`). When other real-time sources become available, these should then appear automagically in Transportr. But the initial work needs to be done first.

**Comment by grote** [comment]
This ticket is quite old and nobody has worked on it until now. I personally don't have time to work on it in the foreseeable future. Since there are many other open tickets, let's close this one until someone is interested in the implementation.
