### ISSUE TITLE
Tap & drag up/down to zoom in/out on map

### ISSUE THREAD

**Issue by jancborchardt** [grote/Transportr#405]
It would make the map view greatly more usable with one hand if the standard zoom gesture tap + drag up/down to zoom in/out would be possible. :)

This is the same as in Google Maps and Maps.me. For Google Maps it always zooms in/out centered on the middle of the viewport, in Maps.me centered on the finger.
The Google Maps style is preferrable since you are likely to use the bottom right (or bottom left if lefthanded) and it would otherwise skew the view.

**Comment by comradekingu** [comment]
I think 
screwing inwards ↻ to zoom in
screwing outwards ↺ to zoom out
makes sense.

The only loss is having to navigate in straight angles ← ↑ → ↓ ↖ ↗ ↘ ↙

**Comment by grote** [comment]
@jancborchardt I am not using proprietary software, so it would help me to understand your request if you would elaborate a bit more. Does it relate to Tranportr v1 or v2? If it relates to v1, please try v2 first.

**Comment by jancborchardt** [comment]
@grote where can I find v2? Found nothing on the website or F-Droid, even with your testing repo.

This pertains to the map view. The gesture basically is a double-tap, but on the second tap you keep the finger on the display and then drag either straight down (to zoom in) or up (to zoom out).
It's comparable to pinch/spread to zoom, except with one finger.

See this video for info: https://lifehacker.com/5993116/zoom-in-and-out-on-google-maps-with-this-one-handed-shortcut (at 0:30) Although beware cause the directions have changed to what I describe above. Double-tap and drag: down to zoom in, up to zoom out. As yeah, you basically pinch the map as if your other finger is mirrored over through the middle.

Let me know if there's still confusion. :)

**Comment by grote** [comment]
Thanks for the explanation. I tried this in Transportr 2 and it works.

If you don't see this in F-Droid, you probably have an incompatible version installed. Please uninstall and you should see beta2.

**Comment by jancborchardt** [comment]
Ah yes, had to check in the "Versions" section as it wasnt automatically shown because of the beta/preview state. :)

Looks really great! Nice new map look, and way better and simpler app design! Congrats! :)
