### ISSUE TITLE
Remembering last connection

### ISSUE THREAD

**Issue by alexanderadam** [grote/Transportr#406]
First of all: thank you again for Transportr.

Now, it would be very useful if Transportr would remember the last state after leaving it.
Most of the apps are doing this and it is not optimal if you are looking for a connection and then switch the application (for example for looking something up), coming back and having to enter the data again.
It even works if I open the app via application overview but it does not work when I reopen the application via launcher.

Thank you in advance and have a nice day!

**Comment by grote** [comment]
I can't really reproduce this. Could it be that your device is low on memory and so the app gets killed by your operating system?

**Comment by alexanderadam** [comment]
Strange, I can't reproduce it at the moment anymore.
The device has 4 GB of RAM so it _should_ not be low on memory.

I will close it now as I can't reproduce it at the moment.
@grote Anything I should look at besides the RAM in case the issue appears again?

**Comment by grote** [comment]
What would be useful are specific steps that reliably reproduce the issue.  #171 should solve this issue as well.
