### ISSUE TITLE
Having a "recommended transport association"

### ISSUE THREAD

**Issue by alexanderadam** [grote/Transportr#407]
I don't know the exact vision of this feature but I can describe the problem to you:

Just recently I attended on a conference where I would love to sponsor you a Mate/Beer/whatever next year if you want (Sorry that I missed the last chance). Of course I used Transportr to navigate in the conference city but I wasn't sure which transport association I should choose. As this conference happened to be in Leipzig (Saxony) I wasn't sure whether I should take VVO (because it clearly mentions "Saxony" in the description, INSA (it clearly mentions Leipzig) or maybe even VMS / DB.

I just wanted to have a connection from one point to another.
Leipziger Verkehrsbetriebe wasn't available and I'm not able to tell which API has which kind of features or would suit best for my connection. It would be wonderful if Transportr could _somehow_ decide what might be the best provider for me. Or if it could look for connections at more than one provider (by GPS selection and/or starting point for example).

Whatever solution you will find: I'm sure this will be handy for tourists.

**Comment by grote** [comment]
Related to or duplicate of #281

Additional info: I am just one busy person and can't keep track of all the details of the various regions and therefore can't recommend anything let alone do automatic recomendations.

**Comment by alexanderadam** [comment]
Yes, definitely duplicate. I guess I overlooked #281. Sorry for that.
