### ISSUE TITLE
Global Coverage in Transportr ?

### ISSUE THREAD

**Issue by adrien-github** [grote/Transportr#408]
Hi,
I am discovering transportr, and find it very useful ! I am using it mainly in western part of France, near Nantes.
It is working well to find quick local trips with several changes : bus/tramway in Nantes (TAN, LILA), then the french railway (SNCF).

I would like to use it the same way when travelling in the west part of France, for instance trip like Nantes/Nancy : Nantes/Paris (train), then metro in Paris, then Paris/Nancy (train), then local bus in Nancy (STAN).
However I have not found a way to do it, as it involves 3 data sets in Navitia : Ile-de-France, North-East quarter and North-West quarter.

However, Navitia seems to provide a global data set : https://navitia.opendatasoft.com/explore/dataset/all-datasets/information/
Do you think it's possible to add it in transportr, so it can calculates any trips ? It could be really cool for people travelling with different network of public transport.

**Comment by grote** [comment]
I personally don't like these huge regions as auto-complete doesn't work well with them. But somebody can add the global coverage to PTE and then it can be added to Transportr. More detailed explanation on how to do it is available here: https://transportr.grobox.de/#add_region

**Comment by grote** [comment]
I'll close this since there's nothing to be done for Transportr at the moment. We can re-open this when public-transport-enabler has support for a larger region.
