### ISSUE TITLE
VRN(Germany) suggestions are limited to one city (Trittenheim)

### ISSUE THREAD

**Issue by Nelsonlittle** [grote/Transportr#409]
I use transportr version 1.1.8 on Android 7.1 and when I use most providers it works well. Only if i choose the VRN provider, then the only places which are suggested are located in a city called Trittenheim. I can enter the right station and get the right connections but I don't get auto completions for any other city except for Trittenheim.

![screenshot_20180111-155001](https://user-images.githubusercontent.com/18367577/34831467-542d8c16-f6e7-11e7-8e3c-8038ee2bba45.png)

**Comment by grote** [comment]
I can't reproduce this with v2-beta2. Please try this version and let me know if it fixes the issue.

**Comment by Nelsonlittle** [comment]
In this version it works perfectly thanks!
