### ISSUE TITLE
UI quirks when Stop Times are missing

### ISSUE THREAD

**Issue by bambamal** [grote/Transportr#410]
Im not sure, if this is a solvable issue, maybe its just a question for my understanding. Why are the stations (the waypoints in the extended view) so misaligned?

![screenshot_20180117-162303](https://user-images.githubusercontent.com/33735248/35050859-13ed2316-fba4-11e7-9e67-dbe7cbddfc96.png)

Also the 'platform say '2(U)', does that mean anything, or is it just what the app receives from the api?

(Awesome app btw, I use it exclusively now and recommend it to everybody)

**Comment by grote** [comment]
The API is missing stop times it seems. Can you please try on latest Transportr 2 beta and post a screenshot for the same query? Thanks!

**Comment by grote** [comment]
> Also the 'platform say '2(U)', does that mean anything, or is it just what the app receives from the api?

This is just what the API returns. No idea what it means.

**Comment by bambamal** [comment]
![screenshot_20180117-170332](https://user-images.githubusercontent.com/33735248/35052962-2e3211fa-fba9-11e7-85e4-c04e71bbcb8b.png)

It mostly looks fine, but some stations have two times.

**Comment by grote** [comment]
In Transportr 2 stations have two times when the arrival time is different from the departure time at the intermediate station. This is the intended behavior.

Thanks for testing again.
