### ISSUE TITLE
2.0.0-beta2 home screen shortcuts always ask for home/work location

### ISSUE THREAD

**Issue by TheLastProject** [grote/Transportr#413]
When adding the "Get Me Home" and "Get Me To Work" shortcuts to my home screen I noticed they always ask me to set my home and work position, even if it's already set

**Comment by grote** [comment]
Thanks for reporting!

Unfortunately, I never saw this and can't reproduce it myself in any way. Can you try to provide steps to reproduce?

**Comment by TheLastProject** [comment]
I thought this always happened, but it indeed seems I triggered it in some odd way. After some more experimenting, it seems to only happen when the Transportr app is not open. Here are reproduction steps that trigger it on my Motorola Moto E 2015 LTE running LineageOS 14.1. It has fairly low RAM, so it may kill Transportr sooner than other devices do:

1. Make sure a Home and Work location are set
2. Open Transportr
3. Tap the 3 dots next to Home or Work and tap "Add Launcher Shortcut"
4. Swipe Transportr away from recent apps or restart the device
5. Tap the launcher shortcut

At this point, it seems you can fix it by manually starting Transportr, which makes the launcher shortcuts work again. If I swipe Transportr away from recent apps, it breaks again.

**Comment by grote** [comment]
Thanks a lot! I could reproduce this now and it looks like a race-condition. The intent from the launcher icon is processed before the actual home location could be loaded from the database.

@Noxsense you already have experience with this. Do you want to look into it?

**Comment by Noxsense** [comment]
Yeah, I'll try to look.
(I guess it's like I mentioned in https://github.com/grote/Transportr/pull/375#issuecomment-340037477 )

**Comment by grote** [comment]
> Yeah, I'll try to look.

Great, thanks!

> (I guess it's like I mentioned in #375 (comment) )

I suppose so, but better check to be sure it is this.

**Comment by grote** [comment]
@Noxsense FYI: I'll touch this code now when working on a related issue. Maybe I'll fix this one as well, let's see.

**Comment by grote** [comment]
OK I fixed it while I was at it. Testing this is appreciated!
