### ISSUE TITLE
Navitia: Error when searching from or to POIs

### ISSUE THREAD

**Issue by hoijui** [grote/Transportr#424]
> IllegalArgumentException: Unhandled error id: no origin nor destination

I never tried the app before, but the above error is what i get when searching for routes in the vicinity of Granada, Spain.
I am a Java dev (though not android (yet)), but i could probably do more testing, if given tips/instructions.

**Comment by grote** [comment]
Could you please provide more information such as which version of Transportr you are trying and what the exact search is that produces this error?

**Comment by hoijui** [comment]
i am using transportr 1.1.9

and am looking for:
From: Alhambra
To: Calle Albaicin, Alhama de Granada

it happened for all locations i tried though, including named, search on map, and current location

**Comment by grote** [comment]
@hoijui would be great if you could help with fixing this issue. The `AbstractNavitiaProvider` is pure Java ;)

**Comment by ialokim** [comment]
Please follow up on this issue at https://github.com/schildbach/public-transport-enabler/issues/299.
