### ISSUE TITLE
[Suggestion] Clearing a field via the x-arrow should open keyboard and suggestions

### ISSUE THREAD

**Issue by bambamal** [grote/Transportr#429]
... because that extra click is inconvenient and after clearing you probably want to pick a new station.

**Comment by grote** [comment]
Thanks for the suggestion! This is actually how it is supposed to work. Which version of Transportr did you try?

Do you have steps to reproduce the problematic behavior with v2 beta3?

**Comment by bambamal** [comment]
I'm using v1, the newest version from the playstore.

I just tested 2.3, suggestions are shown as expected, but not the keyboard:
- start the app
- tap on route
- choose station in field 1
- choose station in field 2
- click x on field 1
- only suggestions are shown, not the keyboard
