### ISSUE TITLE
Adding the LPP (Slovenia) network

### ISSUE THREAD

**Issue by JustMeErazem** [grote/Transportr#432]
Please consider adding the LPP (lpp.si) network. There is already an app on Play Store for that network but it is not open source (https://play.google.com/store/apps/details?id=com.remecsamo.lpp) and apparently there is even an open-source api for the network (https://github.com/opendata-si/trola.si), this should make adding it a breeze.

**Comment by grote** [comment]
Sorry, but I can't add all the world on my own. Somebody living in Slovenia and using public transport there regularly would need to add it and then also maintain it afterwards.

Instruction on how to do this are on the website: https://transportr.grobox.de/#add_region

**Comment by JustMeErazem** [comment]
@grote Ok, thanks, I'll try it or try to convince the app dev.

**Comment by aha999** [comment]
@ghost i made an issue about it in [public transport enabler](https://github.com/schildbach/public-transport-enabler/issues/350) and in [Navitia](https://github.com/CanalTP/navitia/issues/3532)
