### ISSUE TITLE
Hide recent trips on the main screen

### ISSUE THREAD

**Issue by flocke** [grote/Transportr#435]
First of let me say that I have been using this app for long time now and it really is my favorite by far, also I really love the new look in the v2 beta.

There is just one little suggestion I would like to make: could we get the option to hide recent trips from the main screen so it only shows Home, Work and favorite trips?
Of course this should be an optional setting and by default be off. Maybe if it is enabled there could also be a little "+" on the bottom of the list to expand it and show the recent trips again.

**Comment by grote** [comment]
Thanks for trying the 2.0 release already!

> could we get the option to hide recent trips from the main screen so it only shows Home, Work and favorite trips?

Could you explain why you would want to hide these trips?

They get added to the end of the list and the list doesn't increase in size when more recent trips get added to the list. As long as you don't scroll down, you don't see them.

**Comment by flocke** [comment]
Currently it looks like this when I start the app, I haven't touched/scrolled anything yet:

![](https://i.imgur.com/ikYO6PP.png)

I would like the option to hide the recent trips shown at the bottom of the list and only show my favorites. The recents don't have to be disabled completely, it would be enough if they are hidden by default and could be scrolled into view.

**Comment by grote** [comment]
I understand what you want, but I don't understand how this would help you or others users of the app.

**Comment by flocke** [comment]
It's not much of an usability improvement, it's more a visual thing. I would find it more intuitive if, on start, you would only see your favorite trips and then, if you pull the list up it reveals your recent trips. It's more to keep the UI clean and easy to read instead of having 10 trips there to look trough.

**Comment by apexo** [comment]
Haven't tried 2.0 yet, but the screenshot LGTM. I don't like the idea of having an extra config option that makes the UX arguably worse. Maybe this could be turned into a privacy feature: don't store recent trips. But then … there are many things that shouldn't be stored in a privacy-optimized mode …

**Comment by grote** [comment]
Sorry, there's so many other tickets. I am closing this one, as it doesn't have a clear way forward for improving the app.
