### ISSUE TITLE
UX: Irritating white/blank space in "mode of transport" selection

### ISSUE THREAD

**Issue by htgoebel** [grote/Transportr#436]
Even if all modes of transport are selected, here is white/blank space in the row. This is irritating since it leaves the impression that not all modes of transport are selected. I assume this depends on the width of the screen.

As solution I suggest to center the box (esp. the border) instead of changing the size. Any white space shall be added outside the border.

![unbenannt](https://user-images.githubusercontent.com/784161/37960678-7bf92a5c-31b6-11e8-9029-37c58f97aa1f.png)

**Comment by grote** [comment]
This isn't as easy as centering stuff, because this is a horizontal scroll view for devices with small screens.

However, this is for Transportr v1 which is at the end of its life and v2 is due to be released soon. So I won't work on v1 anymore.

**Comment by htgoebel** [comment]
Thanks for the info.
