### ISSUE TITLE
[2.0.0] VGS (Saarland) is broken

### ISSUE THREAD

**Issue by mar-v-in** [grote/Transportr#445]
The VGS provider seems to be unusable in transport 2.0.0-rc2. It was functional before with 1.1.9 release. 

Currently have to fallback to DB.

**Comment by grote** [comment]
Seems to be an upstream issue. Oeffi should be affected as well.

**Comment by grote** [comment]
should be fixed by https://github.com/schildbach/public-transport-enabler/pull/200

unfortunately, there's a jitpack problem, so I can't update right now

**Comment by mar-v-in** [comment]
Yes, this seems to be fixed in 2.0.1

**Comment by grote** [comment]
Thanks for fixing goes to @ialokim !
