### ISSUE TITLE
search in métro in Paris is broken on 1.1.9 and 2.0.0-rc2

### ISSUE THREAD

**Issue by webafrancois** [grote/Transportr#449]
Any request don't give a list of places. 
The API has changed ?

**Comment by webafrancois** [comment]
And a few months ago, it worked ! I used it with pleasure. But now, it's broken.

**Comment by grote** [comment]
I can't reproduce this. Did a quick search for a connection between two stations and it worked nicely.

**Comment by ReekyMarko** [comment]
I don't know if this is related but just noticed the same thing in Helsinki, Finland. Haven't used Transportr in a while so I'm not sure what version broke it.

**Comment by grote** [comment]
No it is not related. The Helsinki thing is due to the [transport company shutting down their API](https://github.com/schildbach/public-transport-enabler/issues/166) most likely. It could be easily re-added via Navitia.

**Comment by ReekyMarko** [comment]
Aah ok. Hopefully someone with more skills in Android dev will catch this sometime soon. From what I understand they're not shutting down the api, they're just transitioning to a new version

**Comment by grote** [comment]
The new API works completely differently though. The easiest path would use Navitia. I am sure you could do it ;)

**Comment by ReekyMarko** [comment]
You just encouraged me to try :) I'll have a look

**Comment by grote** [comment]
Since there was no further response and no way to reproduce the reported issue, I will close this now.
