### ISSUE TITLE
MVV: Location name umlaut encoding

### ISSUE THREAD

**Issue by PF4Public** [grote/Transportr#452]
![s80613-155013](https://user-images.githubusercontent.com/10319700/41352599-9ac3edc4-6f22-11e8-870b-57ac3b46c136.jpg)

**Comment by grote** [comment]
Please see [CONTRIBUTING.md](https://github.com/grote/Transportr/blob/master/CONTRIBUTING.md#creating-issues). This is unrelated to Transportr and needs to be fixed upstream.

**Comment by PF4Public** [comment]
Sorry, but what is _upstream_ in this context? Using MVV website or application those symbols are looking  just fine.

**Comment by grote** [comment]
You might want to try the latest v2-rc release to see if the problem exists there as well.

**Comment by PF4Public** [comment]
Oh, sorry, I was under impression, that Transportr does this on its own.
I will fill this bug with them then.

**Comment by PF4Public** [comment]
I have tried v2-rc, but this bug is still there, so filling this bug upstream and cross-linking them.

**Comment by grote** [comment]
Thanks, I'll close this here, because it needs to get fixes in PTE.
