### ISSUE TITLE
Transportr interferes with lockscreen

### ISSUE THREAD

**Issue by PF4Public** [grote/Transportr#453]
1. Open Transportr
2. Lock the screen (autolock or via power button)
3. Press power button to open lockscreen
4. Transportr showed instead
5. Trying to open application list -- nothing happens
6. Trying to open home screen opens lockscreen
7. After unlocking at this moment everything is as usual

Is this a bug or something?

**Comment by TheLastProject** [comment]
It's a feature, see #85.

**Comment by grote** [comment]
That's not a bug, but a feature. You can turn it off it strings if you don't like it. For phones with fingerprint readers it is less useful now.

**Comment by PF4Public** [comment]
@TheLastProject @grote  Thanks for your fast reply, but I do not see any setting for this in Transportr. Is it a system setting instead?

I'm not saying I don't like it. In fact it is really useful! But this behaviour is rare amongst applications, so I was wondering if it is a bug. Anyway thanks for clarifying this :)

**Comment by grote** [comment]
The setting should at least be available in version 2.
