### ISSUE TITLE
Global UK coverage

### ISSUE THREAD

**Issue by ADepic** [grote/Transportr#455]
I found this website called [bustimes.org](https://bustimes.org) which is released under open government license, with local transport networks throughout every town / city in the UK along with bus times too.

All of its information is obtainted from open source data such as NaPTAN. 
This is amazing because transportr could have local network coverage over the whole of the UK

**Comment by grote** [comment]
Looks like most of those have already been integrated in Navitia: https://navitia.opendatasoft.com/explore/dataset/uk/table/?sort=type_file

Also, see the information on the homepage for how to add new regions: https://transportr.grobox.de/#add_region

**Comment by ADepic** [comment]
What does upstream mean?

**Comment by grote** [comment]
Support for these data sets need to get added to public transport enabler (upstream) first, before it can be integrated into Transportr. It is all explained on the homepage.

**Comment by grote** [comment]
I'll close this since there's nothing to be done for Transportr. We can re-open this when public-transport-enabler has support for the UK Navitia dataset.

**Comment by ADepic** [comment]
No, navitia does not have this, it has "global UK coverage" which almost CERTAINLy means national transport across the country - not local transport within towns and cities. 

I'll have to do that myself.

Also, is google groups the only way to contact navitia?
Because I don't have a Google account for that.

**Comment by grote** [comment]
The google groups is just a regular mailing list hosted at Google. You don't need a Google account for it. I am subscribed with just my regular email address there. But there's also a `#navitia` channel on freenode.
