### ISSUE TITLE
Support for Barcelona transport

### ISSUE THREAD

**Issue by yopaseopor** [grote/Transportr#458]
Please can you make a subgroup network called "Barcelona" transport? 
It has no sense to unite Madrid and Barcelona urban transport. There is no coordination with that.
In the other hand you have FGC (Generalitat de Catalunya) + AMB (Àrea Metropolitana de Barcelona) + (TMB - Transports Metropolitans de Barcelona) who are offering public transport at the same places (Barcelona area).

**Comment by grote** [comment]
I totally agree, but it isn't up to me. Like [explained on the homepage](https://transportr.app/contribute/#translating-into-your-language), this data comes from Navitia. Transportr just used their API and they thought for some reason it would be a good idea to create one API area on the national level. You would need to convince them to split it up (good luck with that!) or run your own Navitia server that only offers Barcelona.

**Comment by yopaseopor** [comment]
I know it , for this reason the text of this issue has been sent to Navitia
also.
Thanks for your help

**Comment by grote** [comment]
Let's open this again when Navitia has support for Barcelona alone or somebody else runs a server for it. For now, there's nothing Transportr can do.
