### ISSUE TITLE
Long station names indistinguishable in auto-completion list

### ISSUE THREAD

**Issue by TheLastProject** [grote/Transportr#463]
![](https://i.imgur.com/GNEN59J.png)

I know it's more 9292's fault than Transportrs, but still, this is kinda an issue. Maybe locations could be displayed multiline instead of ellipsed?

**Comment by grote** [comment]
Can you try it multi-line and post a screenshot how that would look like in practice?

**Comment by TheLastProject** [comment]
![](https://i.imgur.com/08G3TBN.png)

Actually looks surprisingly good! Would you accept a pull request of this (as soon as I fix the alignment of the icon left of the location name)?

**Comment by grote** [comment]
Before preparing a pull request, we should think about line separators and also check how this looks where mixed results are returned: one and multi-line

**Comment by TheLastProject** [comment]
![](https://i.imgur.com/8cRyXGQ.png)

I don't consider this unclear, but a nice light separator between entries would likely improve the ease of telling them apart

**Comment by grote** [comment]
Yep, nice work! If you steal a `1px` separator from elsewhere within the project and align the text/icon properly, I'd merge this. Consider using a `ContraintLayout` if the list item isn't one already.
