### ISSUE TITLE
TLS Error seit v2 für saahrfahrplan.de

### ISSUE THREAD

**Issue by forksmith** [grote/Transportr#468]
VGS Verbund
"Peer not verified"
In der älteren Version in Fdroid gehts.
Downgrade ist wohl verhindert, ich musste erst deinstallieren sonst "konnte nicht installiert werden"

English --> 
Germany, Saarland, VGS
Host saarfahrplan.de
<2.0.0fdroid works.
Is the anti downgrade flag set? I had to reinstall.

**Comment by grote** [comment]
Which version are you using? cc @ialokim

**Comment by forksmith** [comment]
Transportr from Fdroid 1.1.9 --> No TLS Error
Trabsportr from Fdroid 2.0.0 --> TLS Error

**Comment by grote** [comment]
You need version 2.0.1 (not yet available in F-Droid's official repo).

Duplicate of #445
