### ISSUE TITLE
Name of the Map layout

### ISSUE THREAD

**Issue by prog-amateur** [grote/Transportr#469]
Hello ! first, thank you for the app, I really appreciate. 
This is more a question than a real issue : 

I was wondering what the theme of the map was. It's really ergonomic, and looks like Google Map. 

Please, do you have the theme of this Map, I would like to know if this is available on OsmAnd. 
Thank you very much.

**Comment by grote** [comment]
Maps come from http://mapbox.com/. OsmAnd uses their own vector library which is IMHO not compatible with vector tiles.

**Comment by prog-amateur** [comment]
Thank you for your quick feedback ! Mapbox is a nice open-source library.
