### ISSUE TITLE
Directions button hidden below bottom sheet on Android 4

### ISSUE THREAD

**Issue by Wikinaut** [grote/Transportr#471]
On an old MEDION Lifetab S9512 with Android 4.0.4 (which I am currently testing), the navigation symbol is barely visible, and invisible, because covered, when having connections in the connections list.
![img_20180721_112139](https://user-images.githubusercontent.com/1151915/43034234-244972fc-8cd9-11e8-86b8-262e7790d92c.jpg)

* Android 4.0.4 (uh, yes...)
* Transportr 2.0.0 (installed from F-Droid on 20180721)

**Comment by grote** [comment]
Thanks for reporting. I saw this as well on Android 4. It is probably related to `android:elevation` not working properly there. No time to debug exotic platform issues like those. Pull requests welcome!
