### ISSUE TITLE
App crashes on route search when location is off

### ISSUE THREAD

**Issue by ad2h** [grote/Transportr#475]
Since version 2.0, trying to search a route when location services is turned off causes the app to crash.

This happens when touching the red route search button, as well as when selecting a pre-set location (such as home). When searching for a location in the search bar above there is no problem, but then when trying to search a route from that location the app crashes. The only situation in which it doesn't crash is when re-searching an already saved route via the main screen. This leaves the app unusable for most purposes when location services is off.

It works fine when location is on, of course, but some users prefer to keep location off for the most time when possible.

Android 7.0 on Huawei Honor 5c.

**Comment by grote** [comment]
I can't reproduce this myself and I know many people using the app without location services. Can you get me the stacktrace of the crash via logcat? Do you use it via Google Play or F-Droid?

**Comment by ad2h** [comment]
Sorry, I couldn't get to it.

Anyway, the bug was resolved in version 2.0.1, and no sign of regress in 2.0.2.
Thanks!

**Comment by ad2h** [comment]
Via F-Droid, btw.
