### ISSUE TITLE
Reverse Geocoding imprecise

### ISSUE THREAD

**Issue by exploide** [grote/Transportr#478]
First of all, thank you very much and congratulations to the new Transporter v2 release. It looks very nice. :)

I found the following issue. When long pressing the map to do a reverse geocoding, the resolved address is rather imprecise. See the following screenshot
![screenshot_20180723-185323](https://user-images.githubusercontent.com/5670236/43091424-5b8c45c8-8eaa-11e8-9b42-05710ad1c5ca.png)
Here, it shows house number 68 instead of 72.

I looked into the source code and it seems you are using Nominatim. Strangely, when performing the same query on their website, the address is correctly resolved. https://nominatim.openstreetmap.org/reverse.php?format=html&lat=48.50184845693443&lon=9.055255651474&zoom=18

Some addresses in the area were added within the last few months, so maybe the used data is not up to date?! But I wonder how that can be the case when querying Nominatim. On the other hand, I also have issues finding certain addresses from the new search bar you implemented. Some house numbers appear there, some not.

Since I do not fully understand why this issue appears, I decided to open a bug report here.

**Comment by grote** [comment]
I also don't understand it. Do you have Google software installed? Play store for example?

**Comment by n76** [comment]
MicroG also has a geocoder backend that uses Nominatim. Default is for OSM but you can also select MapQuest.

**Comment by exploide** [comment]
Yes, Play Store and associated services are installed. (Though, Transportr is installed from F-Droid.)

I wasn't aware that this is relevant since Transportr seems to implement reverse geocoding on its own by querying Nominatim online.

**Comment by grote** [comment]
No, if you have Google Play installed you already sold your soul and to reduce the load on Nominatim, it will then use Android's default geolocation backend instead.

**Comment by exploide** [comment]
(Wish I could get rid of it, but I still require some stuff that forces me to have play services. :/ )

But ok, that explains it. OSM is way more up to date in this area than Google Maps, which I guess is used by Android's geolocation backend.

Sad to hear that. Would be awesome to have the app completely OSM-based. Especially because I brought the area up to date and now can't benefit from it :D .. But I understand your reasoning to reduce load on Nominatim...
