### ISSUE TITLE
Reduce APK size

### ISSUE THREAD

**Issue by Arnaudv6** [grote/Transportr#480]
Good day everyone, and thanks for this awesome app.
You must have seen that this app got big in size with version 2.0.

By my standards, it has gone huge: do you know the cause and can this be contained anyhow?

**Comment by grote** [comment]
The issue comes from the map library which includes native code for various processor architectures. The obvious solution is to use split APK, one for each architecture, but this isn't really supported by F-Droid (and maybe also not by fastlane, need to check).

A first step could be to strip out some architectures that are not strictly necessary. You can help by researching what those are and making sure they really aren't needed.

See https://gitlab.com/fdroid/fdroiddata/merge_requests/3442#note_87903841 and below for more info.

**Comment by grote** [comment]
Documentation:
* https://developer.android.com/ndk/guides/abis
* https://developer.android.com/studio/build/configure-apk-splits

**Comment by Arnaudv6** [comment]
Just so you know, I'm not taking up the task, sorry, I don't have the time.

**Comment by Bubu** [comment]
Tried this out:
```
diff --git a/app/build.gradle b/app/build.gradle
index b7c2808c..a4ec1058 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -50,6 +50,13 @@ android {
+  splits {
+    abi {
+        enable true
+        universalApk true
+        }
+    }
```

These are the resulting apks and sizes:
```
Transportr (master)$ ll ./app/build/outputs/apk/release/
total 53M
drwxrwxr-x 2 mhoffmann mhoffmann 4,0K Aug 12 12:37 ./
drwxrwxr-x 4 mhoffmann mhoffmann 4,0K Aug 12 12:36 ../
-rw-rw-r-- 1 mhoffmann mhoffmann 8,5M Aug 12 12:37 app-arm64-v8a-release-unsigned.apk
-rw-rw-r-- 1 mhoffmann mhoffmann 8,2M Aug 12 12:37 app-armeabi-v7a-release-unsigned.apk
-rw-rw-r-- 1 mhoffmann mhoffmann  20M Aug 12 12:37 app-universal-release-unsigned.apk
-rw-rw-r-- 1 mhoffmann mhoffmann 8,6M Aug 12 12:37 app-x86_64-release-unsigned.apk
-rw-rw-r-- 1 mhoffmann mhoffmann 8,6M Aug 12 12:37 app-x86-release-unsigned.apk
```

**Comment by Bubu** [comment]
I feel the only thing missing here is f-droid supporting autoupdate for split apks. 
@grote Would you be okay with a script generating and opening a MR in the fdroiddata repo instead?

**Comment by grote** [comment]
@Bubu this looks good!

> Would you be okay with a script generating and opening a MR in the fdroiddata repo instead?

Sorry, I don't understand. What would the script do and what would happen in fdroiddata?

**Comment by Bubu** [comment]
@grote instead of having the fdroidserver check for updates (which doesn't work for split apks currently). integrate a script into your release process which adds the new release to transportrs fdroiddata metadata file and opens a merge request there.

**Comment by grote** [comment]
Ah yes, that could be a nice workaround. We should also add the split APKs to fastlane which is probably easier.

**Comment by ialokim** [comment]
@grote Any news on this one? Now that we have a release script, it might be easy to integrate this into it?

**Comment by grote** [comment]
Yeah could be done. But the work of making automated F-droid MR to update the various split APKs is still the main thing. F-Droid could also use a universal binary (like now) and only other distribution channels benefit from the split.

**Comment by ialokim** [comment]
> F-Droid could also use a universal binary (like now) and only other distribution channels benefit from the split.

This would be perhaps a good starting point. To include this into F-Droid, we might refer to https://gitlab.com/fdroid/fdroiddata/-/issues/1109

In a later step and for the automatic F-Droid MRs, we might look into the [VLC](https://gitlab.com/fdroid/fdroiddata/-/commit/a996d3f9265bd761e4e1150838ee077567bee9ba) or [Telegram FOSS](https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/master/TMessagesProj/build.gradle) approaches.

Also, we might wait until [fdroidserver can handle split apks](https://gitlab.com/fdroid/fdroidserver/-/issues/82).

**Comment by Arnaudv6** [comment]
Agreed. Closing.
*.apk slimmed a tad since I opened this bug 4.5 years ago,
and even 19MB is nothing abnormal by today's standards...
Not much to do. Thanks for your care.
