### ISSUE TITLE
new update: stored locations removed

### ISSUE THREAD

**Issue by Violinchen** [grote/Transportr#483]
**Describe the bug**
All starred locations and routes have been removed, you must search everything again.

**To Reproduce**
Use a while some version before 2.0.0 , star some locations, then update to the recent version.

**Expected behavior**
Show everything I saved as before.

**Screenshots**

**Versions (please complete the following information):**
 - Transportr Version:  2.0.1
 - Device: Sony XPeria
 - Android Version: 5.0

**Comment by grote** [comment]
Sorry @Violinchen the new version has a different database and I couldn't save the old information. Hope you can save your favorite stations and trips again. There's nothing anymore I can do about it now :(

**Comment by DJCrashdummy** [comment]
just a hint @grote: maybe a note at the [release-notes](https://github.com/grote/Transportr/releases/tag/2.0.0)/changelog/etc. would have been reasonable... so careful users will be prepared to copy the favourites before upgrading to 2.0.x.
