### ISSUE TITLE
Add Launcher Shortcut to Directions Search

### ISSUE THREAD

**Issue by Violinchen** [grote/Transportr#485]
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.
* [ ] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**
It is annoying, that I must always click the "search"/"route" button when I need a connection. In version 1.*.* the program immediately showed the route form.

**Describe the solution you'd like**
Display the search form first when starting transportr (like version 1). The map is not that important.

**Comment by grote** [comment]
![directions_shortcut](https://user-images.githubusercontent.com/244947/43427442-e9d91858-942f-11e8-8758-8ec74515bfaf.gif)

**Comment by andreassch** [comment]
The procedure to create the Directions launcher shortcut described above does not work on my phone. When holding my finger on the app icon, no menu appears, unlike shown above. Are there any prerequisites for that to work, such as a special Android version?

**Comment by grote** [comment]
This isn't released, yet. But if it will be you need at least Android 7 and a launcher that supports these shortcuts.
