### ISSUE TITLE
Add automatic search for nearby stops

### ISSUE THREAD

**Issue by sebalis** [grote/Transportr#488]
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.
* [n/a] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

See #421 (closed) – from @techge’s suggestions, this seems to be the one idea that @grote saw as a possible future enhancement so rather than adding `unresolved`to the whole ticket I thought I’d create a new, more specific one.

**Comment by grote** [comment]
The title of this ticket seems to imply that you want to search for and display nearby stops automatically on the map without user interaction. This wasn't exactly the proposal in #421 if I understood it correctly.

**Comment by sebalis** [comment]
I now changed the title and description after spending close to two hours trying to really understand the ticket and the way the map currently works (creating #489 in the process). I probably haven’t figured it out yet. Among other things I only once saw the option to display nearby stations and even I did not understand how the option suddenly appeared (a gift from the gods, given sparingly and randomly?). I would like to see this function more. In line with #489 I would suggest adding it to the context menu after long-tapping a location. But maybe I haven’t understood the new UI enough yet.

**Comment by sebalis** [comment]
I have now discovered how to obtain that gift from the gods: drag the context menu upwards. I find that confusing since there is both a context menu (via the three dots) and more items revealed by dragging upwards. Now I don’t know what to do with this ticket anymore. The initial intention was to capture the ideas you considered feasible at the end of the discussion of #421. Now I want to suggest way of making “find nearby stops” more easy to find. Will now change the title again. Please advise.
