### ISSUE TITLE
Add Föli data

### ISSUE THREAD

**Issue by theel0ja** [grote/Transportr#493]
I'd like to have support for Turku Area Public Transit ("Föli").

GTFS API can be found there: http://data.foli.fi/doc/index-en

**Comment by grote** [comment]
Did you read the documentation about adding new providers? Did you check if this data is already included in the HslProvider?

**Comment by theel0ja** [comment]
HSL Provider is for Helsinki region, not Turku/Föli

**Comment by grote** [comment]
This provider is now covering these areas: https://navitia.opendatasoft.com/explore/dataset/fi/table/?sort=type_file

@aperezdc maybe it should be renamed? At least within transportr and use a different logo?

**Comment by theel0ja** [comment]
Actually, it seems to support Turku area.

**Comment by theel0ja** [comment]
![](https://cloud.eliasojala.me/s/mTafpXpkMBioJiY/preview)

**Comment by grote** [comment]
Cool, so we can close this? If there's something wrong with the data, please talk to Navitia about it.

**Comment by aperezdc** [comment]
Hello! Yes, I am back from holidays and a work trip now, and I'll try to find some spare time to keep improving things for HSL + Finland. Indeed it looks like Navitia provides informaion for all of Finland from the same dataset, so I'll make a PR to rename the location in the UI. Side note: I'll try to get `HslProvider` at some point renamed to `FinlandProvider` in PTE, and then start working in a new `HslProvider` for the OpenTripPlanner-based API that HSL supports now.

**Comment by grote** [comment]
Great @aperezdc, sounds good! :)
