### ISSUE TITLE
NPE when searching return trip with empty current location

### ISSUE THREAD

**Issue by heyarne** [grote/Transportr#497]
**Describe the bug**
First off: Not 100% sure if I'd call all of this a bug, but it seems a bit unintuitive for me. It's about the app's behavior when selecting a previously saved location (home / work).

**To Reproduce**
First behavior:
1. Open the app
2. Tap on "Home"
3. You'll land on the next screen with the trip start being focused and empty; the destination is home.

Second behavior:
1. Open the app
2. Tap on the three dots next to home, click on "return trip" (I'm not 100% sure about the translation, I'm using the german locale and it's called "Rückfahrt suchen")
3. The home address is now the start address

In the second case I had expected the home address to be the destination of my return trip, whereas in the first case I had expected it to be the destination. Selecting a return trip to an address and seeing it used as the start for that return trip seems buggy.

Additionally, I'm getting the following error when trying to reproduce the second behavior:

![screenshot_transportr_20180807-095535](https://user-images.githubusercontent.com/525780/43762470-4da0d5da-9a28-11e8-8e7c-c6361cdf5b05.png)

This is with the DB provider, in case it matters. I realize it says to open a bug report in the PTE repository, but my guess is that there's a location query before I have a destination resulting in the error, so it's expected behavior from the public transport enabler. 

**Versions (please complete the following information):**
 - **Transportr Version:** 2.0.2
 - **Device:** Xiaomi Mi 5
 - **Android Version:** 8.1

**Comment by grote** [comment]
> You'll land on the next screen with the trip start being focused and empty; the destination is home.

This should only happen when you don't have GPS enabled. If you have, it would search automatically from your current location.

The red button is supposed to guide you to the selected location.

> Additionally, I'm getting the following error when trying to reproduce the second behavior:

That's a real bug. Thanks for reporting!

**Comment by heyarne** [comment]
Ok, but why is there the explicit possibility for a return trip (via context menu) and then the "return trip on tap" functionality? Am I missing something?

**Comment by grote** [comment]
The return trip functionality exists for all favorites. We should probably give it another name for home and work. It means go from work to your current location.

Btw. I can't really reproduce the bug with the NullPointerException. Can you please provide exact steps for how to get there?

**Comment by heyarne** [comment]
> I can't really reproduce the bug with the NullPointerException. Can you please provide exact steps for how to get there?

I have the address above set as my home address for the Deutsche Bahn provider (there is no work address set, I don't know if that's relevant). The error occurs when I open the context menu of the "Home" card and select "Return trip". Interestingly enough it doesn't happen with the BVG provider, which gives me the note: *Konnte den Ort 'nach' nicht finden. Bitte versuche es mit einem anderen.*

> The return trip functionality exists for all favorites. [...] It means go from work to your current location.

I see. But why is the destination and source swapped when I don't have a current location? Wouldn't it make sense to leave it empty so I can enter it myself? What I do now (since I have location turned off most of the time): Open the context menu for home, select return trip, swap locations (so destination is my home), enter source location manually. Maybe I'm just thinking differently and this really isn't an issue, but I find it really unintuitive to select return trip and somehow end up with the selection I want to return to as the source.

Anyways, thanks for this great app!

**Comment by grote** [comment]
> I have the address above set as my home address for the Deutsche Bahn provider (there is no work address set, I don't know if that's relevant). The error occurs when I open the context menu of the "Home" card and select "Return trip".

Thanks! Now I can reproduce it!

> But why is the destination and source swapped when I don't have a current location? Wouldn't it make sense to leave it empty so I can enter it myself?

It is not swapped and swapping it depending on whether a location is available or not would be confusing. When you just click your home location it will bring your there from your current position (or leave it empty for you to enter). When pressing "return trip" it swaps the locations. However, the name "return" is confusing here. I just took the same label that the favorite trips have, but should probably use another one like "From here".

**Comment by grote** [comment]
@heyarne Is this still happening? (I lost track of this issue)

**Comment by heyarne** [comment]
The NPE is not happening anymore, I still find it quite confusing to have your home address set as the trip's starting point when selecting "return trip" though, but I guess that's just a completely different discussion. Thanks for you work on the app!

**Comment by grote** [comment]
> I still find it quite confusing to have your home address set as the trip's starting point when selecting "return trip" though

When you just click the home button, it is the destination point. If it would be destination as well for return trip, there would be no way to start from home.
