### ISSUE TITLE
flat 5 sayer court is incorrectly named sayer court 5

### ISSUE THREAD

**Issue by prototype99** [grote/Transportr#498]
**Describe the bug**
flat 5 sayer court (and presumably all other numbers too, i'm not sure how to check) is incorrectly  named.

**To Reproduce**
1. go to the geographical location (due to #499 ) so you can see the name
2. use directions, which will bring up the name
3. you can then observe the erroneous name

**Expected behavior**
property is named flat 5 sayer court

**Screenshots**
![transportr](https://user-images.githubusercontent.com/11457027/43892092-ed0c72be-9bc2-11e8-94e8-708e96cdf2bf.jpg)

**Versions (please complete the following information):**
 - Transportr Version: 2.02
 - Device: google pixel 2
 - Android Version: 9

**Comment by grote** [comment]
Transportr isn't responsible for the data. It gets it from I guess TLEM in your case. You would need to complain with them.
