### ISSUE TITLE
sayer court does not appear in search

### ISSUE THREAD

**Issue by prototype99** [grote/Transportr#499]
**Describe the bug**
sayer court can not be selected in search, the app only seems to acknowledge a 'sayers court'. please see #498 as well.

**To Reproduce**
1. type sayer court into search bar
2. option is not available

**Expected behavior**
sayer court appears in search

**Screenshots**
![transportr-search](https://user-images.githubusercontent.com/11457027/43892358-9997dc8a-9bc3-11e8-9624-e735474611f5.jpg)

**Versions (please complete the following information):**
 - Transportr Version: 2.02
 - Device: google pixel 2
 - Android Version: 9

**Comment by grote** [comment]
Transportr isn't responsible for the data. It gets it from I guess TLEM in your case. You would need to complain with them.
