### ISSUE TITLE
Austrian's VOR network - parse error for valid (suggested!) station name

### ISSUE THREAD

**Issue by tbart** [grote/Transportr#501]
Searching VOR for "Wien Wien-Mitte Landstraße" gives a parse error.
If choosing a route than goes via this station (which works, just choose "Wien Mitte" and the first minutes will be shown as a walk) and then choosing "from here" on "Wien Wien-Mitte Landstraße" you also see the same error, so it is no input error.

**Comment by tbart** [comment]
![screenshot_transportr_20180809-181203](https://user-images.githubusercontent.com/9994131/43912385-5e055d66-9c02-11e8-90c7-057925c9a45d.png)

**Comment by grote** [comment]
Thanks for reporting, but this is an issue of public transport enabler like written in many places, even your screenshot.

**Comment by tbart** [comment]
Sorry, I explicitly searched for public transport enabler and got here. That was obviously not correct. Would you mind adding a clickable link to the error message?
I'll report it upstream.

**Comment by grote** [comment]
It is mentioned when you create a bug here, in the contribution notes and on the transportr homepage. https://github.com/schildbach/public-transport-enabler/
