### ISSUE TITLE
use classic version?

### ISSUE THREAD

**Issue by jeyca** [grote/Transportr#503]
Unfortunately I am very unsatisfied with the 2.0 design break and would love to still use the classic and simple Transportr before the change. I know one should not use old software... but is there any known security issues with the last version in classic design? 
And where could I get it? Could not find anything on https://f-droid.org/en/packages/de.grobox.liberario/

Or is there already anyone who manages a fork from the old version?

**Comment by grote** [comment]
There's no security issues and for an app like Transportr, they are not likely. The issue you will run into is that data source might stop working and not receive fixed.

Duplicate of #462

**Comment by DJCrashdummy** [comment]
@jeyca you can find the old versions via f-droid after enabling the [official F-Droid Archive](https://f-droid.org/archive?fingerprint=43238D512C1E5EB2D6569F4A3AFBF5523418B82E0A3ED1552770ABB9A9C9CCAB) or (NOT recommended) the 1.1.9 apk via its [direct link](https://f-droid.org/archive/de.grobox.liberario_49.apk).
