### ISSUE TITLE
"From" field is missing "My current location"

### ISSUE THREAD

**Issue by ReekyMarko** [grote/Transportr#506]
After the major overhaul, I've been unable to find the option to put my current location in the "From" field when trying to navigate somewhere. Either it has been relocated and I just can't find it or it indeed has been lost in the overhaul.

**Comment by grote** [comment]
Can you please try this?
1. Ensure GPS is on
2. Start Transportr
3. Press the GPS button in the bottom right corner and see if it found your location
4. Press the red directions button and see if your location was entered as From address

**Comment by ReekyMarko** [comment]
Aah now it works! Earlier today it was filling in a location from a completely different town I visited a couple of days ago. I guess it was a fluke specific to my use case.

Either way, leaving out "My location" from the dropdown is very confusing IMO, since almost all apps of this type have it.
