### ISSUE TITLE
Vienna: local trains missing from Wiener Linien

### ISSUE THREAD

**Issue by averageunicorn** [grote/Transportr#510]
I suspect that this is not in the scope of this app, but I don't know where the data comes from, so I am still posting here in the hope that someone can point me to the relevant project.

In Vienna, Austria, local trains (S-Bahnen) are part of the public transport network and don't require a separate ticket, and I'd expect them to be included in searches (they are, for example, on the website of Wiener Linien, Vienna's public transit company).

In Transportr, the Wiener Linien search never shows any S-Bahn even if it would be by far the most logical and fast option.

An alternative for looking up routes in Vienna is the VOR network (for a larger area that includes Vienna), it includes S-Bahnen but it doesn't do addresses, you can only search station to station.

ÖBB, the austrian railway, works fine in Vienna, includes S-Bahnen and does addresses, but it is hard to use because the suggestions include stations all over Austria.

So… if there is any way to make S-Bahnen show up when Wiener Linien is selected, either here at Transportr or by asking nicely at some other place, that would be really great :)

**Comment by grote** [comment]
like written in many places, please go to https://github.com/schildbach/public-transport-enabler/

This question belongs on its mailing list: public-transport-enabler-discuss@googlegroups.com

**Comment by averageunicorn** [comment]
hah I didn't see the "many places" I guess, thank you!
