### ISSUE TITLE
Improve Directions Error UI

### ISSUE THREAD

**Issue by gjedeer** [grote/Transportr#513]
This is what an error UI looks like:

![0000000f screenshot_transportr_20180823-080355](https://user-images.githubusercontent.com/315648/44508474-ba01ca80-a6ae-11e8-932c-3b36a25fd793.png)

Two things that I think would improve it:
* Make the stack trace selectable / copy-able
* Make "public-transport-enabler" a link to https://github.com/schildbach/public-transport-enabler/issues

**Comment by grote** [comment]
Thanks these are great suggestions. Want to do a PR?

**Comment by gjedeer** [comment]
Never mind, I had to set JAVA_HOME differently, something with Ubuntu 18.04 apparently.

**Comment by grote** [comment]
Looks like this is fixed now.
