### ISSUE TITLE
translation work done for swedish

### ISSUE THREAD

**Issue by scrdcow** [grote/Transportr#515]
Hi! I know this is completely the wrong way to do it. but... I have already translated the app to swedish with stringlate (android app). I exported the work and it gave me a zip with everything. Then I found your webpage and  realized how I should have done it with transifex. Maybe I can add it correctly with transifex later or maybe a PR here. But i'm all new to this (translation, github and transifex) and just want to upload it so it will not get lost and forgotten. I'm not sure if lines that should not be changed, should not be translated. For ex links, names etc. Not sure if the strings.xml files overlap somehow or what is the right way to do it. But now I did just copy them.

Thanks for the great app!

[Transportr.zip](https://github.com/grote/Transportr/files/2320509/Transportr.zip)

**Comment by grote** [comment]
Hey, thanks for the translation! Would you mind signing up for Transifex and going through the workflow there? You should be able to upload the translation there.

**Comment by scrdcow** [comment]
No, not in theory :-) But I had problem logging in. I did manage to request swedish language atleast. If I troubleshoot whatever is blocking sending referer-url then I can login and do it. But even with firefox --safe-mode it did not work. I just wanted to upload it in case I then forget about it all. Stringlate was great for working on the phone while commuting. Hope they can fix auto-upload/PR then perhaps it would be easier. Just translating on the whim, not having to sign up for accounts, requesting language etc is much easier. As a complement.

**Comment by grote** [comment]
I accept your request for Swedish, but looks like you still need to join the team there.
