### ISSUE TITLE
GPS position will not updated 

### ISSUE THREAD

**Issue by mseerig** [grote/Transportr#516]
When I'm in the map view (with an active navigation), my currently changing position will not be updated in the map. Only my new orientation will be shown.

For a better self orientation, a change will be nessesary for me. 

Otherwise: Thank you for doing a great job! :)

**Comment by grote** [comment]
Is there a GPS icon in the status bar, indicating that the app is monitoring the position?

Does it help do put the app in the background and open it again? Maybe even pressing back a couple of times until the app closes and then reopen the connection?

**Comment by mseerig** [comment]
it's fixed now :)
