### ISSUE TITLE
Can't find Alicante Airport

### ISSUE THREAD

**Issue by alexanderadam** [grote/Transportr#518]
**Describe the bug**

I know Spain is still in beta but I can't find Alicante Airport in the search although it's available in all other transportation portals I know.

**To Reproduce**
1. Click on the search input
2. type 'Alicante Airport' or 'Alicante Aeropuerto'

**Expected behavior**
See a match

**Screenshots**

![screenshot_20180830-172618_transportr](https://user-images.githubusercontent.com/372620/44862403-e606e800-ac7a-11e8-9c37-1f2b893e1dff.jpg)

**Versions (please complete the following information):**
 - **Transportr Version:** 2.0.2
 - **Device:** every device
 - **Android Version:** every version

**Comment by grote** [comment]
What happens when you move the map to the airport, long press on it and then search for nearby stations? Does it find the station?

**Comment by alexanderadam** [comment]
@grote longpress doesn't work. It just sets the marker and enables "From here" and "Copy location"

**Comment by grote** [comment]
Did you try to pull up the bottom sheet like the onboarding dialog in the beginning told you?

**Comment by alexanderadam** [comment]
No, but I admit that I'm not very comfortable with the new UI anyway. ;)

I tried now and the "NEARBY STATIONS" button was only once functional! After that it stopped working.

I had to restart Transportr to have it working again. However, both times no stations were found.

Even if the bus stations wouldn't be found, I would at least expect that the train station would have been found. For comparison you can see the result on [Google Maps](https://www.google.com/maps/search/Bushaltestelle+in+der+N%C3%A4he+von+Alicante+Airport/@38.2895489,-0.5565427,16z)

**Comment by grote** [comment]
Sounds like an issue with Navitia. Maybe their data is out of date. Nothing I can do about it. You need to talk to them: https://www.navitia.io/ https://groups.google.com/forum/#!forum/navitia

**Comment by alexanderadam** [comment]
Oh, okay. so I guess I should close it then!?

Thank you for your help!
