### ISSUE TITLE
Getting error with PKP in Poland

### ISSUE THREAD

**Issue by Eva850** [grote/Transportr#520]
It used to work, now there is an error, attaching screenshot:
https://ibb.co/cHMYhz

**Comment by grote** [comment]
Thanks for your report @Eva850. The screenshot doesn't load for me. You can also upload images here directly. No need for third-party sited.

Also, did you read the "Important" part here? [Creating Issues](https://github.com/grote/Transportr/blob/master/CONTRIBUTING.md#creating-issues)

**Comment by Eva850** [comment]
![screenshot_20180902_131630_transportr](https://user-images.githubusercontent.com/20646455/44975128-eac0ea00-af61-11e8-8a7f-2be5d922ef74.jpg)

**Comment by grote** [comment]
Thanks Eva, this is already tracked in the correct upstream repository: https://github.com/schildbach/public-transport-enabler/issues/223

cc @mimi89999
