### ISSUE TITLE
Deactivated "Via" field still triggers error

### ISSUE THREAD

**Issue by chris-je** [grote/Transportr#522]
**Description**
If the "Via" field is equal to the "From" or "To" field an error message is displayed.
As far as good. But this error is also displayed when "Via" is deactivated.

**To Reproduce**
1. Search for an Connection (also add a place to the "Via" field)
2. Deactivate the Via field
3. Use the "From" or "To" field and add the place which have been in the "Via" field before deactivating it

**Expected behavior**
The error message "The 'from' and 'to' location are too close together" appears.
This happens even if the two places are several hundred kilometers separated from each other.

**Screenshot**
![photo_2018-09-08_19-41-20](https://user-images.githubusercontent.com/9323103/45257024-590d0e80-b39f-11e8-8716-79b781db22d2.jpg)

**Version**
 - **Transportr Version:** [2.0.2]
 - **Device:** [HTC one M8s]
 - **Android Version:** [6.0.1]

**Comment by grote** [comment]
The Via field isn't deactivated when you can't see it, it just isn't shown. Notice how the label says "Show Via". But I can see how this can be confusing.
