### ISSUE TITLE
Have a contact channel for support/discussion

### ISSUE THREAD

**Issue by anjandev** [grote/Transportr#523]
It would be nice to have a chat channel for discussion/support of transportr.

I love xmpp and would reccomend it for the chatroom. However, having a freenode irc channel is good too. 

Let me know what you think =)

**Comment by grote** [comment]
The only person that could provide support is me and I have barely time to maintain the app.

However, feel free to register a freenode channel, MUC or whatever.

For help with implementation, I prefer to respond in the corresponding ticket asynchronously.

**Comment by anjandev** [comment]
That is completely understandable. I come and go with contributing to open source and I cant imagine the time it would take to consistently maintain a project. 

I'll look into making a freenode channel or MUC when I get more experience with the code.

I appreciate the timely asyncronous replies.

**Comment by grote** [comment]
> would you mind making a fediverse account?

Sorry, I lack the time. But feel free to create one that mirrors the twitter account.

**Comment by MarionMoseby** [comment]
@grote could you sign up for the cross poster at crossposter.masto.donte.com.br? It should be fairly easy, you'd get a fediverse account and that way nobody needs to spend lots of time creating a bot :)
