### ISSUE TITLE
No results when searching for directions, search bar, or adding home/work

### ISSUE THREAD

**Issue by colinner** [grote/Transportr#525]
**Describe the bug**
I've been unable to get the app to provide any search results when searching for places or route results with directions.

**To Reproduce**
1. Open app and zoom to transit-covered area.
2. Type in search bar for places, but no place results appear. Animated loader circle icon appears for 1 second then goes away.
2. Next, (since I cant get search results) I Fill in the To and From fields by tapping "From here" and pasting a place name to be sure that the places are valid.
3. Tap "Next" on keyboard. (nothing happens)
4. Close keyboard. (nothing happens; no buttons or anything to start the search for directions)

**Expected behavior**
Either a button to search for routes/places or routes/places appearing when tapping "Next" on the keyboard.

**Screenshots**
![screenshot_2018-09-15-22-21-58](https://user-images.githubusercontent.com/43309111/45593247-c3eeb480-b960-11e8-890b-438e2056a87a.png)

**Versions (please complete the following information):**
 - **Transportr Version: 2.0.2
 - **Device: Nexus 4
 - **Android Version: 4.4.3

**Comment by grote** [comment]
Thanks for the report. It sounds like the problem is due to pasting a place name. Could you try typing the name instead and selecting one from the list?

**Comment by colinner** [comment]
Yes, I've done that. But that is part of the problem- no results for place searches appear NOR results for directions. I've updated the report to emphasize this more. I'll try again to be sure.

**Comment by grote** [comment]
Sounds like an API issue. If you use british columbia, you'd need to talk to Navitia about this.

**Comment by grote** [comment]
Are you using the British Columbia coverage? If so, if I type "Olym" I get some results of stations and places!?

**Comment by grote** [comment]
Sure you are not blocking transportr's internet access with some firewall or something? Can you try DB in Europe and type test to see if this brings any results? If not, does it work if you put a space at the end?

**Comment by colinner** [comment]
No I don't have any internet blocking apps. I can load and browse the map just fine. Appending spaces doesnt make a difference. I tried the Deutsche Bahn in Europe- and yes! I get some search results!

**Comment by colinner** [comment]
I've tried the other networks in Canada but they also have no search results.

**Comment by grote** [comment]
Very strange! Can you try Paris? It uses the same API as Canada.

**Comment by colinner** [comment]
Hmmm, yes Paris behaves the same way as the Canadian networks. No search results.

**Comment by grote** [comment]
Aha! We are getting closer. Can you open https://api.navitia.io in a browser on the same device? If not, you need to report this to Navitia.

**Comment by colinner** [comment]
At that link all I see is a JSON string all on one line.

**Comment by colinner** [comment]
Is there any chance the API requires Google play services?

**Comment by colinner** [comment]
[logcat_transportr_searchingAndRouting_BC.txt](https://github.com/grote/Transportr/files/2397954/logcat_transportr_searchingAndRouting_BC.txt)
Hopefully this is helpful.

**Comment by grote** [comment]
Unfortunately not. There's nothing related to Transportr in there.

**Comment by colinner** [comment]
Is there any special setting required in logcat?

**Comment by ialokim** [comment]
We had to remove BritishColombia with #884 since data for it is no longer available.
