### ISSUE TITLE
[UI] Bring back button for 'Swap directions'

### ISSUE THREAD

**Issue by Echolon** [grote/Transportr#528]
Hi,

regarding this closed issue #29, I would like to suggest to bring back the 'Swap directions'-button to the top-front. For the moment it is hidden in the burger menu as 'Swap From and To'. 
See picture for the suggestion:

<img src="https://user-images.githubusercontent.com/29168011/46541518-870d4200-c8bc-11e8-918e-2a7c764af144.png" width="250">

_Yes, I know it's just a poorly made impression for you_ :smile:

I personally use swap a lot, but I think it will be helpful for a lot others, too. _(Please vote and we will see)_ Yes, I know the screen-size is maybe a restrictive problem, but I would e.g. switch it with the 'Favorite'-button, as places and last searches are saved anyway.

Cheers

**Comment by grote** [comment]
I am thinking about adding a new line at the bottom (maybe optional) that could include this and other UI elements we had in Transportr 1.

**Comment by Echolon** [comment]
I would rather try to keep this at the top and maybe then put the favorit-button down?

But ok, I have no idea about design.

Thanks for the great app! With this it would be perfect for me!

**Comment by grote** [comment]
Implemented by #535.

**Comment by Echolon** [comment]
_If you want me to create a new issue, I can do so_

Thanks again for bringing back this now often (at least by myself) used feature.

What happens to me is, that I go to a place, I search for the direction and when I come back I just swap the entries. Transportr is doing good on this, however it does use the previous time and not the current time. So, if I started 3 hrs ago, Transportr will check the way back for the same time, 3 hrs ago, which never or in very seldom cases makes sense.

Therefore I would like to suggest to always change to 'Now' once pushing way back..... or am I missing something? At least Transportr should do so, if a specfic time has passed (e.g. 10-30 minutes)

Cheers
