### ISSUE TITLE
SNCB: Results show an erroneous destination

### ISSUE THREAD

**Issue by stemy2** [grote/Transportr#531]
Hello,

I planned a trip to a specific bus stop in Belgium, but the destination i see in the results is not the one i entered in the «destination» field. For example, i entered «Ohey Sapinière [TEC]» for destination, but the results show me the destinations to «Clavier Station Gendarmerie [TEC]». I don't understand why because there's not ary relation between these bus stops.

**Comment by grote** [comment]
did you select the destination from the list that appears when you type? or did you just hit search without selecting from any list of destinations?

**Comment by stemy2** [comment]
I selected the destination from the list.

**Comment by grote** [comment]
hmm.. does it only happen for this special destination or do you see it for others as well?

**Comment by stemy2** [comment]
It happens for some other stops. Another example: «Ottignies Eglise [TEC]» give me results for «Perwez Rue des marronniers [TEC]».

**Comment by grote** [comment]
Must be an upstream issue with https://github.com/schildbach/public-transport-enabler/blob/master/enabler/src/de/schildbach/pte/SncbProvider.java

Does the same happen when you use http://www.belgianrail.be/jp/sncb-nmbs-routeplanner/ directly?

**Comment by stemy2** [comment]
No, i don't have this error on the sncb webapp or mobile app.

**Comment by stemy2** [comment]
The bug is still there, but the erroneous destination are not the same. When i select «OHEY sapinière [TEC] as destination, now it shows the results for «BIESME Wagnée [TEC]».

**Comment by ialokim** [comment]
Does this issue still persist with Transportr 2.1.0? It seems [SNCB support has changed back in 2019](https://github.com/schildbach/public-transport-enabler/issues/256#issuecomment-454748329).

**Comment by stemy2** [comment]
I didn't see it happening again, so i'd say yes.
