### ISSUE TITLE
Problem with German VMS transportation network

### ISSUE THREAD

**Issue by shamis-illya** [grote/Transportr#532]
Please update the methods and classes as the API of VMS (Mittelsachsen) EFA was updated recently and app is not working with this transportation network.

**Comment by grote** [comment]
Is it fixed in PTE already?

**Comment by shamis-illya** [comment]
Yes, I think so, the last version of Öffi (way rolled out today) has fixed that problem

**Comment by grote** [comment]
Fixed in ffaa789b2d9a73d06fe1c66d45a214f15a38ce37
