### ISSUE TITLE
Show trips regardless of optimization

### ISSUE THREAD

**Issue by timokau** [grote/Transportr#539]
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.
* [ ] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**

When comparing transportr and öffi, transportr shows less options. That is because transportr either only shows the shortest trips or the trips with the least switching.

**Describe the solution you'd like**

I would like to see both options so that I can decide when a slightly longer time is worth not switching.

**Describe alternatives you've considered**

Use öffi or always change the optimization in the settings.

**Additional context**
N/A

**Comment by grote** [comment]
What do you mean by "transportr shows less options"? Can you give an example with screenshots from both apps for the exact same search?

**Comment by timokau** [comment]
I  actually cannot find one right now. Maybe it didn't show for some other reason. I'll re-open if I find a suitable example.

How are the "optimize" options implemented though? Do they not hide "non-optimal" routes?

**Comment by grote** [comment]
They *should* be implemented the same way as in Oeffi and hide nothing intentionally.

**Comment by timokau** [comment]
If it doesn't hide, what does it do? The only other thing I could think of is affecting the sorting, but the trips are always ordered by their time.

**Comment by grote** [comment]
It passes the current optimization and walk setting into the query: https://github.com/grote/Transportr/blob/master/app/src/main/java/de/grobox/transportr/trips/search/TripsRepository.kt#L105

If you think there's an issue, please show the screenshots of both applications for exactly the same query, so we can reproduce this.

**Comment by timokau** [comment]
Oh so its actually handled by https://github.com/schildbach/public-transport-enabler, a library both transportr and öffi use. Thats interesting.

As I said I can't find an example anymore. Sorry for the noise.
