### ISSUE TITLE
Belgium : java exception when planning a trip

### ISSUE THREAD

**Issue by gargamelak47** [grote/Transportr#543]
Transportr V 2.02
Android V 8.1
Zone : Belgium

When planning a trip, selecting a place in "from" and "to" fields ends in an UnexpectedRedirectException, as shown here :

![screenshot - 05-11-18 14_33_03](https://user-images.githubusercontent.com/44755327/48001351-988a7980-e108-11e8-869d-d0998e7a450c.png)

**Comment by grote** [comment]
Where does the URL redirect to? https?

**Comment by gargamelak47** [comment]
When trying on the web we are redirected to : https://www.belgiantrain.be

**Comment by grote** [comment]
Does the URL until query.exe still work on the the new domain?

**Comment by grote** [comment]
Looks like they switch to and from HTTPs all the time: https://github.com/schildbach/public-transport-enabler/commit/12a2093912f26320373c915c565ff8426bc38252

This commit probably needs to be reverted upstream.

**Comment by stemy2** [comment]
I had this problem too, but it seems to be fixed.
