### ISSUE TITLE
[UX] Cursor confusingly stays in the target field

### ISSUE THREAD

**Issue by Echolon** [grote/Transportr#544]
Hi,

from the main screen you can search for your target place. If you press the red button below, next the screen should actually ask you FROM where you start your trip - intuetively you start typing but then you recognise that your cursor is still in the target text field. This is unnecessary and once you typed in your target you should directly be able to type in your start.

Thus, I would suggest to change this. Then it's perfect!

Cheers

**Comment by grote** [comment]
duplicate of #472 ?

**Comment by Echolon** [comment]
Yep, sorry!
