### ISSUE TITLE
Add MAV - Hungary

### ISSUE THREAD

**Issue by SecT0uch** [grote/Transportr#545]
MAV is the national train network in Hungary.
I contacted them to obtain their GTFS data, then contacted Navitia for them to add it. 
Their Data team is actually working on it. (CF : https://groups.google.com/forum/#!topic/navitia/22umWYkZq-4)

@schildbach If I can, I will make a PR into public-transport-enabler once available on Navitia.
@grote Can you leave the issue open until then ?

Anyway, I'll let you know about any progress on this topic.

**Comment by grote** [comment]
Hungary was already included in #451 and the new data will show up there without code changes. For PTE upstream, there's already https://github.com/schildbach/public-transport-enabler/pull/195 

I don't see the need for this ticket here. Please close if you agree.

**Comment by SecT0uch** [comment]
MAV is a different provider, they offer train infrastructe all over the country. 
While BKK and MKV are the metro, tram and bus lines of Budapest and Miskolc respectively.

**Comment by grote** [comment]
Navitia won't introduce a new region for it though. They will add it to their existing `hu` region like they did in all other places around the world.

**Comment by SecT0uch** [comment]
They finally added MAV : https://navitia.opendatasoft.com/explore/dataset/hu/table/?sort=type_file
I think the two first lines are MAV tables.
They apparently also adeed KNYKK on the third line (which I'm not familiar with).
@schildbach I'll look into it tomorrow if I'm able/have time to make a PR.

**Comment by grote** [comment]
@SecT0uch The link you posted is to the `hu` region. There is no need for another PR. See https://github.com/grote/Transportr/issues/545#issuecomment-438349702

As MAV was added, this can be closed now.
