### ISSUE TITLE
Make a release please

### ISSUE THREAD

**Issue by gjedeer** [grote/Transportr#546]
Public Transport Enabler has fixed an issue with railroad network in Poland in October, I guess along with many other improvements since the last Transportr release in July.

I've bisected the last build which doesn't fail on jitpack: it's from commit 601572eb. I've built Transportr with that version of PTE but it removes a surprisingly high number of countries ("Unresolved reference: FI" etc), I find it hard to believe that it's not because of my mistake. 

For this reason I'm not sending a pull request. My source, which builds and works for Poland, is available for reference here: https://github.com/grote/Transportr/compare/master...gjedeer:master

**Comment by gjedeer** [comment]
Nope: same error as with all the newer builds:

https://jitpack.io/com/gitlab/opentransitmap/public-transport-enabler/a5e733a3ddb2db9b79b5b4992a980be0286a294d/build.log

**Comment by grote** [comment]
And f2f6eece ?

**Comment by grote** [comment]
Like you see doing a release is quite a but of work. I did the bulk of this now, but there's an issue with the 3-state bottom sheet of the trip detail screen. Help with fixing this is appreciated.

**Comment by gjedeer** [comment]
Works for me - is there a github issue?

**Comment by grote** [comment]
Closed by dd5cc36c4f7c8640e07fa9bbce4e32abc4011f18
