### ISSUE TITLE
Quick way to swap between depature and arrival time

### ISSUE THREAD

**Issue by sphh** [grote/Transportr#548]
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.
* [ ] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**

More often than not, I am using Transportr to find the time, when I have to leave to be at my destination at a certain time. It is frustrating, that I have to click the clock icon to set the time and then the Menu icon > Time is > Arrival.

I also believe, this uses more data, because as soon as I set the time, Transportr checks for connections at the new time.

**Describe the solution you'd like**

IMHO the best way would be, to have a toggle in the screen for entering the time. This toggle would switch between departure and arrival time. The reason why I believe, this is the best place, is as follows: Nearly all of the time when searching for connections to be at the destination at a certain time, the time setting screen has to be called up.

**Describe alternatives you've considered**

A discussion about this can be found at #383

**Comment by grote** [comment]
How about this?

Do you think this is clear for novice users?

![device-2018-12-09-153926](https://user-images.githubusercontent.com/244947/49700649-b98f3000-fbc8-11e8-86f8-2ae061d828d0.png)

**Comment by sphh** [comment]
For me, that looks good.

If all the features of the second toolbar is available from the menu, showing it could be optional.

BTW talking about novice users: Shouldn't the menu (now with the ^v icon) be accessible via a "hamburger" icon?

**Comment by grote** [comment]
> If all the features of the second toolbar is available from the menu, showing it could be optional.

There's no more menu.

> Shouldn't the menu (now with the ^v icon) be accessible via a "hamburger" icon?

hamburger icons are for navigations drawers. In this screen, there's none.
the ^v icon expands the view to show a view search field.

**Comment by sphh** [comment]
Ah, I see. I thought the ^v icon is for a menu ...

**Comment by grote** [comment]
Related to #600

**Comment by nlgranger** [comment]
Hi @grote,
First, thank you for this awesome app! I see this issue is still open, may I suggest to draw inspiration from other map apps for this functionality? They traditionally use an icon with two opposite arrows which is placed between the input fields like so:

![](https://lh3.googleusercontent.com/frIKkgrPv_PA-BOpfkz24DZxEV8wOaXIKdXpnBUXJeJ1YQomwP4oXi4A6g7cCVD1lGc=w1920-h991)

**Comment by Slomo17** [comment]
It took me some time to even find that there is an option to set the time to arrival time. So i also think a switch in the time pickerwould be best.

**Comment by ialokim** [comment]
This is now realized in Transportr 2.1.0, see #664 .
