### ISSUE TITLE
Allow permanent selection of train types

### ISSUE THREAD

**Issue by wonder75** [grote/Transportr#550]
It would be nice to be able to permanently choose the trains I want to use.
I only use regional trains because I got a permanent ticket for them.

Many trips I do allow more expensive long distance trains as well.

As I never use them, I have to deselect them every time I plan a trip.
Would be nice to be able to just set it once in preferences and forget about it.

Thanks for Transportr. Really good app!

**Comment by wonder75** [comment]
No  I don't think so. I use one provider only (Deutsche Bahn) and my train preselection is never saved. Only for the current trip.

**Comment by grote** [comment]
The other ticket is about saving the train/bus/ferry/etc. selection you make. Is this not what you want?

**Comment by wonder75** [comment]
Yes that is what i would like to see. I thought the other ticket was about not saving after changing data providers. Maybe he has the same problem as I have and it has got nothing to do with changing data providers. I guess Transportr never saves the selection?

**Comment by grote** [comment]
Yes changing the region is unrelated. The reporter didn't know that. The ticket is about generally saving the selection and restoring it everytime.
