### ISSUE TITLE
Nothing happens when i enter depurture and destination

### ISSUE THREAD

**Issue by stemy2** [grote/Transportr#551]
Hello,

I can only plan a trip when it's in my history. Because when i enter manually or with a preselected choice my departure and destination, instead of searching for a trip, nothing happens, as if i entered nothing in the text boxes.

**Comment by grote** [comment]
Please use the bug report template when reporting bugs. It asks for more information that is missing from this report.

**Comment by stemy2** [comment]
I'm sorry, but i didn't saw any template anywhere inqthe repository. Where is it ?

**Comment by grote** [comment]
https://github.com/grote/Transportr/issues/new/choose

**Comment by ialokim** [comment]
As you didn't report back, I'm going to close this issue. Feel free to open a new one with more information if needed.
