### ISSUE TITLE
Let specify street number on search

### ISSUE THREAD

**Issue by adocampo** [grote/Transportr#559]
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.
* [ ] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**
On cities where streets are long, is necessary to know in which point of a street we need to go in order to show a useful information. Is not the same to go to the number 12 of a given street, than number 1680 of the same street. Most times the user will have just the name and number of the street, and he/she won't know the adjacent streets or even where is located the destination.

**Describe the solution you'd like**
Let Transportr search specifying the exact number of the street, instead the intersection street, because most times the user won't know that information.

**Describe alternatives you've considered**
none

**Additional context**
Search below should return the needed address: _Avinguda Diagonal 477, Barcelona_
![screenshot_20181217-095006](https://user-images.githubusercontent.com/2266612/50076331-a93b0e80-01e1-11e9-8856-c7521f9c4c8e.png)

**Comment by grote** [comment]
That's a limitation of Navitia based data sources. It is French software and they expect you to give the number in the beginning of the street. Does it work like that?

**Comment by adocampo** [comment]
No, it doesn't seem to start on the number 1, you can see it by yourself on the example above: if you search "Avinguda Diagonal" (from Barcelona) and press search, it will bring you to a point that is really the number 325 of that street, which is really the "middle point" (in meters, not in numbers) of the street
![image](https://user-images.githubusercontent.com/2266612/50086699-22485f00-01fe-11e9-91bf-dca9bd4eb5e7.png)

It does the same with tiny streets
![screenshot_20181217-131810](https://user-images.githubusercontent.com/2266612/50086750-4ad05900-01fe-11e9-90c5-27acdf0f57fd.png)

**Comment by grote** [comment]
Another issue might be that Navitia gets its address data from OpenStreetMap. If there's no address there, it can't find it. Maybe try an address that is also in OpenStreetMap to see if it works.

**Comment by adocampo** [comment]
Mmm, on duckduckgo's map engine, based on OSM, appears just fine, both in large streets
![image](https://user-images.githubusercontent.com/2266612/50087599-e4006f00-0200-11e9-83ef-600af82ccb88.png)
As in the tinier ones.
![image](https://user-images.githubusercontent.com/2266612/50087661-14e0a400-0201-11e9-94e2-3cdbc84b5e2d.png)

Searching directly on OSM it's a bit tricky, I found I need to put the direction without commas, to search engine to found the address.
![image](https://user-images.githubusercontent.com/2266612/50087944-ed3e0b80-0201-11e9-8f0f-a91a889e3bfe.png)
If I put the comma where is supposed to go, after the number (i.e.: Avinguda Diagonal 477, Barcelona), the Image goes to a completely wrong place
![image](https://user-images.githubusercontent.com/2266612/50088181-8e2cc680-0202-11e9-95a7-8fe417ba3b7c.png)
Yet, there are some other results pointing to the right place, the first one, where the browser automatically points, is badly wrong.

The tiny street numbering, but, seems to be ignored by OSM.
![image](https://user-images.githubusercontent.com/2266612/50088433-52dec780-0203-11e9-95b0-2ac3c5a35469.png)

I don't know why it works perfect on DDG. I can ask on their forums, to see if they used something to show the right address in their instant answer minimap, if you found that information somehow useful.

PS: I also tried those searches on mapquest.com, which also uses OSM as source; the large street (Avinguda Diagonal) looks good. The tiny street cannot be even found... so I think everyone implements OSM as they want.

**Comment by grote** [comment]
Please ask Navitia as I think this is strictly unrelated to Transportr itself.

**Comment by adocampo** [comment]
Ok, let me ask there and I'll be back hopefully with some more information.

**Comment by adocampo** [comment]
Well, Navitia community answer me. I feel a bit ashamed for not to try it by myself first...
It uses the english/american street naming convention, so we need to put _first_ the number, and then the address...

![screenshot_20181219-140338](https://user-images.githubusercontent.com/2266612/50222372-59527800-0398-11e9-96c0-dfce3fb113d9.png)

I would suggest accepting both conventions (i.e: let the number be before or after the street name). I suggested upstream, but I don't know if that feature is easily doable in Transportr.

**Comment by grote** [comment]
Isn't this what I had suggested in the first reply to you?

> It is French software and they expect you to give the number in the beginning of the street. Does it work like that?

And then...

> I would suggest accepting both conventions (i.e: let the number be before or after the street name). I suggested upstream, but I don't know if that feature is easily doable in Transportr.

It would be at least difficult. You need special code just for Navitia based providers. Then you need to somehow detect that the number at the end is really a street number and change it, but not change it everywhere. In France in needs to be at the beginning...

Would be better if Navitia would just handle this properly.

**Comment by adocampo** [comment]
I completely misunderstood what you said on that first post... I understood they returned the results on the first number on that street... :flushed:

I can understand the best approach is let them to handle this, so you and everyone who uses their API need to do nothing. 

What I cannot understand is why address is shown properly (see latest screenshot), I guess results are also obtained from them, but I found a bit weird why the user needs to enter the address in an unnatural form (for some) and returns the results as expected.

**Comment by adocampo** [comment]
Navitia devs told this feature is planned in the mid-term when they switch to the new auto completion service https://github.com/CanalTP/mimirsbrunn

It seems it's already done for France, but other countries needs some work for their part. So I guess we can close this issue as it's an upstream issue and the workaround of specifying the number first of all works.

**Comment by grote** [comment]
Except you want to run your own Navitia server for (part of) Spain...

**Comment by adocampo** [comment]
I'm really new to Transportr just as a user, I didn't even know what Navitia was since you told me and I didn't even know I could host my own Navitia instance. 

I don't mind installing my own instance of navitia if that can help somehow. But I guess the problem will be the same: once installed, the auto completion service will be the current one, and as far as I see, mimirsbrunn just have data for France, so I guess is a very hard terrain for a non-developer like myself. If that is a task a sysadmin can do (set up servers, configure this and that, or the like), I would gladly contribute.

I don't know where to start, if there are simple tasks I can contribute, I can do them, but I don't have the experience nor the time to learn complex tools. (I'm just starting with AI and robotics, and those are taking almost my full free time).

**Comment by grote** [comment]
In case you want to dig deeper, https://github.com/CanalTP/navitia-docker-compose is a good starting point. Looks like it doesn't integrate https://github.com/CanalTP/mimirsbrunn yet.

**Comment by adocampo** [comment]
I'm a Linux sysadmin, and I'm very comfortable with docker, so that is not the problem. Setting up the server won't be a problem. The problem is I don't know what I'm supposed to do with that server, and how can I connect Transportr to it, besides mimirsbrunn isn't implemented nor have been adapted to my region.

I'll try to find some time to play with it, to get an idea of what I'm installing and how can I do something with that.

**Comment by grote** [comment]
I'd suggest to start with setting up a regular Navitia server with docker compose. Hooking it up to Transportr is a one line change, but you can also use the [navitia-playground](http://canaltp.github.io/navitia-playground/) with your own API URL to test things.

You can feed it the data from here: https://navitia.opendatasoft.com/explore/dataset/es/table/?sort=type_file (maybe only start with one as you need to merge them otherwise, or use the Global Transport in Spain which might be pre-merged)

When this works, you can look into mimirsbrunn which essentially seems to be an elastic search webservice which you need to feed data (documented) and then hook it up in its own docker container. The navitia people might be able to assist with that last part.

Running your own Navitia server can make sense, because the company behind Navitia services many countries world-wide and as you see doesn't always have time and budget to care of all countries equally well. I run my own Navitia server for where I live for example.

**Comment by adocampo** [comment]
Ok, I'll find time to play with all this ;) I'll let you know if I succeed :)

**Comment by alekksander** [comment]
I guess it's still unavailable to implement? This is what keeps me from depending on transportr. Perhaps GPS could be some sort of walkaround, to precise starting point?
