### ISSUE TITLE
Adding AVV Aachen network

### ISSUE THREAD

**Issue by justin-time** [grote/Transportr#563]
Hi, 
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [x] I can help myself to get this feature implemented.
* [x] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

Since a few week the [AVV Aachen](https://avv.de) network is available in the [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/commit/eda7d37b838f9e08a85ff3b31bfcd131bbd4050e/) based on Hafas client interface. I have implemented it for Transportr locally but unfortunately a API key is needed. 

Can I open a pull request without having a API key?

Kind regards,
justin-time

**Comment by grote** [comment]
Hey @justin-time, thanks for your willingness to create a PR! That's always appreciated. However, I also don't know how to get an API key. Until we have one, the PR will be useless.

**Comment by justin-time** [comment]
Hey @grote, I found a weblink: [Angebot für Webentwickler](https://avv.de/de/fahrplaene/angebote-fuer-webentwickler). 
It looks like you could request a API key by writing a email to api@avv.de.

**Comment by grote** [comment]
Thanks for the hint. However, I don't live in AVV area and don't have time for this. If you want it, please go ahead.

**Comment by getwisp** [comment]
For anyone interested: As of now, there is no need for an API key to use the AVV API. 
Here are two API calls to show what is available (roughly), as time permits I'm willing to do further reasearch. This is the API used by the official AVV app (on iOS, it's likely the same for the Android app)
https://avv.fluidtime.com/monitor?diva=AVV
https://avv.fluidtime.com/location?search=talbot&type=stop
