### ISSUE TITLE
Please add support for Saint Petersburg and Moscow, Russia

### ISSUE THREAD

**Issue by testaccountfortransportr** [grote/Transportr#564]
I don't know how to contribute, branch or git, sorry. I'm not programmer. But there in Russia are many people who use public transport and have not a car. Please add Saint Petersburg and Moscow. And maybe other russian cities.
Thanks and sorry for my bad English.

**Comment by ialokim** [comment]
Please refer to https://transportr.app/contribute/#add_region to see the steps required for adding a new region to Transportr. If data is already available on Navitia, next step would be to add it to the upstream library [public-transport-enabler](/schildbach/public-transport-enabler).

**Comment by ialokim** [comment]
Feel free to drop a new comment when St. Petersburg is available in PTE and we can continue to work on the integration.
