### ISSUE TITLE
Unable to enter stations properly

### ISSUE THREAD

**Issue by madduck** [grote/Transportr#567]
Using the latest version from f-droid, I can add my starting point, but when I enter the destination, the starting point gets changed to the same as the destination, and a connection from the past loaded. If I reverse direction, then it becomes obvious that the two stations are the same.

Here is a screencast of the interaction: https://scratch.madduck.net/transportr-issue.mp4

**Comment by grote** [comment]
@ajbruin did you see this already? Looks similar to the issue you had fixed already.

**Comment by ajbruin** [comment]
It seems to be the same, yes. Is this version 2.0.4?

**Comment by ialokim** [comment]
As you didn't report back in quite some time, I'm going to close this issue.
