### ISSUE TITLE
PTE Exceptions don't show cause, wrong link?

### ISSUE THREAD

**Issue by Moult** [grote/Transportr#569]
https://github.com/schildbach/public-transport-enabler/issues/252 details the full issue - at first I thought it was an issue with public-transport-enabler but as the URL does actually output valid XML I suspect it may be on Transportr's end.

**Comment by schildbach** [comment]
And while you're at it, can you please remove the suggestion to attach a screenshot of the exception? It creates unnecessary noise in the repo – if anything we need the exception in textual form.

**Comment by Moult** [comment]
Is it possible for any dev to replicate this issue? I assume then they can get a stack trace :)

**Comment by grote** [comment]
This issue is about fixing the way PTE exceptions are shown. Your issue is upstream at PTE. Please no cross-posting.

**Comment by grote** [comment]
> can you please remove the suggestion to attach a screenshot of the exception? It creates unnecessary noise in the repo

Screenshots have been helpful for seeing the search query of the user and the provider they use, so I could reproduce their issue or not. But maybe full stack traces already resolve the issue?
