### ISSUE TITLE
Add Japan public transportation network to transportr

### ISSUE THREAD

**Issue by aliceinwire** [grote/Transportr#571]
Rail transport in Japan is a major means of passenger transport. [1]
Unfortunatly in transportr Japan public transport are still not supported and I think this would be a good opportunity for spread a good open source transportation software in Japan. 
Please add Japan public transportation network to transportr. 

[1] https://en.m.wikipedia.org/wiki/Rail_transport_in_Japan

**Comment by grote** [comment]
I don't live in Japan. Somebody who does need to add support. An issue itself also won't help without somebody willing to implement this.

**Comment by aliceinwire** [comment]
Yes, that's why I opened an issue hoping that someone would implement it.

@JostBrand  what API documentation are you talking about ?

**Comment by aliceinwire** [comment]
You can find easily some feed on transit land https://transit.land/feed-registry/

**Comment by ialokim** [comment]
@aliceinwire Please also refer to the official [Transportr website](https://transportr.app/contribute/), especially the part *Adding support for more regions*.

**Comment by ialokim** [comment]
As nobody is working on this right now, I'm going to close this issue. Feel free to drop a new comment if you want to contribute here.

**Comment by nexryai** [comment]
Hello. 
I live in Japan. I would like to make this great app available in my country. Fortunately, some public transportation agencies in Japan publish GTFS data. Is it possible to use this in transportr?
