### ISSUE TITLE
Android Studio Error

### ISSUE THREAD

**Issue by LouisForaux** [grote/Transportr#580]
**Describe the bug**
Get "No dependency for integrity assertion 'caches:transforms-2:files-2.1:jetified-antlr4-4.5.3.jar:2ff3269eeb01c1e00afeb3d645402c8d626c9eedab02ef22263fb11980e50085'" with gradle build 

**To Reproduce**
1. Fresh installation of gradle (5), lastest Android Studio
2. Clone Git project
3. Click on Make after import of project

**Expected behavior**
Simply import project for edit 

**Screenshots**
No screenshots availible

**Versions (please complete the following information):**
 - **Transportr Version:** Git clone (28/01/2019)
 - **Device:** Huwaei Mate 20 Lite (No error on Debug build by terminal)
 - **Android Version:** 8.1

**Comment by israteneda** [comment]
Do you tried to run
```
update-dependency-pinning.sh
```
and
```
gradle assembleRelease
```
and not update the Gradle version.

**Comment by ialokim** [comment]
As there were no new comments in more than a year, I'm closing this issue. See also #693 as we are considering moving away from gradle witness anyway.
