### ISSUE TITLE
Paris : Route Frequently incorrect or incomplete

### ISSUE THREAD

**Issue by jmaris** [grote/Transportr#581]
**Describe the bug**
When attempting to Journey across Paris, I frequently find the routes proposed to be incorrect or incomplete, frequently dropping changes and recommending walking despite it not being faster to do so.

**To Reproduce**
1. Enter "Dugommier" as a From location
2. Enter "Réaumur  /Sébastopol" as a destination
3. Search
4. Note that none of them offer the logical and direct link that google maps offers ( line 6, line 14, line 4)

Additional : I have also changed the settings to avoid walking, however it still only offers walking options. Oddly the official RATP app proposes the correct journey, i thought the data was from the same source.

**Expected behavior**
From Dugommier to Réaumur Sébastopol, one takes the 6 to Bercy, followed by the 14 to Châtelet and the 4 to Réaumur - Sébastopol.  (See Google Maps if necessary)

**Versions (please complete the following information):**
 - **Transportr Version:** 2.0.5
 - **Device:** Moto E
 - **Android Version:** 7.1.2

**Comment by grote** [comment]
This sounds like an upstream issue of Navitia. Please use their Playground to replicate the problem and then tell them with the playground API URL. http://canaltp.github.io/navitia-playground/

**Comment by ialokim** [comment]
As this appears to be an upstream / data source issue and we won't be able to do anything about it here, I'm going to close this issue.
