### ISSUE TITLE
Transport NSW doesn't work

### ISSUE THREAD

**Issue by Moult** [grote/Transportr#582]
The issue is detailed here:

https://github.com/schildbach/public-transport-enabler/issues/252

There is also another bug report about actually reporting a useful stack trace during the exception to help debugging.

**Comment by Moult** [comment]
As mentioned in that bug report I don't think it is an upstream bug.

https://github.com/schildbach/public-transport-enabler/issues/252#issuecomment-451359130

**Comment by Moult** [comment]
I don't understand why this was closed.

1) @grote you asked me to create this bug on the transportr side
2) the evidence of the api URL working outside transportr suggests it could either be a PTE or a transportr bug. Unsure which.

**Comment by grote** [comment]
We have a ticket for the PTE issue report bug already. I think this one is a bug in NswProvider. You can get the full stack trace from logcat, so we can confirm. If not, we can reopen this ticket.
