### ISSUE TITLE
Add public transport for Gothenburg, Sweden

### ISSUE THREAD

**Issue by Limero** [grote/Transportr#586]
Being able to see information about public transport in Gothenburg would be fantastic.
The provider of all transport there is called Västtrafik and they have data available for developers that could be implemented.
https://github.com/vasttrafik/open-data-gtfs
https://github.com/vasttrafik/open-data

**Comment by grote** [comment]
Note that I don't live in Sweden and don't have time to add support for it. Somebody who lives there and maintains the data long-term needs to implement this. See also [information on the homagepage](https://transportr.app/contribute/#translating-into-your-language).

**Comment by Limero** [comment]
An update to this. There are GTFS files available at Samtrafiken Trafiklab where most of Sweden's public transport information is collected and can be used freely. It would  be better to use this data. That way, Gothenburg, Stockholm, etc. all works at once.

https://data.samtrafiken.se/trafiklab/gtfs-sverige-2/
https://www.trafiklab.se/api/gtfs-sverige-2/dokumentation

**Comment by ialokim** [comment]
As nobody is working on this, I'm going to close this issue for now. Feel free to drop a new comment if you want to contribute here.

Please also refer to the official [Transportr website](https://transportr.app/contribute/), especially the part about [_Adding support for more regions_](https://transportr.app/contribute/#add_region).
