### ISSUE TITLE
Stops without times not indented

### ISSUE THREAD

**Issue by thgoebel** [grote/Transportr#587]
**Describe the bug**
The Swiss SBB :switzerland: includes points of interests (like the Gotthard Base Tunnel) as "stops" in their train connections.
Since howerver they are missing arrival/departure times, Transportr renders them shifted to the left and they become malaligned. It's best explained by the screenshots below.

**To Reproduce**
1. Choose Siwtzerland -> SBB as a network provider
2. Choose an affected train connection, e.g: Zurich HB -> Milano Centrale
3. Select any connection
4. Expand all stops

**Expected behavior**
All names should be indented onto the same line.

**Screenshots**

Zurich - Milano | Zurich - Brig | Zurich - Chur
---|---|---
![img_20190216_152001](https://user-images.githubusercontent.com/33295590/52901647-7d9acb80-3206-11e9-86b1-7cf143d73384.jpg) | ![img_20190216_151921](https://user-images.githubusercontent.com/33295590/52901654-88556080-3206-11e9-8616-fb732b72ba4e.jpg) | ![img_20190216_151941](https://user-images.githubusercontent.com/33295590/52901655-88edf700-3206-11e9-9779-70070aa8f0c8.jpg)

**Versions:**
 - **Transportr Version:** [2.0.5]
 - **Device:** [irrelevant]
 - **Android Version:** [7.1.2]

**Comment by grote** [comment]
Thanks for the good report and the screenshots!
