### ISSUE TITLE
Give us an option to launch searches only when requested

### ISSUE THREAD

**Issue by Zeralda** [grote/Transportr#595]
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [X] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [X] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.
* [ ] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**
It's very annoying that TransportR starts searches (and uses a data connection) when I haven't finished entering my question.

**Describe the solution you'd like**
A search button that I can use to start a search once I have entered departure, arrival, day, time, departure or arrival.

**Describe alternatives you've considered**
Going back to a proprietary app if I find one that offers this option

**Comment by ialokim** [comment]
@grote thoughts on this one? I guess this is a fundamental design decision that won't be changed?

**Comment by grote** [comment]
I think there was a similar ticket (maybe closed) somewhere where I explained the reasoning behind the current design. In a nutshell, the data sent/received is super small compared to opening a web page. In my opinion the better UX of immediate searches outweights a few saved bytes.
