### ISSUE TITLE
Cannot find the village "Puchenau" in the Austrian region "OÖVV Linz AG Linien"

### ISSUE THREAD

**Issue by jondo** [grote/Transportr#597]
**Describe the bug**

**To Reproduce**
1. Open Transportr
2. Activate the Austrian region "Linz AG Linien" (with OÖVV logo)
3. Use the "search here" field to search for "puchenau" (which is https://www.openstreetmap.org/relation/86308)
4. Notice that the only search result is "Gramastetten, Oberpuchenauerstraße, Gramastetten".

**Expected behavior**
The village of Puchenau (or some of the Puchenau traffic stops) should appear in the search results.

**Versions:**
 - **Transportr Version:** 2.0.5 from F-Droid
 - **Device:** Samsung S5
 - **Android Version:** 9.0 (Lineage OS without Google services)

**Comment by ialokim** [comment]
This is most probably an issue with the [data source used by this provider](https://github.com/schildbach/public-transport-enabler/blob/master/src/de/schildbach/pte/LinzProvider.java) in PTE. Same happens for me on the [official website](https://www.linzag.at/portal/de/home#) when inserting "Puchenau". We won't be able to do anything about this.

**Comment by jondo** [comment]
Thank you for the feedback! I could now make this work for me by switching to Austria's ÖBB network.
