### ISSUE TITLE
Main screen: Show map

### ISSUE THREAD

**Issue by Echolon** [grote/Transportr#599]
Hello,

For the moment it is possible to scroll and zoom through the map in the main screen.

Somtimes you just want to search directly on the map.

It would be great to be able to expand the window to the whole screen without the need to search for a place.

Cheers

**Comment by grote** [comment]
Sorry, can you explain a bit better what you think would be an improvement for *all* users of Transportr? I didn't really understand the proposal. The main screen is the map and it is full screen and you can search there for places.

**Comment by Echolon** [comment]
Hi,

sorry was in a train. I would like to be able to expand the map as shown in the screenshot to the whole screen, so that I can see the complete map. (and back see the connections again)

<img src="https://user-images.githubusercontent.com/29168011/54884164-f62c2200-4e6d-11e9-80a9-e6e2f7dd20c1.png" width="250">

**Comment by grote** [comment]
Sorry, I still don't follow. You can expand the map as shown on the screenshot, right? Then you see the complete map, right? To get the connections back you press the red round button, right?

**Comment by Echolon** [comment]
Hmm, how can I do what you describe? Because thats what I expect the app to do.

Right now, I cannot.

Okay, I try to explain step by step.

1. Situation as shown in the screen
2. For example, pull down the connection menu below
3. See the whole map and be able to scroll through the map
4. Pull back or close to see 1.

Does that clarify? :/

**Comment by grote** [comment]
You can't get back to 1, but you can click the red round directions button to see the same information.

**Comment by Echolon** [comment]
Yes, but this needs to enter a location or?

Transportr shows the map from the previous search, sometimes its helpful to check out the latest map view.

**Comment by grote** [comment]
At step 3, you want to see the information of saved and recent trips from step 1 again, right? So pressing the directions button should give you exactly this information and you can interact with it exactly like in step 1, right?

> Transportr shows the map from the previous search, sometimes its helpful to check out the latest map view.

What is the map from the previous search? What is the latest map view?

**Comment by Echolon** [comment]
Sorry, I'm not sure if we are on the same page. However, it is not very important and just a luxury feature. So, no problem. I might come back another day.
