### ISSUE TITLE
Station Search broken: NPE Point.getLatAs1E6()

### ISSUE THREAD

**Issue by ArmitageShanks** [grote/Transportr#601]
**Describe the bug**
When I use the search function to find a "from" or "to" location it works extremely seldom (unless the station is stored in history,and what's stored in history is a mystery on a new device since so few stations can be found). 
This is not an issue I had before. 

I use TLEM and when you put in a MAJOR station in London like Paddington or Victoria nothing shows up (unless the station is in your history) 

**To Reproduce**
1. Go to Transportr 
2. Click on search box 
3. Type in "Paddington" 
4. See nothing 

**Expected behavior**
To see a bunch of options showing Paddington in their names. 

**Versions (please complete the following information):**
 - **Transportr Version 2.0.5
 - ** Nexus 6P and Poco phone F1
 - **Android Version 8.1 and 9.

Besides that I want to thank for an amazing app. I was amazed to find a FOSS app that had such an amazing UI and function. This is an app I rely on so it's MOST appreciated.

**Comment by grote** [comment]
Transportr hasn't changed. It uses the API provided by TLEM. So this is what might have changed. Looks like https://github.com/schildbach/public-transport-enabler/ wasn't adapted either. This is what would need to be adapted for a changed API, not Transportr itself.

**Comment by ArmitageShanks** [comment]
Thanks. I'm a bit unsure how to proceed though. Should I open the same issue on public-transport-enabler?

And to clarify, this issue might not have been recent. I just realised that this issue could have been around for a while and I haven't noticed until I switched devices. Because all the stations I normally use were already saved on my previous device, so I might have not realised that the search wasn't working.

**Comment by uspoma** [comment]
Since a while I experience the same behavior. Search results are unreliable. Lately I almost never get results for different cities. Thought that it might be a network problem but then I tried Oeffi and there it works. So the problem is somewhere with Transportr. Please look into that.

**Comment by grote** [comment]
Also with TLEM?

**Comment by grote** [comment]
Oeffi might have downloaded all stations and cached locally, so it wouldn't be affected by API search problems if it did that.

**Comment by uspoma** [comment]
No, MVV for example.

**Comment by ArmitageShanks** [comment]
It's not an issue of caching since I solely used Transportr before and switched to Oeffi after Transportr stopped working and I never had the issue again.
In the issue I started on Public Transport Enabler the dev says there is no issue at that end.

**Comment by grote** [comment]
@uspoma the search comes from MVVs API. It is possible that their server is overloaded sometimes or has other issues. Then things won't work. Are you sure you are seeing the exactly same issue? Directions search still works when using saved/favorite stations, but *some* stations can't be found when typing their name?

@ArmitageShanks if you know this better, why don't you go ahead and fix it? Oeffi might be loading a pre-loaded/cached database of *all* stations and then use this for offline searches. So if the API has issues, the station search would not be affected by it.

**Comment by grote** [comment]
Looks like it is a completely different problem:

```ruby
W/Filter: An exception occured during performFiltering()!
    java.lang.NullPointerException: Attempt to invoke virtual method 'int de.schildbach.pte.dto.Point.getLatAs1E6()' on a null object reference
        at de.schildbach.pte.dto.Location.getLatAs1E6(Location.java:108)
        at de.grobox.transportr.locations.WrapLocation.<init>(WrapLocation.java:70)
        at de.grobox.transportr.locations.SuggestLocationsFilter.performFiltering(SuggestLocationsFilter.java:52)
        at de.grobox.transportr.locations.LocationAdapter$1.performFiltering(LocationAdapter.java:169)
        at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by ArmitageShanks** [comment]
Easy, mate. Not sure why you're starting to sound upset, but I'm just trying to help and nowhere did I suggest I know better. 

I'm grateful for all the work that has been done on this app and I'm trying to help out myself in the only way I can by reporting bugs and trying to pinpoint the issue. 
If I could fix it myself I'd obviously wouldn't have started this issue. 

I'm not sure what your last post implies, but nice to see that you seem to have found the root of the issue.

**Comment by ArmitageShanks** [comment]
Edit, phone closed issue.
