### ISSUE TITLE
Navitia: no_origin_nor_destination

### ISSUE THREAD

**Issue by y0rune** [grote/Transportr#602]
**Versions (please complete the following information):**
 - **Transportr Version:** 2.0.5
 - **Device:** Mi8
- **Android Version:** 9
![Screenshot_2019-04-16-10-24-51-445_de grobox liberario](https://user-images.githubusercontent.com/10187235/56193901-0af57300-6032-11e9-8e5c-cc5889e6dd07.png)

**Comment by grote** [comment]
Like the screenshot says in the bottom, this needs to be fixed in public-transport-enabler, specifically its abstract Navitia provider. It has an issue with points of interest, I think.

**Comment by grote** [comment]
Does it work if you enter other stations instead?

**Comment by ialokim** [comment]
This is most probably a duplicate of #424. You could check if it works with stations instead of POIs / addresses.
