### ISSUE TITLE
Add the Poznan Trams 

### ISSUE THREAD

**Issue by y0rune** [grote/Transportr#603]
Could you add the Poznan in the app ;) I can updating data etc. because I live here. 
Also data  https://www.ztm.poznan.pl/pl/dla-deweloperow/gtfsFiles or RealLive https://www.peka.poznan.pl/vm/

Thank You ;)

**Comment by grote** [comment]
Like [explained on the homepage](http://transportr.app/contribute/), this needs to get added to Navitia first.

**Comment by ialokim** [comment]
As nobody is working on this, I'm going to close this issue for now. Feel free to drop a new comment if you want to contribute here.

Please also refer to the official [Transportr website](https://transportr.app/contribute/), especially the part about [_Adding support for more regions_](https://transportr.app/contribute/#add_region).
