### ISSUE TITLE
Privacy Statement

### ISSUE THREAD

**Issue by aeph6Ee0** [grote/Transportr#604]
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.

**Is your feature request related to a problem? Please describe.**
I am missing a privacy statement in the Transportr app.
Even though, Transportr claims not to include third party tracking code, there are still data traces created by using third party services which allow conclusions to be drawn about the users.
To be specific, the online map, geocoding, and route search providers (GTFS) receive detailed location information when requested.
These service providers could potentially identify users by their IP address and create motion profiles.
From the app information screen, it is not clear which exact online services are used by Transportr.

As an enlightened user, I don't want to use an app that does magic things, but I want to know how it works, and what information flows to which service.

**Describe the solution you'd like**
One good example of an app which includes a privacy statement is [StreetComplete](https://github.com/westnordost/StreetComplete).
It is easy to understand and covers all online activity of the app.
A screenshot of the privacy statement screen of StreetComplete is attached below.

**Additional context**
![StreetComplete_Privacy_Statement](https://user-images.githubusercontent.com/14131260/56285293-2a1a0080-6117-11e9-8ff8-3aa81111cb63.png)

**Comment by grote** [comment]
Thanks for the suggestion. As  lack time and you seem to have a good understanding of where Transportr leaks data, please feel free to draft up a statement, as short as possible. Thanks!

**Comment by aeph6Ee0** [comment]
I'll see what I can do in the next couple of days.

**Comment by ialokim** [comment]
@aeph6Ee0 Are you still interested in proposing a draft?

**Comment by grote** [comment]
@aeph6Ee0 any news? This got more urgent now as Transportr has been removed from Google play for the lack of such statement.

**Comment by Altonss** [comment]
I am willing to write a draft based on the Streetcomplete template which seems already quite complete :)
So the key informations are:
- location which is only used to retrieve easily the start/arrival of a route when planning and download the correct map tile?
- map tiles, here the mapbox privacy policy would apply I guess?
- route planning (start, arrival and date/time) which is directly dependent on the third party api endpoints privacy policy

**Comment by ialokim** [comment]
> * location which is only used to retrieve easily the start/arrival of a route when planning and download the correct map tile?

yes, location is kind of leaked to map provider when downloading tiles though mapbox might not be sure if the downloaded map tiles are for the current position or the user just scrolling around on the map.

> * map tiles, here the mapbox privacy policy would apply I guess?

Yes, we are still using tile data from mapbox, but were planning to change it in some future: #668

> * route planning (start, arrival and date/time) which is directly dependent on the third party api endpoints privacy policy

Yes, exactly, it should be mostly the same as using the official apps to search for trips, stops or departures (except additional third-party trackers we are obviously not including).

**Comment by Altonss** [comment]
I've written a short pricacy statement, should I make a PR including it as a markdown file?

**Comment by grote** [comment]
done in https://github.com/grote/Transportr/pull/825
