### ISSUE TITLE
Font size of delay time (green or red)

### ISSUE THREAD

**Issue by markuskramerIgitt** [grote/Transportr#607]
**Acknowledgments**
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [x] Maybe I can help myself.

**Is your feature request related to a problem? Please describe.**

I have difficulties to read the smaller font size of the delay time (in green or red).

**Describe the solution you'd like**

Common font size for departure, arrival and delay.

**Alternatives considered in vain**

No font size settings (found).

**Screenshot**

![ttt](https://user-images.githubusercontent.com/8489107/57480502-391c4a80-72a0-11e9-9239-a915d7a97ef1.jpg)

**Comment by ialokim** [comment]
@grote How do you feel about this?

**Comment by grote** [comment]
I guess they could be made bigger if people have trouble reading them.
