### ISSUE TITLE
[UI] Show departure platform in search results list

### ISSUE THREAD

**Issue by thgoebel** [grote/Transportr#608]
**Acknowledgments**
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.

**Is your feature request related to a problem? Please describe.**
Having searched for a trip, I always need to go to the trip details to find the departure platform.

However, the time and the platform are the two single data points I need to successfully board the train on time, so both should be shown directly. This helps in quickly comparing trains and deciding which to take.

**Describe the solution you'd like**
Display the departure platform in the results list.

**Describe alternatives you've considered**
Maybe display arrival platform as well to be consistent.

**Additional context**
<img src="https://user-images.githubusercontent.com/33295590/58553062-2dbf9d80-8214-11e9-89f3-4dd086261f73.jpg" width=250px />

**Problem to keep in mind**
Some departures do not have a platform (e.g. the TGV from Paris to Zurich). So do most tram and bus connections.
Should it be left empty, or what short but meaningful placeholder should be shown?
(I think the former makes the most sense.)

**Comment by grote** [comment]
Sorry, I disagree with that feature request. Try putting the platform on a tiny screen with a long station name. There's no space. I also don't think most people need to know the platform for deciding for a connection.

**Comment by thgoebel** [comment]
The screen space usage is a valid concern. For that, the SBB uses abbreviations: *Pl. 7* in English or *Gl. 7* in German. See their screenshots [here](https://play.google.com/store/apps/details?id=ch.sbb.mobile.android.b2c).
Then it would not be much more space than the journey time.

If you think it won't be useful for the majority, then that's your shout. For me in the more metropolitan area of Zurich, I would find this very useful for choosing S-Bahn connections. But I cannot extrapolate to other cities, I assume it depends very much on the kind of transport network you have.

**Comment by ialokim** [comment]
This use-case might also be covered by #416.

**Comment by Emilv2** [comment]
Your decision is final of course, but I really like this feature request. It's very useful if you have several connections to choose from, and abbreviated it takes up barely no space.
