### ISSUE TITLE
Last release is not in Google Play Store

### ISSUE THREAD

**Issue by jony0008** [grote/Transportr#611]
The version in Google Play Store is still 2.0.5. Please submit the latest release to the Google Play Store.

**Comment by ouzowtf** [comment]
Since the latest release at GitHub is 2.0.5 too, this seems to be the latest version :stuck_out_tongue_winking_eye:
https://github.com/grote/Transportr/releases

**Comment by grote** [comment]
@jony0008 thanks for reminding me. I actually forgot to move this release from beta to production in Google Play and make the release entry here on GitHub...
