### ISSUE TITLE
Some train connections are ignored

### ISSUE THREAD

**Issue by stemy2** [grote/Transportr#612]
Hello

I tried to plan a trip between 2 train stations, but only bus connections are showed between those stations. If i uncheck «bus», i have a «no connection error», even if those connections actually exist. The stations mentioned above are Ottignies and Louvain-la-neuve.

**Comment by grote** [comment]
The data comes from Navitia, check if their Playground returns the same result: https://canaltp.github.io/navitia-playground/play.html Maybe their data is incomplete?

**Comment by stemy2** [comment]
> The data comes from Navitia, check if their Playground returns the same result: https://canaltp.github.io/navitia-playground/play.html Maybe their data is incomplete?

I don't understand how it works, could you explain to me ?

**Comment by stemy2** [comment]
Yes, and the problem is still happening.

**Comment by ialokim** [comment]
Okay, as SNCB indeed doesn't make use of data from Navitia, but instead uses the [official back-end at http://www.belgianrail.be/bin/query.exe/en](https://github.com/schildbach/public-transport-enabler/blob/2d7d882f70cc70aee06e7ac2ece932665a9bf755/src/de/schildbach/pte/SncbProvider.java#L33), it would be interesting to know if this error also occurs on their official website http://www.belgianrail.be/bin/query.exe/en.

**Comment by ialokim** [comment]
There seems to be indeed a problem:
![grafik](https://user-images.githubusercontent.com/18088991/92447950-3b562800-f1b8-11ea-9962-f68f5302979f.png)

Nevertheless, this seems to be an upstream issue in the way how PTE queries data from this provider. You might consider opening an issue over there: https://github.com/schildbach/public-transport-enabler/issues/new
