### ISSUE TITLE
Link to public-transport-enabler repo is wrong in error message

### ISSUE THREAD

**Issue by regagain** [grote/Transportr#614]
**Describe the bug**
I got an error message which contains a link to the public-transport-enabler repo. Unfortunately, the link is wrong: https://github.com/schildbach/public-transport-enabler/issuespublic-transport-enabler instead of https://github.com/schildbach/public-transport-enabler

**To Reproduce**
1. Using the Swedish provider, search for some direction.

**Expected behavior**
The link in the error message should be https://github.com/schildbach/public-transport-enabler

**Screenshots**
* Error message: ![Screenshot_20190619-090647_Transportr](https://user-images.githubusercontent.com/1060371/59760430-9b4e6f00-9292-11e9-8685-b88840970891.png)
* When pressing on the link: ![Screenshot_20190619-125414_Fennec_F-Droid](https://user-images.githubusercontent.com/1060371/59760432-9b4e6f00-9292-11e9-89a0-c97e4cfb757c.png)

**Versions (please complete the following information):**
 - **Transportr Version:** 2.0.6
 - **Device:** PixelXL
 - **Android Version:** 9

**Comment by regagain** [comment]
On a side note, maybe the content of this error message should be updated as well, the maintainer of public-transport-enabler does [not seem to like screenshots](https://github.com/schildbach/public-transport-enabler/issues/266#issuecomment-503550001).

**Comment by Josue-T** [comment]
I've the same issue...

**Comment by brenard** [comment]
Hello, same issue today, and the [screenshots are still not liked](https://github.com/schildbach/public-transport-enabler/issues/272#issuecomment-509558969).

**Comment by ialokim** [comment]
This has been fixed with #625.
