### ISSUE TITLE
Can I use Transport App with Open Trip Planner Server?

### ISSUE THREAD

**Issue by israteneda** [grote/Transportr#616]
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [x] I can help myself to get this feature implemented or know someone who wants to do it.
* [x] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**
Transport App is amazing but I don't can achieve all requirements for adding a new region because I am not sufficient experience with transportation field and I am testing gtfs. I don't have a complete gtfs yet.

**Describe the solution you'd like**
I'll like to know if I can use Transport directly with [Open Trip Planner](https://www.opentripplanner.org/) for test gtfs files.

**Describe alternatives you've considered**
I try to use [OTP for Android](https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/wiki) but is a little outdated. I think that I can't send my gtfs to Nativia because I am developing the gtfs.

**Comment by grote** [comment]
OTP support needs to get added to public transport enabler. Follow this PR: https://github.com/schildbach/public-transport-enabler/pull/211
