### ISSUE TITLE
Support for Lithuania

### ISSUE THREAD

**Issue by mvglasow** [grote/Transportr#621]
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.
* [ ] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**
No, just a new data set

**Describe the solution you'd like**
GTFS data for Lithuania should be available at the following link:

http://www.visimarsrutai.lt/gtfs/gtfs_all.zip

More information can be found at http://eismoinfo.lt/#!/ after clicking “Atviri duomenys” (Open Data). (Should also be available in English, click the menu button on the top right to switch language.)

As per the information on the page, all data linked there is available under an Open Data license. I didn’t find any specifics, only a link to a general explanation of Open Data, which defines it as data that comes with no restrictions on usage beyond attribution.

It is not on Navitia yet; I have just posted this information on their forum.

**Describe alternatives you've considered**
Does not apply.

**Additional context**
None.

**Comment by ialokim** [comment]
As it seems that nobody is working on this, I'm going to close this issue for now. Feel free to drop a new comment if you want to contribute here.

Please also refer to the official [Transportr website](https://transportr.app/contribute/), especially the part about [_Adding support for more regions_](https://transportr.app/contribute/#add_region) and report back if Lithuania is included in Navitia and PTE.
