### ISSUE TITLE
Support for Estonia

### ISSUE THREAD

**Issue by mvglasow** [grote/Transportr#622]
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.
* [ ] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**
No, just a new data set

**Describe the solution you'd like**
Navitia has GTFS data for public transport in Estonia, which I am not seeing on the current version of Transportr. See: https://navitia.opendatasoft.com/explore/dataset/ee/information/

**Describe alternatives you've considered**
Does not apply.

**Additional context**
None.

**Comment by ialokim** [comment]
As written in the last item you didn't check from the list, support for a new region has to be added first to [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/). You could open an issue there first and come back when support has been successfully added to public-transport-enabler.

Also consider reading the new region integration process as [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Comment by mvglasow** [comment]
I have opened an issue at https://github.com/schildbach/public-transport-enabler/issues/274.

**Comment by ialokim** [comment]
As nobody is working on this, I'm going to close this issue for now. Feel free to drop a new comment if you want to contribute here.

Please also refer to the official [Transportr website](https://transportr.app/contribute/), especially the part about [_Adding support for more regions_](https://transportr.app/contribute/#add_region) and report back if Estonia is included in PTE.
