### ISSUE TITLE
Locations in Valencia, Spain can no longer be found

### ISSUE THREAD

**Issue by guushoekman** [grote/Transportr#626]
Up until recently Transportr worked well in Valencia, Spain. However, recently (maybe since a month or two) I've been getting "could not find the 'from' location. Please try another one."

I went through the most recent commits, but haven't been able to find anything related to it.

**Comment by ialokim** [comment]
Please add more information: which `from` location did you try? Sometimes there happen to be changes in the server database which change the internal id. This could lead to Transportr not finding some cached or favorite stations anymore. You could try to search for the specific station again and see if it works then.

Also note that Transportr uses [PTE](/schildbach/public-transport-enabler) internally for retrieving information, so please consider opening an issue there if the problem persists.

**Comment by guushoekman** [comment]
Ah yes I searched again rather than using a saved trip, now it works again.

I thought Valencia was removed because it's not listed on the homepage, so I thought support had been dropped.

Thank you so much for the quick reply.
