### ISSUE TITLE
[UI] Improve visibility of the white arrow in top left corner

### ISSUE THREAD

**Issue by Echolon** [grote/Transportr#629]
- [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
- [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.

Hi,

often, especially when the map it in the background, the top left arrow which brings you back to the previous menu is hard to see. Therefore improving the visibility (different color or shadow) would be good.

I can drop a screenshot later.

**Comment by Echolon** [comment]
<img src="https://user-images.githubusercontent.com/29168011/64491236-2b82cb80-d266-11e9-8ba4-2fc65e10fdfc.png" width="300">

In this case, which appears quite often, it's hard to see the arrow in the top left.

The menu is shown as result of a search for a trip from Hamburg to Berlin for example.

**Comment by ialokim** [comment]
Thanks for your suggestion! How exactly would you like the style to be changed? I fear some other grey color or a little grey shadow might be difficult to see too.

**Comment by Echolon** [comment]
@ialokim 

One solution could be to change the color of the arrow and encircle it completly with e.g. white?

What do you think?

**Comment by ialokim** [comment]
I'm not sure whether this would meet the Material Design guidelines... I'm wondering how other apps handle this case, perhaps you could investigate and compare different approaches?

**Comment by Echolon** [comment]
This is how StreetComplete (the idea I basically suggested) and Osmand are doing it:
I also suggested a mock up which I think is suitable and not really a problem for the design in my taste.

StreetComplete:

<img src="https://user-images.githubusercontent.com/29168011/74749979-445ac880-526b-11ea-8311-0383cedab1fd.png" width="300">

Osmand:

_But I guess is not material design, however I like the transparent solution as well_
<img src="https://user-images.githubusercontent.com/29168011/74750335-dcf14880-526b-11ea-8459-ed8e05aad7d7.png" width="200">

<img src="https://user-images.githubusercontent.com/29168011/74750352-e2e72980-526b-11ea-99a3-0cac448eb5f4.png" width="150">

Mock-up suggestion:

_Actually you already have something to gather from_
<img src="https://user-images.githubusercontent.com/29168011/74750762-88020200-526c-11ea-8160-ce61c295c477.png" width="80">

_Likely a little bit bigger..._
<img src="https://user-images.githubusercontent.com/29168011/74751511-a4526e80-526d-11ea-9eb6-7bd2564ccae0.png" width="300">

**Comment by ialokim** [comment]
I don't really like the red background as it draws to much attention in my opinion, but I've found following image in the internet: 
![](https://miro.medium.com/max/2880/1*STIJMEsZjoHri2EZkZcAZg.jpeg)
*(source: https://proandroiddev.com/android-full-screen-ui-with-transparent-status-bar-ef52f3adde63)*

Perhaps this could be a way to go?

I've also found the following:
![](https://i.pinimg.com/originals/09/92/a7/0992a7907d21a66d990475c87f548130.jpg)

Do you think it could also be sufficient to just switch to a black arrow as in the second example?

**Comment by Echolon** [comment]
Et voila!

Sufficient as Mock-up? I think the red-color is never present in the map the color-scheme of the underlaying map. So that actually the obvious best shot, or? @grote 
However I would incread the thickness and/or size.

<img src="https://user-images.githubusercontent.com/29168011/74775121-54879d80-5295-11ea-9ede-b64403976598.png" width="300">

**Comment by grote** [comment]
I like what Uber is doing. When the dark theme is used the arrow should likely be in a whitish color.
