### ISSUE TITLE
time issues

### ISSUE THREAD

**Issue by francescosoave** [grote/Transportr#634]
**Describe the bug**
Hi I often have time issues with the app. I'm on android 9. As example you can see below. The time is set to "now" but I only get 1 result, the latter are for tomorrow early morning (I guess) so are not relevant. I'm not sure if this is related to the app or public-transport-enabler (I've also opened another issue there with results problems but this one sound like might be more related with transporttr. The other issue - Just in case - https://github.com/schildbach/public-transport-enabler/issues/285)

**To Reproduce**
1. Add addresses for departure/ arrival
2. Click on search
3. Scroll down to see results

**Expected behavior**
I expect to see various combinations of transports to get me from departure to destination, from now onwards (I don't understand why it displays past trips), at least 5-8 results. Please check same route on https://tfl.gov.uk to see expected results

**Screenshots**
![Screenshot_20191017-164842](https://user-images.githubusercontent.com/26126452/67026769-5cc1a780-f100-11e9-998b-9aadc7f8d1c2.jpg)

**Versions (please complete the following information):**
 - **Transportr Version:** [2.0.6]
 - **Device:** [OnePlus 3T]
 - **Android Version:** [9]

**Comment by ialokim** [comment]
Thank your for reporting this. Without looking much into it, I guess it could be linked somehow to #577.

**Comment by grote** [comment]
Are the results always one hour behind?

**Comment by francescosoave** [comment]
@ialokim thanks..strange because it doesn't always happen..unless it always does and I haven't realized (which, considering I've been using the app only since a few days it might as well be)

@grote they are 16 hours different (you can see my current time in the topbar 16:48)

**Comment by grote** [comment]
And you are sure that your phone's time and timezone is set correctly?

**Comment by francescosoave** [comment]
yes, this is my settings. It looks correct to me. Is there any other place in my phone I should check for it?
![Screenshot_20191017-175614](https://user-images.githubusercontent.com/26126452/67030531-829e7a80-f107-11e9-99ed-35098736831e.jpg)

**Comment by ialokim** [comment]
This should be fine.

Which network provider are you using inside Transportr? Is it TLEM? Strangely on my phone it doesn't even find any connections between the stations. Could you link to an actual query on https://tfl.gov.uk?

**Comment by francescosoave** [comment]
@ialokim yes I'm using TLEM. [Link](https://tfl.gov.uk/JourneyPlanner/MultipleJourneyResult?journeyType=Fastest%20by%20public%20transport&cyclepreference=none&query=IsAsync=true|InputFrom=Kenninghall%20Road%2C%20London%2C%20UK|From=Kenninghall%20Road%2C%20London%2C%20UK|FromId=51.55833053588867,-0.05972149968147278|InputTo=Bancroft%20Road%20%2F%20Ocean%20Estate|To=Bancroft%20Road%20%2F%20Ocean%20Estate|ToId=1010513|TimeIs=departing|Date=20191017|Time=2030|WalkingSpeed=average|InputVia=|DataSetsJson=[[%22stopPoints%22,%22journeyPlannerNoSubmit?Input={{input}}%22]]|Via=|ViaId=|NationalSearch=False|MaxWalkingMinutes=40|SavePreferences=false|IsPastWarning=False|JourneyPreference=leasttime|JpType=publictransport|AccessibilityPreference=norequirements|mode=bus|mode=tube|mode=national-rail|mode=dlr|mode=overground|mode=tflrail|mode=river-bus|mode=tram|mode=cable-car|mode=coach|CyclePreference=none|iscyclehire=false|isMultipleJourneySelection=true|WalkingOptimization=False|useMultiModalCall=false) with same bus stops selected:

**Comment by oldenj** [comment]
I did a clean Android install on my phone (Android 7.1) when this started happening for me as well. I got a new phone with Android 10, same thing there.
![Screenshot_20200124-185453](https://user-images.githubusercontent.com/45802959/73091821-89dddd00-3edb-11ea-8701-975441eb40c6.png)
![Screenshot_20200124-185522](https://user-images.githubusercontent.com/45802959/73091822-89dddd00-3edb-11ea-8fe6-02a86e1b32a8.png)
![Screenshot_20200124-185911](https://user-images.githubusercontent.com/45802959/73091868-a0843400-3edb-11ea-82b3-f350b0eddb72.png)

**Comment by ialokim** [comment]
@oldenj Thanks for your report. Which network provider are you using? Is it MVG?

Could you perhaps check whether changing the hour from now to e.g. five minutes later changes the result?

**Comment by oldenj** [comment]
Thank you for looking into it.
The provider is 'MVV' and changing the time doesn't change the results - only when i set them close to the time of the results, e.g. around midnight. In that case, i get slightly different results that even seem to fit the time better.

The way i interpret it is that under some conditions the app only returns "night connections".

Regular connections end at some point and from around midnight to around 5am only night lines are active.

As you can see from the screenshots, line 181 is the regular bus and transportr only returns N40 - N is the night line prefix.

**Comment by ialokim** [comment]
I can confirm this behavior with your given stations. Changing the date and leaving the time as is does affect the results, i.e. on some days it returns all current connections as expected and on some days it produces the same output you've posted above. Really weird!

The next step would be to check whether the PTE library which is used internally in Transportr already produces these strange results or if it's indeed due to some problem inside the app. I'll try to have a look in the coming days.

**Comment by oldenj** [comment]
Great.
By the way, today everything works fine for me. The connection i posted yesterday as well as different ones.

**Comment by ialokim** [comment]
At least for me it seems the problem does occur from Monday to Friday, but not on weekends. Could you confirm that?

**Comment by ialokim** [comment]
I've just checked and same happens with Öffi (which is also built on PTE). You could consider reporting the issue over there: https://github.com/schildbach/public-transport-enabler

**Comment by oldenj** [comment]
> At least for me it seems the problem does occur from Monday to Friday, but not on weekends. Could you confirm that?

For the one connection yes. Other connections seem to work any day of the week.
I'm starting to think that it is related to the '181' line specifically.

I'll also file a report there.

**Comment by ialokim** [comment]
@francescosoave Same for your issue, on my phone neither Transportr nor Öffi finds any connection between these two stations. I'm afraid we can't do anything on Transportr side for this. As has been pointed out in https://github.com/schildbach/public-transport-enabler/issues/285, this seems to be a problem of the underlying data provider.

**Comment by francescosoave** [comment]
Hi, thanks for looking in the issues. Unfortunately after reinstalling the app now I'm not even able to set home/work location anymore (and many many others) as they won't be recognized as "from" or "to" (even if they were selected from the suggestions in the dropdown menus). I have now stopped using the app completely as I can't really use it. I understand it's an upstream issue. Thanks again!
