### ISSUE TITLE
French translation needs improvements

### ISSUE THREAD

**Issue by breversa** [grote/Transportr#639]
**Describe the bug**
First of all, thanks for this awesome app ! I installed it on my parent's phone, but they sadly couldn't use it, as the french translation could use some serious improvements. As it stands, several labels are either mistranslated (e.g. "Origine" for "Home") or just not understandable (e.g. "Il est" for… "Select departure or arrival time" ? I guess ?).

I'd love to help correct/improve it, but I've twice been rejected from Transifex, so here I am… :-)

**Versions (please complete the following information):**
 - **Transportr Version:** 2.0.6
 - **Device:** N/A
 - **Android Version:** N/A

**Comment by grote** [comment]
When and by whom have you been rejected? Was any information given?

**Comment by breversa** [comment]
Once yesterday, once today.
The mail said :

> Your request to join the translation team Grobox Translation Team was not accepted
>  
> There are a number of reasons this could have happened. If you would like to better understand why, please contact someone from the Grobox organization directly.

**Comment by breversa** [comment]
Maybe because all the strings in french are already translated ?

**Comment by grote** [comment]
Hmm... maybe. Can you write a message on Transifex to the team coordinator and ask them about the refusal and maybe discuss the translation issues there?

**Comment by breversa** [comment]
I wish I could, but how ? There's no contact information on the Transifex page if you're not part of the team… :-(

**Comment by grote** [comment]
Does this link work for you? https://www.transifex.com/user/messages/compose/yahoe.001/

**Comment by breversa** [comment]
Yes it does ! I’ve sent a message to yahoe.001. Let’s wait for their reply. Thanks ! :-)

**Comment by ialokim** [comment]
yahoe.001 answered me today, you are now part of the French translation team!
