### ISSUE TITLE
A "Follow Your Route" Feature

### ISSUE THREAD

**Issue by MiniBossDK** [grote/Transportr#640]
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [x] I can help myself to get this feature implemented or know someone who wants to do it.
* [x] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

I often had the problem that I had a hard time finding the route I was following either because I accidentally closed the app or went away from it. It is also hard to keep the specific route that I want to follow for the next day. At the moment, I can only add a route like Hamburg to Berlin to my favorites and not save the specific route.   

**Describe the solution you'd like**

I want a new feature that allow me to save the specific route I am currently following. That feature could appear on the different specific routes after I have searched for my route. I have made an illustration to show what I mean in the bottom. Those white three dotted on the right hand side is where I have considered to place them. If you click on the three dotted you get the option to "Follow The Route". It will then save the Followed Route the same place as you place your favorites and history.  

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions you've considered. But please limit this ticket to one feature or use-case.
At the moment, I don't have any alternative solutions but are open to suggestions. :)

**Additional context**
![take1](https://user-images.githubusercontent.com/24865481/67991492-b6b28900-fc39-11e9-8e9e-60afafa4a9dc.png)

**Comment by grote** [comment]
This sounds very similar to #171.

**Comment by MiniBossDK** [comment]
Yeah, that is the same idea. Thanks for the feedback. I have by the way requested a translation to danish and I just need to be accepted.

**Comment by grote** [comment]
Please feel free to pickup #171. A more complex way to do it would be to serialize the Trip objects into the Room database. Alternatively, they could also use the JavaSerialization feature and just store it in a file.

**Comment by grote** [comment]
As for a Danish translation, let's use the more general "Danish" instead of "Danish (Denmark)" language code for now.

**Comment by MiniBossDK** [comment]
Fine with me. Another request has been send.
