### ISSUE TITLE
Added Italy city

### ISSUE THREAD

**Issue by tr567** [grote/Transportr#646]
Open Data & APIs Bolzano, Merano, Laives and Lana,
http://sasabus.org/opendata
Venezia ACTV - General Transit Feed Specification (GTFS)
http://dati.venezia.it/?q=content/actv-general-transit-feed-specification-gtfs
Trentino
https://www.trentinotrasporti.it/open-data?highlight=WyJvcGVuIiwiZGF0YSIsIm9wZW4gZGF0YSJd

**Comment by grote** [comment]
There's information on the homepage on how to add new cities: https://transportr.app/contribute/

In this case, you need to talk to Navitia.
