### ISSUE TITLE
Rebuild against latest public-transport-enabler to get Sweden fix

### ISSUE THREAD

**Issue by regagain** [grote/Transportr#649]
Hi!

Sweden stopped working a while ago. The issue has been fixed in public-transport-enabler (see schildbach/public-transport-enabler#266).

Is there any chance you guys could trigger a rebuild of the app so we can get that fix?

Thanks!

**Comment by ialokim** [comment]
I guess there are no open issues that would block a new release (apart of perhaps #641 for introducing the price information straight away with smoother animations).

Lately I've been quite busy so I didn't manage to work on #641 and I probably won't have time in the next couple of weeks either.

So I think it would make sense to publish a new release from current master including the new Czechia provider and this fix for Sweden for now. @grote What do you think?

**Comment by grote** [comment]
Sure, we can do a release. @ialokim would you be able to do the preparation?

* upgrade to latest PTE
* bump versions numbers
* do changelog
* transifex translation update (if possible)
* test the release

Then I'll do the signing, F-Droid and Google Play part.

**Comment by grote** [comment]
Did you have a chance to test the new release? Does it work for you?

Notice in Google Play it is still in the beta track you need to opt-in to.
