### ISSUE TITLE
When zooming in, the zoom is delayed and and zoom-out zooms out too much

### ISSUE THREAD

**Issue by aha999** [grote/Transportr#654]
**Describe the bug**
When you're zooming in, the zoom starts delayed by around 0.5s and the zoom-in or out is weird, it just zooms out to the entire country, it's too sensitive for zoom out-in i believe and sometimes it does not immediately respond.
Maybe some sort of optional zoom-slider could be better.

**Versions (please complete the following information):**
 - **Transportr Version:** 2.0.8
 - **Device:** Lenovo P2
 - **Android Version:** 9

**Comment by ialokim** [comment]
This is most likely to be reported to the map library at https://github.com/mapbox/mapbox-gl-native-android.
