### ISSUE TITLE
Realtime information for Paris/France

### ISSUE THREAD

**Issue by bre75** [grote/Transportr#659]
Hello,

As some of you may know, we're facing a month long strike of transportation in France.

For Paris, everyday the public transport company (RATP) is publishing the state of the network for the next day. But even thought it may change on the actual day depending of the situation and unions will.

Since the beginning of the strike i had unfortunately to switch to another application (citymapper) because they include the realtime situation strike included and this option was not available on Transportr. Transportr was even offering me routes through lines that were/are completely closed.

As strike is the national favorite hobby in France, i'd love to find this kind of option in my favorite transport application.

Is it something possible ? Planned ?

Best regards,

**Comment by grote** [comment]
You need to ask [Navitia](https://www.navitia.io/) as the data comes from there.

**Comment by ialokim** [comment]
Just for notekeeping: RATP [offers a realtime api](https://dataratp2.opendatasoft.com/page/temps-reel/), but [PTE](/schildbach/public-transport-enabler) doesn't support it for now. You could consider opening an issue over there as well.

**Comment by bre75** [comment]
I'm not a developer but to be sure to understand well.
It means it's the API you're calling that is not providing real time data for Paris ?

Maybe i'm innocent on this but I thought there was only one main source, the RATP one, realtime and that all the transport application are using as a base before adding their own features.

Am I wrong ?

(it's just for my global understanding) :)

**Comment by grote** [comment]
Transportr just calls Navitia's API and shows what it returns. All further questions about the API need to be directed to Navitia. AFAIK it *does* have some preliminary support for realtime information, but this isn't implemented in PTE (which Transportr uses to call that API) as written above.

**Comment by bre75** [comment]
Thanks for your answer i understand better.

If i have to summarize I'd say that as long as PTE doesn't support realtime, whatever API called, it won't work.

**Comment by ialokim** [comment]
Exactly, just a minor correction: as long as PTE doesn't support *Navitia's* realtime API *and/or Navitia doesn't deliver realtime information for RATP*; or *PTE implements the official realtime API for Paris* it won't work :)

**Comment by ialokim** [comment]
As nobody is working on this, I'm going to close this issue for now. Feel free to drop a new comment if you want to contribute here and/or if PTE or Navitia provides realtime data.
