### ISSUE TITLE
integration with https://www.eway.in.ua/ru/api

### ISSUE THREAD

**Issue by soredake** [grote/Transportr#660]
For integration with ukraine public transport.

**Comment by ialokim** [comment]
Thanks for your suggestion. Please consider reading the section about [Adding Support For More Regions](https://transportr.app/contribute/).

For Transportr to access new APIs, first [PTE](/schildbach/public-transport-enabler) has to support them.

**Comment by ialokim** [comment]
As nobody is working on this, I'm going to close this issue for now. Feel free to drop a new comment if you want to contribute here.
