### ISSUE TITLE
MapBox styles will stop working June 1, 2020

### ISSUE THREAD

**Issue by grote** [grote/Transportr#671]
Apparently we use what is now called Mapbox Studio Classic styles which will stop working June 1, 2020 and need to migrate to new styles. 

Related to #668

**Comment by ialokim** [comment]
We are currently using `mapbox://styles/mapbox/streets-v10` and `mapbox://styles/mapbox/dark-v9.

The newest versions [seem to be](https://docs.mapbox.com/api/maps/#mapbox-styles) `mapbox://styles/mapbox/streets-v11` and `mapbox://styles/mapbox/dark-v10`. Are these really that different? How do you know we are using deprecated styles?

**Comment by grote** [comment]
Not sure. They sent an email telling us that we are using the old ones.

**Comment by ialokim** [comment]
As we are now close to the deadline, I simply tried to apply a hotfix and just changed styles to new versions (see above).
Unfortunately, this doesn't work as expected:
![Screenshot_1590706738](https://user-images.githubusercontent.com/18088991/83202300-98692900-a147-11ea-91b0-15f7e9f7ccda.png)

It seems it will be necessary to update Mapbox SDK to a newer version supporting the newer styles (see #668) as soon as possible.

**Comment by grote** [comment]
Outsch. If they kept breaking their API with their new versions as they did before, this will be a bit of work. But maybe they have finally figured things out and they work like a charm now, who knows?

**Comment by grote** [comment]
Looks like map styles are still working ¯\_(ツ)_/¯

**Comment by grote** [comment]
New email:

> Mapbox is shutting down Mapbox Studio Classic Styles and Legacy Static API on November 1st, 2020. We deprecated requests to Studio Classic styles or Classic projects (created in Mapbox Editor) on June 1, 2020. This is the final notice to migrate your map before you lose access to your Studio Classic styles.
> 
>You’ve made 7231 requests using the following Classic styles in the last 2 weeks:
> 
>     mapbox.streets
> 
> Service for Studio Classic styles will be shut down on November 1st, 2020, and requests to your Classic styles will result in an error with a 410 status code.

**Comment by ialokim** [comment]
As this mail only mentions `mapbox.streets` and not the dark style [mentioned above](#issuecomment-601849537), I'm pretty sure we are using these deprecated classic styles (only) on the Transportr website:
![grafik](https://user-images.githubusercontent.com/18088991/95390550-dba58680-08f5-11eb-9e2e-c5d7be1006ab.png)

The styles used in Transportr itself follow the "new" naming convention with `/` [as described in the Mapbox docs](https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-tiles-api/?#how-can-i-tell-if-my-style-is-a-classic-style-or-a-modern-mapbox-style) and appear to be non-legacy, hopefully.

**Comment by grote** [comment]
Ah that explains it!

Hopefully fixed in https://github.com/grote/Transportr-website/commit/dc65b36c33511f902a49f27923da6aef4aad0213
