### ISSUE TITLE
Changing language in-app does not change title in toolbar

### ISSUE THREAD

**Issue by ialokim** [grote/Transportr#676]
After changing the language to use inside the app's settings, the toolbar titles are not adjusted to the new language but still use the system's default.

![Screenshot_1584728283](https://user-images.githubusercontent.com/18088991/77194082-8b90df00-6adf-11ea-8572-1e8c83e8c9e0.png)

**Comment by grote** [comment]
ah language changer is completely broken. I think Briar has the best one available, but even they ask you to kill the app to have all changes visible.
