### ISSUE TITLE
VMS: unable to search for stations

### ISSUE THREAD

**Issue by txt-file** [grote/Transportr#678]
**Describe the bug**
I have the feeling that [VMS](https://www.vms.de/startseite/) changed something on their service. The behaviour was tested on 2 different devices with 2 different internet service providers. According to a friend it worked 3 days ago but did not work since yesterday evening.

As the last changes on https://github.com/schildbach/public-transport-enabler are from 6. March 2020 I expect the issue to still exist upstream.

I report it here as I can better describe how to reproduce the issue with transportr compared to a library.

**To Reproduce**
1. set Europe→Germany→VMS as provider
2. enter something in the search field
3. get no search result

other way:
1. set Europe→Germany→VMS as provider
2. long tap somewhere in the map
3. tap "nearby stations"
4. get "could not find nearby stations" after 1 second or even less than 1 second

**Expected behavior**
get search results and nearby stations

**Versions (please complete the following information):**
device 1
- **Transportr Version:** 2.0.8 (via f-droid)
- **Device:** Google Nexus 7 (2012)
- **Android Version:** AOSP 7.1.2

device 2
- **Transportr Version:** 2.0.8 (via f-droid)
- **Device:** huawei P20 lite (2018)
- **Android Version:** 8 or 9

**Comment by oli-z** [comment]
This probably has to do with the API endpoint (https://www.vms.de/vms2) being down. Apparently VMS has other API endpoints (https://www.vms.de/VMSSL3 and https://www.vms.de/Oeffi). Maybe we can use these.

**Comment by txt-file** [comment]
@grote @ialokim I just send a pull request to upstream https://github.com/schildbach/public-transport-enabler/pull/335
