### ISSUE TITLE
Project does not build on Windows PC

### ISSUE THREAD

**Issue by mbukovich** [grote/Transportr#679]
**Description**
When the repository is cloned to a Windows PC, the project will not build using both Android Studio as well as the console. 

**To Reproduce**
1. Clone repository on a Windows PC
2. Import the project into Android Studio
3. Wait for the project to build
4. See the following error:
Caused by: org.gradle.api.InvalidUserDataException: No dependency for integrity assertion 'com.android.tools.build:aapt2:3.5.1-5435860:aapt2-3.5.1-5435860-linux.jar:acd3c93095cc982deb4d97262c01e9fceca9e3cd8385c45fb8c3d0401f286d5d'

**Expected behavior**
Expected behavior is for the project to build without errors so that the project may be run on a device.

**Versions (please complete the following information):**
 - **Transportr Version:** Latest version from Github repository
 - **Device:** Samsung Galaxy S10
 - **Android Version:** 10.0
 - **Android Gradle Plugin Version:** 3.5.1
 - **Gradle Version:** 5.6.3

**Comment by mbukovich** [comment]
I did some digging and some research. It appears the issue is the following line in the witness.gradle file under /app/libs/

'com.android.tools.build:aapt2:3.5.1-5435860:aapt2-3.5.1-5435860-linux.jar:acd3c93095cc982deb4d97262c01e9fceca9e3cd8385c45fb8c3d0401f286d5d',

**Comment by grote** [comment]
Yeah Windows builds aren't really supported. The issue is the Android toolchain pulls in platform specific dependencies which are pinned on Linux.  

For now you can just remove or outright empty the lines in witness.gradle.

Maybe only the offending dependencies can be ignored here: https://github.com/grote/Transportr/blob/master/gradle.properties#L3

If nobody cares about dependency pinning, we could also just remove that.

**Comment by mbukovich** [comment]
Hi grote, thank you for looking at this.

I was able to remove that line from witness.gradle, and the project builds and runs on my phone. I am concerned, however, about pull requests and maintaining consistency with the github master. I would like to help with some issues and bringing functionality to certain metropolitan areas, but I'm worried that deleting that line could mess things up. Could I just paste it back into witness.gradle when committing? 

(is it possible to comment out lines in .gradle files?)

**Comment by ialokim** [comment]
@mbukovich perhaps you could check whether current master now builds successfully under Windows. We would be happy to receive contributions from your side in the future!
