### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by sphh** [grote/Transportr#683]
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.
* [ ] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**
I noticed, that there was no release for the last 6 months and that there are many new and useful features / fixes already committed.

**Describe the solution you'd like**
Could you please make a new release!

**Describe alternatives you've considered**
I enabled Transportr's beta channel in F-Droid, but there is no new release.

**Additional context**
* The actual F-Droid version 2.0.8 was made available on 25/11/2019, but the github release for [2.0.8](https://github.com/grote/Transportr/releases/tag/2.0.8) is from 06/12/2020.
* F-Droid still recommends the version 2.0.6 from 02/05/2019.

**Comment by grote** [comment]
This is about my private repo containing, but not recommending the latest release, right?

If so, this should be fixed now. Thanks for noticing!

**Comment by sphh** [comment]
Thanks for recommending the latest version. But this was just a side note ...

Mainly my plea was to make a new release with all the exciting new features and bug fixes.

**Comment by grote** [comment]
@ialokim anything you want to get into the next release? Care to do a PTE upgrade?

**Comment by sphh** [comment]
Myself, I am looking forward to the PRs #664 (Directions UI), #658 and #656 (real time informations) and maybe #524 (collapse text).

**Comment by ialokim** [comment]
> @ialokim anything you want to get into the next release?

Eventually, I wanted to upgrade Mapbox SDK for support of the newer styles #671 (which was in fact not necessary as it seems). As I'm a bit short on time for the moment, I think it would be okay to publish a new version before the migration.

> Care to do a PTE upgrade?

I would have to look into the changes done at upstream, but I'm not aware of any pressing enhancements, so we could probably skip upgrading PTE for now.

Do you want me to prepare the release? I could try to get it done during the next week.

**Comment by ialokim** [comment]
There are still two blocking issues related to the (supposedly better) theming support: #685 and #686. For the first one, it might make sense to update Mapbox SDK (#668) before.

**Comment by grote** [comment]
Updating Mapbox SDK before a release might be too big of a task.
