### ISSUE TITLE
Support Samsung DeX / Clearly mark multi-window support

### ISSUE THREAD

**Issue by alexanderadam** [grote/Transportr#684]
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.
* [x] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**

It would be great if Transportr would be properly resizable on Android Desktops

**Describe the solution you'd like**

According to [Samsung's documentation this is how to enable window resizing for Android applications](https://developer.samsung.com/samsung-dex/modify-optimizing.html):

```xml
<application
    android:resizeableActivity="true">
</application>
```

The folks added [this](https://codeberg.org/gitnex/GitNex/pulls/601/files), too however:

```diff
From 9e352df1ed7d1d285fde61632822e2db5d128f16 Mon Sep 17 00:00:00 2001
From: 6543 <6543@obermui.de>
Date: Thu, 23 Jul 2020 13:29:53 +0200
Subject: [PATCH] Support Samsung DeX

---
 app/src/main/AndroidManifest.xml | 8 +++++++-
 1 file changed, 7 insertions(+), 1 deletion(-)

diff --git a/app/src/main/AndroidManifest.xml b/app/src/main/AndroidManifest.xml
index 8518fe2c..f8c2367c 100644
--- a/app/src/main/AndroidManifest.xml
+++ b/app/src/main/AndroidManifest.xml
@@ -12,6 +12,7 @@
         android:icon="@mipmap/app_logo"
         android:label="@string/app_name"
         android:networkSecurityConfig="@xml/network_security_config"
+        android:resizeableActivity="true"
         android:roundIcon="@mipmap/app_logo_round"
         android:supportsRtl="true"
         tools:targetApi="n">
@@ -60,7 +61,7 @@
             android:name=".activities.RepoDetailActivity"
             android:label="@string/title_activity_repo_detail"
             android:theme="@style/AppTheme.NoActionBar" />
-        <activity android:name=".activities.MainActivity" android:theme="@android:style/Theme.NoTitleBar">
+        <activity android:name=".activities.MainActivity" android:theme="@android:style/Theme.NoTitleBar" android:configChanges="orientation|screenSize|smallestScreenSize|density|screenLayout|uiMode|keyboard|keyboardHidden|navigation">
             <intent-filter>
                 <action android:name="android.intent.action.MAIN" />
 
@@ -84,6 +85,11 @@
         <activity android:name=".activities.AddNewTeamMemberActivity" />
         <activity android:name=".activities.SettingsDraftsActivity" />
 
+        <!-- Version < 3.0. DeX Mode and Screen Mirroring support -->
+        <meta-data android:name="com.samsung.android.keepalive.density" android:value="true"/>
+        <!-- Version >= 3.0. DeX Dual Mode support -->
+        <meta-data android:name="com.samsung.android.multidisplay.keep_process_alive" android:value="true"/>
+
     </application>
 
 </manifest>
```

The Samsung documentation also has more tweaks and information on how to improve the desktop experience in case you're interested.
They also have [an app testing guide](https://developer.samsung.com/samsung-dex/testing.html) (although some apps are fine with this guide but won't work on "real" DeX sometimes).

**Describe alternatives you've considered**

Not being able to resize the application

**Additional context**

I'm using [Samsung DeX](https://www.samsung.com/us/explore/dex/), which gives a desktop like experience and makes use of Android windowing support.

At the moment the resizing button is greyed out and the application is always nearly squarish:

![Screenshot of Transportr on Samsung DeX](https://user-images.githubusercontent.com/372620/88277141-85ef1400-cce0-11ea-841c-ccf143d18bdb.jpg)

**PS:** I know that it is possible to _force_ all apps to be resizable via `Samsung Labs` > `Force Resize` but it would obviously better to make the application natively resizable to create less friction.
**PPS:** I'm not sure whether this is relevant but [this](https://codeberg.org/gitnex/GitNex/pulls/601/files) is how GitNex fixed the issue.

**Comment by ialokim** [comment]
Related to #579. Until we add proper support for landscape orientation / bigger screen sizes, I would suggest you use the "force resize" workaround.

**Comment by alexanderadam** [comment]
@ialokim are you sure that this is related?
Because the Samsung DeX issue is rather about adding metadata that DeX is reading whereas #579 is about introducing another layout.

So since you could have a dedicated landscape layout and resizing still wouldn't work without adding the metatags those two aren't related at all.
This issue here (#684) is just about adding the metatags — so _resizing_ (in the sense of the functionality) would work fine.

This is clearly _not_ about adding another layout.

**Comment by ialokim** [comment]
Okay, I see. Looking at the [Andriod docs](https://developer.android.com/guide/topics/ui/multi-window.html), it indeed might make sense to clearly enable multi-window support for Transportr. Indeed for `android:resizeableActivity` it states the following:
> If your app targets API level 24, but you do not specify a value for this attribute, the attribute's value defaults to true.
There should be no semantic difference (on Android) after adding this attribute. As the other two (meta-data) tags are specific to Samsung DeX, I see indeed no harm in adding the lines in Transportr as well.

**Comment by alexanderadam** [comment]
Thank you for reopen this issue. :pray: 

Please note: NewPipe and GitNex also added `android:configChanges` with some pipe separated values.
I'm not sure whether this is relevant, though. But it was in their commits for supporting DeX.
