### ISSUE TITLE
Popup theme not properly changed

### ISSUE THREAD

**Issue by ialokim** [grote/Transportr#686]
On current master and (at least) API 22, popups are always displayed using dark theme no matter which app theme is picked:

![Screenshot_1595537448](https://user-images.githubusercontent.com/18088991/88337490-1a846100-cd37-11ea-8004-50b73378b089.png)

**Comment by grote** [comment]
Maybe the dialog theme being used is either not properly declared as a theme attribute or declared when launching the dialog, or the dialog theme itself is not a proper DayNight theme.
