### ISSUE TITLE
F-Droid can't build with gradle-witness being present

### ISSUE THREAD

**Issue by licaon-kter** [grote/Transportr#692]
Ref: https://f-droid.org/wiki/index.php?title=de.grobox.liberario/lastbuild_118&oldid=274563

Ref: https://gitlab.com/fdroid/fdroiddata/-/issues/2078

Ref: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7265

**Comment by grote** [comment]
Until and if this project removes/replaces gradle witness, F-Droid can build it from source like so:

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/2598/diffs

Our source: https://github.com/akwizgran/gradle-witness

**Comment by grote** [comment]
Alternatively, Transportr could consider to move to https://docs.gradle.org/current/userguide/dependency_verification.html

**Comment by ialokim** [comment]
For this release, I think it would be easiest to disable and remove gradle witness in fdroid's metadata prebuild. Would that be possible (aka would the prebuild step be run before `INFO: Scanning source for common problems...`) @licaon-kter ? Would you agree with this fix @grote ?

**Comment by licaon-kter** [comment]
Already tried ;) fails to find `:witness` and whatnot, we need more than `sed`

**Comment by licaon-kter** [comment]
> F-Droid can build it from source like so:
> https://gitlab.com/fdroid/fdroiddata/-/merge_requests/2598/diffs

Will take a look then

**Comment by ialokim** [comment]
> > F-Droid can build it from source like so:
> > https://gitlab.com/fdroid/fdroiddata/-/merge_requests/2598/diffs
> 
> Will take a look then

I guess this will not work as we didn't include the witness source code in this repo.

**Comment by licaon-kter** [comment]
I can srclib https://github.com/akwizgran/gradle-witness I guess

**Comment by ialokim** [comment]
These changes should do it too: https://github.com/opentransitmap/Transportr/commit/1483c3eb104f2a1ede234856d82953ad4394eefd

At least on my machine the build completed without problems.

**Comment by licaon-kter** [comment]
The latest fdroidserver became rather sensible to files, ZIPs, JARs, etc, :D

I'm trying to integrate build from source, so no need to rush and remove :)

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7268
