### ISSUE TITLE
Map (mapbox) displays Spanish place-names even using Basque locales

### ISSUE THREAD

**Issue by Porrumentzio** [grote/Transportr#695]
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [ ] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.
* [ ] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**
There are many places all around the world in which due to diglossia, place-names have more than one name. This is the case of Basque Country, where *Pamplona* and *Iruña* are the same place, in Spanish and Basque languages. And this names are not displayed according to the elected languages for the app.

**Describe the solution you'd like**
My proposal is that if user selected a language for the app (for example Basque), those names should be favoured. So, if Basque language selected, it should display *Iruña*, the basque name of the place.
Same for any other situation in any other country in which happens the same.

**Additional context**
The map displays only the Spanish name for the city, not both nor only the Basque
![The map displays only the Spanish name for the city, not both nor only the Basque](https://user-images.githubusercontent.com/61913683/91024355-2003ee00-e5f8-11ea-9726-60454fa5de58.png)

**Comment by ialokim** [comment]
For further investigations: https://docs.mapbox.com/android/plugins/overview/localization/

**Comment by Porrumentzio** [comment]
Cool! Seems that there's a plugin that can be added. However I'm not programmer and I want be able to help with that with coding, but yes with opinions and so on 👍

**Comment by Porrumentzio** [comment]
Yes, that seems to solve the problem! Now it's showing combined names, apparently from OSM. Great, thanks, I'm then closing this issue
