### ISSUE TITLE
Hide Transportr from "Show on External Map" (otherwise error appears)

### ISSUE THREAD

**Issue by Porrumentzio** [grote/Transportr#698]
**Describe the bug**
When chosen Transportr to show as external map, `Couldn't open external location` error appears. Logically, as it's not an **external** map. Could Transportr be hidden from that menu?

**To Reproduce**
1. Go to travel
2. Tap on a line/way/plan
3. Tap on the three points of a place
4. Tap on `Show on External Map`
5. Choose Transport
6. `Couldn't open external location` error appears

**Expected behavior**
Transportr should **not** appear.

**Screenshots**
![transportr-external-map](https://user-images.githubusercontent.com/61913683/91028518-e209c880-e5fd-11ea-8d68-445e37b4d5c0.gif)

**Versions (please complete the following information):**
 - **Transportr Version:** 2.0.1
 - **Device:** Xiaomi Redmi Not 4 X
 - **Android Version:** /e/OS Nougat (7.1.2)

**Comment by ialokim** [comment]
This might be two separate issues here:
- For some reason, Transportr seems to be unable to resolve the intent format it emits itself.
- We could discuss whether it makes sense to hide Transportr from the selector, any opinion @grote? Some ideas on how to accomplish this could be found [here](https://stackoverflow.com/a/18068122) or (probably easier) [here](https://stackoverflow.com/a/19512128).

**Comment by grote** [comment]
I think removing Transportr from its own intents makes sense.
