### ISSUE TITLE
Releases after Nov 2 need to target API level 29

### ISSUE THREAD

**Issue by grote** [grote/Transportr#699]
Otherwise we can't distribute them via Google Play: https://developer.android.com/distribute/best-practices/develop/target-sdk

**Comment by ialokim** [comment]
We're [already targeting API level 29](https://github.com/grote/Transportr/blob/master/app/build.gradle#L19), so I guess we have nothing more to do here?

**Comment by grote** [comment]
Hmm the email Google had sent me claimed that Transportr is on `27`, but we upgraded to `29` months ago: https://github.com/grote/Transportr/commit/7906be7169016c56aa393a5ac798d85357c236c8#diff-39e7d8c00954e920b98e7636f0ac30b2R19

So I guess/hope there's nothing more to do.
