### ISSUE TITLE
"in x minutes" does not update

### ISSUE THREAD

**Issue by ialokim** [grote/Transportr#700]
**Describe the bug**
~When searching for connections and~ In the trip detail view, you can see a "in x minutes"/"now"/"x minutes ago" text. After waiting for e.g. one minute (turning the display off or leaving it on), the displayed text should adapt to the new current time. This does not happen and is especially confusing if you search for a connection, go to the first platform, turn your display off, get on the train (e.g.) and look for your connection after some minutes again, it will still report the time before getting on the train.

**To Reproduce**
1. Search for a connection
2. Select a specific connection within the next minutes ~(optional)~
3. Stay on the same screen for some time (or turn your display off and on again after some time)
4. Notice that the time description does not change over time until reloading.

**Expected behavior**
The string should update according to the current time.

**Versions (please complete the following information):**
 - **Transportr Version:** 2.1.0
 - **Device:** Wileyfox Swift
 - **Android Version:** 9

**Comment by ialokim** [comment]
Also, the departures button in the directions form might update it's value from "now" to a specific time if some minutes passed between searching and viewing the screen again.

**Comment by ialokim** [comment]
The text gets properly updated in the search results view, but not in trip details.

**Comment by ialokim** [comment]
While working on this, I noticed that relative times and delays are always shown as the floored value instead of properly rounded to the next full minute. I would expect e.g. seeing "Now" from 30 seconds before to 30 seconds after the time and starting from the time until time + one minute. @grote How do you feel about this? May we change that behavior?

**Comment by grote** [comment]
fixing/changing this sounds good!
