### ISSUE TITLE
MVV is not working properly

### ISSUE THREAD

**Issue by mdosch** [grote/Transportr#705]
Thanks for this nice app but it seems the MVV (public transport Munich) routing is not working anymore. E.g. searching for "Bereiteranger" or "Ohlmüllerstraße" didn't yield any results in Transportr 2.1.0. Maybe they changed something on their API.

The version 2.1.0 was used on a device with LOS17 (Android 10).

**Comment by ialokim** [comment]
Thanks for your bug report.

Some questions that might help to tackle down the problem:
- Are these names of stations or only addresses?
- Does it happen with all search queries or are there just some missing?
- Did it work for you before and if so, when did it stop working?

Next step would be to check whether this is an API key issue or related to the MVV back-end used in PTE being down.

**Comment by mdosch** [comment]
>     * Are these names of stations or only addresses?

These are streetnames, I am not aware if they are also station names although there is a tram station in Ohlmüllerstraße which might be called Ohlmüllerstraße

>     * Does it happen with all search queries or are there just some missing?

Right now it happened for both streets I tried to look up.

>     * Did it work for you before and if so, when did it stop working?

Before I could navigate to any address in Munich. Unfortunately I can't really tell when it stopped working as I only look up in Transportr when I go to a place where I don't already know how to go there and in my daily life I know how to go around without the app.

**Comment by AnnArcyi** [comment]
I also had issues using MVV network in Transportr: some stations had doubled entries with one not working. This state was awful, because it wasn't easy to figure out the "right entry" as the wrong one also became automatically favorized.

So I reinstalled Transporter just because this often enough works with computer stuff =D
...now I have the same issue described above:
no matter which adress I search for, there is no entry, if there isn't a station which us called the same...

...I'm a noob and software stuff, please tell me how I can help to figure out the problem.

(I wouldn't have installed LineageOS if I didn't know one how did this for me...
version 16.0 // Android 9 // 6. Sept 2020)

Thanks for the extremely nice app and your help to let me help =)

**Comment by ialokim** [comment]
> some stations had doubled entries with one not working

This was most likely due to changed internal station IDs (see #277).

> no matter which adress I search for, there is no entry, if there isn't a station which us called the same...

Okay, so stations are still found?

> I reinstalled Transportr

Do you know whether you reinstalled the same version of Transportr, or were you using an older version before (if so, which one)?

---

> eDiT: I just figured out this problem also exists with the original homepage www.mvv-muenchen.de // seems not to be an issue woth Transportr!?

Okay, nice to know, this indeed seems to be an upstream issue then. Perhaps you might write them stating that the service on their website somehow degraded. I would guess if they fix it for the website it will most probably also start to work in Transportr again.

**Comment by AnnArcyi** [comment]
> This was most likely due to changed internal station IDs (see #207).

Thanks, will do.

> Okay, so stations are still found?

Seemingly also not all of them. For me it's "Ubostraße" is found while "Germeringer Weg" not. But couldn't this also be an issue with MVV itself? Perhaps we should just wait a bit?

> Do you know whether you reinstalled the same version of Transportr, or were you using an older version before (if so, which one)?

That's a thing with this being a foolish noob. Of course I did NOT look this up before, I'm rly sorry -.-

> Okay, nice to know, this indeed seems to be an upstream issue then. Perhaps you might write them stating that the service on their website somehow degraded. I would guess if they fix it for the website it will most probably also start to work in Transportr again.

I called the hotline and asked to give the information to the IT/right place, hopefully this helps...

**Comment by ialokim** [comment]
Looking at [this query](https://efa.mvv-muenchen.de/index.html?itdTime=1129&itdDate=20200909&language=de&name_origin=Ohlm%C3%BCllerstra%C3%9Fe&name_destination=M%C3%BCnchen%2C%20Hauptbahnhof&itdTripDateTimeDepArr=arr#trip@enquiry) it is still possible to search for addresses as well on their EFA frontend. So this might be an issue with how [PTE searches for stations](https://github.com/schildbach/public-transport-enabler/blob/master/src/de/schildbach/pte/MvvProvider.java). You may then also [open an issue in their bug tracker](https://github.com/schildbach/public-transport-enabler/issues/new) explaining the problem and linking to this thread.

**Comment by mdosch** [comment]
Am September 9, 2020 9:23:47 AM UTC schrieb ialokim <notifications@github.com>:
>> some stations had doubled entries with one not working
>
>This was most likely due to changed internal station IDs (see #277).
>
>> no matter which adress I search for, there is no entry, if there isn't a station which us called the same...
>
>Okay, so stations are still found?
>
>> I reinstalled Transportr
>
>Do you know whether you reinstalled the same version of Transportr, or were you using an older version before (if so, which one)?
>
>---
>
>> eDiT: I just figured out this problem also exists with the original homepage www.mvv-muenchen.de // seems not to be an issue woth Transportr!?
>
>Okay, nice to know, this indeed seems to be an upstream issue then. Perhaps you might write them stating that the service on their website somehow degraded. I would guess if they fix it for the website it will most probably also start to work in Transportr again.
>

I just tried and the website worked fine for me.

**Comment by mdosch** [comment]
Am September 9, 2020 9:23:47 AM UTC schrieb ialokim <notifications@github.com>:
>> some stations had doubled entries with one not working
>
>This was most likely due to changed internal station IDs (see #277).
>
>> no matter which adress I search for, there is no entry, if there isn't a station which us called the same...
>
>Okay, so stations are still found?
>
>> I reinstalled Transportr
>
>Do you know whether you reinstalled the same version of Transportr, or were you using an older version before (if so, which one)?
>
>---
>
>> eDiT: I just figured out this problem also exists with the original homepage www.mvv-muenchen.de // seems not to be an issue woth Transportr!?
>
>Okay, nice to know, this indeed seems to be an upstream issue then. Perhaps you might write them stating that the service on their website somehow degraded. I would guess if they fix it for the website it will most probably also start to work in Transportr again.
>

Ha, it also works in Transportr again. 😃

**Comment by AnnArcyi** [comment]
Nice, now it works again in the app as well. But not with my browser on pc xD
(no need for this just funny)

Thanks for your help!
...and again for this app, it's great!!

**Comment by ialokim** [comment]
Nice, glad to read this!
