### ISSUE TITLE
Quick to home

### ISSUE THREAD

**Issue by DJaeger** [grote/Transportr#71]
There should be an possibility to quickly start routing from current possition at current time to home.

**Comment by grote** [comment]
Thanks for the proposal. I wouldn't know where to place this in the UI, but it could be a home screen widget that directly does the query for trips.

Pull are requests very welcome!

**Comment by DJaeger** [comment]
Or an home (for example an house) button on start sceen (maybe top bar?) directly under the search button.

**Comment by grote** [comment]
I want to keep the start screen as simple and concise as possible and I'm afraid it is not immediately clear what this button does. So I would prefer the home screen widget option. Here's how this could be done: https://developer.android.com/guide/topics/appwidgets/index.html

**Comment by ertaiNL** [comment]
I'll look into this

**Comment by grote** [comment]
Awesome! Let me know if you need some help, for example with a widget icon.

**Comment by grote** [comment]
@ertaiNL Any news?

**Comment by patkan** [comment]
@grote Do you have any proposals for a widget layout? I think it should

* contain some visual indicator that it belongs to Transportr (e.g. the logo)
* the configured target (should be configured once for the widget upon creation on the homescreen)
* the whole widget should be clickable and trigger the Activity

**Comment by patkan** [comment]
And how should the widget handle the Transport-Networks?
Should it upon configuration ask for a network and then set it every time the widget is used? Or should it just try to navigate in the currently active network? I think for the long run the first solution would be nice, but the latter is easier to implement.

**Comment by patkan** [comment]
And one last thing: should the search for the route directly start or should the search-dialog (MainActivity) be just pre-populated with the relevant from and to-data?

**Comment by grote** [comment]
Are you interested in implementing this feature @patkan? If so, here's how I imagine this to be done:
* The widget has the size of a normal app icon and uses a logo in the style of the transportr logo: white house on red background. A placeholder image can be used initially.
* The initial implementation should be as simple as possible, so no configuration at all.
* When the widget is clicked, an intent is send to the `MainActivity` that fills out the form with the current location and the target with the home location.
* If there is no existing home location, the home chooser fragment should be opened
* As soon as the current position has been found and a valid home location has been entered, the search should start automatically.
* The widget should work within the currently selected transport network
* There should be no need to directly use the AmbigousLocationActivity

There is already [intent handling code](https://github.com/grote/Transportr/blob/master/src/de/grobox/liberario/activities/MainActivity.java#L468), but it `findDirections()` would probably need to be extended to support current GPS location and home location for the locations. There are already fake location objects for both elsewhere in the code that could be reused for this.

**Comment by patkan** [comment]
Thank you for the info. Yes, I am interested as I would find this useful :-)
I quite like your idea! I will try to sketch a set of changes and then we can iterate over it.

**Comment by patkan** [comment]
Just as a little sign of life: I am still on it, but I hadn't had the time lately to dig through the code and learn how to get a GPS position.
I will update as soon as I have something useful.

**Comment by grote** [comment]
Great, you are still working on this! :)

Normally, you don't need to get a GPS position manually. The idea is that the intent fills out the form the same way as if the user would have said "from: current position, to: home location". This way, the existing code should handle getting the actual position.

**Comment by patkan** [comment]
I know. But I haven't found yet the piece of code that defines the objects that I need for that :-)

**Comment by grote** [comment]
Check where this gets used: https://github.com/grote/Transportr/blob/b6b59a936b8416554cc16d3b500ced4495fefd4d/src/de/grobox/liberario/adapters/LocationAdapter.java#L60

AndroidStudio lets you do "FindUsages" which is quite useful.

**Comment by grote** [comment]
There was a change in the public transport enabler that requires me to refactor the locations. If you haven't started, I recommend to wait until that is done.

**Comment by grote** [comment]
Ok done in 754327e. In theory, you should now only need to pass a `new WrapLocation(HOME)` to get a home location filled in automatically, but I am not even sure you can already serialize a WrapLocation for the intent extras.

Let me know if you have questions or need help. I can probably save you some time.

**Comment by patkan** [comment]
`WrapLocation`s are at the moment not serializable. Am I done with adding `implements Serializable` to the class?
And then I've got the problem that if I pass a `new WrapLocation(WrapLocation.WrapType.HOME)` into the intent extra than the [receiving code](https://github.com/grote/Transportr/blob/master/src/de/grobox/liberario/fragments/DirectionsFragment.java#L429-L431) cannot cast this into a `Location`.
How can I handle this properly?

**Comment by patkan** [comment]
OK wait, I think I might have a problem with my toolchain :-(

**Comment by grote** [comment]
You can not cast a `WrapLocation` into a `Location`. You need to cast all those to `WrapLocation` and make sure only `WrapLocation`s are ever serialized where this intent action is used.

**Comment by patkan** [comment]
Ah ok, I understand. So I have to refactor every piece of code that "delivers" data to `processIntent()` in the DirectionsFragment, right?

**Comment by grote** [comment]
I hope you don't need to refactor, but just pass a WrapLocation instead of the Location, if available there, yes.

**Comment by joaobarcia** [comment]
I understand the rationale behind the widget option. As an android user whose only widget is the main screen clock, I would also vote for an in-app option. How about an additional option on the [drawer](https://github.com/grote/Transportr/blob/master/art/screenshots/drawer.png)?

**Comment by grote** [comment]
The widget is almost ready (right @patkan? :wink:), but there could be other ways to trigger the same action. The first step would be to think about where in the UI you could put that without making it to crowded and complex.

**Comment by patkan** [comment]
Yep, more or leass ready. I think we should get the minimal functionality working, improvements are then still possible.
I still have to adapt the design a bit (not a big one) and refactor the code to iron out the last problems. I haven't had the time yet unfortunately to do the last one properly :-(

**Comment by grote** [comment]
To all those interested in using the quick home functionality (implemented by @patkan), please [test the latest beta](https://twitter.com/TransportrApp/status/825406969443995648) and give feedback. Thanks!
