### ISSUE TITLE
Hide Via toggle in directions form if not supported

### ISSUE THREAD

**Issue by ialokim** [grote/Transportr#711]
After the first part of https://github.com/schildbach/public-transport-enabler/pull/333 has been merged in, we should use this information for hiding the "Via" toggle for providers that don't support this (mainly Navitia-based ones).

**Comment by ialokim** [comment]
One question that arises while implementing this: Should we care for removing legacy favorite trips with the Via field set and if so, how should we handle these? Some sort of database migration?

![grafik](https://user-images.githubusercontent.com/18088991/98036491-6a84c080-1e1a-11eb-9b70-d33dafca9ece.png)

**Comment by grote** [comment]
I wouldn't bother, but if you have fun doing it... :P
