### ISSUE TITLE
website unreachable

### ISSUE THREAD

**Issue by hennr** [grote/Transportr#714]
Hi folks,

just wanted to let you know that https://transportr.app/ is not reachable for me.

**Comment by grote** [comment]
Thanks for the head-up!

That's what you get for hosting your things yourself. Stuff breaks and you need to fix it yourself as well...

Btw. the website has its own repo here: https://github.com/grote/Transportr-website/

**Comment by hennr** [comment]
Ha, yes, I guess so.

Thanks for the fast fix anyways and for this cool app!

Cheers
