### ISSUE TITLE
[UX] Possibility to add any point on the map into favorites

### ISSUE THREAD

**Issue by vazhnov** [grote/Transportr#717]
Thank you very much for this wonderful application!

Usually I use bicycle and OsmAnd. But when I need to use public transport, I'm trying to find some route by Transportr, I experience difficulties.

**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [ ] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.
* [ ] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**

I think the major problem for me is: I'm trying to search by address/POI name, but Transportr is not searching by them sometimes.

For example, my experience today:

1. I'm in Wrocław and I'm trying to plan my trip
2. I'm at home so GPS not works
3. In the main screen with a map, I pressed red button with arrow
4. I selected source address, home, from favorite points list
5. I'm trying to set destination point by searching "Purkyniego 1", without success: I see only one result with whole street name "Jana Ewangelisty Purkyniego", but not buildings/addresses (now it can find it — probably it was some network glitch or infrastructure problem at that moment)
6. OK, I pressed button "back" and returned to the main screen with a map
7. I found the destination point manually on the map, tap it, see two buttons: "From here" and "Copy" (now I know there are third button, red with arrow, to create route with destination point I need, but it looks exactly like button on the main page with map, so I didn't think it works as I need)
8. I copied coordinates of destination point and press button "back"
9. Application exited
10. I ran Transportr again,
11. In the main screen with a map, I pressed red button with arrow
12. I selected source address, home, from favorite points
13. I pasted coordinates of destination point
14. Nothing happens. Where is a button to start route search?

**Describe the solution you'd like**

I think all *my* problems with Transportr can be fixed by possibility to add any point on the map into Favourites. It can be done in multiple steps:
1. when point selected on the map, add button to add this point into favorites
2. pre-fill point name with address/POI name
3. add any tag for point ("work", "bicycle shop", "computer parts store")
4. add possibility to search by tag from favorite points
5. and to have any favorite points manager would be great

Also:
1. when point selected on the map: "back" button shouldn't close the application, but return it to the main screen or unselect point
2. when point selected on the map, red button with arrow can by a little different with the another one on the main screen

**Describe alternatives you've considered**

\-

**Additional context**

I would happy to pay for this feature, for example, $50 through https://liberapay.com/Transportr for resolving step # 1, "when point selected on the map, add button to add this point into favorites". Or it can be some other UX improvement(s) if it will help me to resolve my problems with Transportr.

**Comment by ialokim** [comment]
Thanks for your ideas and your extensive report.

> I'm trying to search by address/POI name, but Transportr is not searching by them sometimes.

Might be related to #517? However, pasting coordinates might lead to a different behavior. You might open a new issue for that specific bug.

> add any point on the map into Favourites

This is related to #505 and quite a lot of work as currently Home/Work locations are hard-coded in Transportr.

> when point selected on the map: "back" button shouldn't close the application, but return it to the main screen or unselect point

Sounds like a fair point. This might be worth a separate issue too.

> when point selected on the map, red button with arrow can by a little different with the another one on the main screen

Not sure how @grote feels about this. I guess this was a design decision that would be confusing if changed?

**Comment by grote** [comment]
Not sure I understand the issue here. The big red FAB button always opens a direction search and when a location is selected, it used that as the TO location. Not sure one more button would help UX here.

**Comment by vazhnov** [comment]
@grote , I just described my way of using UI, with my mistakes. Probably other users can do the same mistakes, maybe not.
@ialokim , thank you, my request here is not about to have multiple Home/Work locations, but to add points into favorites.

**Comment by ialokim** [comment]
> @ialokim , thank you, my request here is not about to have multiple Home/Work locations, but to add points into favorites.

Do you mean a new favorites feature (e.g. with a separate list view of all favorites etc.) or the existing behavior where stations that you'd already used before are marked with a small favorite star? The latter one might be easier to implement, I guess.

Please have also a look at #459 . Would this solve your problem too?

**Comment by vazhnov** [comment]
I'm about of separate Favorites feature.

So now, as I understand, there are two list of POI in Transportr:
* Home and Work POI
* History POIs

In theory, these lists can be a part of Favorites — with different tags (if Favorites will support tags, then, for example, you can use tags \#Home or \#History) or as different lists (if Favorites will support lists, like in OsmAnd).

I can create a new ticket for Favorite POIs feature request and close this one, because here is too much of my personal experience with Transportr.

**Comment by ialokim** [comment]
Indeed it might be good to list the proposed features (add/remove/edit? favorites, tags, lists) again in a separate issue.

**Comment by grote** [comment]
POI is not the right name here. Internally they are called favorite locations and a POI is just one type of location.

**Comment by vazhnov** [comment]
Divided into separate tasks #718 and #719.
