### ISSUE TITLE
Luxembourg transport information no longer available

### ISSUE THREAD

**Issue by Babibabz** [grote/Transportr#729]
Hi team

**Describe the bug**
I noticed that no more transport information relative to Luxembourg could be shown in the app. No more stop location, bus at each stop, impossible to have a trip in Luxembourg... 
This information was shown correctly a few months ago though.

**To Reproduce**
Simulate a trip from any location in Luxembourg city (maybe even for the whole country of Luxembourg)

**Expected behavior**
The transport information for Luxembourg should appear

**Screenshots**

**Versions (please complete the following information):**
 - **Transportr Version:** 2.0.1
 - **Device:** [OPO
 - **Android Version:** running /e/OS with Android  7.1.2

**Comment by ialokim** [comment]
Thanks for your report! Are you really using Transportr in version 2.0.1? If so, you could check whether the current version 2.1.0 has the same issue.

If not, this sounds like an upstream issue at public-transport-enabler (the library used by Transportr to access different network providers).

**Comment by Babibabz** [comment]
The same issue appear with version 2.1.0.
Is there an option to solve this issue?

**Comment by ialokim** [comment]
This issue has already been reported upstream: https://github.com/schildbach/public-transport-enabler/issues/337

Fixes should be done and discussed on their side, but I'll leave this open as an upstream issue.

**Comment by ialokim** [comment]
As the upstream issue has just been resolved, Luxembourg will be usable in the next Transportr release again.
