### ISSUE TITLE
Lieux en français à Bruxelles

### ISSUE THREAD

**Issue by cabnedor** [grote/Transportr#730]
Des lieux à Bruxelles sont affichés en flamand par exemple: Anderlecht, Erasmus Ziekenhuis.
Je recherche Hôpital Érasme à Anderlecht.
Merci

**Comment by ialokim** [comment]
That's interesting - for some reason results in [Navitia Playground](http://canaltp.github.io/navitia-playground/play.html?request=https%3A%2F%2Fapi.navitia.io%2Fv1%2Fcoverage%2Fbe%2Fplaces%3Fq%3DAnderlecht%2520Hopital%26type%255B%255D%3Dstop_area%26type%255B%255D%3Daddress%26type%255B%255D%3Dpoi%26depth%3D1%26) for this query do not coincide with the results shown in Transportr. We might need to investigate further.

See also https://github.com/schildbach/public-transport-enabler/blob/ab3a278da0d47dce36b624663f8a7be19a219fd6/src/de/schildbach/pte/AbstractNavitiaProvider.java#L852 as reference.

**Comment by ialokim** [comment]
Okay, never mind, we are not using the Navitia datasource, but the Hafas interface: see https://github.com/schildbach/public-transport-enabler/blob/master/src/de/schildbach/pte/SncbProvider.java.

On their website http://www.belgianrail.be/bin/query.exe/en, results do match with Transportr. This is thus an upstream issue which cannot be resolved in Transportr.
