### ISSUE TITLE
Parser Exception

### ISSUE THREAD

**Issue by Atari-Frosch** [grote/Transportr#734]
I tried:

1. Start from Helmholtzstraße Düsseldorf
2. Go to Bilker Kirche Düsseldorf
3. Got this error message:

„de.schildbach.pte.exception.ParserException cannot parse xml <?xml version="1.0" encoding="UTF-8"?><itdRequest version="10.4.11.75" language="de" lengthUnit="METER sessionID=EFAMOBIL11_774311359" client="okhttp/3.12.12" clientIP="127.0.01" serverID=EFAMOBIL11_" virtDir="standard" calcTime=476.316 now=2020-12-19T17:54:18" nowWD="7"><itdTripRequest requestID="1"><itdMessage type=warning" module="BROKER" code="-10015" subType="itp-monomodal">itp</itdMessage><itdPrintConfiguration active="-1" printerDirect="0" layout="" outputFormat="pdf" fontSizeNormal="1" shading="1" commuterFaresOutput="0" fahreUnitOrientation="left" serverAddress="" serverInfo="/><itdAddress name="" street="" place="" addressExt1="" addressExt2=""/><itdOdv type="stop" usage="origin" anyObjFilter="0"><itdOdvPlace state="identified" method="itp"><odvPlaceElem omc="5111000" placeID="6" value="5111000:6" span="0" type="remote" mainPlace="1"stateless="placeID:5111000:6>Düsseldorf</odvPlaceElem><odvPlaceInput></odvPlaceInput></itdOdvPlace><itdOdvName state="identified" method="itp><odtNameElem selected="0" matchQuality="100000 x="6.7870684" y="51.2145937" mapName="WGS84[DD.ddddd]" stopID="20018252" value="20018252:1" isTransferStop="0" stateless="20018252" tariffArea="" tariffAreaName="" tariffLayer1="" tariffLayer2="">Helmholtzstraße</odvNameElem><odvNameInput><itdOdvName></itdOdv> …"

– sorry, there is more, but I have to read this from the screen of my smartphone and type it into this window; if you need more of it, please let me know.

 - **Transportr Version:** 2.1.0
 - **Device:** Nokia 2.2
 - **Android Version:** 10

**Comment by ialokim** [comment]
Thanks for the bug report and your impressive patience to copy everything by hand! :smile: However, this seems to be an upstream issue which has to be fixed in [public-transport-enabler](/schildbach/public-transport-enabler). You should be able to scroll down and see a button for reporting this error directly (and copying the error message automatically) to PTE. If not, you might open a new issue over there manually.

**Comment by Altonss** [comment]
Is this error still happening?

**Comment by Atari-Frosch** [comment]
Nope. Works fine now. :-)

**Comment by Altonss** [comment]
Great to hear, thanks! Then I think we can close the issue :) (I don't have the ability, but maybe @Atari-Frosch you can close it)
