### ISSUE TITLE
UI bug on API level 16

### ISSUE THREAD

**Issue by ialokim** [grote/Transportr#738]
**Screenshot**
![Screenshot_1609011631](https://user-images.githubusercontent.com/18088991/103171915-0c8bbc80-4850-11eb-9e2a-6e4c5619079b.png)

**Versions (please complete the following information):**
 - **Transportr Version:** 2.1.1
 - **Device:** Android Emulator
 - **Android Version:** 4.1

**Comment by grote** [comment]
maybe some constraintlayout regression/behavior change?

**Comment by ialokim** [comment]
Already happens with Transportr Version 2.1.0 and seems to be specific to low API levels (at least >= API 19 it looks as expected).

**Comment by ialokim** [comment]
There are also some other ugly UI issues like missing inset:
![Screenshot_1609083285](https://user-images.githubusercontent.com/18088991/103174333-824c5400-4861-11eb-8acc-350102e9dc4d.png)

I'd prefer to have a deeper look into this after the next release.

**Comment by Altonss** [comment]
Is this bug still happenning?

**Comment by ialokim** [comment]
I would guess so, yes. We didn't change anything in the UI layout. Anyway, supporting all those old Android versions is getting harder over time. Also taking into account that fewer and fewer people actually use those, we might focus on other things.

**Comment by Altonss** [comment]
> I would guess so, yes. We didn't change anything in the UI layout. Anyway, supporting all those old Android versions is getting harder over time. Also taking into account that fewer and fewer people actually use those, we might focus on other things.

Any idea on which is the lowest API level we should target? I know F-Droid now has API 23 as minimum. I think under API level 21 is pretty old (< Android 5.0)... so maybe we could just drop support for these older versions?

**Comment by grote** [comment]
feel free to bump minSdk to 21 (or higher if you want)
