### ISSUE TITLE
About section: Annual license information not up to date (still 2018)

### ISSUE THREAD

**Issue by Echolon** [grote/Transportr#740]
**Describe the bug**

In the About section the recent year still says 2018 instead of, I'd guess, at least 2020.

**To Reproduce**
1. Go to 'Settings/About'

**Screenshots**
I can upload if necessary

**Versions (please complete the following information):**
 - **Transportr Version:** 2.1.1

**Comment by ialokim** [comment]
Good catch, had that on my todo list for 2021 :)
