### ISSUE TITLE
[Feature request] Add support for SwissPass

### ISSUE THREAD

**Issue by julianfairfax** [grote/Transportr#749]
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [ ] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] The feature I want to propose would be useful for the majority of users in Switzerland, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.

**Is your feature request related to a problem? Please describe.**
Transportr can show public transport routes for the SBB network in Switzerland, but you cannot use the app to show your SwissPass to a controller on those routes. To use your SwissPass you'd have to use the closed source SBB Mobile app in addition to Transportr.

**Describe the solution you'd like**
Transportr could add support for this using the SwissPass SDK that the SBB network provides. This would allow you to show your SwissPass to a controller from within the Transportr app, and not have to use the closed source SBB Mobile app.

**Describe alternatives you've considered**
You could use the closed source SBB Mobile app in addition to the Transportr app to show your SwissPass to a controller.

**Additional context**
- [Link to the SwissPass SDK](https://github.com/SchweizerischeBundesbahnen/SwissPassSDK-Android)

**Comment by ialokim** [comment]
Thanks for your suggestion! However, Transportr in general does not include region-specific code and functions as we barely have the time to maintain the functionality available for all regions. Also, I wasn't able to find a proper licence for the SDK, it seems they [just pull a binary blob](https://github.com/SchweizerischeBundesbahnen/SwissPassSDK-Android/blob/master/demoapp/build.gradle#L52) which anyhow would not meet the FLOSS guidelines of this app.

**Comment by julianfairfax** [comment]
> Thanks for your suggestion! However, Transportr in general does not include region-specific code and functions as we barely have the time to maintain the functionality available for all regions. Also, I wasn't able to find a proper licence for the SDK, it seems they [just pull a binary blob](https://github.com/SchweizerischeBundesbahnen/SwissPassSDK-Android/blob/master/demoapp/build.gradle#L52) which anyhow would not meet the FLOSS guidelines of this app.

As you've pointed out it definitely is just a binary blob. I've also done some more detective work and it turns out that the SBB Movile app (and most likely this SDK) has two different method of displaying a QR code: it can display a dynamic string of letters and numbers, or it can display the same static URL as on the physical cards they give you. Because of this, it should be possible for me to just take a screenshot of the second method and then use another app for the actual display of routes (such as Transportr). Thanks for your work on this app and hopefully this information can prove useful to someone!
