### ISSUE TITLE
Migrate to ViewBinding

### ISSUE THREAD

**Issue by ialokim** [grote/Transportr#754]
During the build process, the following message appears:
> Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

It seems the migration is quite straightforward.

**Comment by grote** [comment]
Yeah the only tricky part is that you [need to null the binding in `onDestroyView()` for fragments](https://developer.android.com/topic/libraries/view-binding#fragments) and then handle it possibly being `null`.

**Comment by ialokim** [comment]
Ups, duplicate of #737.
