### ISSUE TITLE
F-Droid failed to build

### ISSUE THREAD

**Issue by linsui** [grote/Transportr#758]
**Describe the bug**
```
A problem occurred evaluating root project 'gradlewitnessakwizgran'.
> Could not find method compile() for arguments [org.gradle.api.internal.artifacts.dependencies.DefaultSelfResolvingDependency_Decorated@2c029fbb] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```
Could you please take a look? Thanks!

**Comment by grote** [comment]
Looks [like this gradle witness fix](https://gitlab.com/fdroid/fdroiddata/-/commit/36727c2b9f14984d5fce05ae605c553ce8045862) isn't working anymore? 

Maybe ask the author of that fix to look into it.

**Comment by linsui** [comment]
Thanks!
