### ISSUE TITLE
Picking on Map Improperly formats Location

### ISSUE THREAD

**Issue by yue-dongchen** [grote/Transportr#761]
**Describe the bug**
This is definitely not PTE's problem. The error message indicates the locations entered are invalid (line 57 of [Location.java](https://github.com/schildbach/public-transport-enabler/blob/master/src/de/schildbach/pte/dto/Location.java)  in PTE checks `place == null || name != null`). Picking a location on the map seems to format the query incorrectly (I don't know how that works).

**To Reproduce**
1. SydneyProvider (NSW)
2. Long press to pick a location
3. Press the red query button, to route from current place (I was near a bus stop) to the location picked
4. Encounter error
5. Tap on the destination address box and select the relevant suggestion, which formats itself differently
6. Journeys appear without error
```
java.lang.RuntimeException: uncategorized problem while processing https://transportnsw.info/web/XML_TRIP_REQUEST2?outputFormat=XML&language=en&stateless=1&coordOutputFormat=WGS84[DD.ddddd]&coordOutputFormatTail=7&sessionID=0&requestID=0&coordListOutputFormat=string&type_origin=stop&name_origin=10143553&type_destination=coord&name_destination=151.1790100%3A-33.8568250%3AWGS84%5BDD.ddddd%5D&itdDate=20210620&itdTime=2044&itdTripDateTimeDepArr=dep&calcNumberOfTrips=6&ptOptionsActive=1&itOptionsActive=1&routeType=LEASTTIME&changeSpeed=normal&includedMeans=checkbox&inclMOT_0=on&inclMOT_14=on&inclMOT_15=on&inclMOT_16=on&inclMOT_0=on&inclMOT_13=on&inclMOT_1=on&inclMOT_2=on&inclMOT_3=on&inclMOT_4=on&inclMOT_5=on&inclMOT_6=on&inclMOT_7=on&inclMOT_9=on&inclMOT_8=on&inclMOT_10=on&trITMOTvalue100=10&locationServerActive=1&useRealtime=1&nextDepsPerLeg=1&inclMOT_11=on&inclMOT_17=on
de.schildbach.pte.AbstractEfaProvider.lambda$queryTrips$8$AbstractEfaProvider(AbstractEfaProvider.java:2097)
de.schildbach.pte.-$$Lambda$AbstractEfaProvider$jCpHTMjRbCiVoDnWKo1dEuT46BU.onSuccessful(Unknown Source:6)
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:281)
Cause: com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
de.schildbach.pte.dto.Location.<init>(Location.java:57)
de.schildbach.pte.dto.Location.<init>(Location.java:68)

```
**Expected behavior**
Journeys appear after pressing the red query button

**Screenshots**
![Incorrect locations](https://i.ibb.co/JqNb6zQ/Screenshot-20210620-212243-Transportr.png)
![Correct format](https://i.ibb.co/R46X5tc/Screenshot-20210620-212401-Transportr.png)
**Versions (please complete the following information):**
 - **Transportr Version:** [2.1.2]
 - **Device:** [Mi 8]
 - **Android Version:** [11]

**Comment by yue-dongchen** [comment]
Perhaps related also to #734 , for which I switched to VRR and entered the locations manually; the reported issue did not appear (however not proof that it's absolutely due to this, since the error message in that issue wasn't complete, and I also haven't verified by emulating my location).

**Comment by ialokim** [comment]
Thanks for reporting this! I was able to reproduce the error and will look into it with some more time.

**Comment by yue-dongchen** [comment]
The logs show,
Wrong format:`2021-07-09 16:16:49.065 5664-5664/de.grobox.liberario.debug I/TripsRepository: To: Location{ADDRESS, -33.7706490/151.1109680, place=Sydney, name=Culloden Road}`
Correct format:`2021-07-09 16:18:22.962 5664-5664/de.grobox.liberario.debug I/TripsRepository: To: Location{ADDRESS, streetID:1500000007::95352007:-1:Culloden Rd:Macquarie Park:Culloden Rd::Culloden Rd: 2122 2113:ANY:DIVA_STREET:4880697:3744253:GDAV:nsw, -33.7700070/151.1100210, place=Macquarie Park, name=Culloden Rd, Macquarie Park}`

In PTE, the `Location` class requires the following five variables. `id` is missing in the wrong format (which is set by placing the map marker). I'm now looking into it. Writing this FYI

```
    public final LocationType type;
    @Nullable
    public final String id;
    @Nullable
    public final Point coord;
    @Nullable
    public final String place;
    @Nullable
    public final String name;
    @Nullable
```

**Comment by yue-dongchen** [comment]
It actually seems like a logical flaw in PTE. It checks that all ids aren't null or empty. With type `COORD`, the id should accept empty.

**Comment by yue-dongchen** [comment]
It's probably something with PTE, since the same format works with MVV.

**Comment by yue-dongchen** [comment]
Related issues
https://github.com/schildbach/public-transport-enabler/issues/252
https://github.com/grote/Transportr/issues/569

**Comment by yue-dongchen** [comment]
It actually seems to be PTE. Öffi also crashes here (SydneyProvider) when using the current location (coordinates).
