### ISSUE TITLE
Removing of tracker "Mapbox" - privacy concern

### ISSUE THREAD

**Issue by nk4044** [grote/Transportr#762]
As mention in your 'README.md', first sentence _"The public transport companion that respects your privacy and your freedom. ..."_ Could you please remove the last current running tracker softwae in your app, see:
https://reports.exodus-privacy.eu.org/en/reports/184216
v2.1.2 tracker: "Mapbox":
https://reports.exodus-privacy.eu.org/en/trackers/171

It was somehow integrated while updating to v2, (in detail from v1.1.9 to v2.0.2) see history:
https://reports.exodus-privacy.eu.org/en/reports/search/de.grobox.liberario

Thanks a lot :-)

**Comment by ialokim** [comment]
We [disabled all telemetry from Mapbox](https://github.com/grote/Transportr/blob/0074a93e10e3a74cf0bd971ed3ce32bf81b3f113/app/src/main/java/de/grobox/transportr/TransportrApplication.kt#L36), but I suppose Exodus can't detect that and just searches for the mere existence of the library in the apk. We are currently working on switching to MapLibre SDK, where Telemetry is completely removed from SDK altogether. See also #668.

**Comment by nk4044** [comment]
Thanks for reply, did another check run with another tool (ClassyShark3xodus), and it says 0 Trackers / 0 Classes :-)

=> closed
