### ISSUE TITLE
Search requires a specific way of entering a stations name to be able to find it

### ISSUE THREAD

**Issue by snubz** [grote/Transportr#763]
**Describe the bug**
I have to enter the name of certain stations in a unique way to be able to find them. Some cannot be found at all, although present as intermediary station in Trips.

**To Reproduce**
1. Open Transportr
2. Select DB in Europe as carrier
3. Search for
    * Yorckstraße
    * Walther-Schreiber-Platz
4. transportr does not deliver any results

**Expected behavior**
Transportr should be able to find both (all) stations

**Versions (please complete the following information):**
 - **Transportr Version:** 2.1.0
 - **Device:** Pixel 4a
 - **Android Version:** 11

**Additional Information
I am able to find Walther-Schreiber-Platz (U), if I start typing u walther. I found no way to find yorckstraße. 
I tried using hyphens or not, upper/lowercase first letter, abbrevate "Straße" by "Str", and adding "U" and/or "S" in front.

**Comment by snubz** [comment]
Allright, it is no issue of the app. If I switch to BVG, everything works finde

**Comment by dontub** [comment]
This is fixed in Public Transport Enabler by https://github.com/schildbach/public-transport-enabler/commit/676dccea011cd097a6e57f12678b09a733713c51

So Transportr just needs to be build with the current state of Public Transport Enabler.

**Comment by ialokim** [comment]
Thanks for your report and for already providing the solution to this! We always update the Public Transport Enabler library shortly before a release, so stay tuned for the next one :)

**Comment by dontub** [comment]
Do you have a plan when to do the next release? Currently the DB provider fails for many queries. A provider that stopped working is a major bug (at least for those using it) which I think should be fixed as soon as possible.

**Comment by ialokim** [comment]
You are right, I was just short of time lately. Now that I have some time, I will try to push things towards a release during this weekend.
