### ISSUE TITLE
Add Israel(2)

### ISSUE THREAD

**Issue by Alex344431** [grote/Transportr#769]
I saw this (https://github.com/grote/Transportr/issues/365) issue, but another one may change something,
In public transport enabler created a pull request that adds Israel from 2020 year to public-transport-enabler:
https://github.com/schildbach/public-transport-enabler/pull/296
Will Israel be added to Transportr?

**Comment by ialokim** [comment]
If the author of the PR (@renrene) or yourself rebase it to current master, open a PR at the [staging repo that Transportr uses internally](https://gitlab.com/opentransitmap/public-transport-enabler) and then prepare a PR for Transportr providing a logo (flag?) and strings in English, then yes, Israel can be finally added to Transportr :)

**Comment by RustyStriker** [comment]
I rebased the original PR to master [(new pr)](https://github.com/schildbach/public-transport-enabler/pull/484), can you elaborate on the rest of the things that needs to be done @ialokim ?

**Comment by nomq1** [comment]
I used [Hungary](https://github.com/grote/Transportr/pull/451/files). example , and added a pull request .
It works locally on my phone , but I could not understand how to update PTE dependency version while maintaining sha verification on gradle witness file .

**Comment by ialokim** [comment]
Israel is unfortunately not served by Navitia anymore, see https://github.com/grote/Transportr/issues/877#issuecomment-1751665629.
