### ISSUE TITLE
Routing issue in Hamburg (GVH)

### ISSUE THREAD

**Issue by kojid0** [grote/Transportr#788]
**Describe the bug**
Sometimes, the routing has issues like the one in this screenshot:

![Screenshot_20211018-103640_1](https://user-images.githubusercontent.com/24477557/137721643-00711c9d-a154-49dd-918c-cafa201e8d63.png)

Coming from U1, the most simple way would be to change at Jungfernstieg to S3 in the direction of Hamburg Neugraben. But Transportr recommends to ride S3 in the direction of Pinneberg until Stadthausbrücke just to change over there and ride back to Jungfernstieg.

**Versions (please complete the following information):**
 - **Transportr Version:** [e.g. 2.1.3]
 - **Device:** [e.g.  Google Pixel 5]
 - **Android Version:** [e.g. 11]

**Comment by ialokim** [comment]
Thanks for your report. Did you try to search for the exact same connection on the official GVH website? Does it produce the same result? As Transportr itself is not calculating the routes, but just retrieving and displaying them form third-parties, I'm afraid we cannot do anything about it on our side.

**Comment by kojid0** [comment]
> Thanks for your report. Did you try to search for the exact same connection on the official GVH website? Does it produce the same result? As Transportr itself is not calculating the routes, but just retrieving and displaying them form third-parties, I'm afraid we cannot do anything about it on our side.

I wasn't able to enter any addresses of Hamburg at https://www.gvh.de/fahrplan/auskunft/. It seems to be for Hannover only. But you are right - not the fault of Transportr.
