### ISSUE TITLE
Improve Performance when Auto-Completing Locations

### ISSUE THREAD

**Issue by kangyu** [grote/Transportr#79]
We are working on a project called PersisDroid (http://www.cudroid.com/PersisDroid/) for detecting potential performance issues. Our tool could find performance degradation caused by improper usage of asynchronous executions.
  We find that in some cases your app may suffer a long processing delay.

Case 1:
  **Related source code**  Class: de.grobox.liberario.adapters.LocationAdapter function: performFiltering.
  **Circumstance**  It may take long to react when the user enters chars swiftly in the AutoCompleteTextView.
  **Problem**  The current implemention of performFiltering may take long to execute. Notice the AutoCompleteTextView processes the inputs and filters the content in a single handler. If the previous filtering procedure is not completed the new filtering procedure would be blocked. For example, if I input 'abc' consequently, the view would process 'a', 'ab' and 'abc' one by one. This may not cause trouble when each word could be processed instantly. But if the process is long outdated processing should be cancelled. 
  **Suggested modification** Design a cancellation mechanism for the Filter. It would be better to cancel the previous processing when new character is input. I would suggest a cancellation mechanism in the while loop of *"suggestLocations"* function. 

Case 2:
  **Related source code** Class: de.grobox.liberario.fragments.DirectionsFragment function: onCreateView line: query_trips.execute();
  **Circumstance** Slow on querying directions multiple times.
  **Problem** The *execute* function of AsyncTask would actually execute the multiple tasks in a sequential manner (after Android 3.0 HoneyComb). That means multiple queries would be queued to be executed. The outdated queries should be cancelled to release the pool resource. 
  **Suggested modification** Design a cancellation mechanism of *AsyncQueryTripsTask* and cancel previous queries when new queries arrive.

**Comment by grote** [comment]
Hi @kangyu!

Thanks for the input. Could you please clarify your suggestions a little bit?

Case 1:
I'm using the [DelayAutoCompleteTextView](https://github.com/grote/Liberario/blob/master/src/de/grobox/liberario/ui/DelayAutoCompleteTextView.java) which already has a cancellation mechanism. Does this not already address your finding?

Case 2:
When querying directions, a progress dialog is shown that prevents people from requesting directions multiple times i sequence. Does this not already address your finding?

**Comment by kangyu** [comment]
Hi @grote Thanks for your reply. 

Case 1:
I have checked your implementation of [DelayAutoCompleteTextView](https://github.com/grote/Liberario/blob/master/src/de/grobox/liberario/ui/DelayAutoCompleteTextView.java). The cancellation works well but with one trouble, it does not cancel tasks that have already started. For the case that a user inputs 'abc', if 'b' is input 750ms after 'a' is input, then the input of 'a' is processed (suggesting location for 'a'). After 'bc' is input, the processing of 'a' will not be cancelled. 

It should be better if the network location suggestion in the performFilter function could be cancelled. 

Case 2:
Personally I think it is not friendly that the progress dialog cannot be cancelled by the *back* key. When the input is not correct, the user has to wait until the search finishes (worse with my poor network state).

For my original question, it should be all right in this version. I reviewed my logs that I found conflicts of the AsyncQueryTask with [AsyncLocationAutoCompleteTask] (https://github.com/grote/Liberario/blob/c12a6bfaa62fca02926501ef7b4fd1d71ed15c7a/src/de/grobox/liberario/LocationAdapter.java) in some old versions. The *AsyncLocationAutoCompleteTask* is still executing for filtering input words when the search button is clicked. The search has to wait until the filtering task finishes. 

The general idea is that multiple AsyncTasks executed via invoking *execute* function are run sequentially. Sometimes this may cause some unintended performance issue.

**Comment by grote** [comment]
Hi @kangyu,
would you consider submitting a pull request making these two enhancements?

**Comment by kangyu** [comment]
@grote 
All right, I will but maybe several days later.

**Comment by grote** [comment]
I noticed that the list of favorite locations is not filtered when typing, but only when locations have been retrieved from the internet. This could probably be improved at the same time.

**Comment by kangyu** [comment]
Noted with thanks.

**Comment by h-2** [comment]
:+1 for faster search results :)
