### ISSUE TITLE
Blank Libraries page in About section

### ISSUE THREAD

**Issue by Altonss** [grote/Transportr#793]
**Describe the bug**
Blank Libraries page in About section

**To Reproduce**
1. Go to 'Hamburger menu'
2. Click on 'About'
3. Click on 'Libraries'

**Expected behavior**
The Libraries tab should display correctly the libraries used and not a blank page (because in that case this page would be useless)

**Screenshots**
![Screenshot_2021-11-08-00-37-59](https://user-images.githubusercontent.com/66519591/140666221-afa0e497-4acd-4860-9ae2-f109dbe3cd5e.png)

**Versions (please complete the following information):**
 - **Transportr Version:** 2.1.3
 - **Device:** Samsung Galaxy Core Prime
 - **Android Version:** 5.0.1

**Comment by Mortein** [comment]
Same for Transportr version 2.1.4

**Comment by Altonss** [comment]
> Same for Transportr version 2.1.4

For me too on 2.1.4 What version of Android are you using @Mortein ?

**Comment by Mortein** [comment]
**Transportr version:** 2.1.4
**Device:** OnePlus 6T
**Android version:** 11

**Comment by Altonss** [comment]
I thought this is only an issue because of my old android version, but seems to be a global issue!

**Comment by ialokim** [comment]
Yes, I can confirm this seems to be some form of regression bug in one of the last releases. Will need to look into it.

**Comment by wallalex0** [comment]
Interestingly, this issue only appears in release builds, I have not seen this issue in debug builds.
