### ISSUE TITLE
Calendar application cannot be found on 2.1.4

### ISSUE THREAD

**Issue by njmdietrich** [grote/Transportr#795]
**Describe the bug**
Transportr is unable to find my installed calendar app (Etar), which makes adding connections to your calendar impossible.
This only applies to 2.1.4; on 2.1.3 and previous versions it works fine.

**To Reproduce**
1. Select any connection in the app
2. Press the calendar icon in the top right corner

**Expected behavior**
Transportr would open my calendar app to create a new event with all the details of the selected connection

**Versions (please complete the following information):**
 - **Transportr Version:** 2.1.4
 - **Device:** Pocophone F1
 - **Android Version:** 11 (LineageOS for MicroG 18.1)

**Comment by Kelvino9** [comment]
I just installed Etar and Simple Calendar from F-Droid and could not reproduce the issue with the latest version of Transportr. The event was successfully exported.

**Comment by njmdietrich** [comment]
I just downloaded Etar from f-droid (the one I had installed is the one that comes by default with lineageos) as well as simple calendar pro. On Transportr 2.1.4, I still get the message that no calendar app is installed if I try to export an event. So it must be something about my android version.

**Comment by ialokim** [comment]
I'm experiencing the same problem here with Android 11 (CalyxOS) with the default calendar app. Until 2.1.3 there was no problem. We will have to investigate this, it might be related to a change in the targetSdkVersion?

**Comment by Dafnik** [comment]
Can also confirm the problem for Google Pixel 4a running Android 12 and using aCalendar.

**Comment by Dabako** [comment]
Can also confirm the Problem for Google Pixel 4a running Graphene OS Android 12, using Etar from F-Droid

If more information is required I am more than happy to provide it.

Transportr version: 2.1.4

**Comment by femto-code** [comment]
+1

**Comment by joeyboon** [comment]
+1 Can also confirm the problem for Google Pixel 4a running Graphene OS Android 12, using Etar from F-Droid

**Comment by rugk** [comment]
I can confirm this bug with Etar and the pre-installed calendar, also based on Etar version, on this system:

Pixel 4
CalyxOS 3.1.0
Android 12 (SQ1A.220105.002)

**Comment by toas-koas** [comment]
I have the same issue
CalyxOS 2.14.0
Android 11
Transportr 2.1.4
Etar Version 11

**Comment by femto-code** [comment]
Any progress on this issue? Project seems dead at the moment...

**Comment by bibnumber** [comment]
Confirm the issue on Android 11 with multiple calendars apps.

**Comment by mdosch** [comment]
@njmdietrich how did you downgrade? It doesn't work for me with fdroid.

**Comment by bibnumber** [comment]
@mdosch make sure to uninstall your current version first. Then scroll all the way down to the foldout menu versions and download a previous versions. Let me know if it works for you.

**Comment by mdosch** [comment]
Ah, so it's uninstalling and reinstalling. I thought there would be a way to downgrade as reinstalling always removes all settings.

**Comment by ialokim** [comment]
see https://developer.android.com/training/package-visibility/use-cases:

> This document presents several common examples of use cases in which an app interacts with other apps. Each section provides guidance on how to declare package visibility of other installed apps, which you need to consider if your app targets Android 11 (API level 30) or higher.
> 
> When your app targets Android 11 or higher and uses an intent to start an activity in another app, the most straightforward approach is to invoke the intent and handle the [ActivityNotFoundException](https://developer.android.com/reference/android/content/ActivityNotFoundException) exception if no app is available.
> 
> If part of your app depends on knowing whether the call to [startActivity()](https://developer.android.com/reference/android/app/Activity#startActivity(android.content.Intent)) can succeed, such as showing a UI, add an element to the [<queries>](https://developer.android.com/guide/topics/manifest/queries-element) element of your app's manifest. Typically, this new element is an <intent> element.

Most probably we should just react to the `ActivityNotFoundException` instead of first checking whether we can locate any calendar app (which we can't if we don't declare it and target API >= 30).
