### ISSUE TITLE
MVV issue with trams in transportr

### ISSUE THREAD

**Issue by ikbuibui** [grote/Transportr#796]
**Describe the bug**
I think Transportr isn't suggesting routes involving trams in Munich.

**To Reproduce**
Set location from - Baldeplatz
Set location to - Olympiapark West

**Expected behavior**
The suggested routes should be the same as the mvv page, but what is shown is just a subset without trams. 
The corresponding search in the mvv is - 
https://efa.mvv-muenchen.de/index.html?itdTime=1818&itdDate=20211124&language=de&name_origin=M%C3%BCnchen%2C%20Baldeplatz&name_destination=M%C3%BCnchen%2C%20Olympiapark%20West&itdTripDateTimeDepArr=dep#trip@origdest

**Versions (please complete the following information):**
 - **Transportr Version:** 2.1.4
 - **Device:** Xiaomi Mi 9T
 - **Android Version:** 11

**Comment by Altonss** [comment]
This is maybe an upstream issue with https://github.com/schildbach/public-transport-enabler ?

**Comment by ialokim** [comment]
@taproot97 Do you remember which network provider you had selected in Transportr when experiencing this issue?
