### ISSUE TITLE
Broken link in Transportr contribute page.

### ISSUE THREAD

**Issue by sivaraam** [grote/Transportr#798]
This is not about an issue in the app but about a broken link in the Transportr website. I couldn't locate the repo for the website. So, I'm opening an issue here. 

In the "Using GTFS" section of the [contribute page](https://transportr.app/contribute/#using-gtfs), there's a line stating that a long list of transportation agencies that provide data to Google:

> There is a long list that you can consult.

The link in the line points to the following:

   https://maps.google.com/landing/transit/cities/index.html

... which seems to redirect to ...

   https://support.google.com/transitpartners/answer/1111471

Does that Google has taken down the list now? Or could it be available in some other location?

**Comment by ialokim** [comment]
Copied to https://github.com/grote/Transportr-website/issues/12
