### ISSUE TITLE
Möchte Limburg/Lahn hinzu fügen

### ISSUE THREAD

**Issue by wolli** [grote/Transportr#802]
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [ ] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [ ] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.
* [ ] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions you've considered. But please limit this ticket to one feature or use-case.

**Additional context**

**Comment by Altonss** [comment]
Und NVV/RMV unter den Netzwerken auswählen funktionniert nicht?

**Comment by ialokim** [comment]
This issue provides no further information apart from the title. For adding new regions, please refer to https://transportr.app/contribute. Also Deutsche Bahn (DB) should include information for Limburg already.

**Comment by wolli** [comment]
Danke Euch,
aber ich fürchte das übersteigt mein IT Können.
LG

**Comment by Altonss** [comment]
Hallo @wolli,
Das Netwerk (z.B. DB) zu ändern geht ganz einfach über die App. Wenn Sie das nicht finden, kann ich Ihnen gerne weiterhelfen!

**Comment by wolli** [comment]
Das ist sehr nett,

Ja ich wollte meinen Wohnort mit DB und RVM vernetzten.

LG
Wolle

**Comment by Altonss** [comment]
Du kann versuchen das RMV oder das DB Netzwerk auszuwählen, und dann wirst du sehen welches von den beiden für dich am Besten funktionniert. Dafür musst du folgende Schritte machen:
- Transportr App öffnen
- Beim ersten Öffnen der App, kannst du das Netzwerk auswählen (die Zone) -> z.B. Europa > Deutschland DB (oder RMV)
- Wenn du diese Auswahl später ändern willst, kann du oben links auf das Hamburger Menu (3 horizontal gestapelte Linien), dann auf das Netzwerk Logo oben links clicken (z.B. DB wenn du DB ausgewählt hattest), und dann kannst du in der Liste nach NVV/RMV schauen und clicken wenn du dieses Netzwerk ausprobieren willst.
- Transportr behählt deine vorher ausgewählten Netzwerke einfach griffbereit, denn wenn du nun wieder auf den Hamburgermenu clickst, wirst du sehen, dass nun DB (oder das vorheriges Netzwerk) in klein ob rechts zu finden ist. Du kannst einfach wieder zu diesem Netzwerk wechseln indem du darauf clickst.

Aber für den Anfang würde ich einfach mit der DB versuchen :)

**Comment by wolli** [comment]
Prima herzlichen Dank,

Versuche ich später.

LG
Wolle
