### ISSUE TITLE
Errore di navigazione

### ISSUE THREAD

**Issue by damiano85** [grote/Transportr#805]
java.lang.IllegalArgumentException: Unhandled error id: no_origin
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1065)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)

Versione Android:
11 (Red Velvet Cake)

Versione Java runtime:
Android Runtime 0.9

Modello dispositivo:
Xiaomi Redmi 9

**Comment by ialokim** [comment]
These kind of bugs should be reported to [PTE](https://github.com/schildbach/public-transport-enabler/) instead, as mentioned in the app. Also, you need to provide the provider (network) you were using.
