### ISSUE TITLE
App not visible on Google Play Store

### ISSUE THREAD

**Issue by newhinton** [grote/Transportr#811]
**Describe the bug**

If a user opens transportr.app and uses the google play store button, the app cannot be found and it shows the search.

Also, searching for Transportr does not show the app. Has it been taken down from google play?

Location: Germany

**Comment by Altonss** [comment]
Indeed I noticed the same thing...

**Comment by nicolasform** [comment]
Same thing from France. I guess it does not depend on the location, the page seems to have vanished completely.
As a workaround, you can use F-Droid to get the app: https://f-droid.org/

**Comment by ialokim** [comment]
This is due to the required privacy statement that is missing for Transportr #604. We would highly welcome any contribution that proposes such a text.

**Comment by Altonss** [comment]
Maybe we could be inspired by https://catima.app/privacy-policy/ or https://www.westnordost.de/streetcomplete/privacy.html
ping @TheLastProject :)

**Comment by TheLastProject** [comment]
Well, Catima's privacy policy is extremely simple as the app works fully offline, I don't think that'll be completely usable for Transportr.

I suppose you might be able to get away with a statement like "When searching for a trip, the entered data (start and end location of trip, desired start or end time of trip, your IP address and the fact you're using Transportr) will be available to the transport provider selected. For more information about how the selected transport provider stores your data, check their privacy policies."

Google's desire to want a privacy policy does kinda... hurt apps like Transportr most as Tranportr can't possibly keep up with whatever every single transport provider does and when they change their policy. I'm kinda worried my sentence may not make Google happy, but it's worth a try maybe?

**Comment by Altonss** [comment]
I think it's worth a try :) Thanks a lot for your help!

**Comment by Altonss** [comment]
I've written a short priacy policy. The inclusion in Google Play might be even more important as the latest version is now unavailable on F-Droid, see latest comments on #668.

**Comment by Altonss** [comment]
@grote Do you think the current privacy policy is enough to try an attempt of submitting to the play store?

**Comment by ialokim** [comment]
We'll see as soon as he's back from holidays :)

**Comment by Altonss** [comment]
> We'll see as soon as he's back from holidays :)

No worries :) Enjoy the holidays!

**Comment by grote** [comment]
Submitted it for review on Google Play now. They say it can take up to 7 days.

**Comment by Altonss** [comment]
> Submitted it for review on Google Play now. They say it can take up to 7 days.

Hope it will work :crossed_fingers:

**Comment by Altonss** [comment]
I just found the app on the play store, am I the only one or is the app really back?

**Comment by grote** [comment]
Looks like the app is indeed back. Thanks @Altonss for the help!
