### ISSUE TITLE
Share button not working

### ISSUE THREAD

**Issue by endim8** [grote/Transportr#818]
**Describe the bug**
the 'Share' button results in a toast saying 'No external map installed :('

**To Reproduce**
0. install a map app compatible with geo intent (eg. organicmaps, osmand)
1. make a point on the map
2. Click on 'share'
3. See error

**Expected behavior**
it should trigger a geo intent 

**Screenshots**
![Screenshot_20220615-192752_Transportr](https://user-images.githubusercontent.com/26939824/173901510-d70fb190-9886-4e6b-82ec-6964a4abdbad.png)

**Versions (please complete the following information):**
 - **Transportr Version:** 2.1.4
 - **Device:** Oneplus 8 Pro
 - **Android Version:** 12

**Comment by ialokim** [comment]
Same problem as #795 and will be fixed with #814.
