### ISSUE TITLE
Sometimes Last Line Icon Gets Cut Off

### ISSUE THREAD

**Issue by dktzde** [grote/Transportr#82]
When I search for a connection I get the following bug with the "little icons" in the trip overview. When I have so many changes of trains that there should be a line break with the icons: sometimes this works and sometimes the second line is missing. I assume that the second line is missing, when the last "train" in the first line is a "walkway". 

Example:
2.7.2015; Network "db"
From: Furth im Wald
To: Offenbach(Ost)
at the second 11:01 connection an icon is missing

![umstiege_liberario](https://cloud.githubusercontent.com/assets/12322609/8424971/647c86fa-1f01-11e5-8c07-e6139f4bf3d2.png)

(When there is a "walkway" on the first line and afterwards a train everything goes right.)
using: 0.6.1
screen resolution: 1280 x 720

**Comment by grote** [comment]
I can't reproduce this with a larger screen resolution, but the trip overview has been rewritten for the upcoming version anyway, so we would need to see if you can reproduce the issue with this version.

**Comment by dktzde** [comment]
I will have a look when the new version is on F-Droid.

**Comment by dktzde** [comment]
What this time is different: The second line icons gets cut off when there would be only one icon on the second line. (I could reproduce this with my first example - also there would be only one icon on the second line)

Second Example:
30.7.2015; Network "db"
From: Siegmund Adam Str 4 in Eschlkam
To: Aachen
at the third 10:25 connection an icon is missing

![overview](https://cloud.githubusercontent.com/assets/12322609/8977436/6ee3f934-3699-11e5-82be-99c8e04bb5a4.jpg)
On the second picture you see that THA9484 is missing:
![detail](https://cloud.githubusercontent.com/assets/12322609/8977437/7288bc3c-3699-11e5-9f0a-1c6dd7b61c96.jpg)

using: 0.6.1
screen resolution: 1280 x 720
