### ISSUE TITLE
Calendar is not installed

### ISSUE THREAD

**Issue by Saturdaynightlife** [grote/Transportr#828]
When trying to save an Entry to my calendar i geht the message 'no calendar installed :-( '. 
But there are several calendar apps installed in my phone likre 'business calendar'. What went wrong? How can I installiert a calendar?

I'd appreciate any hell.

**Comment by ialokim** [comment]
Thanks for reporting! This is actually a duplicate of #795 which has already been addressed. The issue will be fixed in the next version of Transportr.
