### ISSUE TITLE
Provide More Donation Options

### ISSUE THREAD

**Issue by dktzde** [grote/Transportr#83]
Hi grote,
I really like this app and I'm so happy, that there is an oss public transport app, so I would like to invite you for a beer - but I don't use flickr. Is there an other option to send you some money?
For me it would be easy to use either paypal, send you a "snail mail" letter with money, Euro bank transfer or an posteo voucher. Maybe we also could see each other when I will be next time in Berlin - but I don't know if I will be there this year. Which way would you prefer? 
You can contact me under the following mail adress:
grote-temp@posteo.cz
Regards dktzde

**Comment by motatuc** [comment]
I second that. Thank you very much for making this app! It's really useful to me. With version 1.0 from today this app is really a good peace of software. So I'd like to donate, but I don't use flattr.

Keep up the good work!

**Comment by grote** [comment]
What donations options would you like to see? PayPal, Bitcoin?

**Comment by dktzde** [comment]
for me personally paypal would be fine. I thing it's really nice, when there are options which can be used without any additional registration.

**Comment by DJaeger** [comment]
I would prefer options without registration.

**Comment by motatuc** [comment]
+1 without the need for registration.

**Comment by grote** [comment]
So then Bitcoin would be the only option?

**Comment by DJaeger** [comment]
And in addition a simple money transfer, as most people already have a bank account

**Comment by grote** [comment]
I'd be reluctant to publish my bank account information online.

**Comment by dktzde** [comment]
What about having a second bank account, with no money on it, without the possibility to overdraft it.

**Comment by grote** [comment]
Alright, I created a Bitcoin Wallet and an address that can receive donations: ```12JaQp8zfqRb83JfSwVjH4rZWsZnWRPoyG```
If you want to help me test that this actually works, you can donate a small amount to that address. Thanks!

**Comment by DJaeger** [comment]
Have send you 5 Cent as Bitcoin.

**Comment by grote** [comment]
Thanks @DJaeger that seems to have worked! :)

The address will then be the official Bitcoin donation from now on.

I'll close this issue, but will leave it open for further comments.

**Comment by amo13** [comment]
This is exactly the application I was missing from f-droid, and it is awesome! Thanks a lot for your great work on that! Keep on!
Unfortunately, I don't use bitcoin or flattr, but I would absolutely buy you some beer with paypal

**Comment by L1am0** [comment]
Hey guys,

what is about liberapay.org?

Would love to donate you a bit. Your APP is just awesome <3

Best regards Form Berlin,
l1am0

**Comment by grote** [comment]
There's [an existing pledge](https://liberapay.com/on/twitter/TransportrApp) of €0.01 per week on liberapay. When It is at €1 I'll sign up there.

**Comment by rugk** [comment]
Transportr is now on LIberapay! https://liberapay.com/Transportr/

@grote, thanks to [F-Droid integration](https://f-droid.org/de/2018/03/02/liberapay-support.html) you can now even show a donation button in F-Droid.

**Comment by Tonat** [comment]
@grote You can sign up to Liberapay now :)
Please add a logo to [Transportr](https://liberapay.com/Transportr/), since it provides quick recognition when browsing through [Teams](https://liberapay.com/explore/teams) there. :+1:

**Comment by grote** [comment]
@Tonat there's a logo, but your browser's tracking protection doesn't show it, because Liberapay includes it from a remote side. Unfortunately, it is not possible to just upload a logo :(

**Comment by rugk** [comment]
Until some time ago you could include/upload it from/to Libreavatar, which likely tracks less than Twitter, where it is currently included.

**Comment by grote** [comment]
@rugk Thanks for the link! I hope direct upload will be added soon.

**Comment by Echolon** [comment]
I really appriciate your work and new version is very nice and I really wanna support your work. Is it possible to get an IBAN via email or so? I dont have bitcoin and Liberapay is shutting down maybe end of the month...

**Comment by rugk** [comment]
> Liberapay is shutting down maybe end of the month...

They likely/hopefully will not directly shut down, but they will have to stop using Mangopay. Before they do, you still have the chance to donate via Liberapay/via the current system. Just "empty your wallet" afterwards, so you have no money in the wallet anymore.

**Comment by KerstinMaur** [comment]
What is the Flattr link to support you?

**Comment by publicmoneypubliccode** [comment]
Can you send me a private adress so I can send you some money via bank transfer? Don't have bitcoins and don't use liberapay but really like your app.

**Comment by grote** [comment]
> I really appriciate your work and new version is very nice and I really wanna support your work.

Thanks! That's nice to hear after all these complaints about the new UI.

> Is it possible to get an IBAN via email or so?

Yes, you can request an IBAN at t at grobox dot de

> What is the Flattr link to support you?

I used to have Flattr, but they changed completely, so I dropped it. Sorry.

**Comment by aha999** [comment]
Here are some platforms that are often used for donations:
- [OpenCollective](https://opencollective.com/) -- [example](https://opencollective.com/darkreader#sponsor)
- [LiberaPay](https://liberapay.com/) -- [example](https://liberapay.com/k9mail/donate)
- [Github Sponsors](https://github.com/sponsors)
- [PayPal](https://www.paypal.com/)
- [Ko-fi](https://ko-fi.com/)
- [Patreon](https://www.patreon.com/)
- [Flattr](https://flattr.com/)
- [BountySource](https://www.bountysource.com)

Displaying a sponsor button in your repository: [link](https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository) 
A handy list of [donate buttons](https://github.com/aha999/DonateButtons)

**Comment by hxr404** [comment]
Do you plan on accepting Monero?
Bitcoin is not an option for me due to the lack of fungibilty (the risk of unknowingly having "tainted" i.e. illegal bitcoins") and privacy.

**Comment by canisllup** [comment]
Thank for a much needed update, the app is working again. For crypto donations i suggest you consider Nano and Monero, everything else including bitcoin is not suited.
