### ISSUE TITLE
How i can add Greek transport means to this app?

### ISSUE THREAD

**Issue by Ud4ba** [grote/Transportr#830]
How i can add Greek Metro , buses and more ? 
https://telematics.oasa.gr/#main

**Comment by Altonss** [comment]
This needs to be added upstream at https://github.com/schildbach/public-transport-enabler

**Comment by ialokim** [comment]
Please have a look at https://transportr.app/contribute/#Adding-Support-For-More-Regions.
I'm going to close this issue for now, but feel free to comment on this issue in case of further questions or once PTE includes support for this data source.
