### ISSUE TITLE
Map not loading

### ISSUE THREAD

**Issue by siegfried77** [grote/Transportr#831]
**Describe the bug**
The map doesn't load.

**To Reproduce**
1. Click into the "from" field
2. Click "choose place from map" (Ort auf der Karte suchen)
3. See grey rectangles

**Expected behavior**
At 3. a map should be shown.

**Screenshots**
![transportr](https://user-images.githubusercontent.com/114389689/192224985-4040cdf3-010a-485f-9223-1fbc18a87884.png)

**Versions (please complete the following information):**
 - **Transportr Version:** 1.1.9
 - **Device:** Motorola Moto G5
 - **Android Version:** LinneageOS 18 (Android 11)

**Further Comments**
I assume this is an issue with downloading the maps. Logcat shows several entries of the following form:
`09-26 09:48:57.509  9328  9382 W OsmDroid: Problem downloading MapTile: /16/34323/22317 HTTP response: Forbidden`
`09-26 09:48:57.513  9328  9381 W OsmDroid: Problem downloading MapTile: /16/34323/22316 HTTP response: Forbidden`
According to [this issue on OsmDroid](https://github.com/osmdroid/osmdroid/issues/366) the cause may be that the User Agent is set incorrectly. Unfortunately, I do not know how to resolve this.

The issue occurs with all transportation networks that I have tried so far.

**Comment by Altonss** [comment]
This is an expected issue as the latest versions of Transportr have been removed from F-Droid and the remaining version is outdated. See issue #826 
I think this issue can be closed. If you want an up to date version, you can look at the github releases apk or download it from the Google Playstore.

**Comment by siegfried77** [comment]
Thanks, using an up to date version solved my issue :)

I'd be happy if you could provide an up to date version via F-Droid once the upstream dependency on closed source software is fixed. :)

**Comment by Altonss** [comment]
> I'd be happy if you could provide an up to date version via F-Droid once the upstream dependency on closed source software is fixed. :)

I'm not a core developer of Transportr, but I'm pretty sure that as soon as the issue is solved, the F-Droid version will be updated again :)
