### ISSUE TITLE
XMLParseError when trying to find a route on VVO

### ISSUE THREAD

**Issue by FriederHannenheim** [grote/Transportr#832]
Germany - VVO returns XMLParseerror when trying to find departures or a route. 

`de.schildbach.pte.exception.ParserException: cannot parse xml: <?xml version="1.0" encoding="UTF-8"?><itdRequest version="10.5.15.43" language="de" lengthUnit="METER" sessionID="3473781406" client="okhttp/3.12.13" clientIP="192.168.150.10" serverID="efaproxy.fahrinfo.uptrade.de" virtDir="standard" calcTime="1208.756" now="2022-10-02T14:46:14" nowWD="1">  <itdTripRequest requestID="1">    <itdMessage type="warning" module="BROKER" code="-10015" subType="itp-monomodal">itp</itdMessage>    <itdPrintConfiguration active="-1" printerDirect="0" layout="" outputFormat="pdf" fontSizeNormal="1" shading="1" commuterFaresOutput="0" fareUnitOrientation="left" serverAddress="" serverInfo=""/>    <itdAddress name="" street="" place="" addressExt1="" addressExt2=""/>    <itdOdv type="coord" usage="origin" anyObjFilter="0" buildNiveau="0">      <itdOdvPlace state="identified">        <odvPlaceElem omc="14612000" placeID="1500000023" value="14612000:1500000023" span="0" type="remote" mainPlace="0" stateless="placeID:14612000:1500000023">Dresden</odvPlaceElem>        <odvPlaceInput></odvPlaceInput>      </itdOdvPlace>      <itdOdvName state="identified" method="auto">        <odvNameElem selected="1" matchQuality="100000" x="13.7292849" y="51.0869579" mapName="WGS84[DD.ddddd]" value="13.7292849:51.0869579:WGS84[DD.ddddd]:Trachenberger Straße 43" stateless="coord:13.7292849:51.0869579:WGS84[DD.ddddd]:Trachenberger Straße 43">Trachenberger Straße 43</odvNameElem>        <odvNameInput>13.7292790:51.0869370:WGS84[DD.ddddd]</odvNameInput>      </itdOdvName>      <itdOdvAssignedStops select="0">        <itdOdvAssignedStop stopID="33000250" x="13.7293567" y="51.0869917" mapName="WGS84[DD.ddddd]" value="33000250:Betriebshof Trachenberge" place="Dresden" nameWithPlace="Dresden Betriebshof Trachenberge" distance="7" distanceTime="0" isTransferStop="0" vm="100" gid="de:14612:250">Betriebshof Trachenberge</itdOdvAssignedStop>        <itdOdvAssignedStop stopID="33000249" x="13.7281620" y="51.0852199" mapName="WGS84[DD.ddddd]" value="33000249:Trachenberger Platz" place="Dresden" nameWithPlace="Dresden Trachenberger Platz" distance="211" distanceTime="1" isTransferStop="0" vm="100" gid="de:14612:249">Trachenberger Platz</itdOdvAssignedStop>        <itdOdvAssignedStop stopID="33000595" x="13.7311713" y="51.0888989" mapName="WGS84[DD.ddddd]" value="33000595:Maxim-Gorki-Straße" place="Dresden" nameWithPlace="Dresden Maxim-Gorki-Straße" distance="285" distanceTime="2" isTransferStop="0" vm="100" gid="de:14612:595">Maxim-Gorki-Straße</itdOdvAssignedStop>        <itdOdvAssignedStop stopID="33000521" x="13.7314408" y="51.0907439" mapName="WGS84[DD.ddddd]" value="33000521:Döbelner Straße" place="Dresden" nameWithPlace="Dresden Döbelner Straße" distance="462" distanceTime="3" isTransferStop="0" vm="100" gid="de:14612:521">Döbelner Straße</itdOdvAssignedStop>        <itdOdvAssignedStop stopID="33000593" x="13.7236255" y="51.0845653" mapName="WGS84[DD.ddddd]" value="33000593:S-Bahnhof Pieschen" place="Dresden" nameWithPlace="Dresden S-Bahnhof Pieschen" distance="573" distanceTime="4" isTransferStop="0" vm="100" gid="de:14612:593">S-Bahnhof Pieschen</itdOdvAssignedStop>        <itdOdvAssignedStop stopID="33000248" x="13.7301472" y="51.0824435" mapName="WGS84[DD.ddddd]" value="33000248:Zeithainer Straße" place="Dresden" nameWithPlace="Dresden Zeithainer Straße" distance="573" distanceTime="4" isTransferStop="0" vm="100" gid="de:14612:248">Zeithainer Straße</itdOdvAssignedStop>        <itdOdvAssignedStop stopID="33000251" x="13.7237512" y="51.0891302" mapName="WGS84[DD.ddddd]" value="33000251:Hubertusplatz" place="Dresden" nameWithPlace="Dresden Hubertusplatz" distance="582" distanceTime="4" isTransferStop="0" vm="100" gid="de:14612:251">Hubertusplatz</itdOdvAssignedStop>        <itdOdvAssignedStop stopID="33000596" x="13.7363636" y="51.0877196" mapName="WGS84[DD.ddddd]" value="33000596:Sankt-Pauli-Friedhof" place="Dresden" nameWithPlace="Dresden Sankt-Pauli-Friedhof" distance="668" distanceTime="4" isTransferStop="0" vm="100" gid="de:14612:596">Sankt-Pauli-Friedhof</itdOdvAssignedStop>        <itdOdvAssignedStop stopID="33000590" x="13.7220894" y="51.0868394" mapName="WGS84[DD.ddddd]" value="33000590:Markusfriedhof" place="Dresden" nameWithPlace="Dresden Markusfriedhof" distance="755" distanceTime="5" isTransferStop="0" vm="100" gid="de:14612:590">Markusfriedhof</itdOdvAssignedStop>        <itdOdvAssignedStop stopID="33000647" x="13.7329859" y="51.0813656" mapName="WGS84[DD.ddddd]" value="33000647:Eschebachstraße" place="Dresden" nameWithPlace="Dresden Eschebachstraße" distance="880" distanceTime="6" isTransferStop="0" vm="100" gid="de:14612:647">Eschebachstraße</itdOdvAssignedStop>      </itdOdvAssignedStops>    </itdOdv>    <itdOdv type="coord" usage="destination" anyObjFilter="0" buildNiveau="0">      <itdOdvPlace state="identified">        <odvPlaceElem omc="14612000" placeID="200000079" value="14612000:200000079" span="0" type="remote" mainPlace="0" stateless="placeID:14612000:200000079">Dresden</odvPlaceElem>        <odvPlaceInput></odvPlaceInput>      </itdOdvPlace>      <itdOdvName state="identified" method="auto">        <odvNameElem selected="1" matchQuality="100000" x="13.7454456" y="51.0624791" mapName="WGS84[DD.ddddd]" value="13.7454456:51.0624791:WGS84[DD.ddddd]:Königstraße 31" stateless="coord:13.7454456:51.0624791:WGS84[DD.ddddd]:Königstraße 31">Königstraße 31</odvNameElem>        <odvNameInput>13.7454630:51.0624820:WGS84[DD.ddddd]</odvNameInput>      </itdOdvName>      <itdOdvAssignedStops select="0">        <itdOdvAssignedStop stopID="33000013" x="13.7449694" y="51.0628235" mapName="WGS84[DD.ddddd]" value="33000013:Albertplatz" place="Dresden" nameWithPlace="Dresden Albertplatz" distance="62" distanceTime="0" isTransferStop="0" vm="100" gid="de:14612:13">Albertplatz</itdOdvAssignedStop>        <itdOdvAssignedStop stopID="33000016" x="13.7417714" y="51.0646131" mapName="WGS84[DD.ddddd]" value="33000016:Bahnhof Neustadt" place="Dresden" nameWithPlace="Dresden Bahnhof Neustadt" distance="430" distanceTime="3" isTransferStop="0" vm="100" gid="de:14612:16">Bahnhof Neustadt</itdOdvAssignedStop>        <itdOdvAssignedStop stopID="33000018" x="13.7392921" y="51.0601361" mapName="WGS84[DD.ddddd]" value="33000018:Palaisplatz" place="Dresden" nameWithPlace="Dresden Palaisplatz" distance="515" distanceTime="3" isTransferStop="0" vm="100" gid="de:14612:18">Palaisplatz</itdOdvAssignedStop>        <itdOdvAssignedStop stopID="33000012" x="13.7519494" y="51.0626033" mapName="WGS84[DD.ddddd]" value="33000012:Bautzner Straße / Rothenburger Straße" place="Dresden" nameWithPlace="Dresden Bautzner Straße / Rothenburger Straße" distance="551" distanceTime="4" isTransferStop="0" vm="100" gid="de:14612:12">Bautzner Straße / Rothenburger Straße</itdOdvAssignedStop>        <itdOdvAssignedStop stopID="33000014" x="13.7458857" y="51.0578042" mapName="WGS84[DD.ddddd]" value="33000014:Carolaplatz" place="Dresden" nameWithPlace="Dresden Carolaplatz" distance="550" distanceTime="4" isTransferStop="0" vm="100" gid="de:14612:14">Carolaplatz</itdOdvAssignedStop>        <itdOdvAssignedStop stopID="33000017" x="13.7375494" y="51.0634840" mapName="WGS84[DD.ddddd]" value="33000017:Anton-/Leipziger Straße" place="Dresden" nameWithPlace="Dresden Anton-/Leipziger Straße" distance="628" distanceTime="4" isTransferStop="0" vm="100" gid="de:14612:17">Anton-/Leipziger Straße</itdOdvAssignedStop>        <itdOdvAssignedStop stopID="33000261" x="13.7475566" y="51.0676785" mapName="WGS84[DD.ddddd]" value="33000261:Louisenstraße" place="Dresden" nameWithPlace="Dresden Louisenstraße" distance="666" distanceTime="5" isTransferStop="0" vm="100" gid="de:14612:261">Louisenstraße</itdOdvAssignedStop>        <itdOdvAssignedStop stopID="33000011" x="13.7519583" y="51.0592609" mapName="WGS84[DD.ddddd]" value="33000011:Rosa-Luxemburg-Platz" place="Dresden" nameWithPlace="Dresden Rosa-Luxemburg-Platz" distance="676" distanceTime="5" isTransferStop="0" vm="100" gid="de:14612:11">Rosa-Luxemburg-Platz</itdOdvAssignedStop>        <itdOdvAssignedStop stopID="33000019" x="13.7410169" y="51.0573921" mapName="WGS84
de.schildbach.pte.AbstractEfaProvider.lambda$queryTrips$8(AbstractEfaProvider.java:2105)
de.schildbach.pte.AbstractEfaProvider.lambda$queryTrips$8$AbstractEfaProvider(Unknown Source:0)
de.schildbach.pte.-$$Lambda$AbstractEfaProvider$5eRue_1lU86jlgZKDWwyxAlX2bA.onSuccessful(Unknown Source:6)
Cause: com.android.org.kxml2.io.KXmlParser.require(KXmlParser.java:2067)
de.schildbach.pte.util.XmlPullUtil.exit(XmlPullUtil.java:83)
de.schildbach.pte.AbstractEfaProvider.processItdOdv(AbstractEfaProvider.java:701)

If you want to report this error, please report it to public-transport-enabler directly.`

**Comment by Altonss** [comment]
> If you want to report this error, please report it to public-transport-enabler directly.`

As written at the end of the log, you should probably report this issue to public-transport-enabler directly :)
What version of Transportr are you using?

**Comment by IzzySoft** [comment]
I just got this from a user (click to enlarge):

[<img src="https://user-images.githubusercontent.com/6781438/193553799-ccb55f69-1660-43ae-91ec-5a2cc502790d.png" width="250">](https://user-images.githubusercontent.com/6781438/193553799-ccb55f69-1660-43ae-91ec-5a2cc502790d.png)

Which on a quick glance looks like the same error. As Frieder did not yet reply, I though I add it here.Version used was the latest Transportr, i.e. 2.1.4, installed from F-Droid (before it was disabled there). User lives in Dresden, too, so chances are the same provider was used.

**Comment by ialokim** [comment]
You should be able to scroll down iirc (if not, that'd be another issue).

Upstream issue: https://github.com/schildbach/public-transport-enabler/issues/490

**Comment by FriederHannenheim** [comment]
I'm able to scroll down but the last few lines are cut off

**Comment by dasdirksche** [comment]
> I'm able to scroll down but the last few lines are cut off

Same here

**Comment by slot21** [comment]
I use release 2.1.5 and VVO unfortunately does not work for me at all. Compare [https://github.com/grote/Transportr/issues/843#issuecomment-1698060785](url)
