### ISSUE TITLE
Show Walkingroute if it's shorter than with public transport

### ISSUE THREAD

**Issue by Thorgrimson** [grote/Transportr#836]
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [x] Maybe I can help myself to get this feature implemented or know someone who wants to do it.

I would love to have feature that shows me a walkingroute if its shorter than the bus/train route. I saw this #752 but for me there is never a walkingroute shown. So is this a feature that has to be implemented in my region? (Germany)

**Comment by ialokim** [comment]
Transportr doesn't calculate routes on its own, but instead relies on the results returned by the official API (in your case probably Deutsche Bahn). So there is unfortunately nothing we can do about the result on our end.
