### ISSUE TITLE
Remove Regions: Ontario (ca-on) and British Columbia (ca-bc)

### ISSUE THREAD

**Issue by aschaap** [grote/Transportr#838]
Sadly, low usage led Navitia to decommission coverage for these regions, and they do not want to restore it.[1] 

[1]: https://groups.google.com/g/navitia/c/EAz8RFCUElQ/m/OcZOZSDVAgAJ

**Comment by brandondasilva** [comment]
I was wondering why this kept failing. What a shame.

**Comment by Altonss** [comment]
It seems that Québec is also affected :/

**Comment by omentic** [comment]
Are there alternative backends for these regions?

**Comment by ialokim** [comment]
Here's a list of all navitia-based regions which are no longer served: https://github.com/grote/Transportr/issues/877#issuecomment-1751665629

Follow-up of this issue over there.
