### ISSUE TITLE
New Release 2.1.5

### ISSUE THREAD

**Issue by 1Maxnet1** [grote/Transportr#839]
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [X] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [X] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [X] I can help myself to get this feature implemented or know someone who wants to do it.
* [X] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**
With the current Release the issue with the app not finding a calendar application still exists, although it was fixed in July.

**Describe the solution you'd like**
A new minor Release (2.1.5) could include the two fixes, that were available in the master branch for quite some time.

**Describe alternatives you've considered**
I considered to build the app myself and install it, but this wouldn't solve the problem for anyone else.

**Additional context**
-

**Comment by PanderMusubi** [comment]
See also https://gitlab.com/fdroid/fdroiddata/-/issues/2910

**Comment by Altonss** [comment]
Effort to publish a new 2.1.5 release is currently being discussed here: https://github.com/grote/Transportr/issues/852
For now we mainly aim to publish a new version containing the fixes on the current main branch. Efforts for F-Droid publication will probably happen next :)

**Comment by grrrrr** [comment]
Would it be worth inclusion of Transportr into IzzyOnFroid until such time as f-droid builds are working again?

https://apt.izzysoft.de/fdroid/index/info

**Comment by ialokim** [comment]
> Would it be worth inclusion of Transportr into IzzyOnFroid until such time as f-droid builds are working again?
> 
> https://apt.izzysoft.de/fdroid/index/info

It already is available there.

**Comment by 1Maxnet1** [comment]
As the new Release is out, the issue imho can be considered to be resolved :) Thanks a lot!

**Comment by 1Maxnet1** [comment]
> I did not close the other related issues to this new release, was waiting for the release to go out of beta ;)

As I couldn't see any indicator, that it is still in beta here : https://github.com/grote/Transportr/releases/tag/2.1.5, I supposed it was already released.
