### ISSUE TITLE
Allow "by bike" to go from the start address to the first station

### ISSUE THREAD

**Issue by dktzde** [grote/Transportr#84]
Hi, at http://reiseauskunft.bahn.de it is possible to change the "Route to first stop/station" from "on foot" to "by bike". It would be really fine if there is a way to integrate this in Liberario. 
(The option is only shown, when I plan a rout witch starts at an address.)

**Comment by grote** [comment]
public-transport enabler [supports a `BIKE` option](https://github.com/schildbach/public-transport-enabler/blob/548528423417ab911b81f455813c9e591c9e8124/enabler/src/de/schildbach/pte/NetworkProvider.java#L68) that would just need to get passed to the [trip search](https://github.com/schildbach/public-transport-enabler/blob/548528423417ab911b81f455813c9e591c9e8124/enabler/src/de/schildbach/pte/NetworkProvider.java#L156). Great ticket for beginners!

We would just need to think about the UI part.

**Comment by grote** [comment]
This option is actually just for when you want to bring a bike on the train. In this case, the APIs don't support it.
