### ISSUE TITLE
App no longer working in Belgium

### ISSUE THREAD

**Issue by thebluetrains** [grote/Transportr#840]
**Describe the bug**
Searching the map no longer works in Belgium, and attempting to find directions between favorites results in an error message

**To Reproduce**
1. Setttings > Network > Select Belgium
2. Try typing anything in the search bar, eg Brussels-South, it gives no result

**Versions (please complete the following information):**
 - **Transportr Version:** 2.1.4
 - **Device:** Samsung Galaxy A10
 - **Android Version:** 11

**Comment by Zwelf** [comment]
the error when I attempt to use previous route:

SNCB: java.lang.RuntimeException: CLIENTVERSION

### Query
- NetworkId: `SNCB`
- From: `Location{STATION, 240016, 50.8356440/4.3312010, name=ELOY [MIVB], products=[BUS]}`
- Via: `null`
- To: `Location{STATION, 239996, 50.8139260/4.3849470, name=ULB [MIVB], products=[TRAM, BUS]}`
- Date: `Sun Jan 01 13:58:01 GMT+01:00 2023`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `FAST`

### Error
```
java.lang.RuntimeException: CLIENTVERSION 
de.schildbach.pte.AbstractHafasClientInterfaceProvider.jsonTripSearch(AbstractHafasClientInterfaceProvider.java:590)
de.schildbach.pte.AbstractHafasClientInterfaceProvider.queryTrips(AbstractHafasClientInterfaceProvider.java:214)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
```

**Comment by hobbes** [comment]
SNCB changed their API, upstream is aware, but the new API seems to be somewhat obscured and limited: https://github.com/schildbach/public-transport-enabler/issues/502

**Comment by Marechan0** [comment]
I have been using the app for Belgium by setting the region to Europe for the past year, without any issue, if anyone wants a workaround. (I don't know if this applies to other unsupported regions)

**Comment by ialokim** [comment]
Belgium has been disabled in Transportr with 7c13728fd454a550902549ba9c56386ef827b90c and removed from PTE altogether as there is no chance for it to become usable again: https://github.com/schildbach/public-transport-enabler/issues/502#issuecomment-1859318040

Going to close this issue until some other data source for Belgium has been identified upstream.
