### ISSUE TITLE
App no longer work in Germany`s Transport Network "VRS"

### ISSUE THREAD

**Issue by ping4711** [grote/Transportr#841]
The search for a current connection appears to the following error message:

Unable to resolve host "android.vrsinfo.de": No address associated with hostname
java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
java.net.InetAddress.getAllByName(InetAddress.java:1152)
Cause: libcore.io.Linux.android_getaddrinfo(Native Method)
libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:202)

--> no DNS resolution of "android.vrsinfo.de".

in other transport networks the app works!

To Reproduce
    Setttings > Network > Select Germany > VRS
    Search a connection

Versions:
    Transportr Version: 7.0.4
    Device: BQ Aquarius X pro
    Android Version: 11

**Comment by bbastin** [comment]
This has been resolved in a recent PR in the PTE library, see schildbach/public-transport-enabler#509. Updating PTE should resolve it for Transportr.

**Comment by ping4711** [comment]
Thanks for the tip (:-)
