### ISSUE TITLE
VMS removed / merged into VVO

### ISSUE THREAD

**Issue by slowdive-** [grote/Transportr#843]
**Describe the bug**
Transportr still shows VMS (Verkehrsverbund Mittelsachsen) as region, I think the API for this region does not exist anymore. Öffi merged this into VVO:
https://gitlab.com/oeffi/oeffi/-/commit/b10f240ea5824d5edc1dbaea58828baf18fb630d

Trying to plan routes with this region will result in `UnexpectedRedirectException`.

**To Reproduce**
1. Choose VMS as region
2. Stations autocomplete does not work anymore
3. Routes with saved stations will result in `UnexpectedRedirectException`

**Expected behavior**
Probably should be merged into VVO if VMS API is non-existing.

**Versions (please complete the following information):**
 - **Transportr Version:** 2.1.4
 - **Device:** Xiaomi Mi A1
 - **Android Version:** 10

**Comment by Altonss** [comment]
Are you sure you are on v. 2.1.4? Because the version currently available on F-Droid is very outdated (v. 1.1.9)

**Comment by slowdive-** [comment]
I am on 2.1.4. Although you are right, F-Droid is listing this as installed app but is also showing me 1.1.9 as recommended version. Maybe I installed the APK manually. I changed the description.

**Comment by albirs** [comment]
VVO does not work for me at all ... 
my be for the change in the API?
https://gitlab.com/oeffi/oeffi/-/commit/6696c8f293dd5c268775ae1c80eee0a3f0e84e86
i'm on 2.1.4

**Comment by Altonss** [comment]
This issue could be solved as part of the next 2.1.5 release with an updated PTE version :) (but disclaimer, the next release might take some time...)

**Comment by slot21** [comment]
I use release 2.1.5 and unfortunately still have the problem described above.

**Comment by slot21** [comment]
I use release 2.1.5 and VVO unfortunately does not work for me at all.

**Comment by ialokim** [comment]
VMS has already been removed in version 2.1.5: https://github.com/grote/Transportr/commit/6b05ca28ebcd99b8864f67c2b3da1667575a3846

VVO will be fixed in the next release.
