### ISSUE TITLE
Calendar is not installed

### ISSUE THREAD

**Issue by Fuzzybear2** [grote/Transportr#846]
I tried to save my  connection in my calendar. Then I get error message "No Calendar is installed"..

Android standard calendar is deactivated. I am using simple calendar instead. It should work nevertheless, shouldnt it?

Transporter 2.1.4, Android 11

**Comment by Altonss** [comment]
This issue is a duplicate of https://github.com/grote/Transportr/issues/795, please search for already existing issues next time :)
The issue has been fixed, but the fix will only be available in the next version...
