### ISSUE TITLE
Search: Date reset on time change

### ISSUE THREAD

**Issue by petrarca-arezzo** [grote/Transportr#848]
If the date is changed in the search and afterwards the daytime is changed, the date is reset to the current date. Expectation is to keep the date as selected.

1. Go to search, change the date to something in the future
2. Click on '+15' to change the daytime
3. The date is reset to the current date

**Expected behavior**
The date should stay as selected initially when the daytime is changed.

**Versions (please complete the following information):**
 - **Transportr Version: 1.1.9 (F-Droid)
 - **Device: ShiftPhone 5me
 - **Android Version: 8.1

**Comment by Altonss** [comment]
> **Transportr Version: 1.1.9 (F-Droid)

This issue might be due to this version being outdated (sadly the version on F-Droid is currently still outdated...).
Maybe you could try the version available on PlayStore or as an apk here on Github?

**Comment by Altonss** [comment]
This issue is related to an old version (that is sadly currently the only one available on F-Droid) and therefor can be closed.
