### ISSUE TITLE
No maps

### ISSUE THREAD

**Issue by mgw2013** [grote/Transportr#862]
**Describe the bug**
App doesn't show any map despite OSM and here maps locally stored in device.
Missing settings dialog to point Transportr to local storage location of maps.

**To Reproduce**
1. Go to any connection e. g. bus 
2. Click on map icon to show stations and track
3. No map in background despite track being shown

**Expected behavior

Locally stored maps should be used. 
Settings dialog to point Transporter to locally stored map location on device.
Latest update in F-Droid from 2017.

**Screenshots**

**Versions (please complete the following information):**
 - **Transportr Version:** 1.1.9 from F-Droid
 - **Device:** mido 
 - **Android Version:** 13
 - note: no playstore; no play services from G*
 - online maps are working

**Comment by Altonss** [comment]
This is due to F-Droid currently having a vert outdated version.
If you want a newer version, you can use the apk from Github or download Transportr from the PlayStore.
We are trying to solve this issue #826
