### ISSUE TITLE
NVV/RMV: wrong stop position

### ISSUE THREAD

**Issue by mgw2013** [grote/Transportr#864]
The inital stop is shown somewhere else (bus storage area, I presume). First station (start position of route) not shown. Might be a data source issue...?

_Originally posted by @mgw2013 in https://github.com/grote/Transportr/discussions/854#discussioncomment-6028887_

**Comment by mgw2013** [comment]
Transportr 2.1.4 from github on A13
Network NVV/RMV - bus line 275 starting in Wiesbaden
Issue: first stop missing/wrong. Position shown is a rail track in main rail station - see screenshot. Position should be @ bus stop outside station.
![Screenshot_20230529-152523_Transportr](https://github.com/grote/Transportr/assets/5862935/d81a238c-6a53-4480-b2cb-1851ce6a48a9)

**Comment by Altonss** [comment]
Thanks! It seems to me, that this is unfortunately an issue related to upstream data (unrelated to Transportr)...

**Comment by mgw2013** [comment]
Yup. Tested several lines - all have the same issue!

**Comment by Altonss** [comment]
This issue is even available on the official trip planner : see https://www.nvv.de/fahrplanauskunft.
So I'm afraid it's something we won't be able to fix :(

**Comment by Altonss** [comment]
By the way, https://www.rmv.de/auskunft has the same issue
