### ISSUE TITLE
Find an alternative for lost

### ISSUE THREAD

**Issue by pt2121** [grote/Transportr#870]
[lost](https://github.com/lostzen/lost) is deprecated. We should start looking for other options or solutions.
Let's find a library that is still maintained.

**Comment by ialokim** [comment]
With #880 I actually don't use any third-party library anymore, but use Android's location information directly. Would be interesting to have more real-world tests if this is reliable (it has been for me).

**Comment by ialokim** [comment]
Several users reported the GPS working well with #880, so I think we don't need to further consider a replacement for lost.
