### ISSUE TITLE
Adding back support for broken regions

### ISSUE THREAD

**Issue by omentic** [grote/Transportr#876]
A number of regions provided by the app are broken: most notably for me all the Canadian ones. Many others that I have tested appear broken too: ex. Belgium. I thought this issue could serve to collect the currently broken locations so they might be fixed. 

What needs to be done to fix these regions? I see this app relies on https://github.com/schildbach/public-transport-enabler: is there anything else that needs to happen in this repository?

Supercedes #838 and #840, I suppose.

**Comment by julianfairfax** [comment]
There is also #768

**Comment by ialokim** [comment]
Unfortunately we had to remove all Navitia-based providers (including the Canadian ones) since Navitia is no longer serving them. More info on this in #877.

Going to close this one in favor of issues tracking the status for individual regions.
