### ISSUE TITLE
Remove broken Navitia endpoints

### ISSUE THREAD

**Issue by ialokim** [grote/Transportr#877]
Unfortunately, Navitia removed several regions from their servers. We should remove them from Transportr too.

1. check all endpoints that are currently served by Navitia (inheriting the `NavitiaProvider.java` in PTE)
2. list them here in the issue
3. remove the dis-functional ones in a PR

**Comment by ialokim** [comment]
Here's a list of all providers based on Navitia from PTE, marked with if they are still served by navitia.io. The list was recompiled from the PTE sources and compared to the response returned by https://api.navitia.io/v1/coverage (valid API token needed).

| AbstractNavitiaProvider | coverage | still working | 
| --- | --- | --- |
| `AustraliaProvider` | `au` | :white_check_mark: |
| `BrFloripaProvider` | `br-floripa` | :x: |
| `BrazilProvider` | `br` | :x: |
| `BritishColumbiaProvider` | `ca-bc` | :x: |
| `CaliforniaProvider` | `us-ca` | :x: |
| `CostaRicaProvider` | `-¹` | :x: |
| `CzechRepublicProvider` | `cz` | :x: |
| `FinlandProvider` | `fi` | :x: |
| `FranceNorthEastProvider` | `fr-ne` | :white_check_mark: |
| `FranceNorthWestProvider` | `fr-nw` | :white_check_mark: |
| `FranceSouthEastProvider` | `fr-se` | :white_check_mark: |
| `FranceSouthWestProvider` | `fr-sw` | :white_check_mark: |
| `GhanaProvider` | `gh` | :x: |
| `HungaryProvider` | `hu` | :x: |
| `IsraelProvider` | `il` | :x: |
| `ItalyProvider` | `it` | :white_check_mark: |
| `MassachusettsProvider` | `us-ma` | :x: |
| `NewyorkProvider` | `us-ny` | :x: |
| `NicaraguaProvider` | `ni` | :x: |
| `NzProvider` | `nz` | :x: |
| `OntarioProvider` | `ca-on` | :x: |
| `OregonProvider` | `us-or` | :x: |
| `ParisProvider` | `fr-idf` | :white_check_mark: |
| `PlNavitiaProvider` | `pl` | :x: |
| `PortugalProvider` | `pt` | :x: |
| `QuebecProvider` | `ca-qc` | :x: |
| `SpainProvider` | `es` | :white_check_mark: |
| `WashingtonDCProvider` | `us-dc` | :x: |

¹= The Costa Rica region was apparently served by `http://98.158.179.5:9191/` which is not reachable anymore either

As you can see, most of the listed providers are unfortunately not served anymore by Navitia and should be removed from Transportr in the next version.

**Comment by ialokim** [comment]
`br-floripa` was served by `https://api.transportr.app/floripa/v1/` which shows 500 Internal Server Error, should we remove it from Transportr @grote ?

**Comment by grote** [comment]
Yes please.

**Comment by ialokim** [comment]
Fixed with #884
