### ISSUE TITLE
The app is not working in Brazil

### ISSUE THREAD

**Issue by Heus-Sueh** [grote/Transportr#878]
**Describe the bug**
```
java.lang.lllegalArgumentException:` Unhandled error
message: The region br doesn't exists

de.schildbach bstractNavitiaProvider.query Trips(Abstra
ctNavitiaProvider.java:1061)
de.grobox.transportr.trips.search. TripsRepository.query Trips
(TripsRepository.kt:110)

de.grobox.transportr.trips.search. TripsRepository.access$q
`ueryTrips(TripsRepository.kt:52)
```

**To Reproduce**
select any location or search any location

**Expected behavior**
the locations appear and the search works

**Screenshots**
![Screenshot_20230814-180836_Transportr-cropped](https://github.com/grote/Transportr/assets/98482469/16aaaf49-4ce4-4f1b-ae51-2792cf841b15)

**Versions (please complete the following information):**
 - **Transportr Version:** 2.1.5
 - **Device:** Xiaomi Mi A2 Lite - codename: daisy
 - **Android Version:** 13

**Comment by ialokim** [comment]
Unfortunately, Navitia lately removed support for many regions. See #877 as an umbrella issue.
