### ISSUE TITLE
9292 provider returns no stops in the Netherlands

### ISSUE THREAD

**Issue by einalex** [grote/Transportr#881]
**Describe the bug**
When searching for stations, no results pop up.

**To Reproduce**
1. Switch provider to Netherlands / 9292.nl
2. tap the routing button
3. search for something, e.g "Den Haag HS", or "Station Delft", or "Groningen"
4. Despair

**Expected behavior**
Stations being found same as with other providers.

**Versions (please complete the following information):**
 - **Transportr Version:** 2.1.5
 - **Device:** Pixel 7
 - **Android Version:** current GrapheneOS

**Comment by ialokim** [comment]
This is a known issue and tracked upstream at https://github.com/schildbach/public-transport-enabler/issues/438. Unfortunately there is nothing we can do about it from Transportr's end, except disabling the region.

**Comment by TheRealRWJ** [comment]
> This is a known issue and tracked upstream at [schildbach/public-transport-enabler#438](https://github.com/schildbach/public-transport-enabler/issues/438). Unfortunately there is nothing we can do about it from Transportr's end, except disabling the region.

Maybe you can.
I found http://openov.nl
An opensource public transport data source
Unfortunately I cant code
And again Unfortunately: As far as I know the site is only available in the Dutch language

**Comment by ialokim** [comment]
9292 has been disabled in Transportr with 7c13728fd454a550902549ba9c56386ef827b90c

Going to close this issue until some other data source for the Netherlands has been identified upstream.
