### ISSUE TITLE
Latest release (2.1.5) is missing in Google Play Store

### ISSUE THREAD

**Issue by RealMuffinTime** [grote/Transportr#882]
**Describe the bug**
Recently [2.1.5](https://github.com/grote/Transportr/releases/tag/2.1.5) was released, but it is still not available in the Play Store.

**To Reproduce**
View https://play.google.com/store/apps/details?id=de.grobox.liberario and see that latest update is 2021-11-16.

**Expected behavior**
View https://play.google.com/store/apps/details?id=de.grobox.liberario and see that latest update is around 2023-06-xx.

**Comment by pt2121** [comment]
Yes, I think it's a good time to promote the beta to the stable channel.

**Comment by grote** [comment]
promoted 2.1.5 to production, let's see if google accepts it.

**Comment by RealMuffinTime** [comment]
It seems to work since the update is visible on the store.
