### ISSUE TITLE
Can't found Transportr in F-droid

### ISSUE THREAD

**Issue by LaoshuBaby** [grote/Transportr#883]
https://github.com/grote/Transportr/blob/master/README.md?plain=1#L21

Got 404 and can't found this app, was it removed?

**Comment by ialokim** [comment]
We are currently working on being able to publish the new v2 of the app again on f-droid, see #826.

Interestingly, they actually do [have disabled the old versions](https://gitlab.com/fdroid/fdroiddata/-/commit/0b38fbe548cfa419ec3c94c1286baaf9eec031b6) now as well.

I'm still going to close this issue in favor of #826.
