### ISSUE TITLE
Navitia links broken

### ISSUE THREAD

**Issue by tsjordan-eng** [grote/Transportr#907]
**Describe the bug**
The links to Navitia in the documentation to add a region are broken. 

**To Reproduce**
1. Go to https://transportr.app/contribute/
3. Scroll down to Using GTFS section
4. All Navitia links don't link to correct pages

**Comment by dgcampbe** [comment]
I believe this is the correct address now: https://navitia.io/en/

**Comment by Niquarl** [comment]
I just checked the contibute page on the website and the links don't seem to work indeed, I was able to find on their french website (https://navitia.io/) that the "fremium" service will be unavailable from November 1st 2024.

I wanted to give a go at adding public transport in Guadeloupe as I've just found a GTFS file on https://transport.data.gouv.fr/ but now I'm wondering how to? Is new networks not possible with Navitia anymore? Not sure if I should open a new issue. I'm not sure if it's that fremium service that is used for this app.

**Comment by Niquarl** [comment]
Just checked out Transitious, from the sources page https://transitous.org/sources the GTFS file is already there. So nothing more I can do for that I guess.

Is this app actually broken then? I'm not sure I completely understand how it gets the data.

**Comment by grote** [comment]
https://github.com/grote/Transportr-website/issues

**Comment by Golem642** [comment]
> > Is this app actually broken then? I'm not sure I completely understand how it gets the data.
> 
> No the app isn't broken :) If Navitia actually shuts down it's API on November 1st 2024, only following areas will not work anymore: France, Spain, Italy and Australia! All other networks will to continue to work perfectly fine as they get the data from other APIs!

The API isn't shutdown, on their website it's still here apparently. It still says "open access" but it asks you to contact them, this is probably to get an API key so they know who is using their platform and when.
You could try contacting them maybe

**Comment by Golem642** [comment]
> Feel free to try this on your own, I won't spend more time fixing Navitia issue especially since it is now removed from upstream PTE. (see also their repo here: https://github.com/hove-io/navitia)
> If you manage to find the API hasn't been shut down, and are able to get a key for Transportr, I would be open to update the current key, and see if it works :)

The problem is that it requires personal info to contact them and i do not wish to share mine, especially since i do not own or directly contribute to the project as of now sorry. If anyone in the team member is willing to give it a try, the link to the informations I found is https://navitia.io/fr/solutions/navitia-api-insights/#3 and their form is https://hove.com/fr/contact/

**Comment by brad2014** [comment]
> If you manage to find the API hasn't been shut down, and are able to get a key for Transportr, I would be open to update the current key, and see if it works :)

Access costs 5000€ / year per https://navitia.io/fr/solutions/navitia-api-insights/#3

> Information importante : l’offre Freemium Navitia.io n’est plus disponible. Profitez de notre offre d’entrée à 5 000 € HT/an (1 million de requêtes) pour des données de transport fiables et performantes.
