### ISSUE TITLE
Save only the "final cennection" as favorite

### ISSUE THREAD

**Issue by dktzde** [grote/Transportr#91]
Hi, I don't know if it is a bug or and improvement :-)
I used DB Bahn as Networt, ther it is possible to use shorcuts when I search for a city (e.g. German car "" like ac for Aachen)
Wenn I search for a connection like Paderborn -> ac liberario asks me, if I want to search for Paderborn -> Aachen -- to this Point everythink is as I assect it.
Afterwards, my favorite shows Paderborn -> ac AND Paderborn -> Aachen, but I dont want the initial search to be shown up as a favorite.

--- dktzde

![ac_aachen](https://cloud.githubusercontent.com/assets/12322609/10539291/c8352542-73fe-11e5-9072-5e4e21b527e7.jpg)

**Comment by grote** [comment]
I am sorry, but I can not reproduce this. Neither with current master, nor with the latest release.

**Comment by dktzde** [comment]
Hi, I still get this, e.g. when I search "ac" -"pd" that I have two "recent connections" at the end.
