### ISSUE TITLE
Trips that don't require switching train should not be expendable

### ISSUE THREAD

**Issue by TheLastProject** [grote/Transportr#93]
In Transportr 1.0.0-beta1, each card in the trip list has an expand button in the bottom right. However, this button only makes sense when you actually need to switch train during the trip.

If you have a trip where you have to get in a train and it brings you straight from your departure location to your destination, the expand button still appears, and tapping it will do nothing but slightly mess up the spacing for that specific card.

**Comment by grote** [comment]
For trips without changes, it should still show the destination of the one line you need to take, but you could of course also get this by tapping the trip. So I'll remove the expand button for these cases.
