### ISSUE TITLE
On NS (Netherlands) nearby stations all show same nonsense distance

### ISSUE THREAD

**Issue by TheLastProject** [grote/Transportr#94]
![tmp_27158-screenshot_2015-10-19-01-05-28-758460456](https://cloud.githubusercontent.com/assets/1885159/10567226/c90aacf2-75fd-11e5-81be-463c2f858a68.png)

**Comment by grote** [comment]
For some reason, the stations in the NL provider are returned without locations. I will hide the miscalculated distance. If you want the location, you need to file an issue against [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/).

**Comment by TheLastProject** [comment]
You should probably hide the map button in the top right corner as well then, as it gives an error message too (probably related to this)

On 19 October 2015 14:29:28 CEST, Torsten Grote <notifications@github.com> wrote:
>For some reason, the stations in the NL provider are returned without
>locations. I will hide the miscalculated distance. If you want the
>location, you need to file an issue against
>[public-transport-enabler](https://github.com/schildbach/public-transport-enabler/).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/grote/Transportr/issues/94#issuecomment-149200244

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
