### ISSUE TITLE
Make changelog translatable

### ISSUE THREAD

**Issue by TheLastProject** [grote/Transportr#95]
The changelog is untranslatable. Yet, whenever the user updates, this screen is shown rather aggressively. I've seen this confuse several non-English users before. It would be good to be able to translate the screen. Also, because it is now easily accessible in the sidebar, not show it on first launch after updating.

**Comment by grote** [comment]
The changelog itself can not be translated. You would need to [open an issue upstream](https://github.com/cketti/ckChangeLog/issues) about that. However, I will make the title and subtitle translatable within Transportr and hope this will already help. You can also submit these translations to be included in the library upstream.

**Comment by TheLastProject** [comment]
From reading the upstream README, it seems the changelog can be translated: https://github.com/cketti/ckChangeLog#usage

See step 2:
`Create translations of this changelog_master.xml file in files named changelog.xml under language-specific versions of res/xml/, e.g. res/xml-de/changelog.xml.`

**Comment by grote** [comment]
Right, it is possible to translate them in theory. However, this does not work easily with Transifex and I am not convinced the overhead is worth the effort. Let's hope a translated title of that dialog is enough to not confuse the users.

**Comment by eighthave** [comment]
It is now possible to directly translate changelogs in the Fastlane metadata format:

https://github.com/WeblateOrg/weblate/issues/1525

**Comment by grote** [comment]
Would this work with Transifex as well?

**Comment by eighthave** [comment]
Only if Transifex implements it.  But you can have the fastlane metadata
on Weblate while keeping the app strings on Transifex.  Also, the
Android strings.xml files are very portable between Transifex and Weblate.
