### ISSUE TITLE
Merge return trips in favourites

### ISSUE THREAD

**Issue by TheLastProject** [grote/Transportr#99]
If I plan a trip from Eindhoven to Amsterdam, and a trip from Amsterdam to Eindhoven, both will show up in the favourite trips list. To me, this seems a bit silly, as each entry has a button with "Search return trip" as first option in the list.

Merging these (and the trip count for them!) would most likely help to keep the favourite lists clean, especially as this list builds up automatically without user interaction.

One thing to note is that this may harm discoverability of a trip done before.

**Comment by grote** [comment]
The easiest thing here would be to not add a new favorite trip when simply selecting a return trip from another favorite trip.

Always merging would require database layout changes and would be computationally more expensive. There could be a button to merge trips on demand.

**Comment by TheLastProject** [comment]
I don't know the Transportr code well, but I'd imagine the easiest way would be to, before adding a trip to favourites, check if a favourite with the from and to destinations swapped already exists. If it does, just up the count of that one by one, instead of inserting a new trip. Unless the code is drastically different from what I expect, this would only be a single DB query, which should be a negligible delay.

Of course, this wouldn't clean up already existing reversed favourites, but would prevent new ones from being created. Which does cause a problem of inconsistency for users who already have reversed favourites, although I am not sure how to deal with that (wiping the favourites list on upgrade would be easiest, but not very nice to users).

I would recommend against a check on pressing "search return trip" as that sounds like inconsistent behaviour to me.

A manual merge button sounds like a bad idea to me. Manually hitting a button for a very uncommon task like this would add unnecessary code and UI complexity.

Perhaps my suggestion is not worth the time, but I can't help but feel a less cluttered favourites list helps Transportr look and feel more user-friendly.

On 21 October 2015 12:28:32 CEST, Torsten Grote <notifications@github.com> wrote:
>The easiest thing here would be to not add a new favorite trip when
>simply selecting a return trip from another favorite trip.
>
>Always merging would require database layout changes and would be
>computationally more expensive. There could be a button to merge trips
>on demand.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/grote/Transportr/issues/99#issuecomment-149849028

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by grote** [comment]
> Perhaps my suggestion is not worth the time, but I can't help but feel a less cluttered favourites list 
> helps Transportr look and feel more user-friendly.

You would then still have the issue that people are confused by having their favorite trip saved in reverse order and it won't get easier once several via locations are introduced (issue #68).

Unless we have a clear and holistic concept for the favorites, I'm tempted to do nothing here. @ByteHamster also introduced the idea of manually marking certain trips as favorites and show those below the directions form. The current favorites would then be a trip history that you might not want to mess with by reversing it for users.

**Comment by grote** [comment]
Since the former favorite trips are now recent trips, I think it is not necessary to merge anything here. If you agree, please close this issue.
